src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EC_Division__c</fullName>
        <description>This field specifies the division that a Ship To account is related to.</description>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Institutional</fullName>
                    <label>INSTITUTIONAL</label>
                </value>
                <value>
                    <fullName>WATER</fullName>
                </value>
                <value>
                    <fullName>PAPER</fullName>
                </value>
                <value>
                    <fullName>FOOD &amp; BEVERAGE</fullName>
                </value>
                <value>
                    <fullName>ENERGY</fullName>
                </value>
                <value>
                    <fullName>PEST</fullName>
                </value>
                <value>
                    <fullName>TEXTILE CARE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Account/fields/EC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>EC_Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EC_Billing_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>EC_Billing_Account_Number__c</fullName>
    <externalId>true</externalId>
    <label>Billing Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>EC_Ship_To_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC Carts (Ship To Account)</relationshipLabel>
        <relationshipName>CC_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__BillTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a CC Contact Address object that contains the bill to address data. This will be a unique copy of the address information captured during checkout.</description>
        <label>Bill To</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipLabel>Carts (BillToID)</relationshipLabel>
        <relationshipName>E_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__EncryptedId__c</fullName>
        <description>Semi-random UUID used to refer to the order in URLs.</description>
        <label>Encrypted Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a CC Contact Address object that contains the ship to address data. This will be a unique copy of the address information captured during checkout.</description>
        <label>Ship To</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipLabel>Carts (ShipToID)</relationshipLabel>
        <relationshipName>E_Carts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>The storefront under which the order was placed.</description>
        <label>Storefront</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_CartItem__c.object
<CustomObject>
    <description>Cart Items</description>
    <fields>
        <fullName>ccrz__Cart__c</fullName>
        <description>Reference to the parent cart.</description>
        <label>Cart</label>
        <referenceTo>ccrz__E_Cart__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>E_CartItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>The unit price of the line.</description>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line item.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Cart Items (ProductID)</relationshipLabel>
        <relationshipName>E_CartItem2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__UnitOfMeasure__c</fullName>
        <description>Unit of measure as copied from the product data.</description>
        <label>Unit Of Measure</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>CC Cart Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CartItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date that this product will be available.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductId__c</fullName>
        <description>External product Id, tying this product to the source system. Typically contains the SKU/product id from a backend system such as SAP.</description>
        <externalId>true</externalId>
        <label>Product Id</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__ProductIndexStatus__c</fullName>
        <description>Indicates the status of the associated Product Index records. Possible values are Current, Not Current and Pending. This field is primarily used by the Product Index batch process.</description>
        <inlineHelpText>Indicates the status of the associated Product Index records. Possible values are Current, Not Current and Pending. This field is primarily used by the Product Index batch process.</inlineHelpText>
        <label>Product Index Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductStatus__c</fullName>
        <description>The status of the product. In Creation - Newly created product, that still requires augmentation and is not visible on the site; Blocked - product has been blocked from being displayed on the site; Not Orderable - product can be viewed, but cannot be added to a cart or ordered; Released - fully availble product</description>
        <label>Product Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Not Orderable</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>In Creation</fullName>
                    <default>true</default>
                    <label>In Creation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within B2B Commerce</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The first date that this product will be available.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>Mulit-select list that allows you to assign the product to one or more storefronts.</description>
        <label>Storefront</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DefaultStore</fullName>
                    <default>true</default>
                    <label>DefaultStore</label>
                </value>
                <value>
                    <fullName>Connect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Taxonomy__c</fullName>
        <description>To identity the type of product (Equipment or Chemical)</description>
        <label>Taxonomy </label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__UnitOfMeasure__c</fullName>
        <description>Product unit of measure - such as Each</description>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Each</fullName>
                    <default>true</default>
                    <label>Each</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>User_Type__c</fullName>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/EC_ccLogicCartValidateTest.cls
/* Class Name    : EC_ccLogicCartValidateTest 
 * Description      Test Class to cover EC_ccLogicCartValidate
 * Created By       :Priyanka Priya
 * Created On       :2019-Aug-19
 */

 /* Modification Log:
 * -------------------------------------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID         Description
 * -------------------------------------------------------------------------------------------------------------------------------------
 * Priyanka Priya     2019-Aug-19       BC-76559            Created the class   
 */
@isTest
public class EC_ccLogicCartValidateTest {
/***************************************************************************************************************************************
  Method Name : processPositiveTest
  Description : Test method to cover process method
  Return type : void
/************************************************************************************************************************************/
    @isTest 
    static void processPositiveTest(){
        
        User thisUser = [SELECT Id  FROM User WHERE Id = :UserInfo.getUserId()];
        
        system.runas(thisUser){
            
            EC_TestData.setupCatalog();
            EC_TestData.setupTestUser();
            ccrz__E_Cart__c cart = EC_TestData.createCart();
            
            ccrz.cc_RemoteActionContext rac = new ccrz.cc_RemoteActionContext();
            Contact con =[SELECT id from Contact limit 1];
            rac.priceGroupId = con.id;
            
            AccountContactRelation accCon = new AccountContactRelation();
            accCon.AccountId = EC_TestData.testAccountSoldTo.id;
            accCon.ContactId = con.id;
            Insert accCon;
            
            Account shipTo = EC_TestData.testAccountShipTo;
            shipTo.EC_Division__c = 'WATER';
            update shipTo;

            rac.userLocale = EC_TestData.testAccount.id;
            rac.effAccountId = shipTo.id;
            rac.currentCartId = cart.ccrz__EncryptedId__c;
            ccrz.cc_CallContext.initRemoteContext(rac);
            
            
            Map<String, Object> inputData = new Map<String, Object>{
                    ccrz.ccAPICart.CART_ID => cart.id,
                    ccrz.ccAPI.API_VERSION => 8
                };
            

            Map<String,Object> outData = new Map<String,Object>();
            EC_ccLogicCartValidate classOb = new EC_ccLogicCartValidate();
            Test.startTest();
            thisUser.User_Type__c='Internal';
            thisUser.Phone='123456';
            thisUser.MobilePhone='98765432';
            update thisUser;
            outData = classOb.process(inputData);
            System.assertNotEquals(outData,null);
                        
            Test.stopTest();
        }
    }
    /***********************************************************************************************************************************
  Method Name : processNegativeTest
  Description : Test method to cover process method
  Return type : void
 *************************************************************************************************************************************/
    @isTest 
    static void processNegativeTest(){
        
        User thisUser = [SELECT Id  FROM User WHERE Id = :UserInfo.getUserId()];
        
        system.runas(thisUser){
            
            EC_TestData.setupCatalog();
            EC_TestData.setupTestUser();
            ccrz__E_Cart__c cart = EC_TestData.createCart();
            cart = [Select ccrz__BillTo__c, ccrz__ShipTo__c from ccrz__E_Cart__c Where Id=: cart.id Limit 1];
            cart.ccrz__BillTo__c = null;
            cart.ccrz__ShipTo__c = null;
            update cart;

            ccrz.cc_RemoteActionContext rac = new ccrz.cc_RemoteActionContext();
            Contact con =[SELECT id from Contact limit 1];
            rac.priceGroupId = con.id;
            
            AccountContactRelation accCon = new AccountContactRelation();
            accCon.AccountId = EC_TestData.testAccountSoldTo.id;
            accCon.ContactId = con.id;
            Insert accCon;
            
            Account shipTo = EC_TestData.testAccountShipTo;
            shipTo.EC_Division__c = 'WATER';
            update shipTo;

            rac.userLocale = EC_TestData.testAccount.id;
            rac.effAccountId = shipTo.id;
            rac.currentCartId = cart.id;
            ccrz.cc_CallContext.initRemoteContext(rac);
            
            
            Map<String, Object> inputData = new Map<String, Object>{
                    ccrz.ccAPICart.CART_ID => cart.id,
                    ccrz.ccAPI.API_VERSION => 8
                };
            

            Map<String,Object> outData = new Map<String,Object>();
            EC_ccLogicCartValidate classOb = new EC_ccLogicCartValidate();
            Test.startTest();
            outData = classOb.process(inputData);
            
            System.assertNotEquals(outData,null);
            Test.stopTest();
        }
    }
    
/***************************************************************************************************************************************
  Method Name : ISE_HybridDirect
  Description : Test method to cover Hybrid Direct for Sales Entitlement
  Return type : void
/************************************************************************************************************************************/
    @isTest 
    static void ISE_HybridDirect() {
        EC_ISETestDataFactory.setupInstSalesEntitlements();
        list<Account> testAccountISE = [select Name,OwnerId,BillingStreet,BillingCity,BillingState,BillingCountry,BillingPostalCode,EC_Account_Number__c,EC_Billing_Account_Number__c,RecordTypeId from Account where Name LIKE '%_HybridDirect%'];
        list<ccrz__E_Product__c> prodNew = new list<ccrz__E_Product__c>{
            new ccrz__E_Product__c(
                        Name                       = '3D TRASAR Boiler BD, HPSCS, Frame, BD',
                        ccrz__SKU__c               = '0000000000060-BLC6131B.88',
                        ccrz__ProductId__c         = '5285',
                        ccrz__ProductStatus__c     = 'Released',
                        ccrz__UnitOfMeasure__c     = 'Each',
                        ccrz__StartDate__c         = Date.today().addDays(-7),
                        ccrz__EndDate__c           = Date.today().addDays(7),
                        ccrz__Storefront__c        = 'DefaultStore',
                		Taxonomy__c				= 'Chemical',
                    ccrz__ProductIndexStatus__c = Label.EC_ProductIndexCurrent)
                };
        insert prodNew;
        
        User thisUser = [SELECT Id  FROM User WHERE Id = :UserInfo.getUserId()];
        system.runas(thisUser) {
            Test.startTest();
            
            ccrz.cc_RemoteActionContext ctx = new ccrz.cc_RemoteActionContext();
            ctx.effAccountId = testAccountISE[0].id;
            
            ccrz.cc_CallContext.effAccountId = testAccountISE[0].id;            
            ccrz.cc_CallContext.initRemoteContext(ctx);
            ccrz.cc_CallContext.currAccountId = testAccountISE[0].id;
            List<ccrz__E_Cart__c> cart = EC_TestData.createCarts(1);
            cart[0].EC_Ship_To_Account__c = testAccountISE[0].id;
            update cart[0];
            
            ccrz__E_CartItem__c cartItem1 = new ccrz__E_CartItem__c();
            cartItem1.ccrz__Cart__c = cart[0].Id;
            cartItem1.ccrz__Product__c = prodNew[0].id;
            cartItem1.ccrz__Price__c = 100;
            insert cartItem1;  
            
            EC_TestData.setupCatalog();
            List<ccrz.ccApiCart.LineData> lineDataList = new List<ccrz.ccApiCart.LineData>();
            
            List<ccrz__E_cartitem__c> cartitemlist = [SELECT id,ccrz__Product__r.ccrz__sku__c FROM ccrz__E_cartitem__c WHERE ccrz__cart__c = :cart[0].id];
            
            for(ccrz__E_cartitem__c cartitem : cartitemlist){
                ccrz.ccApiCart.LineData lineData = new ccrz.ccApiCart.LineData();
                lineData = new ccrz.ccApiCart.LineData();
                lineData.sku = cartitem.ccrz__Product__r.ccrz__sku__c;
                lineDataList.add(lineData);
            }
            
            Map<String, Object> inputData = new Map<String, Object>();
            Map<String,Object> outData = new Map<String,Object>();
            EC_ccLogicCartValidate classOb = new EC_ccLogicCartValidate();
            inputData = new Map<String, Object>{
                ccrz.ccAPICart.CART_ID => cart[0].Id,
                    ccrz.ccAPI.API_VERSION => 8
                    };
                        
            outData = classOb.processValidate(inputData);
            System.assertNotEquals(outData,null);
            
            Test.stopTest();
        }
    }
    
/***************************************************************************************************************************************
  Method Name : ISE_IndirectCore
  Description : Test method to cover Hybrid Direct for Sales Entitlement
  Return type : void
/************************************************************************************************************************************/
    @isTest 
    static void ISE_IndirectCore() {
        EC_ISETestDataFactory.setupInstSalesEntitlements();
        list<Account> testAccountISE = [select Name,OwnerId,BillingStreet,BillingCity,BillingState,BillingCountry,BillingPostalCode,EC_Account_Number__c,EC_Billing_Account_Number__c,RecordTypeId from Account where Name LIKE '%_InDirectCore%'];
        list<ccrz__E_Product__c> prodNew = new list<ccrz__E_Product__c>{
            new ccrz__E_Product__c(
                        Name                       = '3D TRASAR Boiler BD, HPSCS, Frame, BD',
                        ccrz__SKU__c               = '0000000000060-BLC6131B.88',
                        ccrz__ProductId__c         = '5285',
                        ccrz__ProductStatus__c     = 'Released',
                        ccrz__UnitOfMeasure__c     = 'Each',
                        ccrz__StartDate__c         = Date.today().addDays(-7),
                        ccrz__EndDate__c           = Date.today().addDays(7),
                        ccrz__Storefront__c        = 'DefaultStore',
                		Taxonomy__c				= 'Chemical',
                    ccrz__ProductIndexStatus__c = Label.EC_ProductIndexCurrent)
                };
        insert prodNew;
        
        User thisUser = [SELECT Id  FROM User WHERE Id = :UserInfo.getUserId()];
        system.runas(thisUser) {
            Test.startTest();
            
            ccrz.cc_RemoteActionContext ctx = new ccrz.cc_RemoteActionContext();
            ctx.effAccountId = testAccountISE[0].id;
            
            ccrz.cc_CallContext.effAccountId = testAccountISE[0].id;            
            ccrz.cc_CallContext.initRemoteContext(ctx);
            ccrz.cc_CallContext.currAccountId = testAccountISE[0].id;
            List<ccrz__E_Cart__c> cart = EC_TestData.createCarts(1);
            cart[0].EC_Ship_To_Account__c = testAccountISE[0].id;
            update cart[0];
            
            ccrz__E_CartItem__c cartItem1 = new ccrz__E_CartItem__c();
            cartItem1.ccrz__Cart__c = cart[0].Id;
            cartItem1.ccrz__Product__c = prodNew[0].id;
            cartItem1.ccrz__Price__c = 100;
            insert cartItem1;  
            
            EC_TestData.setupCatalog();
            List<ccrz.ccApiCart.LineData> lineDataList = new List<ccrz.ccApiCart.LineData>();
            
            List<ccrz__E_cartitem__c> cartitemlist = [SELECT id,ccrz__Product__r.ccrz__sku__c FROM ccrz__E_cartitem__c WHERE ccrz__cart__c = :cart[0].id];
            
            for(ccrz__E_cartitem__c cartitem : cartitemlist){
                ccrz.ccApiCart.LineData lineData = new ccrz.ccApiCart.LineData();
                lineData = new ccrz.ccApiCart.LineData();
                lineData.sku = cartitem.ccrz__Product__r.ccrz__sku__c;
                lineDataList.add(lineData);
            }
            
            Map<String, Object> inputData = new Map<String, Object>();
            Map<String,Object> outData = new Map<String,Object>();
            EC_ccLogicCartValidate classOb = new EC_ccLogicCartValidate();
            inputData = new Map<String, Object>{
                ccrz.ccAPICart.CART_ID => cart[0].Id,
                    ccrz.ccAPI.API_VERSION => 8
                    };
                        
            outData = classOb.processValidate(inputData);
            System.assertNotEquals(outData,null);
            
            Test.stopTest();
        }
    }
}