src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EC_Division__c</fullName>
        <description>This field specifies the division that a Ship To account is related to.</description>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Institutional</fullName>
                    <label>INSTITUTIONAL</label>
                </value>
                <value>
                    <fullName>WATER</fullName>
                </value>
                <value>
                    <fullName>PAPER</fullName>
                </value>
                <value>
                    <fullName>FOOD &amp; BEVERAGE</fullName>
                </value>
                <value>
                    <fullName>ENERGY</fullName>
                </value>
                <value>
                    <fullName>PEST</fullName>
                </value>
                <value>
                    <fullName>TEXTILE CARE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Account/fields/EC_SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>EC_SalesOrg__c</fullName>
    <label>SalesOrg</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>EC_PurchasedWishlist__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Purchased Wishlist</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__CartType__c</fullName>
        <description>Cart type &quot;WishList&quot; can be used to keep track of items users want.</description>
        <label>Cart Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Read-Only WishList</fullName>
                </value>
                <value>
                    <fullName>WishList</fullName>
                </value>
                <value>
                    <fullName>Cart</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_CartItem__c.object
<CustomObject>
    <description>Cart Items</description>
    <fields>
        <fullName>EC_LastPurchasedDateFormatted__c</fullName>
        <description>To Display on the UI</description>
        <formula>CASE( MONTH( EC_Last_Purchased_Date__c ) ,
1, &quot;Jan&quot;,
2, &quot;Feb&quot;,
3, &quot;Mar&quot;,
4, &quot;Apr&quot;,
5, &quot;May&quot;,
6, &quot;Jun&quot;,
7, &quot;Jul&quot;,
8, &quot;Aug&quot;,
9, &quot;Sep&quot;,
10, &quot;Oct&quot;,
11, &quot;Nov&quot;,
12, &quot;Dec&quot;,
&quot;None&quot;) +&apos; &apos;+ text(DAY( EC_Last_Purchased_Date__c )) +&apos;, &apos;+ Text(YEAR( EC_Last_Purchased_Date__c ))</formula>
        <label>Last Purchased Date Formatted</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_Last_Purchased_Date__c</fullName>
        <label>Last Purchased Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Cart__c</fullName>
        <description>Reference to the parent cart.</description>
        <label>Cart</label>
        <referenceTo>ccrz__E_Cart__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>E_CartItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line item.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Cart Items (ProductID)</relationshipLabel>
        <relationshipName>E_CartItem2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Cart Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CartItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Chemical_Product_Type__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To identify the bulk product (User Story-122127)</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Package_Code__c</fullName>
        <label>Package Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Chemical Product Type</label>
</CustomObject>

src/objects/Tank_Detail__c.object
<CustomObject>
    <description>Object to store all tank numbers for a particular Unloading point &amp; product.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Material_Description__c</fullName>
        <label>Material Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Tank Detail</label>
    <nameField>
        <label>Tank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tank Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EC_ccServiceProduct.cls
/* Class Name       :EC_ccServiceProduct
* Description      :Service Product Related inherited cloud craze interface
* Created By       :Ashish Kr. 
* Created On       :07-08-2019

* Modification Log:
* ------------------------------------------------------------------------------------------------------------------
* Developer                Date            Modification ID         Description
* ------------------------------------------------------------------------------------------------------------------
* Ashish Kr.               07-08-2019                              Initial version (log modification)
*
*
*/

global without sharing class EC_ccServiceProduct extends ccrz.ccServiceProduct{
    
    /***************************************************************************************************************************************
    Method Name : fetch
    Description : Sets the lastPurchaseDate field in the product bean
    Return type : Map<String, Object>
    *************************************************************************************************************************************/
 global override Map<String, Object> fetch(Map<String, Object> inputData){
        ID ownerId = UserInfo.getUserId();
        Map<String,ccrz__E_CartItem__c> cartItemMap = new Map<String,ccrz__E_CartItem__c>();
        for(ccrz__E_Cart__c wishCart : [Select Name,OwnerId,EC_PurchasedWishlist__c, (Select Id,ccrz__Product__c,EC_Last_Purchased_Date__c,EC_LastPurchasedDateFormatted__c from ccrz__E_CartItems__r) from ccrz__E_Cart__c
                                        Where OwnerId = :ownerId AND ccrz__CartType__c='WishList' AND EC_PurchasedWishlist__c = TRUE Limit 1]){
                                            for(ccrz__E_CartItem__c cartItem : wishCart.ccrz__E_CartItems__r){
                                                cartItemMap.put(cartItem.ccrz__Product__c, cartItem);
                                            }
                                        }
        inputData = super.fetch(inputData);
        if(!inputData.containsKey('includeProductIndex') || !(Boolean)(inputData.get('includeProductIndex'))) {
            List<Chemical_Product_Type__c> pkgTypes = new List<Chemical_Product_Type__c>();
            pkgTypes = Chemical_Product_Type__c.getall().values();
            Set<String> pkgCodeSet = new Set<String>();
            if(!pkgTypes.isEmpty()) {
                for (Chemical_Product_Type__c pkgType : pkgTypes) {
                    if(pkgType.Active__c == true) {
                        pkgCodeSet.add(pkgType.Package_Code__c);
                    }
                }
            }
            ccrz.cclog.log('pkgCodeSet-->' + pkgCodeSet);
            if(inputData.containsKey('productList')){
                List<Map<String,Object>> prodList = (List<Map<String,Object>>) inputData.get('productList');                
                // Tank Number & unloading point Logic
               String effAccountId = ccrz.cc_CallContext.effAccountId;
               List<Account> effAccountList = [Select Id,EC_SalesOrg__c,EC_Division__c FROM Account WHERE Id=:effAccountId LIMIT 1];
                for(Map<String,Object> prod : prodList){
                    String productID = String.valueOf(prod.get('sfid')); 
                    if(!effAccountList.isEmpty()){
                        prod.put('ECDivision',effAccountList[0].EC_Division__c);
                    }
                    String packageCode = String.valueOf(prod.get('packageCode'));
                    ccrz.cclog.log('prod Output' + prod);
                    if(!pkgCodeSet.isEmpty() && pkgCodeSet.contains(packageCode)) {
                        prod.put('packageTypeUOM','Bulk');
                    } else {
                        prod.put('packageTypeUOM','NonBulk');
                    }
                    
                    if(!cartItemMap.isEmpty() && cartItemMap.containsKey(productID) && cartItemMap.get(productID).EC_Last_Purchased_Date__c != null){
                        // 4/2/20 | TB | Story 116762 - replaced formatted value with actual value for sorting purposes. Formatting is done on VF component
                        //prod.put('lastPurchaseDate',(Object)String.valueOf(cartItemMap.get(productID).EC_LastPurchasedDateFormatted__c));
                        prod.put('lastPurchaseDate',(Object)String.valueOf(cartItemMap.get(productID).EC_Last_Purchased_Date__c));
                    }
                }              
                ccrz.cclog.log('CCTXX: ' ,'super fetch--->' + inputData);
                
                // TankNumber & Delivery Point Logic :
                if(ccrz.cc_CallContext.currPageName =='ccrz__Cart') {
                    set<string> deliverTmpltMaterialSet = new set<string>();
                    Map<String,List<String>> packageCodeDelTemplMap = new Map<String,List<String>>();
                    Map<String,List<String>> packageCodeMaterialListMap = new Map<String,List<String>>();
                    Map<String,boolean> isTankNumberApplicableMap = new Map<String,Boolean>();
                    for(Map<String,Object> prod : prodList){
                        String packageCode = String.valueOf(prod.get('packageCode'));
                        String material = String.valueOf(prod.get('materialDescription'));
                        packageCodeDelTemplMap.put(packageCode,new List<String>());
                        if(packageCodeMaterialListMap.containsKey(packageCode)){
                            packageCodeMaterialListMap.get(packageCode).add(material);
                        }else{
                            packageCodeMaterialListMap.put(packageCode,new List<String>{material});
                        }
                    }
                    
                    ccrz.cclog.log('packageCodeDelTemplMap--->' + packageCodeDelTemplMap);
                    if(!packageCodeDelTemplMap.isEmpty()) {
                        String salesOrg='';
                        if(!effAccountList.isEmpty()){
                            salesOrg = effAccountList[0].EC_SalesOrg__c;
                        }
                        
                        isTankNumberApplicableMap = EC_ProductDetailController.isTankNumberApplicable(packageCodeDelTemplMap.keySet(),salesOrg);
                        ccrz.cclog.log('isTankNumberApplicableMap--->' + isTankNumberApplicableMap);
                        packageCodeDelTemplMap = EC_ProductDetailController.getDeliveryTemplateCode(isTankNumberApplicableMap.keySet(),salesOrg);
                        ccrz.cclog.log('packageCodeDelTemplMap--->' + packageCodeDelTemplMap);
                        if(!packageCodeMaterialListMap.isEmpty()){
                            for(String packageCode : packageCodeMaterialListMap.keySet()){
                                for(String material : packageCodeMaterialListMap.get(packageCode)){
                                    if(!packageCodeDelTemplMap.isEmpty() && packageCodeDelTemplMap.containsKey(packageCode)){
                                        for(String delTemp : packageCodeDelTemplMap.get(packageCode)){
                                            String material_DeliveryTempCode = material+ '.'+delTemp;
                                            deliverTmpltMaterialSet.add(material_DeliveryTempCode);
                                        }
                                    }
                                }
                            }
                        }
                        
                        ccrz.cclog.log('deliverTmpltMaterialSet keyset--->' + deliverTmpltMaterialSet);
                    }
                    
                    Map<String,Set<Tank_Detail__c>> materialDelTemplTankList = new Map<String,Set<Tank_Detail__c>>();
                    materialDelTemplTankList  = EC_CartDetailController.getTankNumbersbytmpltCodes(deliverTmpltMaterialSet);
                    ccrz.cclog.log('materialDelTemplTankList--->' + materialDelTemplTankList); 
                    
                    for(Map<String,Object> prod : prodList) {
                        String packageCode = String.valueOf(prod.get('packageCode'));
                        String material = String.valueOf(prod.get('materialDescription'));
                        List<Tank_Detail__c> TankNumbers = new List<Tank_Detail__c>();
                        if(!packageCodeDelTemplMap.isEmpty() && packageCodeDelTemplMap.containsKey(packageCode)){
                            for(String delTemp : packageCodeDelTemplMap.get(packageCode)){
                                String material_DeliveryTempCode = material+ '.'+delTemp;
                                if(!materialDelTemplTankList.isEmpty() && materialDelTemplTankList.containsKey(material_DeliveryTempCode)){
                                    TankNumbers.addAll(materialDelTemplTankList.get(material_DeliveryTempCode));
                                }
                            }
                        }

                        if(TankNumbers != null) {
                            prod.put('TankNumbers',TankNumbers);
                            
                        }
                        
                        if(!isTankNumberApplicableMap.isEmpty() && isTankNumberApplicableMap.containsKey(packageCode)){
                             prod.put('packageTypeTank','Bulk');
                        }else{
                            prod.put('packageTypeTank','NonBulk'); 
                        }
                        ccrz.cclog.log('TankNumbers--->' + TankNumbers);
                    }
                }
            }
        }
        return inputData;
    }

/***************************************************************************************************************************************
  Method Name : getFieldsMap
  Description : used to include object fields in the model on front end
  Return type : Returns Map<String,Object>
**************************************************************************************************************************************/
    global override Map<String, Object> getFieldsMap(Map<String, Object> inputData){
        inputData = super.getFieldsMap(inputData);
        String objectFields = (String)inputData.get(ccrz.ccService.OBJECTFIELDS);
        objectFields += ',Biocide_Disclaimer__c,Package_Code__c,Taxonomy__c,Material_Description__c,FeaturesAndBenefits__c,EC_Statement_Of_Assurance__c,ERP_Product_Description__c';
        inputData.put(ccrz.ccService.OBJECTFIELDS, objectFields);
        return inputData;
    }
}