src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EC_Division__c</fullName>
        <description>This field specifies the division that a Ship To account is related to.</description>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Institutional</fullName>
                    <label>INSTITUTIONAL</label>
                </value>
                <value>
                    <fullName>WATER</fullName>
                </value>
                <value>
                    <fullName>PAPER</fullName>
                </value>
                <value>
                    <fullName>FOOD &amp; BEVERAGE</fullName>
                </value>
                <value>
                    <fullName>ENERGY</fullName>
                </value>
                <value>
                    <fullName>PEST</fullName>
                </value>
                <value>
                    <fullName>TEXTILE CARE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Source_System__c</fullName>
        <label>External Source System</label>
        <length>50</length>
        <type>Text</type>
    </fields>
	<fields>
		<fullName>Integration_Status__c</fullName>
		<description>Integration Status</description>
		<inlineHelpText>Integration Status</inlineHelpText>
		<label>Integration Status</label>
		<length>255</length>
		<type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Error_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Integration Error Log</description>
        <label>Integration Error Log (if any)</label>
        <referenceTo>Integration_Log__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <description>Used to in routing in Ecolab project.</description>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>SupportSubCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Email_Formula__c</fullName>
        <formula>IF( ISBLANK(Contact_Email__c) , 
    Contact.Email  , 
    Contact_Email__c
)</formula>
        <label>Case Contact Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Phone_Formula__c</fullName>
        <formula>IF( ISBLANK(SuppliedPhone) , 
    Contact.Phone, 
    SuppliedPhone
)</formula>
        <label>Case Contact Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/EC_Mulesoft_Integration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>EC_ClientId__c</fullName>
        <description>US:76262:Raghav:This field holds the client id for API Callout.</description>
        <label>EC_ClientId</label>
        <length>90</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_Client_Secret__c</fullName>
        <description>US-76262:Raghav:This fields holds the client secret for API Callout.</description>
        <label>EC_Client_Secret</label>
        <length>90</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_Endpoint__c</fullName>
        <label>Endpoint</label>
        <type>Url</type>
    </fields>
    <label>Mulesoft Integration</label>
</CustomObject>

src/objects/EC_WebServiceCalloutsLog__c.object
<CustomObject>
    <description>This object to log all the Web Service Callouts</description>
    <label>WebService Callouts Log</label>
    <nameField>
        <displayFormat>WBC-{0000000000}</displayFormat>
        <label>WebService Callouts Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WebService Callouts Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Integration_Log__c.object
<CustomObject>
    <description>Object to hold integration related error logs but can be modified</description>
    <fields>
        <fullName>Identifier__c</fullName>
        <label>Identifier</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retry_Counter__c</fullName>
        <description>Retry Counter</description>
        <inlineHelpText>Retry Counter</inlineHelpText>
        <label>Retry Counter</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>INTLOGS-{00000}</displayFormat>
        <label>Integration Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Integration_Settings__mdt.object
<CustomObject>
    <description>Integration Settings</description>
    <fields>
        <fullName>Retry_Limit__c</fullName>
        <description>Generic retry limit for a trying a callout for a failed one.</description>
        <inlineHelpText>Generic retry limit for a trying a callout for a failed one.</inlineHelpText>
        <label>Retry Limit</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Retry_Interval__c</fullName>
        <inlineHelpText>Time in seconds</inlineHelpText>
        <label>Retry Interval</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Integration Setting</label>
    <pluralLabel>Integration Settings</pluralLabel>
</CustomObject>

src/classes/CaseCreationQueueable.cls
/**************************************************************************************************************
** Name             : CaseCreationQueueable
** Description      : This class is used for callouts for Case Creation
** Version          : 1.0
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
** Developer                         Date                    Version                      Description
**------------------------------------------------------------------------------------------------------------
** Graytitude Team                   Sep-2020                    1.0                          Created    
**************************************************************************************************************/
public without sharing class CaseCreationQueueable implements Queueable, Database.AllowsCallouts{
    private String accessToken;
    private list<case> updatedCases = new list<case>();
    private list<case> callOutCases;
    private map<String,Decimal> retryCounterMap = new map<String,Decimal>();
    private static final String requestedFieldsQueryStr = 'Account.EC_Division__c,First_Name__c,Last_Name__c,Company_Name__c,Account.Name, CaseNumber, Account.ShippingCity, Contact_Email_Formula__c, Contact.Name, Contact_Phone_Formula__c, Account.ShippingCountry, Description, Account.ShippingPostalCode, Account.ShippingState, Account.ShippingStreet, Sub_Category__c, Subject';//String.join(fields,',');
    private static Integration_Settings__mdt integrationSettings = [SELECT Id, MasterLabel, Retry_Limit__c,Retry_Interval__c FROM Integration_Settings__mdt where MasterLabel='ServiceNow Retry Limit' limit 1];
    
    public CaseCreationQueueable(list<String> callOutCaseIds,String accessToken){  
        this.accessToken = accessToken;
        if(Case.sObjectType.getDescribe().isAccessible()) {
            String queryStr = String.escapeSingleQuotes('select '+requestedFieldsQueryStr+' from case where id in :callOutCaseIds');
            callOutCases = Database.query(queryStr);
        }
    }
    public void execute(QueueableContext context) {
        Decimal retryMaxCount = integrationSettings.Retry_Limit__c;
        list<Id> retryCases = new list<Id>();
        Boolean isChatbotuser = (userinfo.getName()=='Platform Integration User');
        if(Case.sObjectType.getDescribe().isAccessible() || isChatbotuser) {
            try{ 
                for(case c:callOutCases){
                    try{
                        String requestBody = getRequestBody(c);
                        HttpResponse response = doPostCallToSeviceNow(requestBody,c);
                        EC_WebServiceCalloutsLog__c logRec;
                        Integration_Log__c integraionLogRec;
                        if(response!=null){
                            String statusCode = String.valueOf(response.getStatusCode());
                            if(statusCode==String.valueOf(EC_Constants.statusCode401) && !String.isBlank(accessToken)){
                                accessToken = null;
                                doPostCallToSeviceNow(requestBody,c);
                            }
                            if(label.ServiceNow_Exceptions_Retry_Status_Codes.contains(statusCode)){
                                Case updatedCase = new Case();
                                updatedCase.Id = c.Id;
                                if(statusCode=='200' || statusCode=='201'){
                                    updatedCase.Integration_Status__c  = EC_Constants.submittedSuccess;
                                    CaseCreationQueueable.CreateCaseResponse caseResponse = (CaseCreationQueueable.CreateCaseResponse)JSON.deserialize(response.getBody(),CaseCreationQueueable.CreateCaseResponse.class);
                                    updatedCase.External_Id__c = caseResponse.result.case_number;
                                    updatedCase.External_Source_System__c = 'ServiceNow';
                                }
                                else{
                                    updatedCase.Integration_Status__c  = EC_Constants.submittedFailure;
                                    logRec = EC_Utility.logCallouts('ServiceNow Case Create - '+c.CaseNumber, requestBody, String.valueOf(response), null, EC_Constants.FAIL);
                                    integraionLogRec = EC_Utility.logIntegrationError(String.valueOf(response),EC_Constants.serviceNowCaseCreate, 'SFDC_To_MULESOFT(ServiceNow Case Creation)',
                                                                                      NULL, logRec.Id, 0, 'ERROR', c.CaseNumber);
                                    updatedCase.Integration_Error_Log__c = integraionLogRec.id;
                                }
                                updatedCases.add(updatedCase);
                            }
                            else{
                                createRetryCounterMap(new list<String>{c.CaseNumber});
                                
                                if(retryCounterMap.get(c.CaseNumber)<retryMaxCount || retryCounterMap.get(c.CaseNumber)==null){
                                    logRec = EC_Utility.logCallouts('ServiceNow Case Create - '+c.CaseNumber, requestBody, String.valueOf(response), null, EC_Constants.FAIL);
                                    integraionLogRec = EC_Utility.logIntegrationError(String.valueOf(response),EC_Constants.serviceNowCaseCreate, 'SFDC_To_MULESOFT(ServiceNow Case Creation)',
                                                                                      NULL, logRec.Id, 0, 'ERROR', c.CaseNumber);
                                    retryCases.add(c.id);
                                    Case updatedCase = new Case();
                                    updatedCase.Id = c.Id;
                                    updatedCase.Integration_Error_Log__c = integraionLogRec.id;
                                    updatedCases.add(updatedCase);
                                }
                                else{
                                    Case updatedCase = new Case();
                                    updatedCase.Id = c.Id;
                                    updatedCase.Integration_Status__c = EC_Constants.submittedFailure;
                                    updatedCases.add(updatedCase);
                                }
                            }
                        }
                    }
                    catch(Exception e){
                        System.debug('Error message - '+e.getMessage());
                        System.debug('Stack Trace - '+e.getStackTraceString());
                        Case updatedCase = new Case();
                        updatedCase.Id = c.Id;
                        updatedCase.Integration_Status__c = EC_Constants.submittedFailure;
                        updatedCases.add(updatedCase);
                    }
                }
                if(!updatedCases.IsEmpty()){
                    update updatedCases;
                }
                scheduleJobForCaseCreationRetry(retryCases);
            }
            catch(Exception e){
                System.debug('Error message - '+e.getMessage());
                System.debug('Stack Trace - '+e.getStackTraceString());
                
                //Log Exception on the Exception Framework
                EC_UtilityLogger.logException(e,'CaseCreationQueueable','CaseCreationQueueable-->execute',false,null,'');
            }
        }
    }
    
    /***************************************************************************************************************************************
Method Name : doPostCallToSeviceNow
Description : This method is for make a callout to ServiceNow.
Return type : HttpResponse
Author      : Graytitude
*************************************************************************************************************************************/    
    public HttpResponse doPostCallToSeviceNow(String reqBody,Case c){
        try{
            if(accessToken==null){
                accessToken = getAccessTokenForAPICall();
            } 
            EC_Mulesoft_Integration__c callOutAPIDetails = EC_QueryUtility.getHeader('ServiceNow Case Create'); //why would the token be null?
            HttpResponse response;
            HttpRequest request = new HttpRequest();
            Http http = new Http();
            request.setMethod('POST');
            request.setEndpoint(callOutAPIDetails.EC_Endpoint__c);
            request.setHeader('client_id', callOutAPIDetails.EC_ClientId__c);
            request.setHeader('client_secret', callOutAPIDetails.EC_Client_Secret__c);
            request.setHeader('content-type', 'application/json');
            request.setHeader('Authorization', 'Bearer '+accessToken);
            request.setBody(reqBody);
            response = http.send(request); 
            return response;
        }
        catch(exception e){
            Case updatedCase = new Case();
            updatedCase.Id = c.Id;
            updatedCase.Integration_Status__c = 'Submitted Failure';
            updatedCases.add(updatedCase);
        }
        return null;
    }
    /***************************************************************************************************************************************
Method Name : getAccessTokenForAPICall
Description : This method is for getting token from mulesoft system.
Return type : String
Author      : Graytitude
*************************************************************************************************************************************/
    public string getAccessTokenForAPICall(){ 
        EC_Mulesoft_Integration__c callOutAPIDetails = EC_QueryUtility.getHeader('ServiceNow Get Token');
        EC_Mulesoft_Integration__c callOutAPIScope = EC_QueryUtility.getHeader('ServiceNow Scope');
        String hashString = '1000' + Datetime.now().formatGMT('yyyy-MM-dd HH:mm:ss.SSS');
        Blob hash = Crypto.generateDigest('MD5', Blob.valueOf(hashString));
        String hexDigest = EncodingUtil.convertToHex(hash);
        HttpResponse response;
        HttpRequest request = new HttpRequest();
        Http http = new Http();
        request.setHeader('content-type', 'multipart/form-data; boundary=----'+hexDigest+'');
        request.setMethod('POST');
        request.setEndpoint(callOutAPIDetails.EC_Endpoint__c);
        String requestBody = '------'+hexDigest+'\r\nContent-Disposition: form-data; name=\"client_id\"\r\n\r\n'+callOutAPIDetails.EC_ClientId__c+'\r\n------'+hexDigest+'\r\nContent-Disposition: form-data; name=\"client_secret\"\r\n\r\n'+callOutAPIDetails.EC_Client_Secret__c+'\r\n------'+hexDigest+'\r\nContent-Disposition: form-data; name=\"grant_type\"\r\n\r\nclient_credentials\r\n------'+hexDigest+'\r\nContent-Disposition: form-data; name=\"scope\"\r\n\r\n'+callOutAPIScope.EC_Endpoint__c+'\r\n------'+hexDigest+'--';
        request.setBody(requestBody);
        response = http.send(request);
        system.debug(response.getBody());
        map<String,object> respMap = (map<String,object>)JSON.deserializeUntyped(response.getBody());
        String token = String.valueOf(respMap.get('access_token'));
        if(!String.isBlank(token)){
            return token;
        }
        
        return null;
    }
    /***************************************************************************************************************************************
Method Name : requestBodyGenerator
Description : This method is for generating the request body to for callout.
Return type : String
Author      : Graytitude
*************************************************************************************************************************************/
    public String getRequestBody(Case c){
        map<String,Object> reqBodyMap = new map<String,Object>();
        CaseCreationWrapper wrapper = new CaseCreationWrapper();
        
        String accountDivision = String.isBlank(c.AccountId)?'':c.Account.EC_Division__c; 
        CaseCreationWrapper.CaseCreationValuesWrapper accountDivisionProps = wrapper.accountDivisionProps;
        if(accountDivision!=null && accountDivisionProps.isTrim && accountDivision.length()>accountDivisionProps.maxLength){
            reqBodyMap.put(accountDivisionProps.fieldName,accountDivision.substring(0,accountDivisionProps.maxLength));
        }
        else{
            reqBodyMap.put(accountDivisionProps.fieldName,accountDivision);
        }
        
        String accountName = String.isBlank(c.AccountId)?c.Company_Name__c:c.Account.Name; 
        CaseCreationWrapper.CaseCreationValuesWrapper accountNameProps = wrapper.accountNameProps;
        if(accountName!=null && accountNameProps.isTrim && accountName.length()>accountNameProps.maxLength){
            reqBodyMap.put(accountNameProps.fieldName,accountName.substring(0,accountNameProps.maxLength));
        }
        else{
            reqBodyMap.put(accountNameProps.fieldName,accountName);
        }
        
        String caseNumber  = c.CaseNumber; 
        CaseCreationWrapper.CaseCreationValuesWrapper caseNumberProps = wrapper.caseNumberProps;
        if(caseNumber!=null && caseNumberProps.isTrim && caseNumber.length()>caseNumberProps.maxLength){
            reqBodyMap.put(caseNumberProps.fieldName,caseNumber.substring(0,caseNumberProps.maxLength));
        }
        else{
            reqBodyMap.put(caseNumberProps.fieldName,caseNumber);
        }
        
        String cityName  = String.isBlank(c.AccountId)?'':c.Account.ShippingCity; 
        CaseCreationWrapper.CaseCreationValuesWrapper cityProps = wrapper.cityProps;
        if(cityName!=null && cityProps.isTrim && cityName.length()>cityProps.maxLength){
            reqBodyMap.put(cityProps.fieldName,cityName.substring(0,cityProps.maxLength));
        }
        else{
            reqBodyMap.put(cityProps.fieldName,cityName);
        }
        
        String contactEmail  = c.Contact_Email_Formula__c; 
        CaseCreationWrapper.CaseCreationValuesWrapper contactEmailProps = wrapper.contactEmailProps;
        if(contactEmail!=null && contactEmailProps.isTrim && contactEmail.length()>contactEmailProps.maxLength){
            reqBodyMap.put(contactEmailProps.fieldName,contactEmail.substring(0,contactEmailProps.maxLength));
        }
        else{
            reqBodyMap.put(contactEmailProps.fieldName,contactEmail);
        }
        
        String contactName  = String.isBlank(c.ContactId)?c.First_Name__c+' '+c.Last_Name__c:c.contact.Name; 
        CaseCreationWrapper.CaseCreationValuesWrapper contactNameProps = wrapper.contactNameProps;
        if(contactName!=null && contactNameProps.isTrim && contactName.length()>contactNameProps.maxLength){
            reqBodyMap.put(contactNameProps.fieldName,contactName.substring(0,contactNameProps.maxLength));
        }
        else{
            reqBodyMap.put(contactNameProps.fieldName,contactName);
        }
        
        String contactPhone  = c.Contact_Phone_Formula__c; 
        
        CaseCreationWrapper.CaseCreationValuesWrapper contactPhoneProps = wrapper.contactPhoneProps;
        if(contactPhone!=null && contactPhoneProps.isTrim && contactPhone.length()>contactPhoneProps.maxLength){
            reqBodyMap.put(contactPhoneProps.fieldName,contactPhone.substring(0,contactPhoneProps.maxLength));
        }
        else{
            reqBodyMap.put(contactPhoneProps.fieldName,contactPhone);
        }
        
        String country  = String.isBlank(c.AccountId)?'':c.Account.ShippingCountry; 
        CaseCreationWrapper.CaseCreationValuesWrapper countryProps = wrapper.countryProps;
        if(country!=null && countryProps.isTrim && country.length()>countryProps.maxLength){
            reqBodyMap.put(countryProps.fieldName,country.substring(0,countryProps.maxLength));
        }
        else{
            reqBodyMap.put(countryProps.fieldName,country);
        }
        
        String description  = c.Description; 
        CaseCreationWrapper.CaseCreationValuesWrapper descriptionProps = wrapper.descriptionProps;
        if(description!=null && descriptionProps.isTrim && description.length()>descriptionProps.maxLength){
            reqBodyMap.put(descriptionProps.fieldName,description.substring(0,descriptionProps.maxLength));
        }
        else{
            reqBodyMap.put(descriptionProps.fieldName,description);
        }
        
        String postalCode  = String.isBlank(c.AccountId)?'':c.Account.ShippingPostalCode; 
        CaseCreationWrapper.CaseCreationValuesWrapper postalCodeProps = wrapper.postalCodeProps;
        if(postalCode!=null && postalCodeProps.isTrim && postalCode.length()>postalCodeProps.maxLength){
            reqBodyMap.put(postalCodeProps.fieldName,postalCode.substring(0,postalCodeProps.maxLength));
        }
        else{
            reqBodyMap.put(postalCodeProps.fieldName,postalCode);
        }
        
        String state  = String.isBlank(c.AccountId)?'':c.Account.ShippingState; 
        CaseCreationWrapper.CaseCreationValuesWrapper stateProps = wrapper.stateProps;
        if(state!=null && stateProps.isTrim && state.length()>stateProps.maxLength){
            reqBodyMap.put(stateProps.fieldName,state.substring(0,stateProps.maxLength));
        }
        else{
            reqBodyMap.put(stateProps.fieldName,state);
        }
        
        String street  = String.isBlank(c.AccountId)?'':c.Account.ShippingStreet; 
        CaseCreationWrapper.CaseCreationValuesWrapper streetProps = wrapper.streetProps;
        if(street!=null && streetProps.isTrim && street.length()>streetProps.maxLength){
            reqBodyMap.put(streetProps.fieldName,street.substring(0,streetProps.maxLength));
        }
        else{
            reqBodyMap.put(streetProps.fieldName,street);
        }
        
        String subcategory  = c.Sub_Category__c; 
        CaseCreationWrapper.CaseCreationValuesWrapper subcategoryProps = wrapper.subcategoryProps;
        if(subcategory!=null && subcategoryProps.isTrim && subcategory.length()>subcategoryProps.maxLength){
            reqBodyMap.put(subcategoryProps.fieldName,subcategory.substring(0,subcategoryProps.maxLength));
        }
        else{
            reqBodyMap.put(subcategoryProps.fieldName,subcategory);
        }
        
        String subject  = c.Subject; 
        CaseCreationWrapper.CaseCreationValuesWrapper subjectProps = wrapper.subjectProps;
        if(subject!=null && subjectProps.isTrim && subject.length()>subjectProps.maxLength){
            reqBodyMap.put(subjectProps.fieldName,subject.substring(0,subjectProps.maxLength));
        }
        else{
            reqBodyMap.put(subjectProps.fieldName,subject);
        }
        
        return JSON.serializePretty(reqBodyMap,true); 
    }
    
    /***************************************************************************************************************************************
Method Name : createRetryCounterMap
Description : This method is for retry counter details.
Return type : void
Author      : Graytitude
*************************************************************************************************************************************/
    private void createRetryCounterMap(list<String> callOutCaseIds){
        for(Integration_Log__c intlog:[SELECT Id,identifier__c,Retry_Counter__c from Integration_Log__c  where identifier__c in :callOutCaseIds]){
            retryCounterMap.put(intlog.identifier__c,intlog.Retry_Counter__c); //this is incorrect. See comments where this is called
        }
    } 
    /***************************************************************************************************************************************
Method Name : scheduleJobForCaseCreationRetry
Description : This method is for making callout after certain time Intervals.
Return type : void
Author      : Graytitude
*************************************************************************************************************************************/
    private void scheduleJobForCaseCreationRetry(list<Id> retryCases){
        Decimal retryInterval = integrationSettings.Retry_Interval__c;
        if(!retryCases.IsEmpty()){ 
            DateTime dt = Datetime.now();
            Integer day = dt.Day();
            string mnthstr = dt.format('MMM');
            //Integer month = dt.Month(); 
            Integer year = dt.Year(); 
            String hour = String.valueOf(Datetime.now().hour());
            String min = String.valueOf(Datetime.now().minute()); 
            //Adding the interval of 10 secs
            String ss = String.valueOf(Datetime.now().second() + retryInterval);
            
            //construct cron expression
            String nextjobRun = ss+' '+min+' '+hour+' '+day+' '+mnthstr+' ? '+year;
            CaseCreationSchedulable s = new CaseCreationSchedulable(retryCases,accessToken);
            System.schedule('CaseCreationRetry ' + Datetime.now(), nextjobRun, s);
            //System.enqueueJob(new CaseCreationQueueable(retryCases));
        }
    } 
    
    public class CreateCaseResponse{
        public Result result {get;set;} 
    }
    public class Result {
        public String case_number {get;set;} 
        public String state {get;set;} 
    }
}