src/objects/Account.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Account/fields/EC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>EC_Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EC_CDM_Account__c.field-meta.xml
<CustomField>
    <fullName>EC_CDM_Account__c</fullName>
    <description>US-74958:Raghav:26/06/2019:This field will be used for mapping between CDM and account object.</description>
    <externalId>true</externalId>
    <label>External Account Key</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EC_CDM_Contact__c</fullName>
        <description>US-74958:Raghav:26/06/2019:This field will be used for mapping between CDM and contact object.</description>
        <externalId>true</externalId>
        <label>External Contact Key</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EC_isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>New Checkbox to soft delete the contacts</description>
        <label>EC_isActive</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>EC_CDM_User__c</fullName>
        <description>US-74960:Raghav:26/06/2019:This field will be used for mapping between CDM and user object.</description>
        <externalId>true</externalId>
        <label>External UserKey</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

force-app/main/default/classes/EC_StagingPermissionUserUpdateTest.cls
@istest
public class EC_StagingPermissionUserUpdateTest {
    /***************************************************************************************************************************************
Method Name : createPermissionSetAssignment
Description : Used to test Permission Set Insert scenarios for staging Records
Return type : void
Author      : Shivam Vats
*************************************************************************************************************************************/
    
    @istest 
    public static void createPermissionSetAssignment(){
        List<RecordType> lstRecordTypeSoldTO =  [SELECT id,DeveloperName from RecordType where Name = :Label.EC_Account_SoldTo];
        
        Account testSoldParent = new Account();
        testSoldParent.Name = 'TESTSOldParenNamehere';
        testSoldParent.EC_Account_Number__c = '14102012';
        testSoldParent.EC_CDM_Account__c = '14102012';
        testSoldParent.RecordTypeId = lstRecordTypeSoldTO[0].Id;
        Insert testSoldParent;
        
        
        Contact contactCC = new Contact(
            FirstName = 'Community',
            LastName  = 'StagingPermissionTest2',
            Email = 'testingContacthere@xydfz.com',
            MailingStreet = 'abc',
            AccountId = testSoldParent.Id,
            EC_CDM_Contact__c = '15102019',
            EC_isActive__c = true
        );
        
        insert contactCC;
        User testOwner = [SELECT TimeZoneSidKey, UserRoleId
                          FROM User
                          WHERE Id = :UserInfo.getUserId()];
        
        system.runAs(testOwner){
            UserRole role = new UserRole(DeveloperName = 'TestUser1', Name = 'TestRole');
            insert role;
            
            Profile profile = [SELECT Id
                               FROM Profile
                               WHERE Name = 'Ecolab Customer Community Plus Users' LIMIT 1];
            
            
            String emailAddress = String.valueOf(System.now().getTime() + '@3cc-test.mail');
            User  testUser = new User(
                Alias                    = 'cctest',
                Email                    = emailAddress,
                EmailEncodingKey         = 'UTF-8',
                LastName                 = 'TestUser',
                LanguageLocaleKey        = 'en_US',
                LocaleSidKey             = 'en_US',
                ProfileId                = profile.Id,
                TimeZoneSidKey           = testOwner.TimeZoneSidKey,
                Username                 = emailAddress,
                isActive                 = true,
                ContactId                = contactCC.Id,
                Contact                  = contactCC,
                UserRole                 = role,
                EC_CDM_User__c           = '15102019'
                
            );
            insert testUser;       
        }
        
        List<String> lstUserKeys = new List<String>();
        lstUserKeys.add(contactCC.EC_CDM_Contact__c);
        
        test.startTest();
        EC_StagingPermissionUserUpdate batchObj = new EC_StagingPermissionUserUpdate(lstUserKeys);
        Id batchId = Database.executeBatch(batchObj,2);
        test.stopTest();
        
    }
}