src/objects/Account.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Account/fields/EC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>EC_Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EC_Billing_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>EC_Billing_Account_Number__c</fullName>
    <externalId>true</externalId>
    <label>Billing Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
        <fields>
        <fullName>Default_Unloading_Point__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Selected Unloading Point</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipLabel>CC Carts (Default Unloading Point)</relationshipLabel>
        <relationshipName>CC_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__EffectiveAccountID__c</fullName>
        <description>Holds the effective account for this cart.  This field will be utilized in implementations where a user can order for multiple accounts inclusive or exclusive of their own.  The effective account is used to control the entitlements, pricing, integrations etc that drive the site experience.</description>
        <inlineHelpText>This field will be utilized in implementations where a user can order for multiple accounts inclusive or exclusive of their own.  The effective account is used to control the entitlements, pricing, integrations etc that drive the site experience.</inlineHelpText>
        <label>Effective Account ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__EncryptedId__c</fullName>
        <description>Semi-random UUID used to refer to the order in URLs.</description>
        <label>Encrypted Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_ContactAddr__c.object
<CustomObject>
    <description>Used to store address information.  Associated with Carts, Orders, Invoices, Subscriptions, Payments, etc.</description>
    <fields>
        <fullName>EC_Account_Number__c</fullName>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Contact Address</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Contact Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Contact Addresss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within B2B Commerce</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EC_ccLogicCartPriceTest.cls
/* Test Class Name : EC_ccLogicCartPriceTest
* Class Name       : EC_ccLogicCartPrice
* Description      : Below class is a test class to EC_ccLogicCartPrice
* Created By       : Bharath KN
* Created On       : 05/27/2020

* Modification Log:
* ----------------------------------------------------------------------------------------------------------------
* Developer                Date                   Description
* ----------------------------------------------------------------------------------------------------------------
* Bharath                 05/27/2020               Created the initial class.
*/
@isTest
public without sharing class  EC_ccLogicCartPriceTest {
    
    static testMethod void processMethod() {
        Map<String, Object> testData=new Map<String, Object>();
        EC_TestData.setupCatalog();
        EC_TestData.setupTestUser();
        Account shipTo = EC_TestData.testAccountShipTo;
        ccrz__E_ContactAddr__c unloadingPoint = new ccrz__E_ContactAddr__c();
        unloadingPoint.EC_Account_Number__c = shipTo.EC_Billing_Account_Number__c;
        insert unloadingPoint;
        ccrz.cc_CallContext.effAccountId = shipTo.id;
        ccrz__E_Cart__c cart = EC_TestData.createCart();
        cart.ccrz__EffectiveAccountID__c = shipTo.Id;
        cart.Default_Unloading_Point__c =unloadingPoint.Id;
        update cart;
        ccrz.cc_CallContext.currCartId = cart.ccrz__EncryptedId__c;
        CCRZ.cc_CallContext.currPageName =  'ccrz__Cart';
        string cartId = cart.ccrz__EncryptedId__c;
        shipTo.Id = cart.ccrz__EffectiveAccountID__c;
        update shipTo;
        ccrz__E_Product__c proditem = [SELECT id, ccrz__sku__c FROM ccrz__E_Product__c LIMIT 1  ]; 
        system.debug('proditem' + proditem);
        EC_CartDetailController.updateCartItemUOM(cartId);
        Test.startTest();
        EC_ccLogicCartPrice var=new EC_ccLogicCartPrice();
        Map<String,Object> resp = var.process(testData);
        System.assert(null != resp);
        Test.stopTest();        
    }
}