src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EC_Division__c</fullName>
        <description>This field specifies the division that a Ship To account is related to.</description>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Institutional</fullName>
                    <label>INSTITUTIONAL</label>
                </value>
                <value>
                    <fullName>WATER</fullName>
                </value>
                <value>
                    <fullName>PAPER</fullName>
                </value>
                <value>
                    <fullName>FOOD &amp; BEVERAGE</fullName>
                </value>
                <value>
                    <fullName>ENERGY</fullName>
                </value>
                <value>
                    <fullName>PEST</fullName>
                </value>
                <value>
                    <fullName>TEXTILE CARE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Account/fields/EC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>EC_Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EC_Billing_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>EC_Billing_Account_Number__c</fullName>
    <externalId>true</externalId>
    <label>Billing Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/AccountContactRelation.object
<CustomObject>
    <fields>
        <fullName>Alignment_Type__c</fullName>
        <description>Holds alignment type sent from CDM</description>
        <label>Alignment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Account Owner</fullName>
                </value>
                <value>
                    <fullName>Caretaker</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
                <value>
                    <fullName>Shared</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/ccrz__E_AccountAddressBook__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>ccrz__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account that owns the address book entry</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC Address Books</relationshipLabel>
        <relationshipName>E_AccountAddressBooks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__E_ContactAddress__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CC Contact Address</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipLabel>CC Address Books</relationshipLabel>
        <relationshipName>E_Account_Address_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Account Address Book</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Account Address Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_AccountGroup__c.object
<CustomObject>
    <description>This object is used to group multiple accounts together to provide pricing and/or entitlements.  An account group can have 1 or more accounts associated with it.  It also can have 1 or more pricelists (used for pricing and entitlements) associated.  This object then ties the accounts and entitlements/pricing together, ultimately controlling the product list and pricing that a given account can see within B2B Commerce.</description>
    <label>CC Account Group</label>
    <nameField>
        <label>Account Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Account Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>EC_Ship_To_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC Carts (Ship To Account)</relationshipLabel>
        <relationshipName>CC_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Account of the User that this cart was created for.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Carts</relationshipLabel>
        <relationshipName>E_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__EncryptedId__c</fullName>
        <description>Semi-random UUID used to refer to the order in URLs.</description>
        <label>Encrypted Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_ContactAddr__c.object
<CustomObject>
    <description>Used to store address information.  Associated with Carts, Orders, Invoices, Subscriptions, Payments, etc.</description>
    <fields>
        <fullName>EC_Account_Number__c</fullName>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Contact Address</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Contact Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Contact Addresss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EC_cc_hk_EffectiveAccountTest.cls
/* Class Name    : EC_cc_hk_EffectiveAccountTest
 * Description      Test Class to cover EC_cc_hk_EffectiveAccount
 * Created By       :Viraj 
 * Created On       :2019-Jul-3
 

 * Modification Log:
 * -----------------------------------------------------------------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID         Description
 * -----------------------------------------------------------------------------------------------------------------------------------------------------------------
 * Viraj     2019-Jul-3      BC-76559        Created the class   
 *
 */
@isTest
public class EC_cc_hk_EffectiveAccountTest{
    /***************************************************************************************************************************************
  Method Name : fetchAccountsTest
  Description : Test method to cover fetchAccounts and EC_SetAccount_BillingNumber class
  Return type : void
 *************************************************************************************************************************************/
    @isTest 
    static void fetchAccountsTest(){
        
        User thisUser = [SELECT Id  FROM User WHERE Id = :UserInfo.getUserId()];

        system.runas(thisUser){
            
            EC_TestData.setupCatalog();
            EC_TestData.setupTestUser();
            
            Map<String,Object> inData = new Map<String,Object>();
            Contact con =[SELECT id, FirstName, LastName from Contact limit 1]; //PBI-121283
            //Contact con =[SELECT id from Contact limit 1];
            CCRZ.cc_CallContext.currContact = con;
            
            AccountContactRelation accCon = new AccountContactRelation();
            accCon.AccountId = EC_TestData.testAccountSoldTo.id;
            accCon.ContactId = con.id;
            accCon.Alignment_Type__c = EC_Constants.PRIMARY_ALIGNMENT_TYPE;
            Insert accCon;
            
            accCon = new AccountContactRelation();
            accCon.AccountId = EC_TestData.testAccountShipTo.id;
            accCon.ContactId = con.id;
            accCon.Alignment_Type__c = EC_Constants.PRIMARY_ALIGNMENT_TYPE;
            Insert accCon;
			
            accCon = new AccountContactRelation();
            accCon.AccountId = EC_TestData.testAccountShipTo2.id;
            accCon.ContactId = con.id;
            Insert accCon;
            									  
            Account shipTo = EC_TestData.testAccountShipTo;
            Account shipTo2 = EC_TestData.testAccountShipTo2;
            Account shipTolone2 = EC_TestData.testAccountShipTolone2;
            Account shipTocorp2 = EC_TestData.testAccountShipTocorp2;
			Account soldToFaB = EC_TestData.testAccountShipToFaB;	
            soldToFaB.EC_Account_Number__c    = '';
            soldToFaB.EC_Billing_Account_Number__c = 'Test';
            update  soldToFaB;      
            soldToFaB.EC_Account_Number__c    = EC_TestData.generateRandomString(5);
            update soldToFaB;     												 
            
            accCon = new AccountContactRelation();
            accCon.AccountId = shipTolone2.id;
            accCon.ContactId = con.id;
            Insert accCon;
            
            accCon = new AccountContactRelation();
            accCon.AccountId = shipTocorp2.id;
            accCon.ContactId = con.id;
            Insert accCon;
            
			accCon = new AccountContactRelation();
            accCon.AccountId = soldToFaB.id;
            accCon.ContactId = con.id;
            accCon.Alignment_Type__c = EC_Constants.PRIMARY_ALIGNMENT_TYPE;
            Insert accCon;	
			
            ccrz.cc_CallContext.currAccountId = EC_TestData.testAccount.id;
            ccrz.cc_CallContext.effAccountId = shipTo.id;
            
            inData.put(ccrz.cc_hk_EffectiveAccount.PARAM_EFFACCOUNT_LIST,new List<ccrz.cc_bean_EffectiveAccount>{new ccrz.cc_bean_EffectiveAccount(EC_TestData.testAccountSoldTo)});
            Map<String,Object> outData = new Map<String,Object>();
            EC_cc_hk_EffectiveAccount classOb = new EC_cc_hk_EffectiveAccount();
            Test.startTest();
            outData = classOb.fetchAccounts(inData);
            System.assertNotEquals(outData,null);
            
            ccrz.cc_CallContext.effAccountId = EC_TestData.testAccountSoldTo.id;
            outData = classOb.fetchAccounts(inData);
            System.assertNotEquals(outData,null);
            
            ccrz.cc_CallContext.effAccountId = shipTolone2.id;
            outData = classOb.fetchAccounts(inData);
            System.assertNotEquals(outData,null);
            
            ccrz.cc_CallContext.effAccountId = shipTocorp2.id;
            outData = classOb.fetchAccounts(inData);
            System.assertNotEquals(outData,null);
            
			ccrz.cc_CallContext.effAccountId = soldToFaB.id;
            outData = classOb.fetchAccounts(inData);
			System.assertNotEquals(outData,null);			
			
            ccrz__E_Cart__c cartOb = EC_TestData.createCart();
			cartOb.EC_Ship_To_Account__c = EC_TestData.testAccountShipTo.id;
            update cartOb;
            CCRZ.cc_CallContext.currCartId = cartOb.ccrz__EncryptedId__c;
            inData.put('CartData',cartOb);
            outData = classOb.saveCart(inData);
            
            ccrz.cc_CallContext.effAccountId = shipTo.id;
            ccrz__E_AccountAddressBook__c addrBook = new ccrz__E_AccountAddressBook__c();
            ccrz__E_ContactAddr__c  conAddr = new ccrz__E_ContactAddr__c ();
            insert conAddr;
            addrBook.ccrz__Account__c= EC_TestData.testAccountShipTo.id;
            addrBook.ccrz__E_ContactAddress__c = conAddr.id;
            insert addrBook;
            
            outData = classOb.saveCart(inData);
            
            Account testAccount1 = new Account();
            Account testAccount2 = new Account();
            
            testAccount1.Name = 'testAccount2';
            testAccount1.EC_Division__c = 'WATER';
            testAccount1.EC_Account_Number__c = '000456456WA';
            testAccount1.RecordTypeId = EC_TestData.getRecordType('soldTo');
            insert  testAccount1;
            
            testAccount2.Name = 'testAccount1';
            testAccount2.EC_Division__c = 'WATER';
            testAccount2.EC_Account_Number__c = '000456456WA/000345346JIASJI';
            testAccount2.RecordTypeId = EC_TestData.getRecordType('shipTo');
            testAccount2.ParentId = testAccount1.Id;
            insert testAccount2;

            System.assertNotEquals(outData,null);
            
            Test.stopTest();
        }
        
      
    }
    
    
      
    @isTest 
    static void fetchAccounts2Test(){
        
        User thisUser = [SELECT Id  FROM User WHERE Id = :UserInfo.getUserId()];

        system.runas(thisUser){
            
            EC_TestData.setupCatalog();
            EC_TestData.setupTestUser();
            
            Map<String,Object> inData = new Map<String,Object>();
            Contact con =[SELECT id, FirstName, LastName from Contact limit 1]; //PBI-121283
            //Contact con =[SELECT id from Contact limit 1];
            CCRZ.cc_CallContext.currContact = con;
            
            AccountContactRelation accCon = new AccountContactRelation();
            accCon.AccountId = EC_TestData.testAccountSoldTo.id;
            accCon.ContactId = con.id;
            accCon.Alignment_Type__c = EC_Constants.PRIMARY_ALIGNMENT_TYPE;
            Insert accCon;
            
            
            Account testAccountShipTo = [Select Id,Name,ccrz__E_AccountGroup__c,ShippingStreet,ShippingCity,ShippingPostalCode,ShippingCountry,ShippingState,RecordTypeId,BillingStreet,BillingCity,
                                         BillingState,BillingCountry,BillingPostalCode,EC_Account_Number__c,ParentId,EC_Division__c from Account Where Id=:EC_TestData.testAccountShipTo.id Limit 1];
            testAccountShipTo.ParentId = EC_TestData.testAccountSoldTo.id;
            update testAccountShipTo;
            Account testAccountShipTo2 = [Select Id,Name,ccrz__E_AccountGroup__c,ShippingStreet,ShippingCity,ShippingPostalCode,ShippingCountry,ShippingState,RecordTypeId,BillingStreet,BillingCity,
                                         BillingState,BillingCountry,BillingPostalCode,EC_Account_Number__c,ParentId,EC_Division__c from Account Where Id=:EC_TestData.testAccountShipTo2.id Limit 1];
            testAccountShipTo2.ParentId = EC_TestData.testAccountSoldTo.id;
            update testAccountShipTo2;
            
            accCon = new AccountContactRelation();
            accCon.AccountId = testAccountShipTo.id;
            accCon.ContactId = con.id;
            accCon.Alignment_Type__c = EC_Constants.PRIMARY_ALIGNMENT_TYPE;
            Insert accCon;
			
            accCon = new AccountContactRelation();
            accCon.AccountId = testAccountShipTo2.id;
            accCon.ContactId = con.id;
            Insert accCon;
            									  
            Account shipTo = testAccountShipTo;
            Account shipTo2 = testAccountShipTo2;
            Account shipTolone2 = EC_TestData.testAccountShipTolone2;
            Account shipTocorp2 = EC_TestData.testAccountShipTocorp2;
			Account soldToFaB = EC_TestData.testAccountShipToFaB;	
            soldToFaB.EC_Account_Number__c    = '';
            soldToFaB.EC_Billing_Account_Number__c = 'Test';
            update  soldToFaB;      
            soldToFaB.EC_Account_Number__c    = EC_TestData.generateRandomString(5);
            update soldToFaB;     												 
            
            accCon = new AccountContactRelation();
            accCon.AccountId = shipTolone2.id;
            accCon.ContactId = con.id;
            Insert accCon;
            
            accCon = new AccountContactRelation();
            accCon.AccountId = shipTocorp2.id;
            accCon.ContactId = con.id;
            Insert accCon;
            
			accCon = new AccountContactRelation();
            accCon.AccountId = soldToFaB.id;
            accCon.ContactId = con.id;
            accCon.Alignment_Type__c = EC_Constants.PRIMARY_ALIGNMENT_TYPE;
            Insert accCon;	
			
            ccrz.cc_CallContext.currAccountId = EC_TestData.testAccount.id;
            ccrz.cc_CallContext.effAccountId = shipTo.id;
            
            inData.put(ccrz.cc_hk_EffectiveAccount.PARAM_EFFACCOUNT_LIST,new List<ccrz.cc_bean_EffectiveAccount>{new ccrz.cc_bean_EffectiveAccount(EC_TestData.testAccountSoldTo)});
            Map<String,Object> outData = new Map<String,Object>();
            EC_cc_hk_EffectiveAccount classOb = new EC_cc_hk_EffectiveAccount();
            Test.startTest();
            outData = classOb.fetchAccounts(inData);
            System.assertNotEquals(outData,null);
            
            ccrz.cc_CallContext.effAccountId = EC_TestData.testAccountSoldTo.id;
            outData = classOb.fetchAccounts(inData);
            System.assertNotEquals(outData,null);
            
            ccrz.cc_CallContext.effAccountId = shipTolone2.id;
            outData = classOb.fetchAccounts(inData);
            System.assertNotEquals(outData,null);
            
            ccrz.cc_CallContext.effAccountId = shipTocorp2.id;
            outData = classOb.fetchAccounts(inData);
            System.assertNotEquals(outData,null);
            
			ccrz.cc_CallContext.effAccountId = soldToFaB.id;
            outData = classOb.fetchAccounts(inData);
			System.assertNotEquals(outData,null);			
			
            ccrz__E_Cart__c cartOb = EC_TestData.createCart();
			cartOb.EC_Ship_To_Account__c = testAccountShipTo.id;
            update cartOb;
            CCRZ.cc_CallContext.currCartId = cartOb.ccrz__EncryptedId__c;
            inData.put('CartData',cartOb);
            outData = classOb.saveCart(inData);
            
            ccrz.cc_CallContext.effAccountId = shipTo.id;
            ccrz__E_AccountAddressBook__c addrBook = new ccrz__E_AccountAddressBook__c();
            ccrz__E_ContactAddr__c  conAddr = new ccrz__E_ContactAddr__c ();
            insert conAddr;
            addrBook.ccrz__Account__c= testAccountShipTo.id;
            addrBook.ccrz__E_ContactAddress__c = conAddr.id;
            insert addrBook;
            
            outData = classOb.saveCart(inData);
            
            Account testAccount1 = new Account();
            Account testAccount2 = new Account();
            
            testAccount1.Name = 'testAccount2';
            testAccount1.EC_Division__c = 'WATER';
            testAccount1.EC_Account_Number__c = '000456456WA';
            testAccount1.RecordTypeId = EC_TestData.getRecordType('soldTo');
            insert  testAccount1;
            
            testAccount2.Name = 'testAccount1';
            testAccount2.EC_Division__c = 'WATER';
            testAccount2.EC_Account_Number__c = '000456456WA/000345346JIASJI';
            testAccount2.RecordTypeId = EC_TestData.getRecordType('shipTo');
            testAccount2.ParentId = testAccount1.Id;
            insert testAccount2;

            System.assertNotEquals(outData,null);
            
            Test.stopTest();
        }
    }
}