src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EC_Division__c</fullName>
        <description>This field specifies the division that a Ship To account is related to.</description>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Institutional</fullName>
                    <label>INSTITUTIONAL</label>
                </value>
                <value>
                    <fullName>WATER</fullName>
                </value>
                <value>
                    <fullName>PAPER</fullName>
                </value>
                <value>
                    <fullName>FOOD &amp; BEVERAGE</fullName>
                </value>
                <value>
                    <fullName>ENERGY</fullName>
                </value>
                <value>
                    <fullName>PEST</fullName>
                </value>
                <value>
                    <fullName>TEXTILE CARE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>EC_Ship_To_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC Carts (Ship To Account)</relationshipLabel>
        <relationshipName>CC_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>The storefront under which the order was placed.</description>
        <label>Storefront</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>EC_Division__c</fullName>
        <formula>TEXT(ccrz__OriginatedCart__r.EC_Ship_To_Account__r.EC_Division__c)</formula>
        <label>Division</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__OrderStatus__c</fullName>
        <description>Displayed order status. Orders initially placed are all in Order Submitted status. All other statuses may be implementation specific.</description>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancel Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Return Submitted</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Partial Shipped</fullName>
                </value>
                <value>
                    <fullName>Bill Of Material</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__OriginatedCart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the CC Cart object used to create this order.</description>
        <label>Originated Cart</label>
        <referenceTo>ccrz__E_Cart__c</referenceTo>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>The storefront under which the order was placed.</description>
        <label>Storefront</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/EC_OrderSubmissionBatchJobTest.cls
/********************************************************************************************************
* @Class Name    EC_OrderSubmissionBatchJobTest 
* @description   EC_OrderSubmissionBatchJobTest is used to test functionality of EC_OrderSubmissionBatchJob
* @Created By -  Ravindra Singh  
* @Created On -  2019-8-25
* *********************************************************************************************************

 * Modification Log:  
 * ------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID             Description 
 * ------------------------------------------------------------------------------------------------------
 * Ravindra               2019-8-25                                    Initial version
 *********************************************************************************************************/ 


@isTest
public class EC_OrderSubmissionBatchJobTest {

  
   /***************************************************************************************************************************************
      Method Name : testBatchWithException
      Description : This method is used to test exception scenario
      Return type : void
     **************************************************************************************************************************************/
     
     

    static testMethod void testBatchWithException() {
         EC_TestData.setupTestUser();
         EC_TestData.setupCatalog();
         list<ccrz__E_Order__c> orders = EC_TestData.createOrders(1);
          orders[0].ccrz__OrderStatus__c = 'Failed';
          orders[0].ccrz__Storefront__c = 'Exception Condition';
          update orders;
         
        ccrz__E_Cart__c cart = [Select id,EC_Ship_To_Account__c from ccrz__E_Cart__c where id = :orders[0].ccrz__OriginatedCart__c];
        Account acc = [Select id,EC_Division__c from Account Where id = :cart.EC_Ship_To_Account__c];
        acc.EC_Division__c = 'Institutional';
        update acc;
             
        Test.startTest();
            EC_OrderSubmissionBatchJob bJob = new EC_OrderSubmissionBatchJob();
            Database.executeBatch(bJob); 
        Test.stopTest();
        
        ccrz__E_Order__c order = [select ccrz__OrderStatus__c from ccrz__E_Order__c where Id = :orders[0].Id];
        system.assert( order.ccrz__OrderStatus__c == 'Failed');

    }
    
   
  
   /***************************************************************************************************************************************
      Method Name : testBatchJobWithNoRecords
      Description : This method is used to test order submission batch job
      Return type : void
     **************************************************************************************************************************************/
     
    
    static testMethod void testBatchJobWithNoRecords(){
        
        Test.startTest();
            EC_OrderSubmissionBatchJob bJob = new EC_OrderSubmissionBatchJob();
           Database.executeBatch(bJob);
           
        Test.stopTest();
        
    }
    
}