src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EC_Division__c</fullName>
        <description>This field specifies the division that a Ship To account is related to.</description>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Institutional</fullName>
                    <label>INSTITUTIONAL</label>
                </value>
                <value>
                    <fullName>WATER</fullName>
                </value>
                <value>
                    <fullName>PAPER</fullName>
                </value>
                <value>
                    <fullName>FOOD &amp; BEVERAGE</fullName>
                </value>
                <value>
                    <fullName>ENERGY</fullName>
                </value>
                <value>
                    <fullName>PEST</fullName>
                </value>
                <value>
                    <fullName>TEXTILE CARE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Account/fields/EC_SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>EC_SalesOrg__c</fullName>
    <label>SalesOrg</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Billing_Arrangement_Types__mdt.object
<CustomObject>
    <description>List of Billing Arrangement Types which are in Scope (Eg: Usage, Fixed, UseRisk)</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Applicable_On_BADP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Applicable On BADP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BA_Type_Code__c</fullName>
        <label>BA Type Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Billing Arrangement Type</label>
    <pluralLabel>Billing Arrangement Types</pluralLabel>
</CustomObject>

src/objects/ccrz__E_AccountGroup__c.object
<CustomObject>
    <description>This object is used to group multiple accounts together to provide pricing and/or entitlements.  An account group can have 1 or more accounts associated with it.  It also can have 1 or more pricelists (used for pricing and entitlements) associated.  This object then ties the accounts and entitlements/pricing together, ultimately controlling the product list and pricing that a given account can see within B2B Commerce.</description>
    <fields>
        <fullName>ccrz__Desc__c</fullName>
        <description>Short description of the account group - internal only.</description>
        <label>Desc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Account Group</label>
    <nameField>
        <label>Account Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Account Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_AccountGroupPriceList__c.object
<CustomObject>
    <description>Represents a mapping of Account Group to Pricelist.  This objects ties the two together, enabling the assignment and entitlement/pricing functionality.</description>
    <fields>
        <fullName>EC_Price_List_Type__c</fullName>
        <label>Price List Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Z1CP</fullName>
                </value>
                <value>
                    <fullName>Z1GP</fullName>
                </value>
                <value>
                    <fullName>Z1MP</fullName>
                </value>
                <value>
                    <fullName>ZFCP</fullName>
                </value>
                <value>
                    <fullName>ZF00</fullName>
                </value>
                <value>
                    <fullName>Z1LS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__AccountGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the account group</description>
        <label>Account Group</label>
        <referenceTo>ccrz__E_AccountGroup__c</referenceTo>
        <relationshipLabel>Account Group Price Lists</relationshipLabel>
        <relationshipName>E_AccountGroupPriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Enable__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag determining whether or not this mapping record is active</description>
        <label>Enable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer available for the account group.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is available to the account group will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the pricelist</description>
        <label>Pricelist</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>Account Group Price Lists</relationshipLabel>
        <relationshipName>E_AccountGroupPriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this mapping record is active. This is the first date the mapping will be applied</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Account Group Price List</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Acct Group Pricelist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Account Group Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceList__c.object
<CustomObject>
    <description>Represents a grouping of products to control pricing and entitlements.  The B2B Commerce pricelist object controls both pricing and entitlements, but can be used just for the purposes of entitlements. A list needs to be created for each currency that needs to be represented, allowing for different entitlments and pricing based on the locale and currency.</description>
    <fields>
        <fullName>EC_Price_List_Type__c</fullName>
        <description>This field stores the type of pricelist i.e. Sales Org, Customer Group</description>
        <inlineHelpText>This field stores the type of pricelist i.e. Sales Org, Customer Group</inlineHelpText>
        <label>Price List Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_List_Type_Expansion__c</fullName>
        <formula>IF(EC_Price_List_Type__c = &apos;FBA&apos;, &apos;Fixed BA&apos;, IF(EC_Price_List_Type__c = &apos;USG&apos;,&apos;Usage&apos;,IF(EC_Price_List_Type__c =&apos;USR&apos;,&apos;Use Risk&apos;,IF(EC_Price_List_Type__c=&apos;SBA&apos;,&apos;Special Pricing Agreement&apos;,&apos;&apos;))))</formula>
        <label>Price List Type Expansion</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Desc__c</fullName>
        <description>A description of the pricelist - internal only</description>
        <label>Desc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag determining whether or not this pricelist record is active</description>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer active.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is valid will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this pricelist record is active. This is the first date the pricing/entitlements will be applied</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BA_Allocated__c</fullName>
        <label>BA Allocated</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BA_Number__c</fullName>
        <description>To store BA number</description>
        <label>BA Number</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <label>CC Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceListItem__c.object
<CustomObject>
    <description>Represents an entry in the Pricelist.  Each pricelist object is made up of 1 or more pricelist item objects.  This item objects contain a reference to the product and hold a price value (0, in the case where only entitlements are being used).  The products referenced within these items will be displayed in search and product listings on the external site.</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The end date for the price list item.  The end date is the date at which the item will no longer be available.  For example if the end date is July 1, 2015 then the price list item is valid on June 30, 2015 but no longer valid on July 1, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Pricelist__c</fullName>
        <description>Required - The reference to the pricelist</description>
        <label>Pricelist</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>E_PriceListItems1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this item record is active. This is the first date the item will be active</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Price List Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>PriceListItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date that this product will be available.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The first date that this product will be available.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Package_Code__c</fullName>
        <description>formula field to get the package code from SKU</description>
        <formula>IF(CONTAINS(ccrz__SKU__c,&quot;.&quot; ), MID(ccrz__SKU__c, FIND(&apos;.&apos;, ccrz__SKU__c )+1,LEN(ccrz__SKU__c)) , &apos;&apos;)</formula>
        <label>Package Code</label>
        <type>Text</type>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Chemical_Product_Type__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To identify the bulk product (User Story-122127)</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Package_Code__c</fullName>
        <label>Package Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Chemical Product Type</label>
</CustomObject>

src/classes/EC_BillingArrangementController.cls
/* Class Name      : EC_BillingArrangementController
* Description      :Controller Class for Billing Arrangement and Billing Arrangement Detail PAge
* Created By       :Moin Sawar
* Created On       :2020-Aug-27


* Modification Log:
* ---------------------------------------------------------------------------------------------------------------------
* Developer                Date            Modification ID         Description
* ---------------------------------------------------------------------------------------------------------------------
* Moin Sawar            2020-Aug-27         PBI-                    Created the class
*
*/
global with sharing class EC_BillingArrangementController {
    //public List<baWrapper> bas{get;set;}
    public String baJSON {get;set;}
    public class baWrapper{
        public String profile{get;set;}
        public String baNumber{get;set;}
        public String baId{get;set;}
        public String baType{get;set;}
        public String baDesc{get;set;}
        public String startDate{get;set;}
        public String EndDate{get;set;}
        public List<ItemWrapper> prodLineItems {get;set;}
        public List<ItemWrapper> ItemWrapper{get;set;}
    }
    public class ItemWrapper{
        public Decimal price{get;set;}
        public String taxonomy{get;set;}
        public String customPricingUOM{get;set;}
        public Decimal customUnitPrice{get;set;}
        public String packageTypeUOM{get;set;}
        Public Integer PricePer{get;set;}
        public String startDate{get;set;}
        public String EndDate{get;set;}
        public ccrz__E_Product__c product{get;set;}
        public List<ccrz__E_PriceListItem__c> priceListItem{get;set;}
        public String uri{get;set;}
    }

    public class ProfileAndBAWrapper
    {
        public String loggedInUserProfile{get;set;}
        public List<baWrapper> baWrapper{get;set;}
        public ProfileAndBAWrapper(String loggedInUserProfile,List<baWrapper> baWrapper)
        {
            this.loggedInUserProfile=loggedInUserProfile;
            this.baWrapper = baWrapper;
        }
    } 

    public Boolean checkNALCO(){
        return true;
    }    
    
    /***************************************************************************
  Method Name : getBANums
  Description : queries all the pricelists 
  Return type : ccrz.cc_RemoteActionResult
***********************************************************************************/
    @RemoteAction
    global static ccrz.cc_RemoteActionResult getBANums(final ccrz.cc_RemoteActionContext ctx, string effAccountId) {
        
        ccrz.cc_RemoteActionResult res = new ccrz.cc_RemoteActionResult();
        res.success = false;
        try { 
            Set<String> BATypeSet = new Set<String>();
            List<Billing_Arrangement_Types__mdt> BATypes = new List<Billing_Arrangement_Types__mdt>();
            if(Billing_Arrangement_Types__mdt.sObjectType.getDescribe().isAccessible()){
                BATypes = [Select Label,BA_Type_Code__c,Active__c,Applicable_On_BADP__c from Billing_Arrangement_Types__mdt where Active__c = true AND Applicable_On_BADP__c =true];
                for (Billing_Arrangement_Types__mdt BAType : BATypes) {
                    BATypeSet.add(BAType.Label);
                }
            }
            
            List<baWrapper> baWrapperList =new List<baWrapper> ();
            Date today = Date.today();
            if(Account.sObjectType.getDescribe().isAccessible() && String.isNotBlank(effAccountId)){             
                List<Account> effAccountList = [Select Id,EC_SalesOrg__c,EC_Division__c,ccrz__E_AccountGroup__c FROM Account WHERE Id=:effAccountId LIMIT 1];
                if(ccrz__E_PriceList__c.sObjectType.getDescribe().isAccessible()){                                       
                    for(ccrz__E_PriceList__c pl: [select ID, BA_Allocated__c,Name,BA_Number__c,ccrz__StartDate__c,ccrz__EndDate__c,ccrz__Desc__c,Price_List_Type_Expansion__c from ccrz__E_PriceList__c where EC_Price_List_Type__c IN: BATypeSet and ccrz__StartDate__c <= :today and ccrz__EndDate__c>=:today and ccrz__Enabled__c = true 
                                                  AND ID IN (select ccrz__Pricelist__c from ccrz__E_AccountGroupPriceList__c where ccrz__AccountGroup__c=:effAccountList[0].ccrz__E_AccountGroup__c and ccrz__StartDate__c <= :today and ccrz__EndDate__c>=:today and ccrz__Enable__c = true)  order by ccrz__Desc__c asc ] ){
                                                      baWrapper baWrapperObj = new baWrapper();
                                                      baWrapperObj.baNumber = pl.BA_Number__c;
                                                      baWrapperObj.baId = pl.ID;
                                                      baWrapperObj.baType = pl.Price_List_Type_Expansion__c;
                                                      baWrapperObj.baDesc = pl.ccrz__Desc__c;
                                                      DateTime startDate = pl.ccrz__StartDate__c;
                                                      DateTime EndDate = pl.ccrz__EndDate__c;                         
                                                      String formattedordStartDate = startDate.formatGMT(EC_Constants.MMM)+' '+startDate.formatGMT(EC_Constants.d)+', '+startDate.formatGMT(EC_Constants.yyyy);
                                                      String formattedordEndDate = EndDate.formatGMT(EC_Constants.MMM)+' '+EndDate.formatGMT(EC_Constants.d)+', '+EndDate.formatGMT(EC_Constants.yyyy);
                                                      baWrapperObj.startDate = formattedordStartDate; 
                                                      baWrapperObj.EndDate = formattedordEndDate; 
                                                      baWrapperObj.profile = EC_QueryUtility.getProfile();  
                                                      baWrapperList.add(baWrapperObj);
                                                  }
                } 
                ProfileAndBAWrapper varWrapper = new ProfileAndBAWrapper(EC_QueryUtility.getProfile(),baWrapperList);
                res.success = true;
                res.data = varWrapper;
            }
        } catch(Exception ex) {
            system.debug('Exception occured on saving Billing Arrangement'+ ex.getMessage());
        }
        ccrz.cclog.log('saveBillingArrangement: ' , + res);
        return res;
    }        
/***************************************************************************
  Method Name : getBADetail
  Description : queries the price list item for particular Price List.
  Return type : ccrz.cc_RemoteActionResult
***********************************************************************************/
    @RemoteAction
    global static ccrz.cc_RemoteActionResult getBADetail(final ccrz.cc_RemoteActionContext ctx, string baId) {
         
        ccrz.cc_RemoteActionResult res = new ccrz.cc_RemoteActionResult();
        res.success = false;
        try {
            EC_BillingArrangementDetailHelper.fetchBADPData(res,baId);  
        } catch(Exception ex) {
            system.debug('Exception occured on saving Billing Arrangement'+ ex.getMessage());
        }
        ccrz.cclog.log('saveBillingArrangement: ' , + res);
        return res;
    }
    
/***************************************************************************
  Method Name : getPackageCode
  Description : return package code set.
  Return type : Set<String>
***********************************************************************************/
    
    public static Set<String> getPackageCode(){
        
        List<Chemical_Product_Type__c> pkgTypes = new List<Chemical_Product_Type__c>();
        pkgTypes = Chemical_Product_Type__c.getall().values();
        Set<String> pkgCodeSet = new Set<String>();
            for (Chemical_Product_Type__c pkgType : pkgTypes) {
                if(pkgType.Active__c == true) {
                    pkgCodeSet.add(pkgType.Package_Code__c);
                }
            }
        
        return pkgCodeSet;
    }

    /****************************************************************
Method Name : addToCartBADP
Description : add to cart from BADP
Return type : ccrz.cc_RemoteActionResult
**********************************************************************/
    @RemoteAction
    global static ccrz.cc_RemoteActionResult addToCartBADP(final ccrz.cc_RemoteActionContext ctx, string productId, string cartEncId,String baSFID) {
        ccrz.cc_CallContext.initRemoteContext(ctx);
        ccrz.cc_RemoteActionResult res = new ccrz.cc_RemoteActionResult();
        res.success = false;
        Savepoint sp = Database.setSavepoint();
        Boolean wasSuccessful = false;
        List<Map<string,Object>> cartItemsToInsert = new List<Map<string,Object>>();
        Map<string,Object> cartItem = new Map<string,Object>{
            'productId' => productId,
            ccrz.ccApiCart.LINE_DATA_QUANTITY => 1,
            'baSFID' => baSFID
        };
        cartItemsToInsert.add(cartItem);
        ccrz.ccLog.log(System.LoggingLevel.INFO, 'cartItemsToInsert',cartItemsToInsert);
        
        try {
            Map<String,Object> addResults = ccrz.ccApiCart.addTo(new Map<String,Object>{
                ccrz.ccApi.API_VERSION => ccrz.ccApi.CURRENT_VERSION,
                    ccrz.ccApiCart.CART_ENCID => cartEncId,
                    ccrz.ccApiCart.LINE_DATA => cartItemsToInsert
                    });          
            //General check, since the cart Id will be blank if not successful we technically do not need this.
            wasSuccessful = (Boolean)addResults.get(ccrz.ccApi.SUCCESS);
            res.data = cartEncId;
            res.success = wasSuccessful;
        } catch(Exception ex) {
            system.debug('Exception occured on stamping '+ ex.getMessage());
            ccrz.ccLog.log(System.LoggingLevel.ERROR, 'ERR',ex.getMessage());
        }finally{
            ccrz.ccLog.log(System.LoggingLevel.INFO,'M:X','myMethod');
            ccrz.ccLog.close(res);
        }
        if(!wasSuccessful){
            Database.rollback(sp);
        }
        return res;
    }  
    
}