src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EC_Division__c</fullName>
        <description>This field specifies the division that a Ship To account is related to.</description>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Institutional</fullName>
                    <label>INSTITUTIONAL</label>
                </value>
                <value>
                    <fullName>WATER</fullName>
                </value>
                <value>
                    <fullName>PAPER</fullName>
                </value>
                <value>
                    <fullName>FOOD &amp; BEVERAGE</fullName>
                </value>
                <value>
                    <fullName>ENERGY</fullName>
                </value>
                <value>
                    <fullName>PEST</fullName>
                </value>
                <value>
                    <fullName>TEXTILE CARE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/ccrz__E_PriceList__c.object
<CustomObject>
    <description>Represents a grouping of products to control pricing and entitlements.  The B2B Commerce pricelist object controls both pricing and entitlements, but can be used just for the purposes of entitlements. A list needs to be created for each currency that needs to be represented, allowing for different entitlments and pricing based on the locale and currency.</description>
    <fields>
        <fullName>ccrz__CurrencyISOCode__c</fullName>
        <description>Required - The 3-character ISO currency code corresponding to this list. For example, USD</description>
        <label>Currency ISO Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag determining whether or not this pricelist record is active</description>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer active.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is valid will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__PricelistId__c</fullName>
        <description>External reference id for this entry</description>
        <externalId>true</externalId>
        <label>Pricelist Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this pricelist record is active. This is the first date the pricing/entitlements will be applied</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>Mulit-select list that allows you to assign the pricelist to one or more storefronts.</description>
        <label>Storefront</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DefaultStore</fullName>
                </value>
                <value>
                    <fullName>Connect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceListItem__c.object
<CustomObject>
    <description>Represents an entry in the Pricelist.  Each pricelist object is made up of 1 or more pricelist item objects.  This item objects contain a reference to the product and hold a price value (0, in the case where only entitlements are being used).  The products referenced within these items will be displayed in search and product listings on the external site.</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The end date for the price list item.  The end date is the date at which the item will no longer be available.  For example if the end date is July 1, 2015 then the price list item is valid on June 30, 2015 but no longer valid on July 1, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>Holds the price for the item. If pricing is not being utilized, fill in a default value, such as 0.</description>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__PricelistItemId__c</fullName>
        <description>External reference id for this entry</description>
        <externalId>true</externalId>
        <label>Pricelist Item Id</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__Pricelist__c</fullName>
        <description>Required - The reference to the pricelist</description>
        <label>Pricelist</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>E_PriceListItems1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the product entry</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>E_PriceListItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this item record is active. This is the first date the item will be active</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__UnitOfMeasure__c</fullName>
        <description>Unit of Measure for this price.  This field in combination with the product can give UOM specific pricing.  This field is optional, and allows for general pricing for a product independent of UOM.</description>
        <inlineHelpText>Unit of Measure for this price.  This field in combination with the product can give UOM specific pricing.  This field is optional, and allows for general pricing for a product independent of UOM.</inlineHelpText>
        <label>Unit Of Measure</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Price List Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>PriceListItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date that this product will be available.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__HazardousFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Product is Hazardous.</description>
        <label>Hazardous Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__LongDesc__c</fullName>
        <description>Product long description</description>
        <label>LongDesc</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductId__c</fullName>
        <description>External product Id, tying this product to the source system. Typically contains the SKU/product id from a backend system such as SAP.</description>
        <externalId>true</externalId>
        <label>Product Id</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__ProductStatus__c</fullName>
        <description>The status of the product. In Creation - Newly created product, that still requires augmentation and is not visible on the site; Blocked - product has been blocked from being displayed on the site; Not Orderable - product can be viewed, but cannot be added to a cart or ordered; Released - fully availble product</description>
        <label>Product Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Not Orderable</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>In Creation</fullName>
                    <default>true</default>
                    <label>In Creation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__ProductWeight__c</fullName>
        <description>Weight of the product - used as a shipping parameter</description>
        <label>Product Weight</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within B2B Commerce</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__ShortDesc__c</fullName>
        <description>Product short description</description>
        <label>ShortDesc</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The first date that this product will be available.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>Mulit-select list that allows you to assign the product to one or more storefronts.</description>
        <label>Storefront</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DefaultStore</fullName>
                    <default>true</default>
                    <label>DefaultStore</label>
                </value>
                <value>
                    <fullName>Connect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__UnitOfMeasure__c</fullName>
        <description>Product unit of measure - such as Each</description>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Each</fullName>
                    <default>true</default>
                    <label>Each</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EC_ccLogicProductPricingTest.cls
/* Test Class Name  : EC_ccLogicProductPricingTest
* Class Name       : EC_ccLogicProductPricing
* Description      : Below class is a test class to EC_ccLogicProductPricing, whcih is used to for accessing custom fields for price list items in ccLogicProductPricing and accessing it in the model from the front-end
* Created By       : Bharath KN
* Created On       : 05/27/2020

* Modification Log:
* ----------------------------------------------------------------------------------------------------------------
* Developer                Date                   Description
* ----------------------------------------------------------------------------------------------------------------
* Bharath                 05/27/2020               Created the initial class.
*/
@isTest
private without sharing class EC_ccLogicProductPricingTest {

    @testSetup static void setup(){
         List<ccrz__E_Product__c> product = new List<ccrz__E_Product__c> {
            new ccrz__E_Product__c(
                Name                       = 'test',
                ccrz__SKU__c               = 'test001',
                ccrz__ProductId__c         = 'test001',
                ccrz__ProductStatus__c     = 'Released',
                ccrz__UnitOfMeasure__c     = 'BG',
                ccrz__StartDate__c         = Date.today().addDays(-7),
                ccrz__EndDate__c           = Date.today().addDays(7),
                ccrz__Storefront__c        = 'DefaultStore',
                ccrz__ProductWeight__c     = 500,
                ccrz__HazardousFlag__c     = true,
                ccrz__ShortDesc__c         ='product001 Bag',
                ccrz__LongDesc__c          ='product001 Bag')
                };
                    insert product;
        List<ccrz__E_PriceList__c> priceLists = new List<ccrz__E_PriceList__c> 
        {
            new ccrz__E_PriceList__c(
                Name                     = 'Enterprise',
                ccrz__CurrencyISOCode__c = 'USD',
                ccrz__Enabled__c         = true,
                ccrz__Storefront__c      = 'DefaultStore',
                ccrz__StartDate__c       = Date.today().addDays(-7),
                ccrz__EndDate__c         = Date.today().addDays(7),
                ccrz__PricelistId__c         = '250287'
            ),
                new ccrz__E_PriceList__c(
                    Name                     = 'Contract',
                    ccrz__CurrencyISOCode__c = 'USD',
                    ccrz__Enabled__c         = true,
                    ccrz__Storefront__c      = 'DefaultStore',
                    ccrz__StartDate__c       = Date.today().addDays(-7),
                    ccrz__EndDate__c         = Date.today().addDays(7),
                    ccrz__PricelistId__c         = '070289'
                )
                };
                    insert priceLists;
     }
    static testMethod void processMethod() {
        List<ccrz__E_Product__c> product = [Select    Name,ccrz__SKU__c ,ccrz__ProductId__c,ccrz__ProductStatus__c,ccrz__UnitOfMeasure__c,ccrz__StartDate__c,ccrz__EndDate__c,ccrz__Storefront__c,ccrz__ProductWeight__c,ccrz__HazardousFlag__c,ccrz__ShortDesc__c,ccrz__LongDesc__c from ccrz__E_Product__c];        
        List<ccrz__E_PriceList__c> priceLists = [Select Name,ccrz__CurrencyISOCode__c,ccrz__Enabled__c,ccrz__Storefront__c,ccrz__StartDate__c,ccrz__EndDate__c,ccrz__PricelistId__c from ccrz__E_PriceList__c];
        
        Account shipTo = EC_TestData.testAccountShipTo;
        ccrz.cc_CallContext.effAccountId = shipTo.id;
        Map<String,Object> productList = new Map<String, Object>();
        Map<String,Object> pricingResult = new Map<String, Object>();
        ccrz__E_PriceListItem__c objPriceListItem = new ccrz__E_PriceListItem__c();
        objPriceListItem .ccrz__Product__c = product[0].id;
        objPriceListItem .ccrz__Pricelist__c = priceLists[0].id;
        objPriceListItem.ccrz__StartDate__c = Date.today().addDays(-7);
        objPriceListItem.ccrz__EndDate__c = Date.today().addDays(7);
        insert objPriceListItem;
        ccrz__E_PriceListItem__c objPriceListItem1 = new ccrz__E_PriceListItem__c();
        objPriceListItem1 .ccrz__Product__c = product[0].id;
        objPriceListItem1 .ccrz__Pricelist__c = priceLists[1].id;
        objPriceListItem1.ccrz__StartDate__c = Date.today().addDays(-7);
        objPriceListItem1.ccrz__EndDate__c = Date.today().addDays(7);
        objPriceListItem1.ccrz__Price__c = 5;          
        objPriceListItem1.ccrz__PricelistItemId__c = '1235';
        insert objPriceListItem1;
        
        Map<String, Object> insidePricing = new Map<String, Object>();
        Map<String, Object> listObject = new Map<string, Object>();
        
        List<Map<String,Object>> productDataMapList = new List<Map<String,Object>>();
        for(ccrz__E_Product__c prd:product)
        {
            Map<String,Object> prodData = new Map<String,Object>();
            prodData.put('sfid',prd.Id);
            productDataMapList.add(prodData);
        }
        listObject.put('listItemID', objPriceListItem.Id);
        
        Map<String,Object> spfIDValue = new Map<String,Object>();
        spfIDValue.put('sfid',objPriceListItem.id);
        List<Map<String, Object>> listMap = new List<Map<String, Object>>();
        listMap.add(listObject);
        insidePricing.put(ccrz.cc_hk_Pricing.PRICE_MAP_ENTRIES, listMap);
        insidePricing.put('productPrice', spfIDValue);
        pricingResult.put(product[0].id, insidePricing);    
        
        Map<String, Object> testData=new Map<String, Object>();
        List<Map<String, Object>> productMapList = new List<Map<String, Object>>();
        productMapList.add(productList);
        testData.put('productList',productDataMapList);
        testData.put('productPricingData',pricingResult);
        
        testData.put('sfid',objPriceListItem1.Id);
        Map<string,Object> retData=new Map<string,Object>();
        Map<string,Object> retDataValue=new Map<string,Object>();
        retDataValue.put(''+product[0].id, product[0]);
        
        retData.put('sfid',objPriceListItem1.Id);
        retData.put('CustomFactor', 10);
        retData.put('CustomPricingUOM', 'KG');
        retData.put('CustomUnitPrice', 30.00);       
        
        retData.put('productPricingData',retDataValue);
        retData.put('PricePer',600);
        
        
        List<Map<string,Object>> lstPriceList = new List<Map<string,Object>>();
        lstPriceList.add(retData);
        System.debug('retData - > '+retData);   
        List<Map<string,Object>> lstProdList = new List<Map<string,Object>>();
        lstProdList.add(retData);
        testData.put('priceListItems',lstPriceList);
        
        Test.startTest();
        EC_ccLogicProductPricing var=new EC_ccLogicProductPricing();
        var.process(testData);
        system.assertNotEquals(var.process(testData), null);
        var.determinePrice(testData);
        system.assertNotEquals(var.determinePrice(testData), null);
        Test.stopTest();
    }
    static testMethod void processMethod2() {
        List<ccrz__E_Product__c> product = [Select    Name,ccrz__SKU__c ,ccrz__ProductId__c,ccrz__ProductStatus__c,ccrz__UnitOfMeasure__c,ccrz__StartDate__c,ccrz__EndDate__c,ccrz__Storefront__c,ccrz__ProductWeight__c,ccrz__HazardousFlag__c,ccrz__ShortDesc__c,ccrz__LongDesc__c from ccrz__E_Product__c];        
        List<ccrz__E_PriceList__c> priceLists = [Select Name,ccrz__CurrencyISOCode__c,ccrz__Enabled__c,ccrz__Storefront__c,ccrz__StartDate__c,ccrz__EndDate__c,ccrz__PricelistId__c from ccrz__E_PriceList__c];
        
        Account shipTo2 = EC_TestData.testAccountShipTo;
        shipTo2.EC_Division__c = 'INSTITUTIONAL';
        update shipTo2;
        ccrz.cc_CallContext.effAccountId = shipTo2.id;        
        Map<String,Object> productList = new Map<String, Object>();
        Map<String,Object> pricingResult = new Map<String, Object>();
        ccrz__E_PriceListItem__c objPriceListItem = new ccrz__E_PriceListItem__c();
        objPriceListItem .ccrz__Product__c = product[0].id;
        objPriceListItem .ccrz__Pricelist__c = priceLists[0].id;
        objPriceListItem.ccrz__StartDate__c = Date.today().addDays(-7);
        objPriceListItem.ccrz__EndDate__c = Date.today().addDays(7);
        insert objPriceListItem;
        ccrz__E_PriceListItem__c objPriceListItem1 = new ccrz__E_PriceListItem__c();
        objPriceListItem1 .ccrz__Product__c = product[0].id;
        objPriceListItem1 .ccrz__Pricelist__c = priceLists[1].id;
        objPriceListItem1.ccrz__StartDate__c = Date.today().addDays(-7);
        objPriceListItem1.ccrz__EndDate__c = Date.today().addDays(7);
        objPriceListItem1.ccrz__Price__c = 5;          
        objPriceListItem1.ccrz__PricelistItemId__c = '1235';
        insert objPriceListItem1;
        
        Map<String, Object> insidePricing = new Map<String, Object>();
        Map<String, Object> listObject = new Map<string, Object>();
        
        List<Map<String,Object>> productDataMapList = new List<Map<String,Object>>();
        for(ccrz__E_Product__c prd:product)
        {
            Map<String,Object> prodData = new Map<String,Object>();
            prodData.put('sfid',prd.Id);
            productDataMapList.add(prodData);
        }
        listObject.put('listItemID', objPriceListItem.Id);
        
        Map<String,Object> spfIDValue = new Map<String,Object>();
        spfIDValue.put('sfid',objPriceListItem.id);
        List<Map<String, Object>> listMap = new List<Map<String, Object>>();
        listMap.add(listObject);
        insidePricing.put(ccrz.cc_hk_Pricing.PRICE_MAP_ENTRIES, listMap);
        insidePricing.put('productPrice', spfIDValue);
        pricingResult.put(product[0].id, insidePricing);
                
        Map<String, Object> testData=new Map<String, Object>();
        List<Map<String, Object>> productMapList = new List<Map<String, Object>>();
        productMapList.add(productList);
        testData.put('productList',productDataMapList);
        testData.put('productPricingData',pricingResult);
        
        testData.put('sfid',objPriceListItem1.Id);
        Map<string,Object> retData=new Map<string,Object>();
        Map<string,Object> retDataValue=new Map<string,Object>();
        retDataValue.put(''+product[0].id, product[0]);
        
        retData.put('sfid',objPriceListItem1.Id);
        retData.put('CustomFactor', 10);
        retData.put('CustomPricingUOM', 'KG');
        retData.put('CustomUnitPrice', 30.00);       
        
        retData.put('productPricingData',retDataValue);
        
        
        List<Map<string,Object>> lstPriceList = new List<Map<string,Object>>();
        lstPriceList.add(retData);
        System.debug('retData - > '+retData);   
        List<Map<string,Object>> lstProdList = new List<Map<string,Object>>();
        lstProdList.add(retData);
        testData.put('priceListItems',lstPriceList);
        
        Test.startTest();
        EC_ccLogicProductPricing var=new EC_ccLogicProductPricing();
        var.process(testData);
        system.assertNotEquals(var.process(testData), null);
        var.determinePrice(testData);
        system.assertNotEquals(var.determinePrice(testData), null);
        Test.stopTest();
    }
}