src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EC_Division__c</fullName>
        <description>This field specifies the division that a Ship To account is related to.</description>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Institutional</fullName>
                    <label>INSTITUTIONAL</label>
                </value>
                <value>
                    <fullName>WATER</fullName>
                </value>
                <value>
                    <fullName>PAPER</fullName>
                </value>
                <value>
                    <fullName>FOOD &amp; BEVERAGE</fullName>
                </value>
                <value>
                    <fullName>ENERGY</fullName>
                </value>
                <value>
                    <fullName>PEST</fullName>
                </value>
                <value>
                    <fullName>TEXTILE CARE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Account/fields/EC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>EC_Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EC_Billing_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>EC_Billing_Account_Number__c</fullName>
    <externalId>true</externalId>
    <label>Billing Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EC_SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>EC_SalesOrg__c</fullName>
    <label>SalesOrg</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
        <fields>
        <fullName>Default_Unloading_Point__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Selected Unloading Point</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipLabel>CC Carts (Default Unloading Point)</relationshipLabel>
        <relationshipName>CC_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__EffectiveAccountID__c</fullName>
        <description>Holds the effective account for this cart.  This field will be utilized in implementations where a user can order for multiple accounts inclusive or exclusive of their own.  The effective account is used to control the entitlements, pricing, integrations etc that drive the site experience.</description>
        <inlineHelpText>This field will be utilized in implementations where a user can order for multiple accounts inclusive or exclusive of their own.  The effective account is used to control the entitlements, pricing, integrations etc that drive the site experience.</inlineHelpText>
        <label>Effective Account ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__EncryptedId__c</fullName>
        <description>Semi-random UUID used to refer to the order in URLs.</description>
        <label>Encrypted Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_ContactAddr__c.object
<CustomObject>
    <description>Used to store address information.  Associated with Carts, Orders, Invoices, Subscriptions, Payments, etc.</description>
    <fields>
        <fullName>EC_Account_Number__c</fullName>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>CC Contact Address</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Contact Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Contact Addresss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EC_ccLogicCartPrice.cls
/* Class Name      : EC_ccLogicCartPrice
* Description      : Logic Cart Price Related inherited cloud craze interface
* Created By       : Bharath KN 
* Created On       : 05-29-2020

* Modification Log:
* ------------------------------------------------------------------------------------------------------------------
* Developer                Date            Modification ID         Description
* ------------------------------------------------------------------------------------------------------------------
* Bharath KN               05-29-2020                              Initial version (log modification)
*
*
*/

global virtual with sharing class EC_ccLogicCartPrice extends ccrz.ccLogicCartPrice {
    global virtual override Map<String,Object> Process(Map<String,Object> inputData) {
        // Save UOM fields in cartItem for NALCO
        String effAccountId = ccrz.cc_CallContext.effAccountId;
        String division='';
        if (Account.sObjectType.getDescribe().isAccessible()) {
            List<Account> effAccountList = [Select Id,EC_SalesOrg__c,EC_Division__c FROM Account WHERE Id=:effAccountId LIMIT 1];
            if(!effAccountList.isEmpty()){
                division = effAccountList[0].EC_Division__c;
            }
        }
        if(System.label.EC_DivisionValueNACLO.containsIgnoreCase(division) && ccrz.cc_CallContext.currPageName =='ccrz__Cart') {
            String currCart = ccrz.cc_CallContext.currCartId;
            if (ccrz__E_Cart__c.sObjectType.getDescribe().isAccessible() && ccrz__E_ContactAddr__c.sObjectType.getDescribe().isAccessible()) {
                checkUnlodingPoint(currCart);
            }
            EC_CartDetailController.updateCartItemUOM(currCart);
        }
        Map<String,Object> retData = super.process(inputData);
        ccrz.cclog.log('ccLogicCartPriceAK applyPricing retData--->' + retData);
        return retData;
    }
    
    public static void checkUnlodingPoint(String currCart){
        List<ccrz__E_Cart__c> cart = [Select Id, Default_Unloading_Point__c,ccrz__EffectiveAccountID__c  from ccrz__E_Cart__c Where id=:currCart OR ccrz__EncryptedId__c =:currCart ];
        if(!cart.isEmpty() && cart[0].Default_Unloading_Point__c != null ){
            String billingAccountNumber = [Select EC_Billing_Account_Number__c from Account Where Id=:cart[0].ccrz__EffectiveAccountID__c].EC_Billing_Account_Number__c;
            Id selectedUnloadingPoint = cart[0].Default_Unloading_Point__c;
            List<ccrz__E_ContactAddr__c> unloadingPointForSelectedAccount = [SELECT Id, EC_Account_Number__c FROM ccrz__E_ContactAddr__c Where id=:selectedUnloadingPoint and Active__c=true and EC_Account_Number__c =: billingAccountNumber];
            cart[0].Default_Unloading_Point__c = null;
            if(ccrz__E_Cart__c.sObjectType.getDescribe().isAccessible() && unloadingPointForSelectedAccount.isEmpty()){
                update cart;
            }
        }
    }
}