src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EC_Division__c</fullName>
        <description>This field specifies the division that a Ship To account is related to.</description>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Institutional</fullName>
                    <label>INSTITUTIONAL</label>
                </value>
                <value>
                    <fullName>WATER</fullName>
                </value>
                <value>
                    <fullName>PAPER</fullName>
                </value>
                <value>
                    <fullName>FOOD &amp; BEVERAGE</fullName>
                </value>
                <value>
                    <fullName>ENERGY</fullName>
                </value>
                <value>
                    <fullName>PEST</fullName>
                </value>
                <value>
                    <fullName>TEXTILE CARE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>ccrz__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Account of the User that this cart was created for.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Carts</relationshipLabel>
        <relationshipName>E_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a CC Contact Address object that contains the ship to address data. This will be a unique copy of the address information captured during checkout.</description>
        <label>Ship To</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipLabel>Carts (ShipToID)</relationshipLabel>
        <relationshipName>E_Carts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_ContactAddr__c.object
<CustomObject>
    <description>Used to store address information.  Associated with Carts, Orders, Invoices, Subscriptions, Payments, etc.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__AddressFirstline__c</fullName>
        <description>First line of the street address.</description>
        <label>Address Firstline</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Contact Address</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Contact Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Contact Addresss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>EC_ERP_Order_Number__c</fullName>
        <formula>IF(ISNULL(ccrz__OrderId__c) || ccrz__OrderId__c == &apos;&apos; , &apos;See Order Confirmation&apos;,  ccrz__OrderId__c)</formula>
        <label>ERP Order Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Account of the User that this order was placed for.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EC_Division__c</fullName>
        <formula>TEXT(ccrz__OriginatedCart__r.EC_Ship_To_Account__r.EC_Division__c)</formula>
        <label>Division</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__OrderDate__c</fullName>
        <description>The date of the order.</description>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__OrderNumber__c</fullName>
        <description>Derived from the SFDC Name field as the digit portion of the order Name + 1000000.</description>
        <label>Order Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent order, which originally submitted the subscription for this order, if applicable</description>
        <inlineHelpText>Parent order, which originally submitted the subscription for this order, if applicable</inlineHelpText>
        <label>Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Children Orders</relationshipLabel>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a CC Contact Address object that contains the ship to address data. This will be a unique copy of the address information captured during checkout.</description>
        <label>Ship To</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipName>E_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_OrderItem__c.object
<CustomObject>
    <description>The E_OrderItem__c object contains the line level detail of placed orders.</description>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <description>The order that this order line is a part of.</description>
        <label>Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>The price of the product at the time the item was ordered.</description>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Custom_PricingUOM__c</fullName>
        <label>Custom Pricing UOM</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom_UnitPrice__c</fullName>
        <label>Custom UnitPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Order Items (ProductID)</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Order Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>OrderItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>Taxonomy__c</fullName>
        <description>To identity the type of product (Equipment or Chemical)</description>
        <label>Taxonomy </label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Package_Code__c</fullName>
        <description>formula field to get the package code from SKU</description>
        <formula>IF(CONTAINS(ccrz__SKU__c,&quot;.&quot; ), MID(ccrz__SKU__c, FIND(&apos;.&apos;, ccrz__SKU__c )+1,LEN(ccrz__SKU__c)) , &apos;&apos;)</formula>
        <label>Package Code</label>
        <type>Text</type>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_ProductMedia__c.object
<CustomObject>
    <description>Encapsulates media such as hero, thumbnail images, product brochures, owner&apos;s manuals, assembly guides, and videos associated with a product. Media&apos;s source could be in a form of attachment, static resource, or external resource(URI).</description>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <description>Reference to the category entry to which this media corresponds</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>E_ProductMedias</relationshipLabel>
        <relationshipName>E_ProductMedias</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__URI__c</fullName>
        <description>If the source is a URL, contains the full URL to the image. This should reference a location with secure storage (SSL defined)</description>
        <label>URI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Product Media</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Product Media Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Product Media</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Chemical_Product_Type__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To identify the bulk product (User Story-122127)</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Package_Code__c</fullName>
        <label>Package Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Chemical Product Type</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EC_SalesRep_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EC SalesRep User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/INST_Sales_Entitlement__c.object
<CustomObject>
    <description>This object is used by Informatica to dump the INST Sales Entitlement Data</description>
    <fields>
        <fullName>Taxonomy__c</fullName>
        <label>Taxonomy</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Chemical</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>INST Sales Entitlement</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>INST Sales Entitlement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>INST Sales Entitlements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>User_Type__c</fullName>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/EC_OrderInfo.cls
/* Class Name       :EC_OrderInfo
 * Description      :This is the controller class for homepage order processing
 * Created By       :Harsha N
 * Created On       :06-27-2019
 *
 * Modification Log:
 * ----------------------------------------------------------------------------------------------------------------
 * Developer                Date                Modification ID             Description
 * ----------------------------------------------------------------------------------------------------------------
 *  Harsha N               06-27-2019                                   The functionality to pull the 6 recent products purchased by the logged in user is added
 *
 */

public without sharing class EC_OrderInfo {

/***************************************************************************************************************************************
Method Name : getRecentOrder
Description : to fetch recent orders
Parameter   : N/A
Return type : List<ProdInfo>
Author      : Harsha N
*************************************************************************************************************************************/
    @AuraEnabled
    public static List<ProdInfo> getRecentOrder(){
        List<ProdInfo> lstProdInfo = new List<ProdInfo>();
        Contact con = new Contact() ;

            User usr = EC_QueryUtility.getCurrentUser();

            //Check if Salesrep
            if(usr.User_Type__c !='External'){
                List<Contact> conlist = [Select Id,EC_SalesRep_User__c from Contact where EC_SalesRep_User__c =: UserInfo.getUserId() limit 1];
                if(conlist.size()>0){
                  con = conlist[0];
                 }

                }

                List<AccountContactRelation> lstAccContRel = new List<AccountContactRelation>();

            //to check if user has an associated contact
            if(usr!=null && usr.contactId != null){
               lstAccContRel = EC_QueryUtility.getAccountContactRelation(usr);
               } else {
            lstAccContRel = [SELECT id, accountId, account.ccrz__E_AccountGroup__c FROM AccountContactRelation WHERE contactId =: con.Id];
               }

            List<String> lstAccIds = new List<String>();

            //to check if contact record is associated to the account
            if(lstAccContRel!=null){
                    for(AccountContactRelation accContRec : lstAccContRel){
                        lstAccIds.add(accContRec.accountId);
                    }
                }
                    List<ccrz__E_OrderItem__c> lstOrderItem = EC_QueryUtility.getOrderListItemSortByName(lstAccIds);

                    //to check if the orders has order items present
                    if(lstOrderItem != null && lstOrderItem.size() > 0){
                        Set<Id> lstProduct = new Set<Id>();
                        Set<Id> setAccIds = new Set<Id>();
                        for(ccrz__E_OrderItem__c ordItemRec : lstOrderItem){
                            lstProduct.add(ordItemRec.ccrz__Product__c);
                            if(ordItemRec.ccrz__Order__r.ccrz__Account__r.EC_Division__c == EC_Constants.INSTITUTIONAL)
                	            setAccIds.add(ordItemRec.ccrz__Order__r.ccrz__Account__c);
                        }
                        Map<String, INST_Sales_Entitlement__c> mapInstSalesEntitlements = new Map<String, INST_Sales_Entitlement__c>();
                        if(setAccIds != null) mapInstSalesEntitlements = EC_QueryUtility.getInstSalesEntitlements(setAccIds);
                        
                        Map<Id, String> mapPrdctImg = new Map<Id, String>();
                        //To check if order items has associated products, then fetch their image
                        if(lstProduct!=null && lstProduct.size() > 0){
                            List<ccrz__E_ProductMedia__c> lstProdMedia = EC_QueryUtility.getListProdMedia(lstProduct);

                            //to check if the product has product image
                            if(lstProdMedia != null && lstProdMedia.size() > 0){
                                for(ccrz__E_ProductMedia__c prdMed : lstProdMedia){
                                    mapPrdctImg.put(prdMed.ccrz__Product__c, prdMed.ccrz__URI__c);
                                }
                            }
                        }
                        List<Chemical_Product_Type__c> pkgTypes = new List<Chemical_Product_Type__c>();
            			pkgTypes = [SELECT Active__c,Id,Name,Package_Code__c,Product_Type__c FROM Chemical_Product_Type__c];
                        for(ccrz__E_OrderItem__c ordItemRec : lstOrderItem){
                            ProdInfo prdInfoRec = new ProdInfo();
                            prdInfoRec.orderSFId = ordItemRec.ccrz__Order__c;

                            //prdInfoRec.orderId = String.valueOf(ordItemRec.ccrz__Order__r.ccrz__OrderNumber__c);
                            prdInfoRec.orderId = String.valueOf(ordItemRec.ccrz__Order__r.EC_ERP_Order_Number__c);

                            prdInfoRec.orderItemId = String.valueOf(ordItemRec.Id);
                            prdInfoRec.price = String.valueOf(ordItemRec.ccrz__Price__c);
                            prdInfoRec.uom = ordItemRec.Custom_PricingUOM__c;
                            prdInfoRec.unitPrice = String.valueOf(ordItemRec.Custom_UnitPrice__c);
                            prdInfoRec.taxonomy = String.valueOf(ordItemRec.ccrz__Product__r.Taxonomy__c);
                            String packageCode = String.valueOf(ordItemRec.ccrz__Product__r.Package_Code__c);
                            
            				Set<String> pkgCodeSet = new Set<String>();
            				if(!pkgTypes.isEmpty()) {
                				for (Chemical_Product_Type__c pkgType : pkgTypes) {
                    				if(pkgType.Active__c == true) {
                        			pkgCodeSet.add(pkgType.Package_Code__c);
                    				}
               				 	}
            				} 
                            if(!pkgCodeSet.isEmpty() && pkgCodeSet.contains(packageCode)) {
                                prdInfoRec.chemicalProductType = System.Label.EC_Bulk;
                    		} 
                            else {
                       			prdInfoRec.chemicalProductType = System.Label.NonBulk;
                   			}
                            
                            prdInfoRec.purchasedOn = formatDate(ordItemRec.ccrz__Order__r.ccrz__OrderDate__c);
                            String addressString = '';

                            //null check for shipping address line 1
                            if(ordItemRec.ccrz__Order__r.ccrz__ShipTo__r.ccrz__AddressFirstline__c != null){
                                addressString = addressString + ordItemRec.ccrz__Order__r.ccrz__ShipTo__r.ccrz__AddressFirstline__c + ', ';
                            }

                            //null check for shipping address line 2
                            if(ordItemRec.ccrz__Order__r.ccrz__ShipTo__r.ccrz__AddressSecondline__c != null){
                                addressString = addressString + ordItemRec.ccrz__Order__r.ccrz__ShipTo__r.ccrz__AddressSecondline__c + ', ';
                            }

                            //null check for shipping address line 3
                            if(ordItemRec.ccrz__Order__r.ccrz__ShipTo__r.ccrz__AddressThirdline__c != null){
                                addressString = addressString + ordItemRec.ccrz__Order__r.ccrz__ShipTo__r.ccrz__AddressThirdline__c + ', ';
                            }
                            prdInfoRec.shippedTo = addressString + ordItemRec.ccrz__Order__r.ccrz__ShipTo__r.ccrz__City__c + ', ' + ordItemRec.ccrz__Order__r.ccrz__ShipTo__r.ccrz__State__c + ', ' + ordItemRec.ccrz__Order__r.ccrz__ShipTo__r.ccrz__Country__c + ', ' + ordItemRec.ccrz__Order__r.ccrz__ShipTo__r.ccrz__PostalCode__c;
                            prdInfoRec.productName = ordItemRec.ccrz__Product__r.Name;
                            prdInfoRec.productCode = ordItemRec.ccrz__Product__r.ccrz__SKU__c;
                            prdInfoRec.productUnitMeasure = ordItemRec.ccrz__Product__r.ccrz__UnitOfMeasure__c ;
                            prdInfoRec.description = System.label.EC_Home_ProductDescription;
                            prdInfoRec.PDPUrl = generatePDPURL(usr.LanguageLocaleKey, ordItemRec.ccrz__Product__r.ccrz__SKU__c);

                            //to check if mapPrdctImg contains the product id for fetching the associated image.
                            if(mapPrdctImg != null && mapPrdctImg.containsKey(ordItemRec.ccrz__Product__c)){
                                prdInfoRec.image = mapPrdctImg.get(ordItemRec.ccrz__Product__c);
                            }

                            //PBI-139350
                            prdInfoRec.accountId = ordItemRec.ccrz__Order__r.ccrz__Account__c;
                            //INST HYBRID/DIRECT Account having SKU
                            if(mapInstSalesEntitlements.containsKey(prdInfoRec.productCode)) {
                                INST_Sales_Entitlement__c instSales = mapInstSalesEntitlements.get(prdInfoRec.productCode);
                                //Hide 'Add to Cart' button IF the Product's Account is present in the ISE List 
                                prdInfoRec.hideAddtoCart = (instSales.Account_Salesforce_Id__c == prdInfoRec.accountId) ? true : false;
                            //INST INDIRECT CORE Account
                            } else if(mapInstSalesEntitlements.containsKey(prdInfoRec.accountId)) {
                                INST_Sales_Entitlement__c instSales = mapInstSalesEntitlements.get(prdInfoRec.accountId);
                                //Hide 'Add to Cart' button IF Product Taxonomy is Chemical
                                prdInfoRec.hideAddtoCart = (instSales.Taxonomy__c == prdInfoRec.taxonomy) ? true : false;
                            } else {
                                prdInfoRec.hideAddtoCart = false;
                            }

                            lstProdInfo.add(prdInfoRec);
                        }
                    }



        return lstProdInfo;
    }

 /***************************************************************************************************************************************
Method Name : generatePDPURL
Description : to fetch Product Page URL
Parameter   : String,String
Return type : String
Author      : Harsha N
*************************************************************************************************************************************/

    private static String generatePDPURL(String localeValue, String skuValue){
        String tempURL = EC_Utility.getCommunityUrl() + System.label.EC_PDPTemplateUrl;
        tempURL = tempURL.replace(EC_Constants.LOCALE,localeValue);
        tempURL = tempURL.replace(EC_Constants.SKUVALUE,skuValue);
        return tempURL;
    }

    /***************************************************************************************************************************************
Method Name : formatDate
Description : to format date
Parameter   : Date
Return type : String
Author      : Harsha N
*************************************************************************************************************************************/
    private static String formatDate(Date dt){
        Map<Integer,String> monthNameMap=new Map<Integer, String>{EC_Constants.ONE =>EC_Constants.JAN, EC_Constants.TWO =>EC_Constants.FEB, EC_Constants.THREE =>EC_Constants.MAR, EC_Constants.FOUR =>EC_Constants.APR, EC_Constants.FIVE =>EC_Constants.MAY,
                                                                    EC_Constants.SIX =>EC_Constants.JUN, EC_Constants.SEVEN =>EC_Constants.JUL, EC_Constants.EIGHT =>EC_Constants.AUG, EC_Constants.NINE =>EC_Constants.SEP,EC_Constants.TEN =>EC_Constants.OCT,
                                                                    EC_Constants.ELEVEN =>EC_Constants.NOV, EC_Constants.TWELVE =>EC_Constants.DEC};
        return monthNameMap.get(dt.month()) + ' ' + dt.day() + ', ' + dt.year();
    }

    /***************************************************************************************************************************************
Method Name : getCartURL
Description : to redirect to the shopping cart
Parameter   : String
Return type : String
Author      : Harsha N
*************************************************************************************************************************************/

    @AuraEnabled
    public static String getCartURL(Id orderItemId){
        String cartURL = '';
        User usr = EC_QueryUtility.getCurrentUser();
        /*Map<String, Object> addToCartRequest = new Map<String, Object>();
        Map<String, Object> addToCartResponse = new Map<String, Object>();
        List<Map<String, Object>> lineItemData = new List<Map<String, Object>>();

        Map<String, Object> lineItemRec = new Map<String, Object>();
        lineItemRec.put(ccrz.ccApiCart.LINE_DATA_QUANTITY, 1);
        lineItemRec.put(ccrz.ccApiCart.LINE_DATA_SKU, prodSKU);
        lineItemData.add(lineItemRec);

        addToCartRequest.put(ccrz.ccApi.API_VERSION, ccrz.ccApi.CURRENT_VERSION);

        addToCartRequest.put(ccrz.ccApiCart.LINE_DATA, lineItemData);

        addToCartResponse = ccrz.ccApiCart.addTo(addToCartRequest);

        if(addToCartResponse.get(ccrz.ccApiCart.CART_ENCID) != null){
            List<ccrz__E_Cart__c> activeCartRec = EC_QueryUtility.getActiveCartRec(String.valueOf(addToCartResponse.get(ccrz.ccApiCart.CART_ENCID)));
            cartURL = EC_Utility.getCommunityUrl() +EC_Constants.CARTQURYSTRING1+ addToCartResponse.get(ccrz.ccApiCart.CART_ENCID) + EC_Constants.CARTQURYSTRING2+ activeCartRec[0].ccrz__EffectiveAccountID__c + EC_Constants.CARTQURYSTRING3 + usr.LanguageLocaleKey;
        }*/

		List<ccrz__E_OrderItem__c> orderItemRec = [SELECT  Id, ccrz__Product_Name__c, ccrz__Product__r.ccrz__SKU__c, ccrz__Product__r.ccrz__UnitOfMeasure__c, ccrz__Quantity__c, ccrz__Price__c, ccrz__Product__c, ccrz__Order__r.ccrz__CurrencyISOCode__c, ccrz__OriginalQuantity__c, ccrz__UnitOfMeasure__c, ccrz__Order__r.ccrz__EffectiveAccountID__c FROM ccrz__E_OrderItem__c WHERE Id =: orderItemId LIMIT 1];

		ccrz__E_Cart__c activeCartRec = EC_Utility.getActiveCartForUser(orderItemRec[0].ccrz__Order__r.ccrz__EffectiveAccountID__c);

		String itemAddedStatus = EC_Utility.addItemsToCart(activeCartRec.id, orderItemRec[0].ccrz__Order__r.ccrz__EffectiveAccountID__c, orderItemRec, false);

		return cartURL;
    }
      /************************************************************************************************************************************
Method Name : outageRedirect
Description : to get the permission from cache.
Return type : Boolean
Author      : Mishika Mahajan
*************************************************************************************************************************************/

    @auraEnabled
    public static Boolean outageRedirect(){
       return EC_Utility.getOutageFlag();
    }

    /***************************************************************************************************************************************
Method Name : compVisible
Description : to get list of custom permissions of user
Parameter   : N/A
Return type : List<EC_Utility.PermWrapper>
Author      : Mishika Mahajan
*************************************************************************************************************************************/
    @auraEnabled
    public static List<EC_Utility.PermWrapper>  compVisible(){
        return  EC_Utility.getPermCache();
    }

 /***************************************************************************************************************************************
Class Name  : ProdInfo
Description : wrapper class containing the product information
Author      : Harsha N
*************************************************************************************************************************************/
    public class ProdInfo{
        @auraEnabled
        public string chemicalProductType,taxonomy, unitPrice, uom, productName, productCode, image, orderId, purchasedOn, orderSFId, shippedTo, price, description, PDPUrl, productUnitMeasure, orderItemId, accountId;
        //PBI-139350
        @AuraEnabled
        public Boolean hideAddtoCart;
    }
}