src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EC_Division__c</fullName>
        <description>This field specifies the division that a Ship To account is related to.</description>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Institutional</fullName>
                    <label>INSTITUTIONAL</label>
                </value>
                <value>
                    <fullName>WATER</fullName>
                </value>
                <value>
                    <fullName>PAPER</fullName>
                </value>
                <value>
                    <fullName>FOOD &amp; BEVERAGE</fullName>
                </value>
                <value>
                    <fullName>ENERGY</fullName>
                </value>
                <value>
                    <fullName>PEST</fullName>
                </value>
                <value>
                    <fullName>TEXTILE CARE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Chat_Bot_Routing__c.object
<CustomObject>
    <description>Used in routing for chat bot in Ecolab project.</description>
    <label>Chat Bot Routing</label>
    <nameField>
        <displayFormat>CBR-{0000}</displayFormat>
        <label>Chat Bot Routing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chat Bot Routings</pluralLabel>
    <!---->
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SupportCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                </value>
                <value>
                    <fullName>INSTITUTIONAL</fullName>
                </value>
                <value>
                    <fullName>WATER</fullName>
                </value>
                <value>
                    <fullName>PAPER</fullName>
                </value>
                <value>
                    <fullName>ENERGY</fullName>
                </value>
                <value>
                    <fullName>FOOD &amp; BEVERAGE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>SupportSubCategory</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <formula>TEXT(Account.EC_Division__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Division</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/globalValueSets/SupportCategory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Checkout</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Login</fullName>
    </customValue>
    <customValue>
        <fullName>Orders</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <customValue>
        <fullName>Quicklist</fullName>
    </customValue>
    <customValue>
        <fullName>Self-Service Register</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>User</fullName>
    </customValue>
    <description>Common picklist values on case and Chat bot routing object for Ecolab Project.</description>
    <masterLabel>Category</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/ChatBotCategoryList.cls
/* Class Name      :ChatBotCategoryList
* Description      :class called from einstien bot
* Created By       :Graytitude Team
* Created On       :14.09.2020
*
* Modification Log:
* ----------------------------------------------------------------------------------------------------------------
* Developer                Date                Modification ID             Description
* ----------------------------------------------------------------------------------------------------------------
* Graytitude Team          14.09.2020                                      return list of categories from chat bot routing records
*/
public without sharing class ChatBotCategoryList {
    
    public class Input{
       @InvocableVariable
       public String category;
       @InvocableVariable(required=true)
        public String routableId;
    }
    
    @InvocableMethod(label='Get Categories')
    public static List<List<String>> getCategories(List<Input> input){
        List<List<String>> chatBotRoutings = new List<List<String>>();
        Set<String> setCategories = new Set<String>(); 
        try{            
            if(String.isNotBlank(input[0].category)) {
                setCategories = getSubCategories(input[0].category, input[0].routableId);
            } else {               
                setCategories = getCategory(input[0].routableId);
            }
            List<String> lstCategories = new List<String>(setCategories);
            lstCategories.sort();
            chatBotRoutings.add(new List<String>(lstCategories));
            return chatBotRoutings;
        }
        catch(Exception ex) { chatBotRoutings.add(new List<String>{'Error!!'}); return chatBotRoutings; }
    }
    
    private static Set<String> getSubCategories(String category, String routableId) {
        Set<String> setSubCategories = new Set<String>(); 
        LiveChatTranscript objCT;
        if(Schema.sObjectType.LiveChatTranscript.isAccessible()) {  
            objCT = [SELECT Id, Contact.account.EC_Division__c FROM LiveChatTranscript WHERE Id=:routableId];  
        }
        String division;
        if(objCT.contact.account.EC_Division__c!=null) {
            division = objCT.contact.account.EC_Division__c;
        }
        if(Schema.sObjectType.Chat_Bot_Routing__c.isAccessible()) {        
            for(Chat_Bot_Routing__c routing : [SELECT Sub_Category__c,Division__c FROM Chat_Bot_Routing__c where  Category__c =:category AND Sub_Category__c!=null])
            { 
                if(routing.Division__c==null || routing.Division__c=='All' || (division!=null && routing.Division__c.containsIgnoreCase(division)))
                    setSubCategories.add(routing.Sub_Category__c);                
            }
        }
        return setSubCategories;
    }
    
    private static Set<String> getCategory(String routableId) {
        Set<String> setCategories = new Set<String>(); 
        LiveChatTranscript objCT;
        if(Schema.sObjectType.LiveChatTranscript.isAccessible()) {  
            objCT = [SELECT Id, Contact.account.EC_Division__c FROM LiveChatTranscript WHERE Id=:routableId];  
        }
        String division;
        if(objCT.contact.account.EC_Division__c!=null) {
            division = objCT.contact.account.EC_Division__c;
        }
        if(Schema.sObjectType.Chat_Bot_Routing__c.isAccessible()) {        
            for(Chat_Bot_Routing__c routing : [SELECT Category__c,Division__c FROM Chat_Bot_Routing__c where Category__c!=null]) {
                if(routing.Division__c==null || routing.Division__c=='All' || (division!=null && routing.Division__c.containsIgnoreCase(division)))
                setCategories.add(routing.Category__c);                
            }
        }
        return setCategories;
    }
    
    @TestVisible private ChatBotCategoryList(){} //added as per suggestion of codescan
}