src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Name2__c</fullName>
        <label>Account Name 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Name3__c</fullName>
        <label>Account Name 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Name4__c</fullName>
        <label>Account Name 4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Account/fields/EC_SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>EC_SalesOrg__c</fullName>
    <label>SalesOrg</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>ccrz__EncryptedId__c</fullName>
        <description>Semi-random UUID used to refer to the order in URLs.</description>
        <label>Encrypted Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_CartItem__c.object
<CustomObject>
    <description>Cart Items</description>
    <fields>
        <fullName>ccrz__Cart__c</fullName>
        <description>Reference to the parent cart.</description>
        <label>Cart</label>
        <referenceTo>ccrz__E_Cart__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>E_CartItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>The unit price of the line.</description>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line item.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Cart Items (ProductID)</relationshipLabel>
        <relationshipName>E_CartItem2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Arrangement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Arrangement</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>CC Cart Items</relationshipLabel>
        <relationshipName>CC_Cart_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Cart Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CartItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceList__c.object
<CustomObject>
    <description>Represents a grouping of products to control pricing and entitlements.  The B2B Commerce pricelist object controls both pricing and entitlements, but can be used just for the purposes of entitlements. A list needs to be created for each currency that needs to be represented, allowing for different entitlments and pricing based on the locale and currency.</description>
    <fields>
        <fullName>Price_List_Type_Expansion__c</fullName>
        <formula>IF(EC_Price_List_Type__c = &apos;FBA&apos;, &apos;Fixed BA&apos;, IF(EC_Price_List_Type__c = &apos;USG&apos;,&apos;Usage&apos;,IF(EC_Price_List_Type__c =&apos;USR&apos;,&apos;Use Risk&apos;,IF(EC_Price_List_Type__c=&apos;SBA&apos;,&apos;Special Pricing Agreement&apos;,&apos;&apos;))))</formula>
        <label>Price List Type Expansion</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Desc__c</fullName>
        <description>A description of the pricelist - internal only</description>
        <label>Desc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BA_Number__c</fullName>
        <description>To store BA number</description>
        <label>BA Number</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <label>CC Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceListItem__c.object
<CustomObject>
    <description>Represents an entry in the Pricelist.  Each pricelist object is made up of 1 or more pricelist item objects.  This item objects contain a reference to the product and hold a price value (0, in the case where only entitlements are being used).  The products referenced within these items will be displayed in search and product listings on the external site.</description>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>Holds the price for the item. If pricing is not being utilized, fill in a default value, such as 0.</description>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the product entry</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>E_PriceListItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Price List Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>PriceListItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within B2B Commerce</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Package_Code__c</fullName>
        <description>formula field to get the package code from SKU</description>
        <formula>IF(CONTAINS(ccrz__SKU__c,&quot;.&quot; ), MID(ccrz__SKU__c, FIND(&apos;.&apos;, ccrz__SKU__c )+1,LEN(ccrz__SKU__c)) , &apos;&apos;)</formula>
        <label>Package Code</label>
        <type>Text</type>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Chemical_Product_Type__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To identify the bulk product (User Story-122127)</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Package_Code__c</fullName>
        <label>Package Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Chemical Product Type</label>
</CustomObject>

src/classes/EC_BillingArrangementControllerTest.cls
/* Class Name       : EC_BillingArrangementControllerTest
* Description      : Test Class to cover EC_BillingArrangementController
* Created By       : Moin
* Created On       : 2020-Sep-01
*/
@isTest
public class EC_BillingArrangementControllerTest {
    
     private static EC_BillingArrangementController.ItemWrapper createItemWrapper(){
       EC_BillingArrangementController.ItemWrapper itwr = new EC_BillingArrangementController.ItemWrapper();            
            itwr.price = 22.11;
            itwr.customPricingUOM ='43';
            itwr.customUnitPrice = 45.99;
            itwr.taxonomy ='88';
            //itwr.productID =products[0].Id;
            itwr.PricePer = 45;
            itwr.packageTypeUOM = 'LBS';
            itwr.startDate = '09/09/2020';
            itwr.EndDate = '09/09/2020';
            itwr.uri = 'https://ecolabconnect--devec1.my.salesforce.com/home/home.jsp';
            return itwr;
     
    }
    
    @testSetup static void setup() {
        Account testAccountSoldTo = EC_TestData.testAccount;
        
        ccrz.cc_RemoteActionContext ctx=new ccrz.cc_RemoteActionContext();
        ctx.effAccountId = testAccountSoldTo.id;
        
        Account shipTo = [Select EC_SalesOrg__c from Account Where Id=:EC_TestData.testAccountShipTo.id];
        shipTo.EC_SalesOrg__c = '1001';
        shipTo.Account_Name2__c = 'ShipTo1';
        shipTo.Account_Name3__c = 'ShipTo2';
        shipTo.Account_Name4__c = 'ShipTo3';
        shipTo.parent =EC_TestData.testAccountShipTo;
        update shipTo;
        ccrz.cc_CallContext.effAccountId = testAccountSoldTo.id;
        
        ccrz.cc_CallContext.initRemoteContext(ctx);
        
        ccrz.cc_CallContext.currAccountId = testAccountSoldTo.id;
        List<ccrz__E_Product__c> productList = EC_SplitOrderTest.productUtility(4);
        productList[0].ccrz__sku__c='GEN CHEMICAL';
        update productList[0];
            
        
        List<ccrz__E_PriceList__c> listPriceLists = new List<ccrz__E_PriceList__c>();
        listPriceLists.add(EC_SplitOrderTest.priceListUtility('BA1','SBA'));
        listPriceLists.add(EC_SplitOrderTest.priceListUtility('Z1MP','Contract'));
        
        EC_SplitOrderTest.accountGroupPriceListUtility(testAccountSoldTo.id,listPriceLists[0].Id);
        EC_SplitOrderTest.accountGroupPriceListUtility(testAccountSoldTo.id,listPriceLists[1].Id);
        
        EC_SplitOrderTest.priceListItemUtility(productList,listPriceLists[0].Id);
        EC_SplitOrderTest.priceListItemUtility(productList,listPriceLists[1].Id);    
     
    }
    
    private static ccrz__E_CartItem__c fetchCartItem(String cartId,String productId, String priceListId){
        ccrz__E_CartItem__c cartItem = new ccrz__E_CartItem__c();
        cartItem.ccrz__Cart__c = cartId;
        cartItem.ccrz__Price__c = 100;
        cartItem.ccrz__Product__c = productId;
        cartItem.Billing_Arrangement__c = priceListId;
        return cartItem;
    }
    
    private static EC_BillingArrangementController.baWrapper fetchBAWrapper(String baNumber, String baSFID, String priceListTypeExpansion, String description){
        EC_BillingArrangementController.baWrapper wr = new EC_BillingArrangementController.baWrapper();    
        wr.baNumber = baNumber;
        wr.baId = baSFID;
        wr.baType = priceListTypeExpansion;
        wr.baDesc = description;
        wr.startDate = '21/09/2020';
        wr.EndDate = '23/09/2020';
        return wr;
    }
    
    
    /*****************************************************************
Method Name : BA
Description : Test method to cover EC_BillingArrangementController method
Return type : void
******************************************************************/
    @isTest
    static void BA() {
        User thisUser = [SELECT Id  FROM User WHERE Id = :UserInfo.getUserId()];
        system.runas(thisUser){
            Test.startTest();            
            Account testAccountSoldTo = [SELECT id from Account Order by createddate desc limit 1];
            ccrz.cc_RemoteActionContext ctx=new ccrz.cc_RemoteActionContext(); 
            ctx.effAccountId = testAccountSoldTo.id;
            
            Account shipTo = [Select EC_SalesOrg__c from Account Where Id=:EC_TestData.testAccountShipTo.id];
            shipTo.EC_SalesOrg__c = '1001';
            shipTo.Account_Name2__c = 'ShipTo1';
            shipTo.Account_Name3__c = 'ShipTo2';
            shipTo.Account_Name4__c = 'ShipTo3';
            shipTo.parent =EC_TestData.testAccountShipTo;
            update shipTo;
            ccrz.cc_CallContext.effAccountId = testAccountSoldTo.id;            
            ccrz.cc_CallContext.initRemoteContext(ctx);            
            ccrz.cc_CallContext.currAccountId = testAccountSoldTo.id;     
            
			ccrz__E_PriceList__c pl1 = [Select id,BA_Number__c,Price_List_Type_Expansion__c, ccrz__Desc__c from ccrz__E_PriceList__c where name = 'BA1'];
            List<ccrz__E_Product__c> products = [Select Id from ccrz__E_Product__c];       
            List<ccrz__E_PriceListItem__c> plItems = new List<ccrz__E_PriceListItem__c>();
            
            Set<String > ProdskuSet = new Set<String > ();
            ProdskuSet.add('ST70.15');
            ProdskuSet.add('GEN EQUIPMENT');
            List<ccrz__E_Cart__c> cart = EC_TestData.createCarts(1);
            ccrz__E_CartItem__c cartItem = fetchCartItem(cart[0].Id,products[0].Id,pl1.Id);
            insert cartItem;
            
            List<ccrz__E_CartItem__c> currentItemLists = new List<ccrz__E_CartItem__c>();
            currentItemLists.add(cartItem); 
            
            
            EC_BillingArrangementController Obj = new EC_BillingArrangementController();
            system.debug(Obj);
            EC_BillingArrangementController.baWrapper wr = fetchBAWrapper(Pl1.BA_Number__c,pl1.ID,Pl1.Price_List_Type_Expansion__c,Pl1.ccrz__Desc__c);
           
            
            List<EC_BillingArrangementController.ItemWrapper> itrList = new List<EC_BillingArrangementController.ItemWrapper>();
            EC_BillingArrangementController.ItemWrapper itwr = createItemWrapper();            
            itwr.product = products[0];
            itwr.priceListItem = plItems;
            
            wr.ItemWrapper = itrList;
            wr.prodLineItems = itrList;
            //   ccrz.cc_RemoteActionContext ctx=new ccrz.cc_RemoteActionContext();
            ccrz.cc_RemoteActionResult res= EC_BillingArrangementController.getBADetail(ctx,'12345');
            System.assertNotEquals(null, res);
            ccrz.cc_RemoteActionResult res1= EC_BillingArrangementController.getBANums(ctx,ccrz.cc_CallContext.effAccountId);
            System.assertNotEquals(null, res1);
            Chemical_Product_Type__c cts = new Chemical_Product_Type__c(name= 'test11', Active__c = true, Package_Code__c ='90R',Product_Type__c ='Bulk' );
            insert cts;
            set<string> res3= EC_BillingArrangementController.getPackageCode();
            System.assertNotEquals(null, res3);
            ccrz.cc_CallContext.initRemoteContext(ctx);
            EC_BillingArrangementController.addToCartBADP(ctx,products[0].Id,cart[0].ccrz__EncryptedId__c, pl1.Id);
            Test.stopTest();
        }
    }
    
    @isTest
    static void testBAHelper(){
        Test.startTest();
        ccrz__E_PriceList__c pl1 = [Select id from ccrz__E_PriceList__c where name = 'BA1'];
        ccrz.cc_RemoteActionResult res1 = new ccrz.cc_RemoteActionResult();           
        EC_BillingArrangementDetailHelper.fetchBADPData(res1,pl1.Id);
        System.assertNotEquals(null, res1);
        Test.stopTest();          
    } 

     @isTest
    static void testcheckNALCO(){
        EC_BillingArrangementController varClassInstance = new EC_BillingArrangementController();
        ccrz.cc_RemoteActionContext ctx=new ccrz.cc_RemoteActionContext();        
        Test.startTest();
        EC_BillingArrangementController.getBANums(ctx,'AccountId');
        varClassInstance.baJSON = 'baJSON';
        Boolean boolNalco = varClassInstance.checkNALCO();
        System.assertEquals(true, boolNalco);
        Test.stopTest();          
    }
}