src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EC_Division__c</fullName>
        <description>This field specifies the division that a Ship To account is related to.</description>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Institutional</fullName>
                    <label>INSTITUTIONAL</label>
                </value>
                <value>
                    <fullName>WATER</fullName>
                </value>
                <value>
                    <fullName>PAPER</fullName>
                </value>
                <value>
                    <fullName>FOOD &amp; BEVERAGE</fullName>
                </value>
                <value>
                    <fullName>ENERGY</fullName>
                </value>
                <value>
                    <fullName>PEST</fullName>
                </value>
                <value>
                    <fullName>TEXTILE CARE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Account/fields/EC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>EC_Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Chat_Bot_Routing__c.object
<CustomObject>
    <description>Used in routing for chat bot in Ecolab project.</description>
    <label>Chat Bot Routing</label>
    <nameField>
        <displayFormat>CBR-{0000}</displayFormat>
        <label>Chat Bot Routing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chat Bot Routings</pluralLabel>
    <!---->
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SupportCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Create_Case__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                </value>
                <value>
                    <fullName>INSTITUTIONAL</fullName>
                </value>
                <value>
                    <fullName>WATER</fullName>
                </value>
                <value>
                    <fullName>PAPER</fullName>
                </value>
                <value>
                    <fullName>ENERGY</fullName>
                </value>
                <value>
                    <fullName>FOOD &amp; BEVERAGE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Show_Article__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Show Article</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Walkme__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Show Walkme</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>SupportSubCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transfer_to_Agent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Transfer to Agent</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EC_CDM_Contact__c</fullName>
        <description>US-74958:Raghav:26/06/2019:This field will be used for mapping between CDM and contact object.</description>
        <externalId>true</externalId>
        <label>External Contact Key</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <formula>TEXT(Account.EC_Division__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Division</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
	<fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SupportCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SupportSubCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Walkme_Url__c</fullName>
        <label>Walkme Url</label>
        <type>Url</type>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

src/globalValueSets/SupportCategory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Checkout</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Login</fullName>
    </customValue>
    <customValue>
        <fullName>Orders</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <customValue>
        <fullName>Quicklist</fullName>
    </customValue>
    <customValue>
        <fullName>Self-Service Register</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>User</fullName>
    </customValue>
    <description>Common picklist values on case and Chat bot routing object for Ecolab Project.</description>
    <masterLabel>Category</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/ChatBotTest.cls
/* Class Name      :ChatBotTest
* Description      :Test class for all einstien bot related classes
* Created By       :Graytitude Team
* Created On       :24.09.2020
*
* Modification Log:
* ----------------------------------------------------------------------------------------------------------------
* Developer                Date                Modification ID             Description
* ----------------------------------------------------------------------------------------------------------------
* Graytitude Team          24.09.2020                                      create test class
*/
@isTest
private class ChatBotTest {    

    testmethod static void Test_ChatBotArticleSearch() {        
        User runUser = getUser();
 
        system.runAs(runUser){
            knowledge__kav newArticle = new knowledge__kav(Title='How to checkout',summary='How to checkout',urlname='How-to-Checkout1', category__c = 'Checkout', Sub_Category__c = 'How to checkout',IsVisibleInCsp=true);
            insert newArticle;
            knowledge__kav newArticle2 = new knowledge__kav(Title='How to Login',summary='How to Login',urlname='How-to-Login1', category__c = 'Login', Sub_Category__c = 'How to Login',IsVisibleInCsp=true, Walkme_Url__c='www.walkme.com');
            insert newArticle2;
            Id kAId = [SELECT KnowledgeArticleId FROM knowledge__kav WHERE Id=:newArticle.Id LIMIT 1].KnowledgeArticleId;
            KbManagement.PublishingService.publishArticle(kAId, true);
            Id kAId2 = [SELECT KnowledgeArticleId FROM knowledge__kav WHERE Id=:newArticle2.Id LIMIT 1].KnowledgeArticleId;
            KbManagement.PublishingService.publishArticle(kAId2, true);
            
            ChatBotArticleSearch.SearchInput input = new ChatBotArticleSearch.SearchInput();
            input.category = 'Checkout';
            input.subCategory = 'How to checkout';
            Test.startTest();
            List<ChatBotArticleSearch.SearchOutput> lstResult = ChatBotArticleSearch.searchFAQ(new List<ChatBotArticleSearch.SearchInput>{input});
            input.category = 'Login';
            input.subCategory = 'How to Login';
            lstResult = ChatBotArticleSearch.searchFAQ(new List<ChatBotArticleSearch.SearchInput>{input});
            ChatBotArticleSearch inst = new ChatBotArticleSearch();
            Test.stopTest();
            System.assertNotEquals(lstResult.size(), 0);
            System.assertNotEquals(inst, null);
        }
    }
    
    testmethod static void Test_ChatBotRouting() {        
        User runUser = getUser();
        system.runAs(runUser){       
            String category = 'Checkout';
            String subcategory = 'How to Checkout';
           
            Chat_Bot_Routing__c objCBR = new Chat_Bot_Routing__c(
                Category__c=category,
                Sub_Category__c=subcategory, 
                Show_Walkme__c=true,  
                Show_Article__c=true, 
                Transfer_to_Agent__c=true, 
                Create_Case__c=true,
                Division__c='All' 
            );              
            insert objCBR;
            
            ChatBotRouting.RoutingRequest input = new ChatBotRouting.RoutingRequest();
            input.category = category;
            input.subCategory = subCategory;
            Test.startTest();
            List<ChatBotRouting.RoutingResponse> lstResult = ChatBotRouting.chatBotRoutingData(new List<ChatBotRouting.RoutingRequest>{input});
            ChatBotRouting inst = new ChatBotRouting();
            Test.stopTest();
            System.assertNotEquals(lstResult.size(), 0);
            System.assertNotEquals(inst, null);
        }
    }
    
    testmethod static void Test_ChatBotcategoryList() {        
        User runUser = getUser();
 
        system.runAs(runUser){        
            String category = 'Checkout';
            String subcategory = 'How to Checkout';
           
            Chat_Bot_Routing__c objCBR = new Chat_Bot_Routing__c(
                Category__c=category,
                Sub_Category__c=subcategory, 
                Show_Walkme__c=true,  
                Show_Article__c=true, 
                Transfer_to_Agent__c=true, 
                Create_Case__c=true,
                Division__c='All' 
            );              
            insert objCBR;
            
            Account ac = new Account(name ='Grazitti') ;
            ac.EC_Division__c = 'INSTITUTIONAL';
            insert ac;         
            Contact conRec = new Contact(LastName ='testCon',AccountId=ac.Id,EC_CDM_Contact__c='test');
            insert conRec; 
            
            LiveChatVisitor lcv = new LiveChatVisitor();
            insert lcv;
            LiveChatTranscript lct = new LiveChatTranscript();
            lct.LiveChatVisitorid = lcv.id;
            lct.ContactId=conRec.Id;
            insert lct;
            
            ChatBotCategoryList.Input input = new ChatBotCategoryList.Input();        
            input.routableId=lct.Id;
            Test.startTest();
            List<List<String>> lstResult = ChatBotCategoryList.getCategories(new List<ChatBotCategoryList.Input>{input});
            input.category = category;
            lstResult = ChatBotCategoryList.getCategories(new List<ChatBotCategoryList.Input>{input});
            ChatBotCategoryList inst = new ChatBotCategoryList();
            Test.stopTest();
            System.assertNotEquals(lstResult.size(), 0);
            System.assertNotEquals(inst, null);
        }
    }
    
    testmethod static void Test_ChatBotRelatedAccountList() { 
        User runUser = getUser();
 
        system.runAs(runUser){      
            Account ac = new Account(name ='Grazitti') ;
            ac.EC_Account_Number__c = '981276345';
            insert ac;         
            Contact conRec = new Contact(LastName ='testCon',AccountId=ac.Id,EC_CDM_Contact__c='test');
            insert conRec; 
            
            LiveChatVisitor lcv = new LiveChatVisitor();
            insert lcv;
            LiveChatTranscript lct = new LiveChatTranscript();
            lct.LiveChatVisitorid = lcv.id;
            lct.ContactId=conRec.Id;
            insert lct;
            
            ChatBotRelatedAccountList.Input input = new ChatBotRelatedAccountList.Input();        
            input.routableId=lct.Id;
            Test.startTest();
            List<List<String>> lstResult = ChatBotRelatedAccountList.getRelatedAccount(new List<ChatBotRelatedAccountList.Input>{input});
            ChatBotRelatedAccountList inst = new ChatBotRelatedAccountList();
            Test.stopTest();
            System.assertNotEquals(lstResult.size(), 0);
            System.assertNotEquals(inst, null);
        }   
    }
    
    testmethod static void Test_ChatBotGetContactInfo() { 
        User runUser = getUser();
 
        system.runAs(runUser){      
            Account ac = new Account(name ='Grazitti') ;
            ac.EC_Account_Number__c = '981276345';
            insert ac;         
            Contact conRec = new Contact(LastName ='testCon',AccountId=ac.Id,EC_CDM_Contact__c='test');
            insert conRec; 
            
            LiveChatVisitor lcv = new LiveChatVisitor();
            insert lcv;
            LiveChatTranscript lct = new LiveChatTranscript();
            lct.LiveChatVisitorid = lcv.id;
            lct.ContactId=conRec.Id;
            insert lct;
            
            ChatBotGetContactInfo.Input input = new ChatBotGetContactInfo.Input();        
            input.routableId=lct.Id;
            Test.startTest();
            List<ChatBotGetContactInfo.Output> lstResult = ChatBotGetContactInfo.getContactInfo(new List<ChatBotGetContactInfo.Input>{input});
            ChatBotGetContactInfo inst = new ChatBotGetContactInfo();
            Test.stopTest();
            System.assertNotEquals(lstResult.size(), 0);
            System.assertNotEquals(inst, null);
        }
    }
    
    testmethod static void Test_ChatBotCaseCreate() { 
        User runUser = getUser();
 
        system.runAs(runUser){       
            String category = 'Checkout';
            String subcategory = 'How to Checkout';
            
            Account ac = new Account(name ='Grazitti') ;
            ac.EC_Account_Number__c = '981276345';
            insert ac;         
            Contact conRec = new Contact(LastName ='testCon',AccountId=ac.Id,EC_CDM_Contact__c='test');
            insert conRec; 
            
            LiveChatVisitor lcv = new LiveChatVisitor();
            insert lcv;
            LiveChatTranscript lct = new LiveChatTranscript();
            lct.LiveChatVisitorid = lcv.id;
            lct.ContactId=conRec.Id;
            insert lct;
            
            ChatBotCaseCreate.Request input = new ChatBotCaseCreate.Request();        
            input.routableId = lct.Id;
            input.category = category;
            input.subcategory = subcategory;
            input.accountnumber = ac.Name + ':' + ac.EC_Account_Number__c;
            Test.startTest();
            List<String> lstResult = ChatBotCaseCreate.createCase(new List<ChatBotCaseCreate.Request>{input});        
            ChatBotCaseCreate inst = new ChatBotCaseCreate();
            Test.stopTest();
            System.assertNotEquals(lstResult.size(), 0);
            System.assertNotEquals(inst, null);
        }
    }
    
    private static User getUser() {
        // Create a unique UserName
        String uniqueUserName = 'systemadmin' + DateTime.now().getTime() + '@testorg.com';
        // This code runs as the system user
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        return new User(Alias = 'standt', Email='systemadmin@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        TimeZoneSidKey='America/Los_Angeles',
        UserName=uniqueUserName, 
        UserPermissionsKnowledgeUser = true);  
    } 
}