src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EC_Division__c</fullName>
        <description>This field specifies the division that a Ship To account is related to.</description>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Institutional</fullName>
                    <label>INSTITUTIONAL</label>
                </value>
                <value>
                    <fullName>WATER</fullName>
                </value>
                <value>
                    <fullName>PAPER</fullName>
                </value>
                <value>
                    <fullName>FOOD &amp; BEVERAGE</fullName>
                </value>
                <value>
                    <fullName>ENERGY</fullName>
                </value>
                <value>
                    <fullName>PEST</fullName>
                </value>
                <value>
                    <fullName>TEXTILE CARE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Account/fields/EC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>EC_Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EC_CDM_Account__c.field-meta.xml
<CustomField>
    <fullName>EC_CDM_Account__c</fullName>
    <description>US-74958:Raghav:26/06/2019:This field will be used for mapping between CDM and account object.</description>
    <externalId>true</externalId>
    <label>External Account Key</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/AccountContactRelation.object
<CustomObject>
    <fields>
        <fullName>Alignment_Type__c</fullName>
        <description>Holds alignment type sent from CDM</description>
        <label>Alignment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Account Owner</fullName>
                </value>
                <value>
                    <fullName>Caretaker</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
                <value>
                    <fullName>Shared</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>EC_Account_Number__c</fullName>
        <formula>Account.EC_Account_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_PortalAccessRole__c</fullName>
        <label>Portal Access Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Basic</fullName>
                </value>
                <value>
                    <fullName>Buyer</fullName>
                </value>
                <value>
                    <fullName>Payer</fullName>
                </value>
                <value>
                    <fullName>Basic+</fullName>
                    <isActive>false</isActive>
                    <label>Basic+</label>
                </value>
                <value>
                    <fullName>Buyer+</fullName>
                    <isActive>false</isActive>
                    <label>Buyer+</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EC_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to user field</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/EC_LogsEnabler__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>EC_LogsEnabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EC_LogsEnabled</label>
        <type>Checkbox</type>
    </fields>
    <label>EC_LogsEnabler</label>
</CustomObject>

src/objects/EC_Mulesoft_Integration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>EC_ClientId__c</fullName>
        <description>US:76262:Raghav:This field holds the client id for API Callout.</description>
        <label>EC_ClientId</label>
        <length>90</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_Client_Secret__c</fullName>
        <description>US-76262:Raghav:This fields holds the client secret for API Callout.</description>
        <label>EC_Client_Secret</label>
        <length>90</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_Endpoint__c</fullName>
        <label>Endpoint</label>
        <type>Url</type>
    </fields>
    <label>Mulesoft Integration</label>
</CustomObject>

src/objects/EC_OutageFlag__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>EC_isCommunityActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isCommunityActive</label>
        <type>Checkbox</type>
    </fields>
    <label>EC_OutageFlag</label>
</CustomObject>

src/objects/EC_PermissionSetMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>EC_PermissionSetList__c</fullName>
        <label>PermissionSetList</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>EC_PermissionSetMapping</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>User_Type__c</fullName>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/EC_UserRegistrationTestDataFactory.cls
@isTest
public class EC_UserRegistrationTestDataFactory {

   	public static void insetCustomSettings() {

		List<EC_LogsEnabler__c> listLogSettings = new List<EC_LogsEnabler__c>();
        
        EC_LogsEnabler__c ruSetting = new EC_LogsEnabler__c();
        ruSetting.Name = 'RegisterUser';
        ruSetting.EC_LogsEnabled__c = true;
        listLogSettings.add(ruSetting);
        
        EC_LogsEnabler__c dpSetting = new EC_LogsEnabler__c();
        dpSetting.Name = 'DomainProperties';
        dpSetting.EC_LogsEnabled__c = true;
        listLogSettings.add(dpSetting);
        
        EC_LogsEnabler__c duSetting = new EC_LogsEnabler__c();
        duSetting.Name = 'DirectoryUser';
        duSetting.EC_LogsEnabled__c = true;
        listLogSettings.add(duSetting);

        EC_LogsEnabler__c punchSetting = new EC_LogsEnabler__c();
        punchSetting.Name = 'CaseCreationController';
        punchSetting.EC_LogsEnabled__c = true;
        listLogSettings.add(punchSetting);
        insert listLogSettings;

		List<EC_Mulesoft_Integration__c> listMuleSettings = new List<EC_Mulesoft_Integration__c>();
 
        EC_Mulesoft_Integration__c ruMuleInt = new EC_Mulesoft_Integration__c();
        ruMuleInt.Name = 'RegisterUser';
        ruMuleInt.EC_Endpoint__c = 'http://mule.com/ru';
        ruMuleInt.EC_ClientId__c = '101';
        ruMuleInt.EC_Client_Secret__c = 'xuksi';
		listMuleSettings.add(ruMuleInt);

        EC_Mulesoft_Integration__c dpMuleInt = new EC_Mulesoft_Integration__c();
        dpMuleInt.Name = 'DomainProperties';
        dpMuleInt.EC_Endpoint__c = 'http://mule.com/dp';
        dpMuleInt.EC_ClientId__c = '101';
        dpMuleInt.EC_Client_Secret__c = 'xuksi';
		listMuleSettings.add(dpMuleInt);

        EC_Mulesoft_Integration__c duMuleInt = new EC_Mulesoft_Integration__c();
        duMuleInt.Name = 'DirectoryUser';
        duMuleInt.EC_Endpoint__c = 'http://mule.com/du';
        duMuleInt.EC_ClientId__c = '101';
        duMuleInt.EC_Client_Secret__c = 'xuksi';
		listMuleSettings.add(duMuleInt);
        insert listMuleSettings;

		List<EC_PermissionSetMapping__c> listPermissionSettings = new List<EC_PermissionSetMapping__c>();
        
        EC_PermissionSetMapping__c psmBasic = new EC_PermissionSetMapping__c();
		psmBasic.Name = 'Basic';
		psmBasic.EC_PermissionSetList__c = 'EC_BasicSet';
        listPermissionSettings.add(psmBasic);
        
        EC_PermissionSetMapping__c psmBuyer = new EC_PermissionSetMapping__c();
		psmBuyer.Name = 'Buyer';
		psmBuyer.EC_PermissionSetList__c = 'EC_BuyerSet';
        listPermissionSettings.add(psmBuyer);

        insert listPermissionSettings;
	}

    public static Id createAccount() {
        
        Account objAccount = new Account (
            Name                    = 'B2C',
            Type                    = 'Customer',
            EC_Division__c          = 'WATER',
            BillingStreet           = 'BillingStreet',
            BillingCity             = 'BillingCity',
            BillingState            = 'BillingState',
            BillingCountry          = 'USA',
            ShippingCountry         = 'USA',
            ccrz__SourceSystem__c 	= 'Test',
            BillingPostalCode       = '12807',
            EC_Account_Number__c    = '18787',
            EC_CDM_Account__c		= '17654'	
        );
        
        insert objAccount;
        return objAccount.Id;
    }

    private static Id createContact(String accountId, String userEmail) {

        Contact objContact = new Contact (
            FirstName 	= 'B2C',
            LastName	= 'TestUser',
            Email 		= userEmail,
            AccountId 	= accountId,
            MailingStreet = 'MailingStreet'
        );
        
        insert objContact;
        System.debug('### objContact: ' + objContact.Id);
        return objContact.Id;
    }
    
    private static Id createUser(String contactId, String userEmail) {
        
        Profile profile = [SELECT Id FROM Profile WHERE Name = :EC_TestData.CLOUDCRAZE_CUSTOMER_COMMUNITY_PROFILE_NAME 
                           LIMIT 1];
        
        User testOwner = [SELECT TimeZoneSidKey, UserRoleId FROM User WHERE Id = :UserInfo.getUserId()];
        
        User objUser = new User(
            Alias               = 	'cctest',
            Email               = 	userEmail,
            EmailEncodingKey    = 	'UTF-8',
            LastName            = 	'TestUser',
            LanguageLocaleKey   = 	'en_US',
            LocaleSidKey        = 	'en_US',
            ProfileId           = 	profile.Id,
            Username            = 	userEmail,
            isActive            = 	true,
            ContactId           = 	contactId,
            User_Type__c        =	'External',
            TimeZoneSidKey		=	testOwner.TimeZoneSidKey
        );
        
        insert objUser;
        System.debug('### objUser: ' + objUser.Id);
        return objUser.Id;
    }
    
    public static Case createCase(String userEmail, String caseStatus, Boolean isCreateUser) {

        String fUserEmail = userEmail;
        
        if(System.Label.EC_Email_Extension != EC_Constants.PRODEMAILEXT) {
      		fUserEmail = userEmail + System.Label.EC_Email_Extension;
      	}

        Case objCase = new Case();

        objCase.AccountId = createAccount();
        objCase.ContactId = createContact(objCase.AccountId, fUserEmail);
        
        if(isCreateUser) {
        	objCase.EC_User__c= createUser(objCase.ContactId, fUserEmail);
        }
        
        objCase.Status = caseStatus;
        objCase.Type = EC_Constants.USER_REGISTRATION; 			// User Registration
        objCase.Origin = Label.EC_Origin_Online_Registration; 	// Connect
        objCase.EC_PortalAccessRole__c = EC_Constants.BUYER;
        insert objCase;
        
        return objCase;
    }
    
    public static void updateAPILogger(String apiName, Boolean flag) {
        EC_LogsEnabler__c logSetting = EC_LogsEnabler__c.getvalues(apiName);
        logSetting.EC_LogsEnabled__c = flag;
        update logSetting;
    } 

    public static void updateAPIEndPointURL(String apiName, String endPoint) {
        System.debug('##ruMuleInt' + apiName + '::' + endPoint);
        EC_Mulesoft_Integration__c ruMuleInt = EC_Mulesoft_Integration__c.getvalues(apiName); 
        System.debug('##ruMuleInt' +ruMuleInt);
        ruMuleInt.EC_Endpoint__c = 'http://mule.com/' + endPoint;
        update ruMuleInt;
    } 
    
    public static void createAccountContactRelation(){
        Account parentAcc = new Account(Name= 'DAOAccount', EC_CDM_Account__c = '555', EC_Account_Number__c = '500000005');
        Database.insert(parentAcc);
        
        List<Account> childAccts = new List<Account>();
        for(Integer i=0; i<3; i++) {
            childAccts.add(new Account(Name = 'TestAcct'+i, ParentId = parentAcc.Id));
        }
        Database.insert(childAccts); 
        
        Contact cont = new Contact(LastName = 'Last', AccountId = parentAcc.Id);
        Database.insert(cont); 
        
        AccountContactRelation accRel = new AccountContactRelation();
        accRel = [Select Id FROM AccountContactRelation WHERE AccountId = :parentAcc.Id];
        accRel.Alignment_Type__c = EC_Constants.PRIMARY_ALIGNMENT_TYPE;
        upsert accRel;
    }
    
    public static void createOutageRecord(){
        EC_OutageFlag__c outageRec = new EC_OutageFlag__c();
        outageRec.name = 'CommunityActive';
        outageRec.EC_isCommunityActive__c = true;
        insert outageRec;
    }

}