src/objects/Account.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Account/fields/EC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>EC_Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EC_CDM_Account__c.field-meta.xml
<CustomField>
    <fullName>EC_CDM_Account__c</fullName>
    <description>US-74958:Raghav:26/06/2019:This field will be used for mapping between CDM and account object.</description>
    <externalId>true</externalId>
    <label>External Account Key</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/EC_SalesRepresentative__c.field-meta.xml
<CustomField>
    <fullName>EC_SalesRepresentative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Harsha:07/09/19:The Sales Rep user related to the Sold to Account</description>
    <label>Sales Representative</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EC_CDM_Contact__c</fullName>
        <description>US-74958:Raghav:26/06/2019:This field will be used for mapping between CDM and contact object.</description>
        <externalId>true</externalId>
        <label>External Contact Key</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EC_SalesRep_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EC SalesRep User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EC_User_Type__c</fullName>
        <description>It defines the UserType of the User associated with the contact</description>
        <label>UserType</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>New Checkbox to soft delete the contacts</description>
        <label>EC_isActive</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>EC_CDM_User_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Captures the CDM User status</description>
        <label>CDM User Status</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/classes/EC_UpdateSalesRepOnAccountTest.cls
/* Class Name      :EC_UpdateSalesRepOnAccountTest
 * Description      :Test Class for EC_UpdateSalesRepOnAccountTest
 * Created By       :Mishika Mahajan
 * Created On       :09-23-2019
 *
 * Modification Log:
 * ----------------------------------------------------------------------------------------------------------------
 * Developer                Date                Modification ID             Description
 * ----------------------------------------------------------------------------------------------------------------
 * Mishika Mahajan          09-23-2019                                    Test Class for EC_UpdateSalesRepOnAccountTest
 *
 */

@isTest
public class EC_UpdateSalesRepOnAccountTest {
	/***************************************************************************************************************************************
	 Method Name : updateSalesRepOnUserInactiveTest
	 Description : Test Method for updateSalesRepOnUserInactive
	 Return type : void
	 Author      : Mishika Mahajan
	 *************************************************************************************************************************************/

	@isTest
	public static void updateSalesRepOnUserInactiveTest() {
		List<User> usrList = new List<User>();
		UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
		Profile profile1 = [Select Id from Profile where name = 'System Administrator'];
		User portalUser = new User(UserRoleId = portalRole.Id,
								   ProfileId = profile1.Id,
								   Username = System.now().millisecond() + 'test2@test.com',
								   Alias = 'batman',
								   Email= 'bruce.wayne@wayneenterprises.com',
								   EmailEncodingKey= 'UTF-8',
								   Firstname= 'Bruce',
								   Lastname= 'Wayne',
								   LanguageLocaleKey= 'en_US',
								   LocaleSidKey= 'en_US',
								   TimeZoneSidKey= 'America/Chicago');

		usrList.add(portalUser);

		Profile salesRepProfile = [Select Id from Profile where name = 'Sales Rep'];
		User salesRepUser1 = new User(UserRoleId = portalRole.Id,
										   ProfileId = salesRepProfile.Id,
										   Username = System.now().millisecond() + 'test334@test.com',
										   Alias = 'bunman',
										   Email= 'bruce.wayee23@wayneenterprises.com',
										   EmailEncodingKey= 'UTF-8',
										   Firstname= 'Bruceee',
										   Lastname= 'Waneyy',
										   LanguageLocaleKey= 'en_US',
										   LocaleSidKey= 'en_US',
										   TimeZoneSidKey= 'America/Chicago',
										   EC_CDM_User_Status__c = true);
		usrList.add(salesRepUser1);

		User salesRepUser = new User(UserRoleId = portalRole.Id,
								     ProfileId = salesRepProfile.Id,
								     Username = System.now().millisecond() + 'test3@test.com',
								     Alias = 'bruman',
								     Email= 'bruce.way@wayneenterprises.com',
								     EmailEncodingKey= 'UTF-8',
								     Firstname= 'Bruc',
								     Lastname= 'Wane',
								     LanguageLocaleKey= 'en_US',
								     LocaleSidKey= 'en_US',
								     TimeZoneSidKey= 'America/Chicago',
								     EC_CDM_User_Status__c = true,
								     IsActive= true);
		usrList.add(salesRepUser);
		insert usrList;
		System.runAs(portalUser) {
			Account portalAccount1 = new Account(Name = 'DummyAccountKey',
											     EC_CDM_Account__c = 'DummyAccountKey',
											     OwnerId = portalUser.Id);
			Database.insert(portalAccount1);
			List<RecordType> lstRecordType = [SELECT id, DeveloperName from RecordType where Name = :Label.EC_Account_Corporate];
			Account testAccount = new Account();
			testAccount.EC_Account_Number__c = 'CORP_2';
			testAccount.Name = 'TestCoporateAccount';
			testAccount.RecordTypeId = lstRecordType [0].Id;
			Insert testAccount;



			List<RecordType> lstRecordTypeSoldTO = [SELECT id, DeveloperName from RecordType where Name = :Label.EC_Account_SoldTo];

			Account testSoldto = new Account();
			testSoldto.Name = 'TESTSOLD TO';
			testSoldto.EC_Account_Number__c = '15081947';
			testSoldto.RecordTypeId = lstRecordTypeSoldTO [0].Id;
			testSoldto.EC_SalesRepresentative__c = salesRepUser1.id;
			Insert testSoldto;

			Account testSoldParent = new Account();
			testSoldParent.Name = 'TESTSOldParent';
			testSoldParent.EC_Account_Number__c = '15081950';
			testSoldParent.EC_CDM_Account__c = '15081950';
			testSoldParent.RecordTypeId = lstRecordTypeSoldTO [0].Id;
			Insert testSoldParent;

			Account testAcc = new Account();
			testAcc.Name = 'TESTSOLD TO456';
			testAcc.EC_Account_Number__c = '15089978';
			testAcc.RecordTypeId = lstRecordTypeSoldTO [0].Id;
			testAcc.EC_SalesRepresentative__c = salesRepUser1.id;
			Insert testAcc;

			Contact cntct = new Contact();
			cntct.LastName = 'testLasthere';
			cntct.AccountId = testSoldParent.Id;
			cntct.EC_CDM_Contact__c = '15081950';
			cntct.EC_SalesRep_User__c = salesRepUser.id;
			cntct.EC_isActive__c = true;
			cntct.EC_User_Type__c = 'Employee';
			Insert cntct;
			Contact cntct1 = new Contact();
			cntct1.LastName = 'testLast';
			cntct1.AccountId = testSoldto.Id;
			cntct1.EC_CDM_Contact__c = '789078';
			cntct1.EC_SalesRep_User__c = salesRepUser1.id;
			cntct1.EC_isActive__c = false;
			cntct1.EC_User_Type__c = 'Employee';
			Insert cntct1;

			AccountContactRelation accConRel = new AccountContactRelation(accountId = testSoldto.id, ContactId = cntct.id);

			insert accConRel;
			List<Id> userIdList = new List<Id>();
			userIdList.add(salesRepUser1.id);
			EC_UpdateSalesRepOnAccount.updateSalesRepOnUserInactive(userIdList);
		}

	}
}