src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EC_Division__c</fullName>
        <description>This field specifies the division that a Ship To account is related to.</description>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Institutional</fullName>
                    <label>INSTITUTIONAL</label>
                </value>
                <value>
                    <fullName>WATER</fullName>
                </value>
                <value>
                    <fullName>PAPER</fullName>
                </value>
                <value>
                    <fullName>FOOD &amp; BEVERAGE</fullName>
                </value>
                <value>
                    <fullName>ENERGY</fullName>
                </value>
                <value>
                    <fullName>PEST</fullName>
                </value>
                <value>
                    <fullName>TEXTILE CARE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EC_SalesRep_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EC SalesRep User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/EC_Division_Marketing_Content__c.object
<CustomObject>
    <description>Object to hold the division specific marketing content</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>is Image active or inactive</description>
        <inlineHelpText>active or inactive</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Body_Text__c</fullName>
        <description>Marketing Tile Body Text</description>
        <inlineHelpText>Marketing Tile Body Text</inlineHelpText>
        <label>Body Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EC_Content__c</fullName>
        <description>content for the image</description>
        <inlineHelpText>content for the image</inlineHelpText>
        <label>Image Content</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>EC_Division__c</fullName>
        <description>division to which this image to be displayed</description>
        <inlineHelpText>Ad tile division</inlineHelpText>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>INSTITUTIONAL</fullName>
                </value>
                <value>
                    <fullName>WATER</fullName>
                </value>
                <value>
                    <fullName>PAPER</fullName>
                </value>
                <value>
                    <fullName>FOOD &amp; BEVERAGE</fullName>
                </value>
                <value>
                    <fullName>ENERGY</fullName>
                </value>
                <value>
                    <fullName>TEXTILE CARE</fullName>
                </value>
                <value>
                    <fullName>PEST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Image_CTA_URL__c</fullName>
        <description>Call to action URL for image</description>
        <inlineHelpText>target site for image click</inlineHelpText>
        <label>Image CTA URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Open_In_NewTab__c</fullName>
        <formula>IF(ISPICKVAL(Image_CTA_URL_Type__c, &apos;External&apos;), TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Open In NewTab</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <description>sequence in which image to be displayed</description>
        <inlineHelpText>sequence of image on home page</inlineHelpText>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tile_CTA__c</fullName>
        <description>Marketing Tile CTA Button text</description>
        <inlineHelpText>Marketing Tile CTA Button text</inlineHelpText>
        <label>Tile CTA</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Division Marketing Content</label>
    <nameField>
        <label>Division Marketing Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Division Marketing Content</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>User_Type__c</fullName>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/EC_Adtiles_Content_Controller.cls
/*********************************************************************************
Class Name      : EC_Adtiles_Content_Controller
Description     : This class is used as the handler for adtiles Home page lightning component
Created By      : EDC
Created Date    : 12-08-2019
Modification Log:
---------------------------------------------------------------------------------- 
Developer                 Date                   Description
----------------------------------------------------------------------------------            
EDC                  12-08-2019          		 Initial Version 
*********************************************************************************/
public without sharing class EC_Adtiles_Content_Controller {
	@AuraEnabled
    public static List<EC_Division_Marketing_Content__c> getAdTileContents() { 
        List<EC_Division_Marketing_Content__c> adTileContents= new List<EC_Division_Marketing_Content__c>(); 
        String usrDivision= '';
        User loggedInUser = [Select Id, contact.account.EC_Division__c, User_Type__c FROM User WHERE Id =:UserInfo.getUserId()];
        if(loggedInUser.User_Type__c==null || loggedInUser.User_Type__c.EqualsIgnoreCase('external')){
            usrDivision= loggedInUser.contact.account.EC_Division__c;
        } else {
            Contact currContact = [Select Id,account.EC_Division__c FROM Contact WHERE EC_SalesRep_User__c=:UserInfo.getUserId() limit 1];
            if(currContact != null && currContact.account.EC_Division__c != null) {
                usrDivision = currContact.account.EC_Division__c;
            }
        }
   		adTileContents=[Select Id ,EC_Content__c,Image_CTA_URL__c,Open_In_NewTab__c,Body_Text__c,Tile_CTA__c from EC_Division_Marketing_Content__c where EC_Division__c=: usrDivision and Active__c=TRUE order by Sequence__c];
        if(!adTileContents.isempty()){
            system.debug('adTileContents'+ adTileContents);
            return adTileContents;
        }
        return null;
    }
}