src/objects/Account.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Account/fields/EC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>EC_Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>EC_Account_Number__c</fullName>
        <formula>Account.EC_Account_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Number</label>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>Category__c</fullName>
        <description>Used to in routing in Ecolab project.</description>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SupportCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <description>Used to in routing in Ecolab project.</description>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>SupportSubCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Run_Assignment_Rule__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field used for community case routing in Ecolab Project.</description>
        <label>Run Assignment Rule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <description>Used on community and as agent to take Contact Email as input in Service Cloud project.</description>
        <label>Case Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Hide_from_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hide from Customer</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <businessProcess>Support</businessProcess>
        <!--<compactLayoutAssignment>Support_Compact_Layout</compactLayoutAssignment>-->
        <description>Used for Ecolab service cloud, for Sales Rep, Community user and Agents.</description>
        <label>Support</label>
    </recordTypes>
</CustomObject>

src/globalValueSets/SupportCategory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Checkout</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Login</fullName>
    </customValue>
    <customValue>
        <fullName>Orders</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <customValue>
        <fullName>Quicklist</fullName>
    </customValue>
    <customValue>
        <fullName>Self-Service Register</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>User</fullName>
    </customValue>
    <description>Common picklist values on case and Chat bot routing object for Ecolab Project.</description>
    <masterLabel>Category</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/ChatBotCaseCreate.cls
/* Class Name      :ChatBotCaseCreate
* Description      :class called from einstien bot
* Created By       :Graytitude Team
* Created On       :14.09.2020
*
* Modification Log:
* ----------------------------------------------------------------------------------------------------------------
* Developer                Date                Modification ID             Description
* ----------------------------------------------------------------------------------------------------------------
* Graytitude Team          14.09.2020                                      create case from the einstien bot
*/
public without sharing class ChatBotCaseCreate {
    
    public class Request{
        @InvocableVariable(required=true)
        public String routableId;
        @InvocableVariable(required=true)
        public String category;
        @InvocableVariable(required=true)
        public String subcategory;
        @InvocableVariable(required=true)
        public String accountnumber;
        @InvocableVariable
        public String description;
        @InvocableVariable
        public String phone;
        @InvocableVariable
        public String email;
    }
    
    @InvocableMethod(label='Create Case')
    public static List<String> createCase(List<Request> input){
        List<String> response = new List<String>(); 
        try {
            LiveChatTranscript objCT;
            if(Schema.sObjectType.LiveChatTranscript.isAccessible()) { 
                objCT = [SELECT Id,AccountId,ContactId,CaseId FROM LiveChatTranscript WHERE Id=:input[0].routableId];
            }
            Id caseRTId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Support').getRecordTypeId();
            if(objCT.CaseId!=null) return response;
            
            Case objCase = new Case(
                RecordTypeId = caseRTId,
                ContactId = objCT.ContactId,
                Category__c = input[0].category,
                Sub_Category__c = input[0].subcategory,
                SuppliedPhone = input[0].phone,
                Contact_Email__c = input[0].email,
                Subject = input[0].description,
                Origin = 'Chatbot',
                Run_Assignment_Rule__c = true,                
                Hide_from_Customer__c = true
            );
            if(String.isNotBlank(input[0].accountnumber) && input[0].accountnumber.contains(':') && Schema.sObjectType.Account.isAccessible()) {
                String accNum = input[0].accountnumber.split(':')[1];
                accNum = accNum.trim();
                for(Account objAcc : [SELECT Id FROM Account WHERE EC_Account_Number__c=:accNum]) {
                    objCase.AccountId = objAcc.Id;
                }
            }         
            objCase = createCase(objCase);
            updateChatTranscript(objCT.Id,objCase.Id);            
            response.add(objCase.CaseNumber);
        } catch(Exception ex) { response.add('error'); }
        return response;
    }
    
    private static void updateChatTranscript(Id ctId, Id caseId) {
        if(Schema.sObjectType.LiveChatTranscript.isUpdateable()) {
            LiveChatTranscript newLCT = new LiveChatTranscript(Id=ctId, caseId=caseId);
            update newLCT;
        }
    }
    
    private static Case createCase(Case objCase) {
        if(Schema.sObjectType.Case.isCreateable()) {
            insert objCase;
        }
        Case caseRec;
        if(Schema.sObjectType.Case.isAccessible()){
            caseRec = [SELECT Id,CaseNumber FROM Case WHERE Id=:objCase.Id LIMIT 1];
        }
        return caseRec;
    }
    
    @TestVisible private ChatBotCaseCreate(){} //added as per suggestion of codescan
}