src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EC_Division__c</fullName>
        <description>This field specifies the division that a Ship To account is related to.</description>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Institutional</fullName>
                    <label>INSTITUTIONAL</label>
                </value>
                <value>
                    <fullName>WATER</fullName>
                </value>
                <value>
                    <fullName>PAPER</fullName>
                </value>
                <value>
                    <fullName>FOOD &amp; BEVERAGE</fullName>
                </value>
                <value>
                    <fullName>ENERGY</fullName>
                </value>
                <value>
                    <fullName>PEST</fullName>
                </value>
                <value>
                    <fullName>TEXTILE CARE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Account/fields/EC_SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>EC_SalesOrg__c</fullName>
    <label>SalesOrg</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/ccrz__E_AccountGroup__c.object
<CustomObject>
    <description>This object is used to group multiple accounts together to provide pricing and/or entitlements.  An account group can have 1 or more accounts associated with it.  It also can have 1 or more pricelists (used for pricing and entitlements) associated.  This object then ties the accounts and entitlements/pricing together, ultimately controlling the product list and pricing that a given account can see within B2B Commerce.</description>
    <label>CC Account Group</label>
    <nameField>
        <label>Account Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Account Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_CartItem__c.object
<CustomObject>
    <description>Cart Items</description>
    <fields>
        <fullName>ccrz__CartItemId__c</fullName>
        <description>External id that can be used for data loads.</description>
        <externalId>true</externalId>
        <label>Cart Item Id</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__Cart__c</fullName>
        <description>Reference to the parent cart.</description>
        <label>Cart</label>
        <referenceTo>ccrz__E_Cart__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>E_CartItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line item.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Cart Items (ProductID)</relationshipLabel>
        <relationshipName>E_CartItem2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Arrangement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Arrangement</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>CC Cart Items</relationshipLabel>
        <relationshipName>CC_Cart_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Cart Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CartItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceList__c.object
<CustomObject>
    <description>Represents a grouping of products to control pricing and entitlements.  The B2B Commerce pricelist object controls both pricing and entitlements, but can be used just for the purposes of entitlements. A list needs to be created for each currency that needs to be represented, allowing for different entitlments and pricing based on the locale and currency.</description>
    <fields>
        <fullName>ccrz__Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag determining whether or not this pricelist record is active</description>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer active.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is valid will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date that this product will be available.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within B2B Commerce</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Taxonomy__c</fullName>
        <description>To identity the type of product (Equipment or Chemical)</description>
        <label>Taxonomy </label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EC_CartDetailControllerHelper.cls
/* Class Name    : EC_CartDetailControllerHelper 
* Description      :Helper Class for EC_CartDetailController
* Created By       :Gaurav
* Created On       :2020-Aug-18


* Modification Log:
* ------------------------------------------------------------------------------
* Developer                Date            Modification ID         Description
* ------------------------------------------------------------------------------
* Gaurav                  2020-Aug-18                      
*
*/
public with sharing  class EC_CartDetailControllerHelper {
    
    
/***************************************************************************************************************************************
Method Name : saveBillingArrangement
Description : Stamp the BillingArrangement on cartItem on ProceedTo Checkout
Return type : NA
*************************************************************************************************************************************/
 
    public  void  ECsaveBillingArrangement(String cartsfId) {
        List<ccrz__E_CartItem__c> currentItemLists = new List<ccrz__E_CartItem__c>();
        set<String> ProdskuSet = new set<String>();
        List<ccrz__E_Product__c> prodList= new List<ccrz__E_Product__c>();

        Map<String,ccrz__E_Pricelist__c> lineItemSkuStampBA =new Map<String,ccrz__E_Pricelist__c> ();
        if(ccrz__E_CartItem__c.sObjectType.getDescribe().isAccessible()) {
            currentItemLists = [SELECT ccrz__CartItemId__c,ccrz__Product__r.ccrz__SKU__c,ccrz__Product__r.Taxonomy__c,ccrz__Cart__c,Billing_Arrangement__c,Id,Billing_Arrangement__r.ccrz__EndDate__c,Billing_Arrangement__r.ccrz__Enabled__c FROM ccrz__E_CartItem__c where ccrz__Cart__c =:cartsfId];
        }
        if(!currentItemLists.isEmpty()) { 
            for (ccrz__E_CartItem__c currentItemList : currentItemLists ) {
                ProdskuSet.add(currentItemList.ccrz__Product__r.ccrz__SKU__c);
                prodList.add(currentItemList.ccrz__Product__r);
                lineItemSkuStampBA.put(currentItemList.ccrz__Product__r.ccrz__SKU__c,currentItemList.Billing_Arrangement__r);
                ccrz.cclog.log('lineItemSkuStampBA----> ' , + lineItemSkuStampBA);
            }
        }
       
        Set<String> deleteStampBAset = new Set<String>();
		deleteStampBAset = deleteStampBAset(prodList,ProdskuSet,lineItemSkuStampBA);
        if(ccrz__E_CartItem__c.sObjectType.getDescribe().isAccessible()) {
            List<ccrz__E_CartItem__c> deleteBAs = new List<ccrz__E_CartItem__c>();
            deleteBAs = [SELECT ccrz__CartItemId__c,ccrz__Product__r.ccrz__SKU__c,ccrz__Product__r.Taxonomy__c,ccrz__Cart__c,Billing_Arrangement__c,Id,Billing_Arrangement__r.ccrz__EndDate__c,Billing_Arrangement__r.ccrz__Enabled__c FROM ccrz__E_CartItem__c where ccrz__Cart__c =:cartsfId AND ccrz__Product__r.ccrz__SKU__c IN:deleteStampBAset];       
            if(!deleteBAs.isEmpty()) {
                for(ccrz__E_CartItem__c deleteBA :deleteBAs){
                    //deleteBA.Billing_Arrangement__c = null;
                    ccrz.cclog.log('deleteBA----> ' , + deleteBA);
                }
                update deleteBAs;
            }
        }
    }
    
   /***************************************************************************************************************************************
	Method Name : deleteStampBAset
	Description : to delete the stamp BA on proceed to checkout.
	Return type : Set<String>
	**************************************************************************************************************************************/

    public  Set<String> deleteStampBAset(List<ccrz__E_Product__c> prodList, set<String> ProdskuSet, Map<String,ccrz__E_Pricelist__c> lineItemSkuStampBA) {
        Set<String> deleteStampBAset = new Set<String>();
        Map<String,Set<ccrz__E_Pricelist__c>> lineItemSkuBAsetMap =new Map<String,Set<ccrz__E_Pricelist__c>> ();
        String effAccountId = ccrz.cc_CallContext.effAccountId;
        List<Account> effAccountList = new List<Account>();
        if(Account.sObjectType.getDescribe().isAccessible()) {
            effAccountList = [Select Id,EC_SalesOrg__c,EC_Division__c,ccrz__E_AccountGroup__c FROM Account WHERE Id=:effAccountId LIMIT 1];
        }   
        Map<String,List<ccrz__E_Pricelist__c>> productLineBAMap = EC_ProductDetailController.productLineBASetMap(effAccountList[0].ccrz__E_AccountGroup__c,ProdskuSet);
        for(ccrz__E_Product__c prod : prodList){
            Set<ccrz__E_Pricelist__c> baSet = new Set<ccrz__E_Pricelist__c>();
            String sku = prod.ccrz__SKU__c;
            String taxonomy = prod.Taxonomy__c;
            baSet = baSetResponse(taxonomy,sku,productLineBAMap);
            if(!baSet.isEmpty() ) {
                //prod.put('skuBAset',baSet);
                lineItemSkuBAsetMap.put(sku,baSet);
                ccrz.cclog.log('lineItemSkuBAsetMap-->'+lineItemSkuBAsetMap);
            }
        }  
        for(ccrz__E_Product__c prod : prodList){
            String sku = prod.ccrz__SKU__c;
            if(lineItemSkuBAsetMap.get(sku) == null && lineItemSkuStampBA.get(sku) != null ){
                deleteStampBAset.add(sku);
            }
        }
        return deleteStampBAset;
    }
    @TestVisible
    public static Set<ccrz__E_Pricelist__c> baSetResponse(String taxonomy,String sku,Map<String,List<ccrz__E_Pricelist__c>> productLineBAMap  ){
        String GenEquipment = System.label.GEN_EQUIPMENT; 
        String GenChemical = System.label.GEN_CHEMICAL;
        Set<ccrz__E_Pricelist__c> baSet = new Set<ccrz__E_Pricelist__c>();
        if(taxonomy == System.label.EC_Chemistry && productLineBAMap.containsKey(GenChemical) && !productLineBAMap.isEmpty()){
            baSet.AddAll(productLineBAMap.get(GenChemical));
        }
        if(taxonomy == System.label.EC_Equipment && productLineBAMap.containsKey(GenEquipment)&& !productLineBAMap.isEmpty()){
            baSet.AddAll(productLineBAMap.get(GenEquipment));
        }
        if(productLineBAMap.containsKey(sku) && !productLineBAMap.isEmpty()){
            baSet.AddAll(productLineBAMap.get(sku)); 
        }
        
        return baSet;
    }    
    
}