src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EC_Division__c</fullName>
        <description>This field specifies the division that a Ship To account is related to.</description>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Institutional</fullName>
                    <label>INSTITUTIONAL</label>
                </value>
                <value>
                    <fullName>WATER</fullName>
                </value>
                <value>
                    <fullName>PAPER</fullName>
                </value>
                <value>
                    <fullName>FOOD &amp; BEVERAGE</fullName>
                </value>
                <value>
                    <fullName>ENERGY</fullName>
                </value>
                <value>
                    <fullName>PEST</fullName>
                </value>
                <value>
                    <fullName>TEXTILE CARE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Account/fields/EC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>EC_Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>ccrz__BillTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a CC Contact Address object that contains the bill to address data. This will be a unique copy of the address information captured during checkout.</description>
        <label>Bill To</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipLabel>Carts (BillToID)</relationshipLabel>
        <relationshipName>E_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__EncryptedId__c</fullName>
        <description>Semi-random UUID used to refer to the order in URLs.</description>
        <label>Encrypted Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_ContactAddr__c.object
<CustomObject>
    <description>Used to store address information.  Associated with Carts, Orders, Invoices, Subscriptions, Payments, etc.</description>
    <fields>
        <fullName>EC_Account_Number__c</fullName>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__AddrReadOnly__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field indicates whether this address is read only.</description>
        <label>AddrReadOnly</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__AddressFirstline__c</fullName>
        <description>First line of the street address.</description>
        <label>Address Firstline</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__AddressSecondline__c</fullName>
        <description>Second line of the street address.</description>
        <label>Address Secondline</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__AddressThirdline__c</fullName>
        <description>Third line of the street address.</description>
        <label>Address Thirdline</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__City__c</fullName>
        <description>City for the address.</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__CompanyName__c</fullName>
        <description>Company name associated with this address.</description>
        <label>Company Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__ContactAddrId__c</fullName>
        <description>External unique external id used for data loading.  Not used by B2B Commerce.</description>
        <externalId>true</externalId>
        <label>Contact Addr Id</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__CountryISOCode__c</fullName>
        <description>ISO code associated with the country.</description>
        <label>Country ISO Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Country__c</fullName>
        <description>Descriptive country name.  Typically country ISO code is used.</description>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__DaytimePhone__c</fullName>
        <description>Main phone number for the address.</description>
        <label>Daytime Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ccrz__Email__c</fullName>
        <description>Email address associated with the address.</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ccrz__FirstName__c</fullName>
        <description>Person first name associated with the address.</description>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__HomePhone__c</fullName>
        <description>Secondary phone associated with the address.</description>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ccrz__LastName__c</fullName>
        <description>Person last name associated with the address.</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__MailStop__c</fullName>
        <description>MailStop</description>
        <label>Mail Stop</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__MiddleName__c</fullName>
        <description>Person middle name associated with the address.</description>
        <label>Middle Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Partner_Id__c</fullName>
        <description>External Id used to tie the address to another system.  This id is carried through from the address book to the eventual order.</description>
        <label>Partner_Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__PostalCode__c</fullName>
        <description>Postal Code associated with the address.</description>
        <label>Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__ShippingComments__c</fullName>
        <description>If the user enters any shipping comments during checkout those comments will be in this field on the shipping address associated with the order.</description>
        <label>Shipping Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__StateISOCode__c</fullName>
        <description>For US and Canadian addresses this is the two letter ISO code for the state.</description>
        <label>State ISO Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__State__c</fullName>
        <description>For non-US or non-Canadian addresses this is the name of the state for the address.</description>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Contact Address</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Contact Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Contact Addresss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>ccrz__BillTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a CC Contact Address object that contains the bill to address data. This will be a unique copy of the address information captured during checkout.</description>
        <label>Bill To</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EC_Division__c</fullName>
        <formula>TEXT(ccrz__OriginatedCart__r.EC_Ship_To_Account__r.EC_Division__c)</formula>
        <label>Division</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__EncryptedId__c</fullName>
        <description>Semi-random id used to refer to the order in URLs.</description>
        <label>Encrypted Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__LongDescRT__c</fullName>
        <description>Rich text field for the Long Description</description>
        <label>LongDescRT</label>
        <length>5000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ccrz__LongDesc__c</fullName>
        <description>Product long description</description>
        <label>LongDesc</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EC_CheckoutControllerTest.cls
/* Class Name    : EC_CheckoutControllerTest
 * Description      Test Class to cover EC_CheckoutController
 * Created By       :Ashish
 * Created On       :2019-8-3
 

 * Modification Log:
 * -----------------------------------------------------------------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID         Description
 * -----------------------------------------------------------------------------------------------------------------------------------------------------------------
 * Ashish                 2019-8-3      BC-79847        Created the class   
 *
 */
@isTest
public class EC_CheckoutControllerTest {
    /***************************************************************************************************************************************
  Method Name : getProductDetailsTest
  Description : Test method to cover some methods of EC_CheckoutController
  Return type : void
 *************************************************************************************************************************************/
    @isTest
    static void getProductDetailsTest(){
        Test.setMock(HttpCalloutMock.class, new EC_PaymetricAPIMockImpl());
       // Test.setMock(HttpCalloutMock.class, new EC_PaymetricTokenAPIMockImpl());
       // Test.setMock(HttpCalloutMock.class, new EC_PaymetricXiPayAPIMockImpl());
        
        ccrz.cc_RemoteActionContext ctx = new ccrz.cc_RemoteActionContext(); 
        User thisUser = [SELECT Id  FROM User WHERE Id = :UserInfo.getUserId()];
        
        system.runas(thisUser){
            EC_TestData.setupCatalog();
            ccrz.cc_CallContext.pageLabels.put('EC_NALCO','water,energy,paper');
            ccrz__E_Cart__c cart = EC_TestData.createCart();
            List<ccrz__E_Order__c> ordList = EC_TestData.createOrders(1);
            
            Test.startTest();
            
            ccrz.cc_CallContext.userCurrency = 'USD';
            Account testAccount = EC_Testdata.testAccount;
			testAccount.EC_Division__c = 'water';
	        update testAccount;

            ccrz.cc_CallContext.effAccountId = testAccount.Id;
            EC_CheckoutController checkoutController = new EC_CheckoutController();
            
            EC_CheckoutController.billingObjWrapper billingObj = new EC_CheckoutController.billingObjWrapper();            
            billingObj.address1 = 'address1';
            billingObj.address2 = 'address2';
            billingObj.address3 = 'address3';
            billingObj.address4 = 'address4';
            billingObj.city = 'New York';
            billingObj.state = 'New York';
            billingObj.countryCode = 'USA';
            billingObj.postalCode = '77044';
            string billingObjString = JSON.serialize(billingObj);
            
            EC_CheckoutController.generateIframeURL(ctx);            
            EC_CheckoutController.generateIframeURL();
            ctx.queryParams = new Map<String,String>{
                'cartID' => cart.ccrz__EncryptedId__c
            };
            EC_CheckoutController.getTokenResults(ctx,'123','123','USD',billingObjString);
            
            
            EC_CacheWrapper usrInformation = new EC_CacheWrapper();
            usrInformation.userFirstName = 'testFirstName' ;
            usrInformation.userLastName = 'testLastName' ;
            usrInformation.userProfile = 'Sales Rep';

            Cache.SessionPartition orgPart = Cache.Session.getPartition('local.UserCache');
            orgPart.put('UserInfo1', usrInformation);
            list<ccrz__E_Product__c> prodMap = [SELECT id,ccrz__LongDesc__c,ccrz__LongDescRT__c FROM ccrz__E_Product__c];
            
            //System.assertNotEquals(null, checkoutController);
            ccrz.cc_RemoteActionContext rCon = new ccrz.cc_RemoteActionContext();
            List<Account> accountGroup = [Select id from Account];
            rCon.effAccountId =accountGroup[0].id;
            ccrz.cc_CallContext.initRemoteContext(rCon);
            checkoutController = new EC_CheckoutController();
            System.assertNotEquals(null, checkoutController);
            List<String> prodList = new List<String>();
            for(ccrz__E_Product__c prod : prodMap){
                prodList.add(prod.id);
            }
            
            
            System.assertNotEquals(null, EC_CheckoutController.getProductDetails( ctx, prodList,true,cart.id));
            System.assertNotEquals(null, EC_CheckoutController.getDataDetails( ctx, prodList,ordList[0].id));
            
            ccrz__E_ContactAddr__c billTo = [Select Name,EC_Account_Number__c,ccrz__AddressFirstline__c,ccrz__AddressSecondline__c,
                                             ccrz__AddressThirdline__c,ccrz__AddrReadOnly__c,ccrz__City__c,ccrz__CompanyName__c,ccrz__ContactAddrId__c,
                                             ccrz__Country__c,ccrz__CountryISOCode__c,ccrz__DaytimePhone__c,ccrz__Email__c,ccrz__FirstName__c,
                                             ccrz__HomePhone__c,ccrz__LastName__c,ccrz__MailStop__c,ccrz__MiddleName__c,ccrz__Partner_Id__c,
                                             ccrz__PostalCode__c,ccrz__ShippingComments__c,ccrz__State__c,ccrz__StateISOCode__c 
                                             from ccrz__E_ContactAddr__c where Id=: cart.ccrz__BillTo__c Limit 1];
            billTo.ccrz__Email__c = 'test@email.com';
            billTo.ccrz__MailStop__c = 'mailStop';
            billTo.ccrz__MiddleName__c = 'middleName';
            billTo.ccrz__Partner_Id__c = '123';
            billTo.ccrz__ShippingComments__c ='comments';
            
            update billTo;
            
            System.assertNotEquals(null, EC_CheckoutController.saveAdditionalCartData(ctx, 'attentionTo', 'attenNumber','12345', cart.ccrz__EncryptedId__c, billTo.id,'', true));
            
            
           
            
            Test.stopTest();
        }
    }
    /***************************************************************************************************************************************
  Method Name : getProductDetailsTest2
  Description : Test method to cover some methods of EC_CheckoutController
  Return type : void
 *************************************************************************************************************************************/
    @isTest
    static void getProductDetailsTest2(){
       Test.setMock(HttpCalloutMock.class, new EC_PaymetricXiPayAPIMockImpl());
        ccrz.cc_RemoteActionContext ctx = new ccrz.cc_RemoteActionContext(); 
        User thisUser = [SELECT Id  FROM User WHERE Id = :UserInfo.getUserId()];
        
        system.runas(thisUser){
            EC_TestData.setupCatalog();
            ccrz__E_Cart__c cart = EC_TestData.createCart();
            List<ccrz__E_Order__c> ordList = EC_TestData.createOrders(1);
            
            Test.startTest();
            
            ccrz.cc_CallContext.userCurrency = 'USD';
            ccrz.cc_CallContext.effAccountId = [Select Id from Account Limit 1].id;
            EC_CheckoutController checkoutController = new EC_CheckoutController();
            
            EC_CheckoutController.billingObjWrapper billingObj = new EC_CheckoutController.billingObjWrapper();            
            billingObj.address1 = 'address1';
            billingObj.address2 = 'address2';
            billingObj.address3 = 'address3';
            billingObj.address4 = 'address4';
            billingObj.city = 'New York';
            billingObj.state = 'New York';
            billingObj.countryCode = 'USA';
            billingObj.postalCode = '77044';
            string billingObjString = JSON.serialize(billingObj);
            
            EC_CheckoutController.generateIframeURL(ctx);            
            EC_CheckoutController.generateIframeURL();
            ctx.queryParams = new Map<String,String>{
                'cartID' => cart.ccrz__EncryptedId__c
            };
            EC_CheckoutController.getTokenResults(ctx,'123','123','USD',billingObjString);
            
            
            EC_CacheWrapper usrInformation = new EC_CacheWrapper();
            usrInformation.userFirstName = 'testFirstName' ;
            usrInformation.userLastName = 'testLastName' ;
            usrInformation.userProfile = 'Sales Rep';

            Cache.SessionPartition orgPart = Cache.Session.getPartition('local.UserCache');
            orgPart.put('UserInfo1', usrInformation);
            list<ccrz__E_Product__c> prodMap = [SELECT id,ccrz__LongDesc__c,ccrz__LongDescRT__c FROM ccrz__E_Product__c];
            
            //System.assertNotEquals(null, checkoutController);
            ccrz.cc_RemoteActionContext rCon = new ccrz.cc_RemoteActionContext();
            List<Account> accountGroup = [Select id from Account];
            rCon.effAccountId =accountGroup[0].id;
            ccrz.cc_CallContext.initRemoteContext(rCon);
            checkoutController = new EC_CheckoutController();
            System.assertNotEquals(null, checkoutController);
            List<String> prodList = new List<String>();
            for(ccrz__E_Product__c prod : prodMap){
                prodList.add(prod.id);
            }
            System.assertNotEquals(null, EC_CheckoutController.getProductDetails( ctx, prodList,true,cart.id));
            System.assertNotEquals(null, EC_CheckoutController.getDataDetails( ctx, prodList,ordList[0].id));
            
            ccrz__E_ContactAddr__c billTo = [Select Name,EC_Account_Number__c,ccrz__AddressFirstline__c,ccrz__AddressSecondline__c,
                                             ccrz__AddressThirdline__c,ccrz__AddrReadOnly__c,ccrz__City__c,ccrz__CompanyName__c,ccrz__ContactAddrId__c,
                                             ccrz__Country__c,ccrz__CountryISOCode__c,ccrz__DaytimePhone__c,ccrz__Email__c,ccrz__FirstName__c,
                                             ccrz__HomePhone__c,ccrz__LastName__c,ccrz__MailStop__c,ccrz__MiddleName__c,ccrz__Partner_Id__c,
                                             ccrz__PostalCode__c,ccrz__ShippingComments__c,ccrz__State__c,ccrz__StateISOCode__c 
                                             from ccrz__E_ContactAddr__c where Id=: cart.ccrz__BillTo__c Limit 1];
            billTo.ccrz__Email__c = 'test@email.com';
            billTo.ccrz__MailStop__c = 'mailStop';
            billTo.ccrz__MiddleName__c = 'middleName';
            billTo.ccrz__Partner_Id__c = '123';
            billTo.ccrz__ShippingComments__c ='comments';
            
            update billTo;
            
            System.assertNotEquals(null, EC_CheckoutController.saveAdditionalCartData(ctx, 'attentionTo', 'attenNumber','12345', cart.ccrz__EncryptedId__c, billTo.id,'', true));
            Test.stopTest();
        }
    }
    /***************************************************************************************************************************************
  Method Name : getProductDetailsTest3
  Description : Test method to cover some methods of EC_CheckoutController
  Return type : void
 *************************************************************************************************************************************/
    @isTest
    static void getProductDetailsTest3(){
       Test.setMock(HttpCalloutMock.class, new EC_PaymetricTokenizedAPIMockImpl());
        ccrz.cc_RemoteActionContext ctx = new ccrz.cc_RemoteActionContext(); 
        User thisUser = [SELECT Id  FROM User WHERE Id = :UserInfo.getUserId()];
        
        system.runas(thisUser){
            EC_TestData.setupCatalog();
            ccrz__E_Cart__c cart = EC_TestData.createCart();
            List<ccrz__E_Order__c> ordList = EC_TestData.createOrders(1);
            
            Test.startTest();
            
            ccrz.cc_CallContext.userCurrency = 'USD';
            ccrz.cc_CallContext.effAccountId = [Select Id from Account Limit 1].id;
            EC_CheckoutController checkoutController = new EC_CheckoutController();
            
            EC_CheckoutController.billingObjWrapper billingObj = new EC_CheckoutController.billingObjWrapper();            
            billingObj.address1 = 'address1';
            billingObj.address2 = 'address2';
            billingObj.address3 = 'address3';
            billingObj.address4 = 'address4';
            billingObj.city = 'New York';
            billingObj.state = 'New York';
            billingObj.countryCode = 'USA';
            billingObj.postalCode = '77044';
            string billingObjString = JSON.serialize(billingObj);
            
            EC_CheckoutController.generateIframeURL(ctx);            
            EC_CheckoutController.generateIframeURL();
            ctx.queryParams = new Map<String,String>{
                'cartID' => cart.ccrz__EncryptedId__c
            };
            EC_CheckoutController.getTokenResults(ctx,'123','123','USD',billingObjString);
            
            
            EC_CacheWrapper usrInformation = new EC_CacheWrapper();
            usrInformation.userFirstName = 'testFirstName' ;
            usrInformation.userLastName = 'testLastName' ;
            usrInformation.userProfile = 'Sales Rep';

            Cache.SessionPartition orgPart = Cache.Session.getPartition('local.UserCache');
            orgPart.put('UserInfo1', usrInformation);
            list<ccrz__E_Product__c> prodMap = [SELECT id,ccrz__LongDesc__c,ccrz__LongDescRT__c FROM ccrz__E_Product__c];
            
            //System.assertNotEquals(null, checkoutController);
            ccrz.cc_RemoteActionContext rCon = new ccrz.cc_RemoteActionContext();
            List<Account> accountGroup = [Select id from Account];
            rCon.effAccountId =accountGroup[0].id;
            ccrz.cc_CallContext.initRemoteContext(rCon);
            checkoutController = new EC_CheckoutController();
            System.assertNotEquals(null, checkoutController);
            List<String> prodList = new List<String>();
            for(ccrz__E_Product__c prod : prodMap){
                prodList.add(prod.id);
            }
            System.assertNotEquals(null, EC_CheckoutController.getProductDetails( ctx, prodList,true,cart.id));
            System.assertNotEquals(null, EC_CheckoutController.getDataDetails( ctx, prodList,ordList[0].id));
            
            ccrz__E_ContactAddr__c billTo = [Select Name,EC_Account_Number__c,ccrz__AddressFirstline__c,ccrz__AddressSecondline__c,
                                             ccrz__AddressThirdline__c,ccrz__AddrReadOnly__c,ccrz__City__c,ccrz__CompanyName__c,ccrz__ContactAddrId__c,
                                             ccrz__Country__c,ccrz__CountryISOCode__c,ccrz__DaytimePhone__c,ccrz__Email__c,ccrz__FirstName__c,
                                             ccrz__HomePhone__c,ccrz__LastName__c,ccrz__MailStop__c,ccrz__MiddleName__c,ccrz__Partner_Id__c,
                                             ccrz__PostalCode__c,ccrz__ShippingComments__c,ccrz__State__c,ccrz__StateISOCode__c 
                                             from ccrz__E_ContactAddr__c where Id=: cart.ccrz__BillTo__c Limit 1];
            billTo.ccrz__Email__c = 'test@email.com';
            billTo.ccrz__MailStop__c = 'mailStop';
            billTo.ccrz__MiddleName__c = 'middleName';
            billTo.ccrz__Partner_Id__c = '123';
            billTo.ccrz__ShippingComments__c ='comments';
            
            update billTo;
            
            System.assertNotEquals(null, EC_CheckoutController.saveAdditionalCartData(ctx, 'attentionTo', 'attenNumber','12345', cart.ccrz__EncryptedId__c, billTo.id,'', true));
            Test.stopTest();
        }
    }
}