src/objects/Account.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Account/fields/EC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>EC_Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EC_SalesRepresentative__c.field-meta.xml
<CustomField>
    <fullName>EC_SalesRepresentative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Harsha:07/09/19:The Sales Rep user related to the Sold to Account</description>
    <label>Sales Representative</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/EC_Status__c.field-meta.xml
<CustomField>
    <fullName>EC_Status__c</fullName>
    <description>Harsha:06/27/19:This field determines if an account us active and inactive</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>ccrz__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Account of the User that this cart was created for.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Carts</relationshipLabel>
        <relationshipName>E_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__ActiveCart__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When a new Cart is created, the cart is active by default. Whenever, we want to make anyother cart active, the current active cart should be deactivated</description>
        <label>Active Cart</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Contact of the User that this cart was created for.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CC Carts</relationshipLabel>
        <relationshipName>CC_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__EncryptedId__c</fullName>
        <description>Semi-random UUID used to refer to the order in URLs.</description>
        <label>Encrypted Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>ccrz__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Account of the User that this order was placed for.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Contact of the User that this order was placed for.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CC Orders</relationshipLabel>
        <relationshipName>CC_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__EncryptedId__c</fullName>
        <description>Semi-random id used to refer to the order in URLs.</description>
        <label>Encrypted Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent order, which originally submitted the subscription for this order, if applicable</description>
        <inlineHelpText>Parent order, which originally submitted the subscription for this order, if applicable</inlineHelpText>
        <label>Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Children Orders</relationshipLabel>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_OrderItem__c.object
<CustomObject>
    <description>The E_OrderItem__c object contains the line level detail of placed orders.</description>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <description>The order that this order line is a part of.</description>
        <label>Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Order Items (ProductID)</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Order Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>OrderItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within B2B Commerce</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_ProductMedia__c.object
<CustomObject>
    <description>Encapsulates media such as hero, thumbnail images, product brochures, owner&apos;s manuals, assembly guides, and videos associated with a product. Media&apos;s source could be in a form of attachment, static resource, or external resource(URI).</description>
    <fields>
        <fullName>ccrz__MediaType__c</fullName>
        <description>Determines where this image is displayed. Values are &quot;Product Image&quot;, &quot;Product Image Thumbnail&quot;, &quot;Product Search Image&quot;, &quot;Alternate Image&quot;</description>
        <label>Media Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alternate Images</fullName>
                </value>
                <value>
                    <fullName>Alternate Thumbnails</fullName>
                </value>
                <value>
                    <fullName>Datasheets</fullName>
                </value>
                <value>
                    <fullName>Safety Documents</fullName>
                </value>
                <value>
                    <fullName>Sales Brochures</fullName>
                </value>
                <value>
                    <fullName>Product Search Image</fullName>
                </value>
                <value>
                    <fullName>Owner&apos;s Manuals</fullName>
                </value>
                <value>
                    <fullName>Assembly Guides</fullName>
                </value>
                <value>
                    <fullName>JPG Image</fullName>
                </value>
                <value>
                    <fullName>Product Image</fullName>
                </value>
                <value>
                    <fullName>Product Image Thumbnail</fullName>
                </value>
                <value>
                    <fullName>Flash Files</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>SVG Interactive Diagram</fullName>
                </value>
                <value>
                    <fullName>Specification Sheets</fullName>
                </value>
                <value>
                    <fullName>Product Bulletins</fullName>
                </value>
                <value>
                    <fullName>Operating Manuals</fullName>
                </value>
                <value>
                    <fullName>SDS Documents</fullName>
                </value>
                <value>
                    <fullName>Label 1s</fullName>
                </value>
                <value>
                    <fullName>Label 2s</fullName>
                </value>
                <value>
                    <fullName>Catalog Sheets</fullName>
                </value>
                <value>
                    <fullName>Analytical Procedures</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__ProductMediaSource__c</fullName>
        <description>Source of the image. Values are &quot;URL&quot;, &quot;Static Resource&quot; and &quot;Attachment&quot;</description>
        <label>Product Media Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attachment</fullName>
                </value>
                <value>
                    <fullName>Static Resource</fullName>
                </value>
                <value>
                    <fullName>URI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <description>Reference to the category entry to which this media corresponds</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>E_ProductMedias</relationshipLabel>
        <relationshipName>E_ProductMedias</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CC Product Media</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Product Media Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Product Media</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EC_Athena_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>value__c</fullName>
        <label>value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EC Athena Settings</label>
</CustomObject>

src/objects/EC_Custom_Switch_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This object is to maintain all the Switches for the newly implemented functionalities</description>
    <fields>
        <fullName>Is_Athena_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This attribute is to switch Athena ON and OFF when needed</description>
        <label>Is Athena Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>EC Custom Switch Settings</label>
</CustomObject>

src/objects/EC_Custom_URL_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>custom_url__c</fullName>
        <label>Custom URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EC Custom URL Settings</label>
</CustomObject>

force-app/main/default/classes/EC_PastOrdersTest.cls
/*********************************************************************************
 Class Name      : EC_PastOrdersTest
 Description     : This class is used as the test class for EC_PastOrders
 Created By      :  Shruti Sinha ,Raghav Sharma
 Created Date    : 02-July-19
 Modification Log:
 ----------------------------------------------------------------------------------
 Developer                 Date                   Description
 ----------------------------------------------------------------------------------
 Shruti Sinha,Raghav Sharma              02-July-19              Initial Version
 *********************************************************************************/
@isTest
public class EC_PastOrdersTest {
	/***************************************************************************************************************************************
	 Method Name :  getPastOrderTest
	 Description : to get the previous orders
	 Return type : void
	 Author      : Raghav Sharma
	 *************************************************************************************************************************************/
	@isTest
	public static void getPastOrderTest() {
		EC_TestData.setupTestUser();
		User thisUser = [SELECT Id FROM User WHERE LastName = 'TestUser'];
		List<EC_PastOrders.OrderInfo> lstOrderInfo = new List<EC_PastOrders.OrderInfo>();
		system.runas(thisUser) {
			EC_TestData.setupCatalog();
			EC_TestData.createOrders(8);
			EC_TestData.createOutageRecord();
			EC_PastOrders.outageRedirect();
			Test.startTest();
			lstOrderInfo = EC_PastOrders.getPastOrder();
			System.assert(lstOrderInfo.size() > 0);
			Test.stopTest();
		}
	}
	/***************************************************************************************************************************************
	 Method Name :  reorderTestForExistingCart
	 Description : to test the reorder method of EC_PastOrders
	 Return type : void
	 Author      : Raghav Sharma
	 *************************************************************************************************************************************/
	@isTest
	public static void reorderTestForExistingCart() {
		EC_TestData.setupTestUser();
		User thisUser = [SELECT Id, ContactId FROM User WHERE LastName = 'TestUser'];
		system.runas(thisUser) {
			List<ccrz__E_Order__c> order = EC_TestData.createOrders(1);
			Test.startTest();
			String str = EC_PastOrders.reorder(order [0].Id);
			String str1 = EC_PastOrders.reorder(order [0].Id);

			Test.stopTest();
		}
	}

	/***************************************************************************************************************************************
	 Method Name :  reorderTestForExistingCart
	 Description : to test the reorder method of EC_PastOrders
	 Return type : void
	 Author      : Raghav Sharma
	 *************************************************************************************************************************************/

	@isTest
	public static void reorderTestForNewCart() {
		EC_TestData.setupTestUser();
		User thisUser = [SELECT Id, ContactId FROM User WHERE LastName = 'TestUser'];
		List<ccrz__E_Order__c> order = EC_TestData.createOrders(1);
		List<ccrz__E_Cart__c> cc_carts = [SELECT Id, ccrz__Contact__c, LastModifiedDate, ccrz__EncryptedId__c
									      FROM ccrz__E_Cart__c
									      WHERE ccrz__Contact__c = :thisUser.ContactId
									      AND ccrz__ActiveCart__c = true
									      order by lastModifieddate desc];
		delete cc_carts;
		system.runas(thisUser) {
			Test.startTest();
			String str = EC_PastOrders.reorder(order [0].Id);

			Test.stopTest();
		}
	}
	/***************************************************************************************************************************************
	 Method Name :  getOrderItemDetailsTest
	 Description : to test the reorder method of EC_PastOrders
	 Return type : void
	 Author      : Shruti Sinha
	 *************************************************************************************************************************************/

	@isTest
	public static void getOrderItemDetailsTest() {
		EC_TestData.setupTestUser();
		User thisUser = [SELECT Id, ContactId FROM User WHERE LastName = 'TestUser'];
		system.runas(thisUser) {
			EC_TestData.setupCatalog();
			EC_TestData.createOrders(10);


			ccrz__E_OrderItem__c order = [Select Id, ccrz__Order__r.Id, ccrz__Product__c from ccrz__E_OrderItem__c where ccrz__Product__r.ccrz__SKU__c = 'test003' limit 1];
			ccrz__E_ProductMedia__c sdsDoc = new ccrz__E_ProductMedia__c(ccrz__Product__c = order.ccrz__Product__c,
																    ccrz__ProductMediaSource__c = 'static',
																    ccrz__MediaType__c= 'Safety Documents');
			insert sdsDoc;

			Map<Id, List<ccrz__E_ProductMedia__c>> docmap = new Map<Id, List<ccrz__E_ProductMedia__c>>();

			List<EC_PastOrders.OrderItemWrapper> orderInfo = new List<EC_PastOrders.OrderItemWrapper>();

			Test.startTest();
			EC_PastOrders.OrderItemWrapper orderInfo1 = new EC_PastOrders.OrderItemWrapper();
			orderInfo = EC_PastOrders.getOrderDetails(order.ccrz__Order__r.Id);
			docmap = EC_PastOrders.getSDSDocuments(order.ccrz__Order__r.Id);
			EC_PastOrders.getInvoice(order.ccrz__Order__r.Id);


			System.assert(orderInfo.size() > 0);
			Test.stopTest();
		}
	}
	/***************************************************************************************************************************************
	 Method Name :  compVisibleTest
	 Description : to test the permCache
	 Return type : void
	 Author      : Shruti Sinha
	 *************************************************************************************************************************************/
	public static testmethod void compVisibleTest() {



		List<User> usrlist = EC_TestData.setupCommunityUser();
		EC_TestData.createPermissionSet(usrlist);
		User user = usrlist [0];
		EC_TestData.TestCacheUser(user);
		Test.startTest();
		EC_PastOrders.compVisible();
		Test.stopTest();
	}
	/***************************************************************************************************************************************
	 Method Name :  getPastOrderTest
	 Description : to get the previous orders
	 Return type : void
	 Author      : Shruti Sinha
	 *************************************************************************************************************************************/

	@isTest
	public static void getSalesRepPastOrderTest() {
		EC_TestData.setupTestSalesRepUser();
		User thisUser = [SELECT Id FROM User WHERE LastName = 'SalesRepUser'];
		List<EC_PastOrders.OrderInfo> lstOrderInfo = new List<EC_PastOrders.OrderInfo>();
		system.runas(thisUser) {
			EC_TestData.setupCatalog();
			EC_TestData.createOrders(8);
			EC_TestData.createContactForSalesrep(1);

			Test.startTest();
			lstOrderInfo = EC_PastOrders.getPastOrder();
			//  System.assert(lstOrderInfo.size()>0);
			Test.stopTest();
		}
	}

	/***************************************************************************************************************************************
	 Method Name :  getOrderDetailsTest
	 Description : to orders details
	 Return type : void
	 Author      : Shruti Sinha
	 *************************************************************************************************************************************/

	@isTest
	public static void getSalesRepOrderDetailsTest() {
		EC_TestData.setupTestSalesRepUser();
		User thisUser = [SELECT Id FROM User WHERE LastName = 'SalesRepUser'];

		system.runas(thisUser) {
			EC_TestData.setupCatalog();
			EC_TestData.createOrders(10);



			ccrz__E_OrderItem__c order = [Select Id, ccrz__Order__r.Id, ccrz__Product__c from ccrz__E_OrderItem__c where ccrz__Product__r.ccrz__SKU__c = 'test003' limit 1];

			Map<Id, List<ccrz__E_ProductMedia__c>> docmap = new Map<Id, List<ccrz__E_ProductMedia__c>>();

			List<EC_PastOrders.OrderItemWrapper> orderInfo = new List<EC_PastOrders.OrderItemWrapper>();

			Test.startTest();
			EC_PastOrders.OrderItemWrapper orderInfo1 = new EC_PastOrders.OrderItemWrapper();
			orderInfo = EC_PastOrders.getOrderDetails(order.ccrz__Order__r.Id);
			docmap = EC_PastOrders.getSDSDocuments(order.ccrz__Order__r.Id);
			EC_PastOrders.getInvoice(order.ccrz__Order__r.Id);


			System.assert(orderInfo.size() > 0);
			Test.stopTest();
		}
	}

   
/***************************************************************************************************************************************
      Method Name :  checkPayerPermissionTest
      Description : to orders details
      Return type : void
      Author      : Raghu Varma
*************************************************************************************************************************************/       
    
 @isTest 
    public static void checkPayerPermissionTest(){
        EC_TestData.setupTestUser();
        User thisUser = [SELECT Id FROM User WHERE LastName = 'TestUser'];
        PermissionSetAssignment perm = new PermissionSetAssignment();
        system.debug('thisUser:'+thisUser.Id);
        Test.startTest();
        PermissionSet ps = new PermissionSet();
        List<PermissionSet> pslist =[select id from PermissionSet where name =: EC_Constants.PayerCustomPermission];
            system.debug('pslist:'+pslist);
            if(pslist.size()>0){
                system.debug('pslist:'+pslist);
                ps = pslist[0];
            }
        List<PermissionSetAssignment> newAssignments = new List<PermissionSetAssignment>();
            newAssignments.add(new PermissionSetAssignment(
                PermissionSetId=ps.Id, AssigneeId=thisUser.Id
            ));
         Database.SaveResult[] sr = Database.insert(newAssignments, false);
        system.runas(thisUser) {
		   Boolean result = EC_PastOrders.checkPayerPermission();
        }
        Test.stopTest();
    }

    /***************************************************************************************************************************************
      Method Name :  getAthenaPastOrdersTest
      Description : 
      Return type : void
      Author      : Aravind Tallapaka
*************************************************************************************************************************************/
    @isTest  
    public static  void getAthenaPastOrdersTest(){
        EC_TestData.setupShipToTestUser();
        EC_TestData.createEC_PermissionSetMapping();        
        User usr = [Select Id,FirstName,LastName,ContactId,Contact.Email,Username,Contact.AccountId,Contact.Account.EC_Account_Number__c   FROM User WHERE LastName = 'TestUser'];
        System.runAs(usr){
            Account soldToAccount = new Account(
                Name                    = 'SoldTo_Acc',
                OwnerId                 = UserInfo.getUserId(),
                Type                    = 'Customer',
                EC_Status__c            = 'Active',
                EC_Account_Number__c    = '322235',
                EC_SalesRepresentative__c = UserInfo.getUserId(),
                recordtypeid            = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Sold To').getRecordTypeId()
            );
            insert soldToAccount;
            insert new EC_Custom_URL_Settings__c(Name = 'Athena_Orders_Cloudhub', custom_url__c = 'https://api-cloudhubcentral-st.ecolab.com/orders/v1/shiptonumbers');
            insert new EC_Custom_URL_Settings__c(Name = 'Microsoft OAuth Token', custom_url__c = 'https://login.microsoftonline.com/ecolab.com/oauth2/token');
            insert new EC_Athena_Settings__c(Name = 'GrantType', value__c = 'client_credentials');
            insert new EC_Athena_Settings__c(Name = 'ClientId', value__c = '81e0147a-46f3-4378-a28e-9f107202b9c8');
            insert new EC_Athena_Settings__c(Name = 'ClientSecret', value__c = '+8UK69YONWOA0nCOBwEbFh0X6GlHwASxoDqQec8xpR8=');
            insert new EC_Athena_Settings__c(Name = 'Resource', value__c = '0424e542-1ef6-4a47-81fc-9c533794e78c');            
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new EC_OmniOrdersMock());
            EC_PastOrders.getAthenaPastOrders();
            EC_TestData.createOutageRecord();
            Boolean outageFlag = EC_SelfRegistrationController.outageRedirect();
            System.assert(outageFlag);
            Test.stopTest();
        }
    }
      
/***************************************************************************************************************************************
      Method Name :  getProductDataTest
      Description : 
      Return type : void
      Author      : Raghu Varma
*************************************************************************************************************************************/       
@isTest 
    public static void getProductDataTest(){
        EC_TestData.setupTestUser();
        User thisUser = [SELECT Id FROM User WHERE LastName = 'TestUser'];
        
        List<String> productList = new List<String>();
        
        system.runas(thisUser){
            List<ccrz__E_Product__c> products = new List<ccrz__E_Product__c>();
            products = EC_TestData.products;
            ccrz__E_Cart__c cart = EC_TestData.createCart();
            for(ccrz__E_Product__c prod : products) {
            productList.add(prod.ccrz__SKU__c);
        }
            List<EC_PastOrders.AthenaOrderItemWrapper> productData = new List<EC_PastOrders.AthenaOrderItemWrapper>();
            Test.startTest();   
            productData = EC_PastOrders.getProductData(productList);
            System.assert(productData.size()>0);
            Test.stopTest();
        }
	}
	@isTest
    public static void athenaReorderTestForExistingCart(){
        EC_TestData.setupTestUser();
        User thisUser = [SELECT Id,ContactId FROM User WHERE LastName = 'TestUser'];
        system.runas(thisUser){
            List<ccrz__E_Order__c> order = EC_TestData.createShipToOrders(1);
            Test.startTest();
           
            String effectiveAccountId = order[0].ccrz__Account__c;
            List<ccrz__E_Product__c> products = new List<ccrz__E_Product__c>();
            products = EC_TestData.products;
            List<String> productList = new List<String>();
            List<String> productListQuantity = new List<String>();
            Integer count = 0;
            for(ccrz__E_Product__c prod : products) {
                productList.add(prod.ccrz__SKU__c);
                productListQuantity.add(prod.ccrz__SKU__c+':'+'1');
                count++;
                if(count > 5){
                    break;
                }
            }
            List<Account> AccountNumber = [SELECT EC_Account_Number__c FROM Account WHERE Id =: effectiveAccountId];
            system.debug('effectiveAccountId:'+effectiveAccountId);
            system.debug('productList:'+productList);
            system.debug('productListQuantity:'+productListQuantity);
            if(!AccountNumber.isEmpty()){
            	String str2 = EC_PastOrders.athenaReorder(AccountNumber[0].EC_Account_Number__c,productList,productListQuantity);
            }
            Test.stopTest();
        }
    }
   
    @isTest
    public static void athenaReorderTestForNewCart(){
        EC_TestData.setupTestUser();
        User thisUser = [SELECT Id, ContactId FROM User WHERE LastName = 'TestUser'];
        List<ccrz__E_Order__c> order = EC_TestData.createShipToOrders(1);
        List<ccrz__E_Cart__c> cc_carts = [SELECT Id, ccrz__Contact__c, LastModifiedDate, ccrz__EncryptedId__c
                                              FROM ccrz__E_Cart__c
                                              WHERE ccrz__Contact__c = :thisUser.ContactId
                                              AND ccrz__ActiveCart__c = true
                                              order by lastModifieddate desc];
        delete cc_carts;
        system.runas(thisUser){
            Test.startTest();
           
            String effectiveAccountId = order[0].ccrz__Account__c;
            List<ccrz__E_Product__c> products = new List<ccrz__E_Product__c>();
            products = EC_TestData.products;
            List<String> productList = new List<String>();
            List<String> productListQuantity = new List<String>();
            Integer count = 0;
            for(ccrz__E_Product__c prod : products) {
                productList.add(prod.ccrz__SKU__c);
                productListQuantity.add(prod.ccrz__SKU__c+':'+'1');
                count++;
                if(count > 5){
                    break;
                }
            }
            List<Account> AccountNumber = [SELECT EC_Account_Number__c FROM Account WHERE Id =: effectiveAccountId];
            system.debug('effectiveAccountId:'+effectiveAccountId);
            system.debug('productList:'+productList);
            system.debug('productListQuantity:'+productListQuantity);
            if(!AccountNumber.isEmpty()){
				String str1 = EC_PastOrders.athenaReorder(AccountNumber[0].EC_Account_Number__c,productList,productListQuantity);
            }
        
            Test.stopTest();
        }
    }
    @isTest
    public static void athenaSwitchSettingTest(){
        EC_TestData.setupTestUser();
        User thisUser = [SELECT Id, ContactId FROM User WHERE LastName = 'TestUser'];
        system.runas(thisUser){
            insert new EC_Custom_Switch_Settings__c(Name = 'AthenaSwitch', Is_Athena_Enabled__c = true);
        	Test.startTest();
			Boolean str1 = EC_PastOrders.getAthenaSwitchSetting();
			System.assert(str1 == true || str1 == false);
            Test.stopTest();
        }
    }
}