src/objects/Account.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Account/fields/EC_SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>EC_SalesOrg__c</fullName>
    <label>SalesOrg</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>EC_PurchasedWishlist__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Purchased Wishlist</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__CartType__c</fullName>
        <description>Cart type &quot;WishList&quot; can be used to keep track of items users want.</description>
        <label>Cart Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Read-Only WishList</fullName>
                </value>
                <value>
                    <fullName>WishList</fullName>
                </value>
                <value>
                    <fullName>Cart</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_CartItem__c.object
<CustomObject>
    <description>Cart Items</description>
    <fields>
        <fullName>EC_LastPurchasedDateFormatted__c</fullName>
        <description>To Display on the UI</description>
        <formula>CASE( MONTH( EC_Last_Purchased_Date__c ) ,
1, &quot;Jan&quot;,
2, &quot;Feb&quot;,
3, &quot;Mar&quot;,
4, &quot;Apr&quot;,
5, &quot;May&quot;,
6, &quot;Jun&quot;,
7, &quot;Jul&quot;,
8, &quot;Aug&quot;,
9, &quot;Sep&quot;,
10, &quot;Oct&quot;,
11, &quot;Nov&quot;,
12, &quot;Dec&quot;,
&quot;None&quot;) +&apos; &apos;+ text(DAY( EC_Last_Purchased_Date__c )) +&apos;, &apos;+ Text(YEAR( EC_Last_Purchased_Date__c ))</formula>
        <label>Last Purchased Date Formatted</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_Last_Purchased_Date__c</fullName>
        <label>Last Purchased Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Cart__c</fullName>
        <description>Reference to the parent cart.</description>
        <label>Cart</label>
        <referenceTo>ccrz__E_Cart__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>E_CartItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__ParentProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NOT USED</description>
        <label>Parent Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Cart Items (ParentProductID)</relationshipLabel>
        <relationshipName>E_CartItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line item.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Cart Items (ProductID)</relationshipLabel>
        <relationshipName>E_CartItem2</relationshipName>
        <type>Lookup</type>
    </fields>
        <fields>
        <fullName>Tank_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tank Number</label>
        <referenceTo>Tank_Detail__c</referenceTo>
        <relationshipLabel>CC Cart Items</relationshipLabel>
        <relationshipName>CC_Cart_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Cart Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CartItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>Material_Description__c</fullName>
        <formula>MID(ccrz__SKU__c, 0,FIND(&apos;.&apos;, ccrz__SKU__c )-1 )</formula>
        <label>Material Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Package_Code__c</fullName>
        <description>formula field to get the package code from SKU</description>
        <formula>IF(CONTAINS(ccrz__SKU__c,&quot;.&quot; ), MID(ccrz__SKU__c, FIND(&apos;.&apos;, ccrz__SKU__c )+1,LEN(ccrz__SKU__c)) , &apos;&apos;)</formula>
        <label>Package Code</label>
        <type>Text</type>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_ProductMedia__c.object
<CustomObject>
    <description>Encapsulates media such as hero, thumbnail images, product brochures, owner&apos;s manuals, assembly guides, and videos associated with a product. Media&apos;s source could be in a form of attachment, static resource, or external resource(URI).</description>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <description>Reference to the category entry to which this media corresponds</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>E_ProductMedias</relationshipLabel>
        <relationshipName>E_ProductMedias</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CC Product Media</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Product Media Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Product Media</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Chemical_Product_Type__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To identify the bulk product (User Story-122127)</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Package_Code__c</fullName>
        <label>Package Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Chemical Product Type</label>
</CustomObject>

src/objects/Delivery_Template_Package_Code_Mapping__mdt.object
<CustomObject>
    <fields>
        <fullName>Delivery_Template_Code__c</fullName>
        <label>Delivery Template Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Package_Code__c</fullName>
        <label>Package Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <label>Sales Org</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Delivery Template Package Code Mapping</label>
    <pluralLabel>Delivery Template Package Code Mappings</pluralLabel>
</CustomObject>

src/objects/Tank_Detail__c.object
<CustomObject>
    <description>Object to store all tank numbers for a particular Unloading point &amp; product.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tank Detail</relationshipLabel>
        <relationshipName>EC_Tank_Detail</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delivery_Template_Code__c</fullName>
        <label>Delivery Template Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material_Description__c</fullName>
        <label>Material Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tank_ID__c</fullName>
        <externalId>true</externalId>
        <label>Tank ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Tank_Number__c</fullName>
        <label>Tank Number</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delivery_Priority__c</fullName>
        <label>Delivery Priority</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Tank Detail</label>
    <nameField>
        <label>Tank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tank Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EC_ccServiceProductTest.cls
/* Class Name    : EC_ccServiceProductTest 
 * Description      Test Class to cover EC_ccServiceProduct
 * Created By       :Viraj
 * Created On       :2019-Oct-21
 

 * Modification Log:
 * -----------------------------------------------------------------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID         Description
 * -----------------------------------------------------------------------------------------------------------------------------------------------------------------
 * Viraj                2019-Oct-21      BC-91590        Created the class   
 *
 */
@isTest
public class EC_ccServiceProductTest {
    private static final String productList = 'productList';
    static testMethod void test_getFieldsMap(){
        
        EC_TestData.setupTestUser();
        User thisUser = [SELECT Id FROM User WHERE id = :EC_TestData.testUser.id LIMIT 1];
        system.runas(thisUser){

            EC_TestData.setupCatalog();
            List<ccrz__E_Cart__c> quicklists = EC_TestData.createQuickLists(1);
            
            List<ccrz__E_Cart__c> cartwishlist = [Select Name,OwnerId,EC_PurchasedWishlist__c, (Select Id,ccrz__Product__c,EC_Last_Purchased_Date__c,EC_LastPurchasedDateFormatted__c from ccrz__E_CartItems__r) from ccrz__E_Cart__c Where OwnerId = :thisUser.id AND ccrz__CartType__c='WishList' AND EC_PurchasedWishlist__c = TRUE Limit 1]; 
            
            List<Map<String,Object>> prodList = new List<Map<String,Object>>();
            Map<String,Object> prodMap = new Map<String,Object>();
            
            //Account shipTo = EC_TestData.testAccountShipTo;
            Account shipTo = [Select EC_SalesOrg__c from Account Where Id=:EC_TestData.testAccountShipTo.id];
            shipTo.EC_SalesOrg__c = '1001';
            update shipTo;
            ccrz.cc_CallContext.effAccountId = shipTo.id;
			
            List<ccrz__E_Product__c> prods = [Select Id from ccrz__E_Product__c  Limit 2];
			List<String> ProdIds = new List<String>();
            for(ccrz__E_Product__c prod: Prods) {
                ProdIds.add(prod.Id);
            }
            Chemical_Product_Type__c packTypeCS = new Chemical_Product_Type__c();
            packTypeCS.Active__c = true;
            packTypeCS.Package_Code__c = '91';
            packTypeCS.Name = '91';
            insert packTypeCS;
            prodMap = getProdMap(cartwishlist, shipTo); 
            prodList.add(prodMap);
            Map<String,Object> inputData = new Map<String,Object>();
            inputData.put(productList, prodList);
            Map<String,Object> inputData1 = new Map<String,Object>();
            inputData1.put('E_ProductMedias__r',prodList);
            
            Tank_Detail__c tankDetail = new Tank_Detail__c();
            tankDetail.Active__c = true;
            tankDetail.Tank_Id__c = System.Label.DropOff;
            tankDetail.Account__c = shipTo.Id;
            tankDetail.Tank_Number__c = '1223';
            tankDetail.Delivery_Priority__c = '7';
            tankDetail.Material_Description__c = 'ST70';
            tankDetail.Delivery_Template_Code__c = '91';
            insert tankDetail;
                        
            EC_ccServiceProduct extend= new EC_ccServiceProduct();
            CCRZ.cc_CallContext.currPageName =  'ccrz__Cart';
            
            List<Delivery_Template_Package_Code_Mapping__mdt> Dtemplates = Database.query('SELECT Delivery_Template_Code__c,DeveloperName,Package_Code__c,QualifiedApiName,Sales_Org__c FROM Delivery_Template_Package_Code_Mapping__mdt');
            system.debug(Dtemplates);
            
            Map<String, Object> res=extend.fetch(inputData);
            Map<String, Object> SubQueryMap = extend.getSubQueryMap(inputData1);
            system.debug('SubQueryMap' + SubQueryMap);
            //EC_ccServiceProduct.showHideAddtoCart(prodIds, shipTo.id, 'PLUS10.91', 'Chemistry');
            
            System.assert(null != res);
            
        }        
    }

    static testMethod void getFieldsMapMethod()
    {
        EC_ccServiceProduct var=new EC_ccServiceProduct();
        Test.startTest();
        Map<String, Object> testData=new Map<String, Object>();
        var.getFieldsMap(testData);
        system.assertEquals(0, testData.size());
        Test.stopTest();
    } 

    /***************************************************************************************************************************************
    Method Name : test_getFieldsMapISEDirect
    Description : Test method for Inst Sales Entitlement Direct Account   
    Return type : NA
	*************************************************************************************************************************************/  
    static testMethod void test_getFieldsMapISEDirect(){
        EC_TestData.setupTestUser();
        User thisUser = [SELECT Id FROM User WHERE id = :EC_TestData.testUser.id LIMIT 1];
        EC_ISETestDataFactory.setupInstSalesEntitlements();
        Account acc = EC_ISETestDataFactory.testAccount_ISEDirect;
        
        EC_TestData.setupCatalog();
        List<ccrz__E_Cart__c> quicklists = EC_ISETestDataFactory.createQuickListsforISEDirect(1);
        System.debug('quicklists' + quicklists);     
        List<ccrz__E_Cart__c> cartwishlist = [Select Name,OwnerId,EC_PurchasedWishlist__c, 
                                              (Select Id,ccrz__Product__c,EC_Last_Purchased_Date__c,
                                               EC_LastPurchasedDateFormatted__c from ccrz__E_CartItems__r) 
                                              from ccrz__E_Cart__c Where OwnerId = :thisUser.id 
                                              AND ccrz__CartType__c='WishList' AND EC_PurchasedWishlist__c = TRUE 
                                              Limit 1]; 
        
        ccrz.cc_CallContext.effAccountId = acc.Id; 
        system.debug('@test_getFieldsMapISE->effAccountId:' + acc.Id);
        List<Map<String,Object>> prodList = new List<Map<String,Object>>();
        Map<String,Object> productMap = new Map<String,Object>();
        productMap = getProdMap(cartwishlist, acc); 
        prodList.add(productMap);
        
        Map<String,Object> inputData = new Map<String,Object>();
        inputData.put(productList, prodList);
        
        Test.startTest();
        EC_ccServiceProduct extend= new EC_ccServiceProduct();
        Map<String, Object> result = extend.fetch(inputData);          
        System.assert(!result.isEmpty());
        Test.stopTest();
        
    }
     /***************************************************************************************************************************************
    Method Name : test_getFieldsMapISEIndirect
    Description : Test method for Inst Sales Entitlement InDirect Account   
    Return type : NA
	*************************************************************************************************************************************/  
   
    static testMethod void test_getFieldsMapISEIndirect(){
        EC_TestData.setupTestUser();
        User thisUser = [SELECT Id FROM User WHERE id = :EC_TestData.testUser.id LIMIT 1];
        EC_ISETestDataFactory.setupInstSalesEntitlements();
        Account acc = EC_ISETestDataFactory.testAccount_ISEIndirect;
        
        EC_TestData.setupCatalog();
        List<ccrz__E_Cart__c> quicklists = EC_ISETestDataFactory.createQuickListsforISEIndirect(1);
         System.debug('quicklists' + quicklists);     
        List<ccrz__E_Cart__c> cartwishlist = [Select Name,OwnerId,EC_PurchasedWishlist__c, 
                                              (Select Id,ccrz__Product__c,EC_Last_Purchased_Date__c,
                                               EC_LastPurchasedDateFormatted__c from ccrz__E_CartItems__r) 
                                              from ccrz__E_Cart__c Where OwnerId = :thisUser.id 
                                              AND ccrz__CartType__c='WishList' AND EC_PurchasedWishlist__c = TRUE 
                                              Limit 1]; 
        
        ccrz.cc_CallContext.effAccountId = acc.Id; 
        system.debug('@test_getFieldsMapISE->effAccountId:' + acc.Id);
        List<Map<String,Object>> prodList = new List<Map<String,Object>>();
        Map<String,Object> productMap = new Map<String,Object>();
        productMap = getProdMap(cartwishlist, acc); 
        prodList.add(productMap);
        
        Map<String,Object> inputData = new Map<String,Object>();
        inputData.put(productList, prodList);
        
        Test.startTest();
        EC_ccServiceProduct extend= new EC_ccServiceProduct();
        Map<String, Object> result = extend.fetch(inputData);          
        System.assert(!result.isEmpty());
        Test.stopTest();
        
    }
    static testMethod void test_getFieldsMapIStreetBrand(){
        EC_TestData.setupTestUser();
        User thisUser = [SELECT Id FROM User WHERE id = :EC_TestData.testUser.id LIMIT 1];
        EC_ISETestDataFactory.setupInstSalesEntitlements();
        Account acc = EC_ISETestDataFactory.testAccount_IStreetBrand;
        
        EC_TestData.setupCatalog();
        List<ccrz__E_Cart__c> quicklists = EC_ISETestDataFactory.createQuickListsforIStreetBrand(1);
        System.debug('quicklists' + quicklists);    
        List<ccrz__E_Cart__c> cartwishlist = [Select Name,OwnerId,EC_PurchasedWishlist__c, 
                                              (Select Id,ccrz__Product__c,EC_Last_Purchased_Date__c,
                                               EC_LastPurchasedDateFormatted__c from ccrz__E_CartItems__r) 
                                              from ccrz__E_Cart__c Where OwnerId = :thisUser.id 
                                              AND ccrz__CartType__c='WishList' AND EC_PurchasedWishlist__c = TRUE 
                                              Limit 1]; 
        
        ccrz.cc_CallContext.effAccountId = acc.Id; 
        system.debug('@test_getFieldsMapISE->effAccountId:' + acc.Id);
        List<Map<String,Object>> prodList = new List<Map<String,Object>>();
        Map<String,Object> productMap = new Map<String,Object>();
        productMap = getProdMap(cartwishlist, acc); 
        prodList.add(productMap);
        
        Map<String,Object> inputData = new Map<String,Object>();
        inputData.put(productList, prodList);
        
        Test.startTest();
        EC_ccServiceProduct extend= new EC_ccServiceProduct();
        Map<String, Object> result = extend.fetch(inputData);          
        System.assert(!result.isEmpty());
        Test.stopTest();
        
    }

    private static Map<String,Object> getProdMap(List<ccrz__E_Cart__c> cartwishlist, Account acc){
        Map<String,Object> productMap = new Map<String,Object>();
        
        productMap.put('sfid',cartwishlist[0].ccrz__E_CartItems__r[0].ccrz__Product__c);
        productMap.put('packageCode','91');
        productMap.put('materialDescription','ST70');
        productMap.put('effAccountId', acc.Id);
        productMap.put('taxonomy', 'Chemical');
        
        return productMap;
    }

}