src/objects/Account.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Account/fields/EC_SalesRepresentative__c.field-meta.xml
<CustomField>
    <fullName>EC_SalesRepresentative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Harsha:07/09/19:The Sales Rep user related to the Sold to Account</description>
    <label>Sales Representative</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/EC_Status__c.field-meta.xml
<CustomField>
    <fullName>EC_Status__c</fullName>
    <description>Harsha:06/27/19:This field determines if an account us active and inactive</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/EC_LogsEnabler__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>EC_LogsEnabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EC_LogsEnabled</label>
        <type>Checkbox</type>
    </fields>
    <label>EC_LogsEnabler</label>
</CustomObject>

src/objects/EC_Mulesoft_Integration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>EC_ClientId__c</fullName>
        <description>US:76262:Raghav:This field holds the client id for API Callout.</description>
        <label>EC_ClientId</label>
        <length>90</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_Client_Secret__c</fullName>
        <description>US-76262:Raghav:This fields holds the client secret for API Callout.</description>
        <label>EC_Client_Secret</label>
        <length>90</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_Endpoint__c</fullName>
        <label>Endpoint</label>
        <type>Url</type>
    </fields>
    <label>Mulesoft Integration</label>
</CustomObject>

src/objects/EC_User_Role_CDM__mdt.object
<CustomObject>
    <description>This is used to send the User Access Role to CDM</description>
    <fields>
        <fullName>EC_Permission_Name__c</fullName>
        <label>Permission Name</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <label>User Role CDM</label>
    <pluralLabel>User Role CDM</pluralLabel>
</CustomObject>

src/objects/EC_WebServiceCalloutsLog__c.object
<CustomObject>
    <description>This object to log all the Web Service Callouts</description>
    <fields>
        <fullName>EC_CodeTraverseLog__c</fullName>
        <description>Logs class entry exit, and method entry exits</description>
        <label>Code Traverse Log</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EC_ErrorMessage__c</fullName>
        <description>Error received in the Web Service callout</description>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EC_RequestCall__c</fullName>
        <description>The request JSON used</description>
        <label>Request Call</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EC_RequestName__c</fullName>
        <description>The type of web service callout request performed</description>
        <label>Request Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_ResponseCall__c</fullName>
        <description>The response JSON received.</description>
        <label>Response Call</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EC_Status__c</fullName>
        <description>Status of the Web Service call performed</description>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>WebService Callouts Log</label>
    <nameField>
        <displayFormat>WBC-{0000000000}</displayFormat>
        <label>WebService Callouts Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WebService Callouts Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>EC_CDM_User__c</fullName>
        <description>US-74960:Raghav:26/06/2019:This field will be used for mapping between CDM and user object.</description>
        <externalId>true</externalId>
        <label>External UserKey</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>User_Type__c</fullName>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/EC_AssignRoleInCDM.cls
/* Class Name       :EC_AssignRoleInCDM
* Description      :To assign the user role in CDM
* Created By       :Aqeeb Ahamed
* Created On       :20-05-2020
*
* Modification Log:
* ----------------------------------------------------------------------------------------------------------------
* Developer                Date                Modification ID             Description
* ----------------------------------------------------------------------------------------------------------------
* Aqeeb Ahamed          07-08-2019                                   EC_AssignRoleInCDM
*/
public without sharing class EC_AssignRoleInCDM {

    public static final string currentClassName = 'EC_AssignRoleInCDM';
    /*Constructor method to make it singleTon class */
    @TestVisible
    private EC_AssignRoleInCDM(){

    }


/***************************************************************************************************************************************
Method Name : roleAssignedCDM
Description : callout to  send user's role to CDM
Parameter   : String
Return type : void
Author      : Mishika Mahajan
*************************************************************************************************************************************/

    @future(callout = true)
    public static void roleAssignedCDM(String usrRole,String previousRole, Id UsrId){
        String methodName = 'roleAssignedCDM';
        String postJSon;
        EC_LogsEnabler__c punch =  EC_LogsEnabler__c.getValues('CaseCreationController');
        List<String> prevRole= new List<String>() ;
        List<String> currentRole= new List<String>();
        EC_WebServiceCalloutsLog__c logRec = new EC_WebServiceCalloutsLog__c();
        logRec.EC_RequestName__c = EC_Constants.roleAssignment;
        logRec.EC_CodeTraverseLog__c = currentClassName + EC_Constants.classEntry;
        logRec.EC_CodeTraverseLog__c = logRec.EC_CodeTraverseLog__c + EC_Constants.stringSeperater + methodName + EC_Constants.methodEntry;

        try{
            List<EC_User_Role_CDM__mdt> usrCDMMeta = EC_QueryUtility.getUserRoleCDMmdt(usrRole,null);
            List<EC_User_Role_CDM__mdt> usrCDMMetaPrev = EC_QueryUtility.getUserRoleCDMmdt(null,previousRole);
            User usr=  [SELECT Id,contactId,contact.name,contact.Email,User_Type__c,Name, contact.accountId,contact.Phone,
                        Contact.Account.EC_SalesRepresentative__r.Email, LanguageLocaleKey, EC_CDM_User__c
                    FROM User where Id =:UsrId];
            //null check
            if(usr!=null && usrCDMMeta!=null&& usr.EC_CDM_User__c!=null && usrCDMMetaPrev[0]!=null && usrCDMMeta[0]!=null){
                prevRole.add(usrCDMMetaPrev[0].EC_Permission_Name__c);
                currentRole.add(usrCDMMeta[0].EC_Permission_Name__c);
                EC_RoleMuleSoftWrapper muleWrap = new EC_RoleMuleSoftWrapper(prevRole,currentRole,Integer.valueOf(usr.EC_CDM_User__c),EC_Constants.ECLCONNECT);
                postJSon = JSON.serialize(muleWrap);
                logRec.EC_RequestCall__c = postJSon;
                EC_Mulesoft_Integration__c headerValues = EC_QueryUtility.getHeader(EC_Constants.USERROLE);
                String clientId = headerValues.EC_ClientId__c;
                String clientSecret = headerValues.EC_Client_Secret__c;
                String endPointUrl = headerValues.EC_Endpoint__c;
                HttpResponse response = EC_HTTPCalloutUtils.doPost(endPointUrl,postJSon,clientId,clientSecret);
                // Parse the JSON response
                if (response.getStatusCode() == 201) {
                    String result = response.getBody(); logRec.EC_Status__c = EC_Constants.SUCCESS; logRec.EC_ResponseCall__c = result;
                    logRec.EC_CodeTraverseLog__c = logRec.EC_CodeTraverseLog__c + EC_Constants.stringSeperater + methodName + EC_Constants.methodExit;
                    logRec.EC_CodeTraverseLog__c = logRec.EC_CodeTraverseLog__c + EC_Constants.stringSeperater + currentClassName + EC_Constants.classExit; insert logRec;
                } else {
                    EC_UtilityLogger.calloutErrorResponse(String.valueOf(response.getStatusCode()),'EC_AssignRoleInCDM','roleAssignedCDM',response.getStatus());
                    String result = response.getBody();
                    logRec.EC_Status__c = EC_Constants.failure;
                    logRec.EC_ResponseCall__c = result;
                    logRec.EC_CodeTraverseLog__c = logRec.EC_CodeTraverseLog__c + EC_Constants.stringSeperater + methodName + EC_Constants.methodExit;
                    logRec.EC_CodeTraverseLog__c = logRec.EC_CodeTraverseLog__c + EC_Constants.stringSeperater + currentClassName + EC_Constants.classExit;
                    if(punch.EC_LogsEnabled__c == true){
                        insert logRec;
                    }
                }
                if(Test.isRunningTest()) {
                    throw new DMLException('Test coverage');
                }
            }
        }catch(Exception ex){
            EC_UtilityLogger.logException(ex,'EC_AssignRoleInCDM','roleAssignedCDM',false,null,'');
            logRec.EC_Status__c = EC_Constants.failure;
            logRec.EC_ErrorMessage__c = ex.getMessage();
            logRec.EC_CodeTraverseLog__c = logRec.EC_CodeTraverseLog__c + EC_Constants.stringSeperater + methodName + EC_Constants.methodExit;
            logRec.EC_CodeTraverseLog__c = logRec.EC_CodeTraverseLog__c + EC_Constants.stringSeperater + currentClassName + EC_Constants.classExit;
            if(punch.EC_LogsEnabled__c == true){
                upsert logRec;
            }
        }
    }
}