src/objects/Account.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Account/fields/EC_CDM_Account__c.field-meta.xml
<CustomField>
    <fullName>EC_CDM_Account__c</fullName>
    <description>US-74958:Raghav:26/06/2019:This field will be used for mapping between CDM and account object.</description>
    <externalId>true</externalId>
    <label>External Account Key</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/EC_SalesRepresentative__c.field-meta.xml
<CustomField>
    <fullName>EC_SalesRepresentative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Harsha:07/09/19:The Sales Rep user related to the Sold to Account</description>
    <label>Sales Representative</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EC_SalesRep_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EC SalesRep User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>EC_CDM_User_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Captures the CDM User status</description>
        <label>CDM User Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_Type__c</fullName>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/EC_SalesRepUpdBatch.cls
/* Class Name       :EC_StagingUserDelete
* Description      :Batch class to update Sales rep on account
* Created By       :Shivam Vats
* Created On       :08-23-2019
*
* Modification Log:
* ----------------------------------------------------------------------------------------------------------------
* Developer                Date                Modification ID             Description
* ----------------------------------------------------------------------------------------------------------------
* Shivam Vats        08-23-2019                                    Batch class to update Sales rep on account
*
*/

global class EC_SalesRepUpdBatch implements Database.Batchable<Sobject> {
  global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT EC_CDM_Account__c FROM Account where  EC_SalesRepresentative__c = \'\' OR EC_SalesRepresentative__r.EC_CDM_User_Status__c = false';
        return Database.getQueryLocator(query);
     }
     global void execute(Database.BatchableContext bc,List<Account> acctRecords){
        List<Account> acctUpdate = new list<Account>();
        List<AccountContactRelation> accContactList = new List<AccountContactRelation>();
        Map<String,Id> accContMap = new Map<String,Id>();
        List<String> accKeyRecords = new List<String>();

         for(Account acc:acctRecords)
         {
             accKeyRecords.add(acc.EC_CDM_Account__c);
         }

        accContactList = [SELECT id, contact.EC_SalesRep_User__c, account.EC_CDM_Account__c FROM AccountContactRelation where contact.EC_SalesRep_User__r.EC_CDM_User_Status__c = true and contact.EC_SalesRep_User__r.User_Type__c = 'Internal' and account.EC_CDM_Account__c in :accKeyRecords];
        for(AccountContactRelation accCont: accContactList){
            if(!accContMap.containsKey(accCont.account.EC_CDM_Account__c)){
                if(accCont.contact.EC_SalesRep_User__c != null){
                    accContMap.put(accCont.account.EC_CDM_Account__c,accCont.contact.EC_SalesRep_User__c);
                }
            }
        }
        for(Account acct:[Select EC_CDM_Account__c,EC_SalesRepresentative__c from Account where EC_CDM_Account__c in:accKeyRecords]){
            if(accContMap.containskey(acct.EC_CDM_Account__c)){
                acct.EC_SalesRepresentative__c = accContMap.get(acct.EC_CDM_Account__c);
            }else{
                acct.EC_SalesRepresentative__c = null;
            }
           acctUpdate.add(acct);
        }
        if(acctUpdate != null && !acctUpdate.isEmpty()){
            update acctUpdate;
        }

    }

    global void finish(Database.BatchableContext bc){

    }
      }