src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EC_Division__c</fullName>
        <description>This field specifies the division that a Ship To account is related to.</description>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Institutional</fullName>
                    <label>INSTITUTIONAL</label>
                </value>
                <value>
                    <fullName>WATER</fullName>
                </value>
                <value>
                    <fullName>PAPER</fullName>
                </value>
                <value>
                    <fullName>FOOD &amp; BEVERAGE</fullName>
                </value>
                <value>
                    <fullName>ENERGY</fullName>
                </value>
                <value>
                    <fullName>PEST</fullName>
                </value>
                <value>
                    <fullName>TEXTILE CARE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Account/fields/EC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>EC_Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EC_Billing_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>EC_Billing_Account_Number__c</fullName>
    <externalId>true</externalId>
    <label>Billing Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EC_SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>EC_SalesOrg__c</fullName>
    <label>SalesOrg</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
        <fields>
        <fullName>Default_Unloading_Point__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Selected Unloading Point</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipLabel>CC Carts (Default Unloading Point)</relationshipLabel>
        <relationshipName>CC_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__EffectiveAccountID__c</fullName>
        <description>Holds the effective account for this cart.  This field will be utilized in implementations where a user can order for multiple accounts inclusive or exclusive of their own.  The effective account is used to control the entitlements, pricing, integrations etc that drive the site experience.</description>
        <inlineHelpText>This field will be utilized in implementations where a user can order for multiple accounts inclusive or exclusive of their own.  The effective account is used to control the entitlements, pricing, integrations etc that drive the site experience.</inlineHelpText>
        <label>Effective Account ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__EncryptedId__c</fullName>
        <description>Semi-random UUID used to refer to the order in URLs.</description>
        <label>Encrypted Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__SubtotalAmount__c</fullName>
        <description>Sum of CC Cart Item : Item Total</description>
        <label>Subtotal Amount</label>
        <summarizedField>ccrz__E_CartItem__c.ccrz__ItemTotal__c</summarizedField>
        <summaryForeignKey>ccrz__E_CartItem__c.ccrz__Cart__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_CartItem__c.object
<CustomObject>
    <description>Cart Items</description>
    <fields>
        <fullName>ccrz__Cart__c</fullName>
        <description>Reference to the parent cart.</description>
        <label>Cart</label>
        <referenceTo>ccrz__E_Cart__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>E_CartItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>The unit price of the line.</description>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__PricingType__c</fullName>
        <defaultValue>&quot;auto&quot;</defaultValue>
        <description>Defines how B2B Commerce internally handles the pricing for this cart/order item. If &apos;external&apos; then B2B Commerce pricing will not apply to the cart item (see further documentation for exact rules).</description>
        <label>Pricing Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line item.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Cart Items (ProductID)</relationshipLabel>
        <relationshipName>E_CartItem2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Quantity of the line item.</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__SubAmount__c</fullName>
        <description>Sub Amount total for the line.  Typically will be Price times Quantity.</description>
        <label>Sub Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billing_Arrangement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Arrangement</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>CC Cart Items</relationshipLabel>
        <relationshipName>CC_Cart_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Cart Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CartItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_ContactAddr__c.object
<CustomObject>
    <description>Used to store address information.  Associated with Carts, Orders, Invoices, Subscriptions, Payments, etc.</description>
    <fields>
        <fullName>EC_Account_Number__c</fullName>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>CC Contact Address</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Contact Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Contact Addresss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceList__c.object
<CustomObject>
    <description>Represents a grouping of products to control pricing and entitlements.  The B2B Commerce pricelist object controls both pricing and entitlements, but can be used just for the purposes of entitlements. A list needs to be created for each currency that needs to be represented, allowing for different entitlments and pricing based on the locale and currency.</description>
    <fields>
        <fullName>ccrz__Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag determining whether or not this pricelist record is active</description>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer active.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is valid will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date that this product will be available.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within B2B Commerce</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EC_ccLogicCartPrice.cls
/* Class Name      : EC_ccLogicCartPrice
* Description      : Logic Cart Price Related inherited cloud craze interface
* Created By       : Bharath KN 
* Created On       : 05-29-2020

* Modification Log:
* ------------------------------------------------------------------------------------------------------------------
* Developer                Date            Modification ID         Description
* ------------------------------------------------------------------------------------------------------------------
* Bharath KN               05-29-2020                              Initial version (log modification)
*
*
*/

global virtual with sharing class EC_ccLogicCartPrice extends ccrz.ccLogicCartPrice {
    global virtual override Map<String,Object> Process(Map<String,Object> inputData) {
        // Save UOM fields in cartItem for NALCO
        String effAccountId = ccrz.cc_CallContext.effAccountId;
        String division='';
        if (Account.sObjectType.getDescribe().isAccessible()) {
            List<Account> effAccountList = [Select Id,EC_SalesOrg__c,EC_Division__c FROM Account WHERE Id=:effAccountId LIMIT 1];
            if(!effAccountList.isEmpty()){
                division = effAccountList[0].EC_Division__c;
            }
        }
        if(System.label.EC_DivisionValueNACLO.containsIgnoreCase(division) && ccrz.cc_CallContext.currPageName =='ccrz__Cart') {
            String currCart = ccrz.cc_CallContext.currCartId;
            if (ccrz__E_Cart__c.sObjectType.getDescribe().isAccessible() && ccrz__E_ContactAddr__c.sObjectType.getDescribe().isAccessible()) {
                checkUnlodingPoint(currCart);
            }
            EC_CartDetailController.updateCartItemUOM(currCart);
        }
        Map<String,Object> retData = super.process(inputData);
        return returnCartItems(retData);
    }
    
    public static void checkUnlodingPoint(String currCart){
        if (ccrz__E_Cart__c.sObjectType.getDescribe().isAccessible()) {
            List<ccrz__E_Cart__c> cart = [Select Id, Default_Unloading_Point__c,ccrz__EffectiveAccountID__c  from ccrz__E_Cart__c Where id=:currCart OR ccrz__EncryptedId__c =:currCart ];
            if(!cart.isEmpty() && cart[0].Default_Unloading_Point__c != null ){
                String billingAccountNumber = [Select EC_Billing_Account_Number__c from Account Where Id=:cart[0].ccrz__EffectiveAccountID__c].EC_Billing_Account_Number__c;
                Id selectedUnloadingPoint = cart[0].Default_Unloading_Point__c;
                List<ccrz__E_ContactAddr__c> unloadingPointForSelectedAccount = [SELECT Id, EC_Account_Number__c FROM ccrz__E_ContactAddr__c Where id=:selectedUnloadingPoint and Active__c=true and EC_Account_Number__c =: billingAccountNumber];
                if(unloadingPointForSelectedAccount.isEmpty() && ccrz__E_Cart__c.sObjectType.getDescribe().isAccessible()){
                    cart[0].Default_Unloading_Point__c = null;
                    update cart;
                }
            }
        }
    }

    private static Map<String,Object> returnCartItems(Map<String,Object> returnData)
    {
        //BA Logic - Show Entitled price if BA expired.
        String cartId = String.valueof(returnData.get('cartId'));
        Date today = Date.today();
       	List<ccrz__E_CartItem__c> cartItems = new List<ccrz__E_CartItem__c>();
        if(!ccrz__E_CartItem__c.sObjectType.getDescribe().isAccessible()) {
            return new Map<String, Object>();
        }
        cartItems = [SELECT Id,ccrz__Product__c,ccrz__Quantity__c,ccrz__Price__c,Billing_Arrangement__c,Billing_Arrangement__r.ccrz__EndDate__c,Billing_Arrangement__r.ccrz__Enabled__c,ccrz__Product__r.ccrz__sku__c,ccrz__Cart__c,ccrz__Cart__r.Id,ccrz__Cart__r.ccrz__SubtotalAmount__c FROM ccrz__E_CartItem__c where ccrz__Cart__r.Id=:cartId];

            for(ccrz__E_CartItem__c cartItem: cartItems) {
                if(cartItem.Billing_Arrangement__r.ccrz__Enabled__c == false || cartItem.Billing_Arrangement__r.ccrz__EndDate__c < today){
                    cartItem.ccrz__PricingType__c='auto';
                    cartItem.ccrz__SubAmount__c=cartItem.ccrz__Quantity__c*cartItem.ccrz__Price__c;
                }
            }
            update cartItems;
        ccrz.ccLog.log('ccLogicCartValidate retData---' + cartItems);
        
        ccrz.cclog.log('ccLogicCartPriceAK applyPricing retData--->' + returnData);
        //BA Logic Ends.
        return returnData;   
    }
}