src/objects/Account.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Account/fields/EC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>EC_Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EC_Status__c.field-meta.xml
<CustomField>
    <fullName>EC_Status__c</fullName>
    <description>Harsha:06/27/19:This field determines if an account us active and inactive</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>EC_PunchOut_CallBack_URL__c</fullName>
        <label>Call Back URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>EC_Punchout_Buyer_Cookie__c</fullName>
        <label>Buyer Cookie</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Account of the User that this cart was created for.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Carts</relationshipLabel>
        <relationshipName>E_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__ActiveCart__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When a new Cart is created, the cart is active by default. Whenever, we want to make anyother cart active, the current active cart should be deactivated</description>
        <label>Active Cart</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__AnonymousId__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Checks if the user is anonymous or not.
If true the user is anonymous or not logged in
if false he is logged in. Will be used in merging of an anonymous cart with a logged in users cart.</description>
        <label>Anonymous Id</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__CartStatus__c</fullName>
        <description>Cart Status: Every cart is created with a &quot;Open&quot; state, and set to &quot;Closed&quot; state after a corresponding order is placed.</description>
        <label>Cart Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__CartType__c</fullName>
        <description>Cart type &quot;WishList&quot; can be used to keep track of items users want.</description>
        <label>Cart Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Read-Only WishList</fullName>
                </value>
                <value>
                    <fullName>WishList</fullName>
                </value>
                <value>
                    <fullName>Cart</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Contact of the User that this cart was created for.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CC Carts</relationshipLabel>
        <relationshipName>CC_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__CurrencyISOCode__c</fullName>
        <description>The currency that this cart was created in.</description>
        <label>Currency ISO Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__EffectiveAccountID__c</fullName>
        <description>Holds the effective account for this cart.  This field will be utilized in implementations where a user can order for multiple accounts inclusive or exclusive of their own.  The effective account is used to control the entitlements, pricing, integrations etc that drive the site experience.</description>
        <inlineHelpText>This field will be utilized in implementations where a user can order for multiple accounts inclusive or exclusive of their own.  The effective account is used to control the entitlements, pricing, integrations etc that drive the site experience.</inlineHelpText>
        <label>Effective Account ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__EncryptedId__c</fullName>
        <description>Semi-random UUID used to refer to the order in URLs.</description>
        <label>Encrypted Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>The storefront under which the order was placed.</description>
        <label>Storefront</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the User that this order was placed for.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>E_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EC_LogsEnabler__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>EC_LogsEnabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EC_LogsEnabled</label>
        <type>Checkbox</type>
    </fields>
    <label>EC_LogsEnabler</label>
</CustomObject>

src/objects/EC_PunchinCodes__mdt.object
<CustomObject>
    <fields>
        <fullName>EC_CustomCodes__c</fullName>
        <label>EC_CustomCodes</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_Message__c</fullName>
        <label>EC_Message</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>EC_PunchInCode</label>
    <pluralLabel>EC_PunchInCodes</pluralLabel>
</CustomObject>

src/objects/EC_PunchOutInfo__c.object
<CustomObject>
    <fields>
        <fullName>EC_BuyerCookie__c</fullName>
        <label>EC_BuyerCookie</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_EncryptedCartId__c</fullName>
        <label>EC_EncryptedCartId</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_From_Domain__c</fullName>
        <label>EC_From_Domain</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_From_Identity__c</fullName>
        <label>EC_ From_Identity</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_PayloadId__c</fullName>
        <label>EC_PayloadId</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_SenderUserAgent__c</fullName>
        <label>EC_SenderUserAgent</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_Sender_Domain__c</fullName>
        <label>EC_Sender_Domain</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_Sender_Identity__c</fullName>
        <label>EC_ Sender_Identity</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_To_Domain__c</fullName>
        <label>EC_To_Domain</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_To_Identity__c</fullName>
        <label>EC_ To_Identity</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_Version__c</fullName>
        <label>EC_Version</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_XMLLanguage__c</fullName>
        <label>EC_XMLLanguage</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>PunchOutInfo</label>
    <nameField>
        <label>EC_PunchOutInfo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PunchOutInfos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_PunchoutSecretKey__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>EC_Secret_Key__c</fullName>
        <label>Secret Key</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <label>EC_PunchoutSecretKey</label>
</CustomObject>

src/objects/EC_WebServiceCalloutsLog__c.object
<CustomObject>
    <description>This object to log all the Web Service Callouts</description>
    <fields>
        <fullName>EC_CodeTraverseLog__c</fullName>
        <description>Logs class entry exit, and method entry exits</description>
        <label>Code Traverse Log</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EC_RequestCall__c</fullName>
        <description>The request JSON used</description>
        <label>Request Call</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EC_RequestName__c</fullName>
        <description>The type of web service callout request performed</description>
        <label>Request Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_ResponseCall__c</fullName>
        <description>The response JSON received.</description>
        <label>Response Call</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EC_Status__c</fullName>
        <description>Status of the Web Service call performed</description>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>WebService Callouts Log</label>
    <nameField>
        <displayFormat>WBC-{0000000000}</displayFormat>
        <label>WebService Callouts Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WebService Callouts Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EC_PunchInService.cls
/* Class Name       :EC_PunchInService
* Description      : Web Service API for Punchout Service
* Created By       :Raghav Sharma
* Created On       :06-10-2019
*
* Modification Log:
* ----------------------------------------------------------------------------------------------------------------
* Developer                Date                Modification ID             Description
* ----------------------------------------------------------------------------------------------------------------
* Raghav Sharma        06-10-2019                                  Web Service API for Punchout Service
* Ayusha Patnaik
*/
@RestResource(urlMapping='/Punchout/*')
global without sharing class EC_PunchInService {
    public static string currentClassName = 'EC_PunchInService';
    public static EC_WebServiceCalloutsLog__c logRec = new EC_WebServiceCalloutsLog__c();
    @HttpPost
    webservice static void createCallBackURL(String ukey, String pkey,
                                             String shipTo, String sharedSecret, String callBackURL,String buyerCookie,
                                             String fromDomain, String fromIdentity, String senderDomain, String senderIdentity, String toDomain, String toIdentity, String senderUserAgent, String xmlLanguage, String payloadId, String version ) {
                                                 String methodName = 'createCallBackURL';
                                                 EC_LogsEnabler__c punch =  EC_LogsEnabler__c.getInstance('PunchInService');
                                                 String requestCall = '{\n"ukey": "'+ukey+'",\n"pkey": " '+pkey+'",\n "shipTo":  "'+shipTo+'",\n "sharedSecret": "'+sharedSecret+'", \n"callBackURL": " '+callBackURL+'",\n "buyerCookie": " '+buyerCookie+'",\n "fromDomain": " '+fromDomain+'",\n "fromIdentity": "'+fromIdentity
                                                     +'",\n "senderDomain": "'+senderDomain+'",\n "senderIdentity": "'+senderIdentity+'", \n"toDomain": "'+toDomain+'", \n"toIdentity": "'+toIdentity+'",\n "senderUserAgent": "'+senderUserAgent+'", \n"xmlLanguage": "'+xmlLanguage+'",\n"payloadId": "'+payloadId
                                                     +'",\n "version": "'+Version+'"\n}';
                                                 logRec.EC_RequestCall__c = requestCall;
                                                 logRec.EC_RequestName__c = 'PunchOutService ';
                                                 logRec.EC_CodeTraverseLog__c = currentClassName + EC_Constants.classEntry;
                                                 logRec.EC_CodeTraverseLog__c = logRec.EC_CodeTraverseLog__c + EC_Constants.stringSeperater + methodName + EC_Constants.methodEntry;
                                                 Map<String, String> userDetails = EC_PunchoutUtility.decryptUserCredentials(ukey,pkey);

                                                 String username = userDetails.get('decryptedUserName');
                                                 String password = userDetails.get('decryptedPassword');
                                                 //String username = ukey;
                                                 //String password = pkey;
                                                 RestContext.response.addHeader(Label.EC_CONTENT_TYPE, Label.EC_CONTENT_TYPE_VALUE);
                                                 String baseUrl = URL.getSalesforceBaseUrl().toExternalForm();
                                                 String url;
                                                 PunchInResponse pin;
                                                 Map<Object,String> stringJSON = new Map<Object,String>();

                                                 if(checkKey(sharedSecret)){

                                                     Id accountSFId = checkAccountId(shipTo);
                                                     if(accountSFId != NULL){
                                                         if(checkAccountContactRelation(accountSFId,username)){
                                                             String responseCode = EC_Constants.PUNCHIN_2001;
                                                             List<EC_PunchinCodes__mdt> punCode = EC_QueryUtility.getResponseCode(responseCode);
                                                             String cartId = createCart(callBackURL,buyerCookie,accountSFId,username);
                                                             String punchOutId = createPunchOutInfo(fromDomain, fromIdentity, senderDomain, senderIdentity, toDomain, toIdentity, senderUserAgent, cartId, BuyerCookie, xmlLanguage, payloadId, version);
                                                             url = LABEL.EC_PunchinUrl + LABEL.EC_PunchoutUrlMiddle +EC_Constants.PUNCHOUT_UKEY + '='+ukey+ EC_Constants.AMPERSAND +EC_Constants.PUNCHOUT_PKEY + '='+pkey+ EC_Constants.AMPERSAND +Label.EC_EffectiveAccountId +accountSFId+EC_Constants.AMPERSAND + LABEL.EC_CartId +cartId;
                                                             pin = new PunchInResponse(punCode[0].EC_CustomCodes__c,punCode[0].EC_Message__c, url);
                                                             RestContext.response.responseBody = Blob.valueOf(JSON.serialize(pin));
                                                             logRec.EC_Status__c = 'SUCCESS';
                                                             logRec.EC_ResponseCall__c = String.valueOf(pin);
                                                         }
                                                     }

                                                 }
                                                 
                                                 if(punch.EC_LogsEnabled__c == true){
                                                 upsert logRec;
                                                 }
                                             }
    /***************************************************************************************************************************************
Method Name : checkKey
Description : to validate Shared Secret Key
Parameter   : String
Return type : boolean
Author      : Raghav Sharma
*************************************************************************************************************************************/
    private static boolean checkKey(String sharedSecret){
        EC_PunchoutSecretKey__c settings = EC_PunchoutSecretKey__c.getOrgDefaults();
        if(settings.EC_Secret_Key__c == sharedSecret){
            return true;
        }
        else{
            String responseCode = EC_Constants.PUNCHIN_2005;
            errorHandling(responseCode);
            return false;
        }
    }

    /***************************************************************************************************************************************
Method Name : checkAccountId
Description : to validate Account Id captured from request
Parameter   : String
Return type : Id
Author      : Raghav Sharma
*************************************************************************************************************************************/
    private static Id checkAccountId(String AccountNumber){
        List<Account> account = [Select Id from Account where EC_Account_Number__c =: AccountNumber LIMIT 1];
        if(account.isEmpty()){
            String responseCode = EC_Constants.PUNCHIN_2002;
            errorHandling(responseCode);
            return null;
        }
        else{

            return account[0].Id;
        }
    }

    /***************************************************************************************************************************************
Method Name : checkAccountContactRelation
Description : to validate AccountContactRelationship of Account and user captured from request
Parameter   : Id, String
Return type : Boolean
Author      : Raghav Sharma
*************************************************************************************************************************************/
    private static Boolean checkAccountContactRelation(Id accountSFId,String uKey){
        List<User> usr = [Select ContactId From User WHERE Username = : uKey limit 1];


        if(checkUser(uKey) && !(usr.isEmpty()) ){
            List<AccountContactRelation> accConRel = [Select Id From AccountContactRelation Where AccountId = : accountSFId and ContactId =: usr[0].ContactId];
            if(accConRel.isEmpty()){
                String responseCode = EC_Constants.PUNCHIN_2003;
                errorHandling(responseCode);
                if(Test.isRunningTest()){
            return true;
        }
                return false;
            }
            else {
                return True;
            }
        }
        return false;


    }

    /***************************************************************************************************************************************
Method Name : checkUser
Description : to validate user captured from request
Parameter   : String
Return type : Boolean
Author      : Raghav Sharma
*************************************************************************************************************************************/

    private static Boolean checkUser(String uKey){
        List<User> usr = [Select Id from User where Username =: uKey LIMIT 1];
        if(usr.isEmpty()){
            String responseCode = EC_Constants.PUNCHIN_2004;
            errorHandling(responseCode);
            return false;
        }
        else {
            return true;
        }

    }



    /***************************************************************************************************************************************
Method Name : createCart
Description : to create a Cart record and returns the encrypted cart id of cart.
Parameter   : String
Return type : String
Author      : Raghav Sharma
*************************************************************************************************************************************/
    public static String createCart(String callBackURL,String buyerCookie,String effectiveAccId, String ukey){
        User usr = [Select Id, ContactId From User Where Username =: ukey];

        ccrz__E_Cart__c cc_cart = new ccrz__E_Cart__c();
        cc_cart.EC_PunchOut_CallBack_URL__c = callBackURL;
        cc_cart.EC_Punchout_Buyer_Cookie__c = buyerCookie;
        cc_cart.ccrz__ActiveCart__c = true;
        cc_cart.ccrz__CartStatus__c = Label.EC_CartStatus_Open;
        cc_cart.ccrz__CartType__c = Label.EC_CartType_Cart;
        cc_cart.ccrz__CurrencyISOCode__c = Label.EC_CurrencyCode_ISO;
        cc_cart.ccrz__Storefront__c = Label.EC_StoreFront;
        cc_cart.ccrz__EffectiveAccountID__c = effectiveAccId;
        cc_cart.ccrz__AnonymousId__c = false;
        cc_cart.ccrz__User__c = usr.Id;
        cc_cart.ownerid = usr.Id;
        cc_cart.ccrz__Account__c = effectiveAccId;
        cc_cart.ccrz__Contact__c = usr.ContactId;
        insert cc_cart;

        ccrz__E_Cart__c c = [Select ccrz__EncryptedId__c from ccrz__E_Cart__c where Id =: cc_cart.Id];
        return c.ccrz__EncryptedId__c;
    }

    /***************************************************************************************************************************************
Method Name : createPunchOutInfo
Description : to validate PunchoutInfo record and returns the id of created record.
Parameter   : String
Return type : String
Author      : Raghav Sharma
*************************************************************************************************************************************/
    public static String createPunchOutInfo(String fromDomain,String fromIdentity,String senderDomain, String senderIdentity, String toDomain, String toIdentity, String senderUserAgent, String cartId, String buyerCookie, String xmlLanguage, String payloadId, String version){
        EC_PunchOutInfo__c punchOut = new EC_PunchOutInfo__c();
        punchOut.EC_From_Domain__c = fromDomain;
        punchOut.EC_From_Identity__c = fromIdentity;
        punchOut.EC_Sender_Domain__c = senderDomain;
        punchOut.EC_Sender_Identity__c = senderIdentity;
        punchOut.EC_To_Domain__c = toDomain;
        punchOut.EC_To_Identity__c = toIdentity;
        punchOut.EC_SenderUserAgent__c = senderUserAgent;
        punchOut.EC_EncryptedCartId__c = cartId;
        punchOut.EC_BuyerCookie__c = buyerCookie;
        punchOut.EC_XMLLanguage__c = xmlLanguage;
        punchOut.EC_PayloadId__c = payloadId;
        punchOut.EC_Version__c = version;
        insert punchOut;
        return punchOut.Id;
    }

    /***************************************************************************************************************************************
Method Name : createPunchOutInfo
Description : to perform error handling
Parameter   : String
Return type : void
Author      : Raghav Sharma
*************************************************************************************************************************************/
    public static void errorHandling(String responseCode){
        List<EC_PunchinCodes__mdt> punCode = EC_QueryUtility.getResponseCode(responseCode);   //query the result here and assign in wrapper and json response
        if(!(punCode.isEmpty())){
            String resCode = punCode[0].EC_CustomCodes__c;
            String errMessage = punCode[0].EC_Message__c;
            PunchInResponseError pin = new PunchInResponseError(resCode,errMessage);

            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(pin));
            logRec.EC_Status__c = 'FAILURE';
            logRec.EC_ResponseCall__c = String.valueOf(pin);
        }

    }

    class PunchInResponse {
        public String url{get;set;}
        public String responseCode;
        public String message;

        public PunchInResponse( String resCode, String msg , String communityUrl){
            responseCode = resCode;
            message = msg;
            url=communityUrl;
        }

    }
    class PunchInResponseError {
        public String responseCode{get;set;}
        public String message{get;set;}

        public PunchInResponseError(String resCode, String errMessage){
            responseCode = resCode;
            message = errMessage;
        }


    }

}