src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Ship_To_Name__c</fullName>
        <formula>if(
        NOT(ISNULL(Account_Name2__c)|| ISBLANK(Account_Name2__c)) &amp;&amp;
        NOT(ISNULL(Account_Name3__c) || ISBLANK(Account_Name3__c)) &amp;&amp;
        NOT(ISNULL(Account_Name4__c) || ISBLANK(Account_Name4__c) ),
        Account_Name2__c+&#39;, &#39;+Account_Name3__c+&#39;, &#39;+Account_Name4__c,
                    IF( (ISNULL(Account_Name2__c)|| ISBLANK(Account_Name2__c)) &amp;&amp; (ISNULL(Account_Name3__c) || ISBLANK(Account_Name3__c)),
                                 Account_Name4__c,
                                  IF(( ISNULL(Account_Name3__c)|| ISBLANK(Account_Name3__c)) &amp;&amp; (ISNULL(Account_Name4__c) || ISBLANK(Account_Name4__c)),
                                                    Account_Name2__c,
                                                     IF((ISNULL(Account_Name4__c)|| ISBLANK(Account_Name4__c)) &amp;&amp; (ISNULL(Account_Name2__c) || ISBLANK(Account_Name2__c)),
                                                                    Account_Name3__c,
                                                                     IF(ISNULL(Account_Name2__c)||ISBLANK(Account_Name2__c),
                                                                                Account_Name3__c+&#39;, &#39;+Account_Name4__c,
                                                                                     IF(ISNULL(Account_Name3__c) || ISBLANK(Account_Name3__c),
                                                                                                    Account_Name2__c+&#39;, &#39;+Account_Name4__c,
                                                                                                     IF(ISNULL(Account_Name4__c) || ISBLANK(Account_Name4__c),
                                                                                                                    Account_Name2__c+&#39;, &#39;+Account_Name3__c,&#39;&#39;
                                                                                                          )
                                                                                          )
                                                                                    )
                                                          )
                                          )
                      )
            )</formula>
        <label>Ship To Name</label>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Account/fields/EC_SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>EC_SalesOrg__c</fullName>
    <label>SalesOrg</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/ccrz__E_AccountGroupPriceList__c.object
<CustomObject>
    <description>Represents a mapping of Account Group to Pricelist.  This objects ties the two together, enabling the assignment and entitlement/pricing functionality.</description>
    <fields>
        <fullName>EC_Price_List_Type__c</fullName>
        <label>Price List Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Z1CP</fullName>
                </value>
                <value>
                    <fullName>Z1GP</fullName>
                </value>
                <value>
                    <fullName>Z1MP</fullName>
                </value>
                <value>
                    <fullName>ZFCP</fullName>
                </value>
                <value>
                    <fullName>ZF00</fullName>
                </value>
                <value>
                    <fullName>Z1LS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer available for the account group.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is available to the account group will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the pricelist</description>
        <label>Pricelist</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>Account Group Price Lists</relationshipLabel>
        <relationshipName>E_AccountGroupPriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this mapping record is active. This is the first date the mapping will be applied</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Account Group Price List</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Acct Group Pricelist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Account Group Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_CartItem__c.object
<CustomObject>
    <description>Cart Items</description>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>The unit price of the line.</description>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line item.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Cart Items (ProductID)</relationshipLabel>
        <relationshipName>E_CartItem2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Cart Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CartItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceList__c.object
<CustomObject>
    <description>Represents a grouping of products to control pricing and entitlements.  The B2B Commerce pricelist object controls both pricing and entitlements, but can be used just for the purposes of entitlements. A list needs to be created for each currency that needs to be represented, allowing for different entitlments and pricing based on the locale and currency.</description>
    <fields>
        <fullName>EC_Price_List_Type__c</fullName>
        <description>This field stores the type of pricelist i.e. Sales Org, Customer Group</description>
        <inlineHelpText>This field stores the type of pricelist i.e. Sales Org, Customer Group</inlineHelpText>
        <label>Price List Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag determining whether or not this pricelist record is active</description>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer active.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is valid will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__PricelistId__c</fullName>
        <description>External reference id for this entry</description>
        <externalId>true</externalId>
        <label>Pricelist Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this pricelist record is active. This is the first date the pricing/entitlements will be applied</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BA_Number__c</fullName>
        <description>To store BA number</description>
        <label>BA Number</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <label>CC Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceListItem__c.object
<CustomObject>
    <description>Represents an entry in the Pricelist.  Each pricelist object is made up of 1 or more pricelist item objects.  This item objects contain a reference to the product and hold a price value (0, in the case where only entitlements are being used).  The products referenced within these items will be displayed in search and product listings on the external site.</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The end date for the price list item.  The end date is the date at which the item will no longer be available.  For example if the end date is July 1, 2015 then the price list item is valid on June 30, 2015 but no longer valid on July 1, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>Holds the price for the item. If pricing is not being utilized, fill in a default value, such as 0.</description>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Pricelist__c</fullName>
        <description>Required - The reference to the pricelist</description>
        <label>Pricelist</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>E_PriceListItems1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the product entry</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>E_PriceListItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this item record is active. This is the first date the item will be active</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Price List Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>PriceListItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date that this product will be available.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductIndexStatus__c</fullName>
        <description>Indicates the status of the associated Product Index records. Possible values are Current, Not Current and Pending. This field is primarily used by the Product Index batch process.</description>
        <inlineHelpText>Indicates the status of the associated Product Index records. Possible values are Current, Not Current and Pending. This field is primarily used by the Product Index batch process.</inlineHelpText>
        <label>Product Index Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductStatus__c</fullName>
        <description>The status of the product. In Creation - Newly created product, that still requires augmentation and is not visible on the site; Blocked - product has been blocked from being displayed on the site; Not Orderable - product can be viewed, but cannot be added to a cart or ordered; Released - fully availble product</description>
        <label>Product Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Not Orderable</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>In Creation</fullName>
                    <default>true</default>
                    <label>In Creation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within B2B Commerce</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The first date that this product will be available.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EC_ProductDetailControllerTest.cls
@isTest
public without sharing class  EC_ProductDetailControllerTest {
    
    static testMethod void processMethod() {
        Set<String> ProdPkgCode = new Set<String>();
        ProdPkgCode.add('91');
        ProdPkgCode.add('36');
        String salesorg = '1001';
        Test.startTest();
        Account shipTo = [Select EC_SalesOrg__c,Ship_To_Name__c from Account Where Id=:EC_TestData.testAccountShipTo.id];
        shipTo.EC_SalesOrg__c = '1001';
        shipTo.parent =EC_TestData.testAccountShipTo;
        update shipTo;
        ccrz.cc_CallContext.effAccountId = shipTo.id;        
        EC_ProductDetailController obj = new EC_ProductDetailController();
        system.debug('obj'+obj);
        EC_TestData.setupCatalog();
        ccrz__E_PriceList__c priceList = new ccrz__E_PriceList__c();
        priceList.Name = 'AllProduct_PL';
        priceList.ccrz__PricelistId__c = 'AllProduct_PL';
        priceList.ccrz__EndDate__c = System.today();
        priceList.ccrz__Enabled__c = true;
        priceList.ccrz__StartDate__c = System.today();
        insert priceList;
        priceList.BA_Number__c = 'BANumber007';
        priceList.EC_Price_List_Type__c = 'FBA';
        update priceList;
        List<ccrz__E_Product__c> product = [Select ccrz__SKU__c,ccrz__StartDate__c,ccrz__EndDate__c,ccrz__ProductStatus__c, ccrz__ProductIndexStatus__c FROM ccrz__E_Product__c limit 2];
        product[0].ccrz__SKU__c = 'GEN CHEMICAL';
        update product;
        set<string> pset = new set<string>();
        for(ccrz__E_Product__c prod : product) {
            pset.add(prod.ccrz__SKU__c);
        }
        ccrz__E_PriceListItem__c pli = new ccrz__E_PriceListItem__c();
        pli.ccrz__Product__c =  product[0].id;
        pli.ccrz__Price__c = 0.0;
        pli.ccrz__Pricelist__c = priceList.id;
        pli.ccrz__StartDate__c = System.today();
        pli.ccrz__EndDate__c = System.today();
        insert pli;
        ccrz__E_AccountGroup__c acGrp = EC_TestData.testAccountGroup;
        ccrz__E_AccountGroupPriceList__c testAccountGroupPriceList = new ccrz__E_AccountGroupPriceList__c();
        testAccountGroupPriceList.ccrz__AccountGroup__c = acGrp.Id;
        testAccountGroupPriceList.EC_Price_List_Type__c = 'Z1MP';
        testAccountGroupPriceList.ccrz__PriceList__c    = priceList.Id;
        testAccountGroupPriceList.ccrz__Enable__c       = true;
        testAccountGroupPriceList.ccrz__StartDate__c = System.today();
        testAccountGroupPriceList.ccrz__EndDate__c = System.today();
        insert testAccountGroupPriceList;
        Map<String,List<ccrz__E_Pricelist__c>> productLineBASetMap = EC_ProductDetailController.productLineBASetMap(acGrp.Id,pset);
        Map<String,List<String>> resp = EC_ProductDetailController.getDeliveryTemplateCode(ProdPkgCode,salesorg);
        EC_ProductDetailController.isTankNumberApplicable(ProdPkgCode,salesorg);
        system.assertNotEquals(null, productLineBASetMap);
        System.assert(null != resp);
        Test.stopTest();
    }
    
    @isTest
    private static void testUnstampBillingArrangement()
    {
        ccrz__E_PriceList__c fbaPriceList = EC_SplitOrderTest.priceListUtility('Fixed','FBA');
        ccrz__E_PriceList__c usgPriceList = EC_SplitOrderTest.priceListUtility('Usage','USG');
        Set<ccrz__E_PriceList__c> setPriceList = new Set<ccrz__E_PriceList__c>{usgPriceList};
            
        List<ccrz__E_Product__c> listProducts = EC_SplitOrderTest.productUtility(2);        
        EC_SplitOrderTest.priceListItemUtility(listProducts,usgPriceList.Id);
               
        
        ccrz.cc_CallContext.effAccountId = EC_TestData.testAccount.Id; 
        List<ccrz__E_Cart__c> cart = EC_TestData.createCarts(1); 
        String encryptedId = [SELECT ccrz__EncryptedId__c from ccrz__E_Cart__c Where Id IN: cart Limit 1].ccrz__EncryptedId__c;
        cart[0].ccrz__EffectiveAccountID__c = ccrz.cc_CallContext.effAccountId;
        update cart[0];
        CCRZ.cc_CallContext.currCartId = encryptedId;
        
        Map<id,Set<ccrz__E_Pricelist__c>> productToApplicableBAMap = new Map<id,Set<ccrz__E_Pricelist__c>>();
        Map<String,Set<ccrz__E_Pricelist__c>> prodBAsetMap = new Map<String,Set<ccrz__E_Pricelist__c>>();
        
        ccrz__E_CartItem__c cartItem1;        
        List<ccrz__E_CartItem__c> listInsertCartItems = new List<ccrz__E_CartItem__c>();        
        for(ccrz__E_Product__c varProduct : listProducts)
        {
            cartItem1 = new ccrz__E_CartItem__c();
            cartItem1.ccrz__Cart__c = cart[0].Id;
            cartItem1.ccrz__Product__c = varProduct.id;
            cartItem1.ccrz__Price__c = 100;
            cartItem1.Billing_Arrangement__c = fbaPriceList.Id;
            listInsertCartItems.add(cartItem1);
            productToApplicableBAMap.put(varProduct.Id,setPriceList);
            prodBAsetMap.put(varProduct.Id,setPriceList);
        }    
        insert listInsertCartItems;        
        List<ccrz__E_CartItem__c> listCartItems = EC_ProductDetailController.unstampBillingArrangement(productToApplicableBAMap,prodBAsetMap);
        system.assertEquals(false,listCartItems.isEmpty());
    }
}