src/objects/BA_Product_Lines__mdt.object
<CustomObject>
    <description>Types of Billing arrangement product line sku.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>BA Product Line</label>
    <pluralLabel>BA Product Lines</pluralLabel>
</CustomObject>

src/objects/Billing_Arrangement_Types__mdt.object
<CustomObject>
    <description>List of Billing Arrangement Types which are in Scope (Eg: Usage, Fixed, UseRisk)</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Applicable_On_Cart__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Applicable On Cart</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BA_Type_Code__c</fullName>
        <label>BA Type Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GenChemical_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GenChemical Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GenEquipment_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GenEquipment Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Billing Arrangement Type</label>
    <pluralLabel>Billing Arrangement Types</pluralLabel>
</CustomObject>

src/objects/ccrz__E_AccountGroupPriceList__c.object
<CustomObject>
    <description>Represents a mapping of Account Group to Pricelist.  This objects ties the two together, enabling the assignment and entitlement/pricing functionality.</description>
    <fields>
        <fullName>EC_Price_List_Type__c</fullName>
        <label>Price List Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Z1CP</fullName>
                </value>
                <value>
                    <fullName>Z1GP</fullName>
                </value>
                <value>
                    <fullName>Z1MP</fullName>
                </value>
                <value>
                    <fullName>ZFCP</fullName>
                </value>
                <value>
                    <fullName>ZF00</fullName>
                </value>
                <value>
                    <fullName>Z1LS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__AccountGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the account group</description>
        <label>Account Group</label>
        <referenceTo>ccrz__E_AccountGroup__c</referenceTo>
        <relationshipLabel>Account Group Price Lists</relationshipLabel>
        <relationshipName>E_AccountGroupPriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Enable__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag determining whether or not this mapping record is active</description>
        <label>Enable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer available for the account group.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is available to the account group will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the pricelist</description>
        <label>Pricelist</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>Account Group Price Lists</relationshipLabel>
        <relationshipName>E_AccountGroupPriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this mapping record is active. This is the first date the mapping will be applied</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Account Group Price List</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Acct Group Pricelist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Account Group Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_CartItem__c.object
<CustomObject>
    <description>Cart Items</description>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>The unit price of the line.</description>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line item.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Cart Items (ProductID)</relationshipLabel>
        <relationshipName>E_CartItem2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Cart Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CartItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceList__c.object
<CustomObject>
    <description>Represents a grouping of products to control pricing and entitlements.  The B2B Commerce pricelist object controls both pricing and entitlements, but can be used just for the purposes of entitlements. A list needs to be created for each currency that needs to be represented, allowing for different entitlments and pricing based on the locale and currency.</description>
    <fields>
        <fullName>EC_Price_List_Type__c</fullName>
        <description>This field stores the type of pricelist i.e. Sales Org, Customer Group</description>
        <inlineHelpText>This field stores the type of pricelist i.e. Sales Org, Customer Group</inlineHelpText>
        <label>Price List Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Desc__c</fullName>
        <description>A description of the pricelist - internal only</description>
        <label>Desc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag determining whether or not this pricelist record is active</description>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer active.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is valid will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this pricelist record is active. This is the first date the pricing/entitlements will be applied</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BA_Number__c</fullName>
        <description>To store BA number</description>
        <label>BA Number</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <label>CC Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceListItem__c.object
<CustomObject>
    <description>Represents an entry in the Pricelist.  Each pricelist object is made up of 1 or more pricelist item objects.  This item objects contain a reference to the product and hold a price value (0, in the case where only entitlements are being used).  The products referenced within these items will be displayed in search and product listings on the external site.</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The end date for the price list item.  The end date is the date at which the item will no longer be available.  For example if the end date is July 1, 2015 then the price list item is valid on June 30, 2015 but no longer valid on July 1, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>Holds the price for the item. If pricing is not being utilized, fill in a default value, such as 0.</description>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Pricelist__c</fullName>
        <description>Required - The reference to the pricelist</description>
        <label>Pricelist</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>E_PriceListItems1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the product entry</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>E_PriceListItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this item record is active. This is the first date the item will be active</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Price List Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>PriceListItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date that this product will be available.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within B2B Commerce</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The first date that this product will be available.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Package_Code__c</fullName>
        <description>formula field to get the package code from SKU</description>
        <formula>IF(CONTAINS(ccrz__SKU__c,&quot;.&quot; ), MID(ccrz__SKU__c, FIND(&apos;.&apos;, ccrz__SKU__c )+1,LEN(ccrz__SKU__c)) , &apos;&apos;)</formula>
        <label>Package Code</label>
        <type>Text</type>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Delivery_Template_Package_Code_Mapping__mdt.object
<CustomObject>
    <fields>
        <fullName>Delivery_Template_Code__c</fullName>
        <label>Delivery Template Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Package_Code__c</fullName>
        <label>Package Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <label>Sales Org</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Delivery Template Package Code Mapping</label>
    <pluralLabel>Delivery Template Package Code Mappings</pluralLabel>
</CustomObject>

src/objects/Tank_Number_Applicable_Package_Code__mdt.object
<CustomObject>
    <fields>
        <fullName>Package_Type_Code__c</fullName>
        <label>Package Type Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <label>Sales Org</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Tank Number Applicable Package Code</label>
    <pluralLabel>Tank Number Applicable Package Codes</pluralLabel>
</CustomObject>

src/classes/EC_ProductDetailController.cls
/* Class Name    : EC_ProductDetailController
 * Description      :Controller Class for Product Detail Component
 * Created By       :Viraj
 * Created On       :2019-Aug-1
 

 * Modification Log:
 * -----------------------------------------------------------------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID         Description
 * -----------------------------------------------------------------------------------------------------------------------------------------------------------------
 * Viraj                    2019-Aug-1         BC-80775        Created the class   
 *
 */
public class EC_ProductDetailController {
    public Boolean viewPrice {get;set;}
    public Boolean buyOnline {get;set;}
    public Boolean indirectStreetBrand{get;set;}//WW-152904
    /***************************************************************************************************************************************
  Constructor Name : EC_ProductDetailController
  Description : Constructor to initialize variables of EC_ProductDetailController to be used in the component
  Return type : N/A
 *************************************************************************************************************************************/
    public EC_ProductDetailController(){
        
        viewPrice = false;
        buyOnline = false;
        indirectStreetBrand =false;//ww-152904
        List<EC_Utility.PermWrapper> permWrapperLst =   EC_Utility.getPermissionCacheInfo();
        ccrz.ccLog.log('permWrapperLst54'+permWrapperLst);
        for(EC_Utility.PermWrapper perm : permWrapperLst){
            if(perm.permName == 'View Price'){
                viewPrice = perm.permVal;
            }
            if(perm.permName == 'Buy Online'){
                buyOnline= perm.permVal;
            }
        }
        indirectStreetBrand =EC_Utility.isIndirectStreetBrandAccount();//ww-152904
    }

        /***************************************************************************************************************************************
        Class Name : getDeliveryTemplateCode
        Description : Helper function to get Delivery Template code based on product.
        Return type : set<string>
        *************************************************************************************************************************************/
        
    	public static Map<String,List<String>> getDeliveryTemplateCode(set<String> ProdPkgCode,String salesOrg){
            Map<String,List<String>> packageCodeDelTemplMap = new Map<String,List<String>>();
            try{                
                List<Delivery_Template_Package_Code_Mapping__mdt> Dtemplates = [SELECT Delivery_Template_Code__c,DeveloperName,Package_Code__c,QualifiedApiName,Sales_Org__c FROM Delivery_Template_Package_Code_Mapping__mdt where Package_Code__c IN: ProdPkgCode AND Sales_Org__c=:salesOrg];
                if(!Dtemplates.isEmpty()) {
                    for(Delivery_Template_Package_Code_Mapping__mdt tmp : Dtemplates) {
                        if(packageCodeDelTemplMap.containsKey(tmp.Package_Code__c)){
                            packageCodeDelTemplMap.get(tmp.Package_Code__c).add(tmp.Delivery_Template_Code__c);
                        }else{
                            packageCodeDelTemplMap.put(tmp.Package_Code__c,new List<String>{tmp.Delivery_Template_Code__c});
                        }
                    }
                }
            }catch(Exception ex){
                System.debug('exception getDeliveryTemplateCode-->'+ex.getMessage());
            }
            ccrz.cclog.log('getDeliveryTemplateCode templateCode--->' + packageCodeDelTemplMap); 
            return packageCodeDelTemplMap;
        }
    
        /***************************************************************************************************************************************
        Class Name : isTankNumberApplicable
        Description : Helper function to check if packagecode is applicable for tank details.
        Return type : set<string>
        *************************************************************************************************************************************/
        public static Map<String,boolean> isTankNumberApplicable(set<String> ProdPkgCode,String salesOrg){
            Map<String,Boolean> packageCodeIsTankApplicableMap = new Map<String,Boolean>();
            List<Tank_Number_Applicable_Package_Code__mdt> pkgmetadatas = [SELECT DeveloperName,Id,Label,Package_Type_Code__c,QualifiedApiName,Sales_Org__c FROM Tank_Number_Applicable_Package_Code__mdt where Package_Type_Code__c IN: ProdPkgCode AND Sales_Org__c =:salesOrg];
            if(!pkgmetadatas.isEmpty()) {
                for(Tank_Number_Applicable_Package_Code__mdt pkg : pkgmetadatas ) {
                    packageCodeIsTankApplicableMap.put(pkg.Package_Type_Code__c,true);
                }
            }
            ccrz.cclog.log('packageCodeIsTankApplicableMap' + packageCodeIsTankApplicableMap);
            return packageCodeIsTankApplicableMap;
        }
        /***************************************************************************************************************************************
Class Name : productLineBASetMap
Description : Helper function to fetch all skus which are applicable for Billing arrangements.
Return type : set<ccrz__E_Pricelist__c>
*************************************************************************************************************************************/
    public static Map<String,List<ccrz__E_Pricelist__c>> productLineBASetMap(String accountGroupId, set<string> ProdskuSet){
        Date today = Date.today();
        // Get all BA Types from Custom settings
        Set<String> BATypeSet = new Set<String>();
        BATypeSet = getBATypes();        
        // Get all BA Product Lines from the custom settings
        Set<String> BAProdLineSet = new Set<String>();
        BAProdLineSet = getBAProductLines();
        Set<String> getBothBATypes = new Set<String>();
        getBothBATypes = getBothBATypes();  
        Set<String> getUsageBATypes = new Set<String>();
        getUsageBATypes = getUsageBATypes();
        Map<String,List<ccrz__E_Pricelist__c>> BAMap = new Map<String,List<ccrz__E_Pricelist__c>>();
        String GenEquipment = System.label.GEN_EQUIPMENT;
        list<ccrz__E_PriceListItem__c> PLItems = new list<ccrz__E_PriceListItem__c> ();
        if(ccrz__E_AccountGroupPriceList__c.sObjectType.getDescribe().isAccessible() && ccrz__E_PriceListItem__c.sObjectType.getDescribe().isAccessible()) {
        PLItems = [select Id,name,ccrz__Pricelist__r.BA_Number__c,ccrz__Pricelist__r.ccrz__Desc__c,ccrz__Pricelist__r.EC_Price_List_Type__c,ccrz__Pricelist__r.ccrz__EndDate__c,ccrz__Product__r.ccrz__sku__c,ccrz__EndDate__c,
                   ccrz__Price__c,ccrz__StartDate__c from ccrz__E_PriceListItem__c where ccrz__StartDate__c <= :today AND ccrz__EndDate__c>=:today
                   AND ccrz__Pricelist__c IN (select ccrz__Pricelist__c from ccrz__E_AccountGroupPriceList__c where ccrz__AccountGroup__c=:accountGroupId and ccrz__StartDate__c <= :today and ccrz__EndDate__c>=:today and ccrz__Enable__c = true
                                                          and ccrz__Pricelist__r.EC_Price_List_Type__c IN:BATypeSet AND ccrz__Pricelist__r.ccrz__Enabled__c = true and ccrz__Pricelist__r.ccrz__StartDate__c <= :today 
                                                          AND ccrz__Pricelist__r.ccrz__EndDate__c>=:today) and (ccrz__Product__r.ccrz__sku__c IN:ProdskuSet OR (ccrz__Product__r.ccrz__sku__c =:GenEquipment and ccrz__Pricelist__r.EC_Price_List_Type__c IN:getUsageBATypes)
                   OR (ccrz__Product__r.ccrz__sku__c IN:BAProdLineSet and ccrz__Pricelist__r.EC_Price_List_Type__c IN:getBothBATypes))];
        }
       	system.debug('BA PLItems--->' + PLItems);
        if(!PLItems.isEmpty()) {//PLItems != null
            for(ccrz__E_PriceListItem__c PLItem : PLItems){
                if(BAMap.containsKey(PLItem.ccrz__Product__r.ccrz__sku__c)){
                    BAMap.get(PLItem.ccrz__Product__r.ccrz__sku__c).add(PLItem.ccrz__Pricelist__r);
                }
                else{
                    BAMap.put(PLItem.ccrz__Product__r.ccrz__sku__c, new List<ccrz__E_Pricelist__c>{PLItem.ccrz__Pricelist__r});
                }            
            }
        }
        ccrz.cclog.log('BA BAMap--->' + BAMap);
        return BAMap;
    }
    
    public static set<string> getBATypes(){
        List<Billing_Arrangement_Types__mdt> BATypes = new List<Billing_Arrangement_Types__mdt>();
        BATypes = [Select Label,GenChemical_Enabled__c,GenEquipment_Enabled__c,BA_Type_Code__c,Active__c,Applicable_On_Cart__c from Billing_Arrangement_Types__mdt where Active__c = true  AND Applicable_On_Cart__c = true];
        Set<String> BATypeSet = new Set<String>();
        if(!BATypes.isEmpty()) {
            for (Billing_Arrangement_Types__mdt BAType : BATypes) {
                if(BAType.Active__c == true) {
                    BATypeSet.add(BAType.Label);
                }
            }
        }
        ccrz.cclog.log('BATypeSet-->' + BATypeSet);
        return BATypeSet;
    }
    public static set<string> getBothBATypes(){
        List<Billing_Arrangement_Types__mdt> BATypes = new List<Billing_Arrangement_Types__mdt>();
        BATypes = [Select Label,GenChemical_Enabled__c,GenEquipment_Enabled__c,BA_Type_Code__c,Active__c,Applicable_On_Cart__c from Billing_Arrangement_Types__mdt where Active__c = true AND GenChemical_Enabled__c = true AND GenEquipment_Enabled__c= true  AND Applicable_On_Cart__c = true];
        Set<String> BATypeSet = new Set<String>();
        if(!BATypes.isEmpty()) {
            for (Billing_Arrangement_Types__mdt BAType : BATypes) {
                if(BAType.Active__c == true) {
                    BATypeSet.add(BAType.Label);
                }
            }
        }
        ccrz.cclog.log('getBothBATypes-->' + BATypeSet);
        return BATypeSet;
    }    
    public static set<string> getUsageBATypes(){
        List<Billing_Arrangement_Types__mdt> BATypes = new List<Billing_Arrangement_Types__mdt>();
        BATypes = [Select Label,GenChemical_Enabled__c,GenEquipment_Enabled__c,BA_Type_Code__c,Active__c,Applicable_On_Cart__c from Billing_Arrangement_Types__mdt where Active__c = true AND GenChemical_Enabled__c = false AND GenEquipment_Enabled__c= true  AND Applicable_On_Cart__c = true];
        Set<String> BATypeSet = new Set<String>();
        if(!BATypes.isEmpty()) {
            for (Billing_Arrangement_Types__mdt BAType : BATypes) {
                if(BAType.Active__c == true) {
                    BATypeSet.add(BAType.Label);
                }
            }
        }
        ccrz.cclog.log('getUsageBATypes-->' + BATypeSet);
        return BATypeSet;
    }  
    public static set<string> getBAProductLines(){
        List<BA_Product_Lines__mdt> BAProdLines = new List<BA_Product_Lines__mdt>();
        BAProdLines = [Select Product_Line__c,Active__c from BA_Product_Lines__mdt where Active__c = true];
        Set<String> BAProdLineSet = new Set<String>();
        if(!BAProdLines.isEmpty()) {
            for (BA_Product_Lines__mdt BAProdLine : BAProdLines) {
                if(BAProdLine.Active__c == true) {
                    BAProdLineSet.add(BAProdLine.Product_Line__c);
                }
            }
        }
        ccrz.cclog.log('BAProdLineSet-->' + BAProdLineSet);
        return BAProdLineSet;
    }
/***************************************************************************************************************************************
Method Name : unstampBillingArrangement
Description : Delete the BillingArrangement on cartItem if not entitled
Return type : ccrz.cc_RemoteActionResult
*************************************************************************************************************************************/
    public static List<ccrz__E_CartItem__c> unstampBillingArrangement(Map<id,Set<ccrz__E_Pricelist__c>> productToApplicableBAMap, Map<String,Set<ccrz__E_Pricelist__c>> prodBAsetMap){
        List<ccrz__E_CartItem__c> updateCartItemList = new List<ccrz__E_CartItem__c>();  
        String effAccountId = ccrz.cc_CallContext.effAccountId;
        String EncartId =  CCRZ.cc_CallContext.currCartId;
        Map<String,Set<String>> productToApplicableBAIdMap = new Map<String,Set<String>>();        
        for(String key : productToApplicableBAMap.keySet()){
            Set<String> baIdSet = new Set<String>();
            for(ccrz__E_Pricelist__c pli : productToApplicableBAMap.get(key)){
                baIdSet.add(String.valueOf(pli.Id));
            }
            productToApplicableBAIdMap.put(key,baIdSet);
        }
        ccrz.cclog.log('productToApplicableBAIdMap--->' + productToApplicableBAIdMap);
        if(ccrz__E_CartItem__c.sObjectType.getDescribe().isAccessible()) {
            List<ccrz__E_CartItem__c> cartItems = new List<ccrz__E_CartItem__c>();
            cartItems = [SELECT ccrz__Product__c,Id,ccrz__Cart__c,ccrz__Cart__r.ccrz__EffectiveAccountID__c,Billing_Arrangement__c 
                         FROM ccrz__E_CartItem__c where ccrz__Cart__r.ccrz__EncryptedId__c =: EncartId AND ccrz__Cart__r.ccrz__EffectiveAccountID__c =:effAccountId
                         AND ccrz__Product__c=:productToApplicableBAMap.keySet() AND Billing_Arrangement__c !=null];
            for(ccrz__E_CartItem__c cItem : cartItems){                  
                if(!productToApplicableBAIdMap.get(cItem.ccrz__Product__c).contains(cItem.Billing_Arrangement__c)){
                    if(prodBAsetMap.get(cItem.ccrz__Product__c).isEmpty()) {
                        cItem.Billing_Arrangement__c = null;
                    }
                    cItem.ccrz__PricingType__c='auto';
                    cItem.ccrz__Price__c = 0.0;
                    //  cItem.ccrz__SubAmount__c=cItem.ccrz__Quantity__c*cItem.ccrz__Price__c;
                    updateCartItemList.add(cItem);
                }
                
            }
        }
        ccrz.cclog.log('updateCartItemList--->' + updateCartItemList);
        return updateCartItemList;
    }
}