src/objects/Billing_Arrangement_Types__mdt.object
<CustomObject>
    <description>List of Billing Arrangement Types which are in Scope (Eg: Usage, Fixed, UseRisk)</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Applicable_On_BADP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Applicable On BADP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BA_Type_Code__c</fullName>
        <label>BA Type Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Billing Arrangement Type</label>
    <pluralLabel>Billing Arrangement Types</pluralLabel>
</CustomObject>

src/objects/ccrz__E_PriceList__c.object
<CustomObject>
    <description>Represents a grouping of products to control pricing and entitlements.  The B2B Commerce pricelist object controls both pricing and entitlements, but can be used just for the purposes of entitlements. A list needs to be created for each currency that needs to be represented, allowing for different entitlments and pricing based on the locale and currency.</description>
    <fields>
        <fullName>Price_List_Type_Expansion__c</fullName>
        <formula>IF(EC_Price_List_Type__c = &apos;FBA&apos;, &apos;Fixed BA&apos;, IF(EC_Price_List_Type__c = &apos;USG&apos;,&apos;Usage&apos;,IF(EC_Price_List_Type__c =&apos;USR&apos;,&apos;Use Risk&apos;,IF(EC_Price_List_Type__c=&apos;SBA&apos;,&apos;Special Pricing Agreement&apos;,&apos;&apos;))))</formula>
        <label>Price List Type Expansion</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Desc__c</fullName>
        <description>A description of the pricelist - internal only</description>
        <label>Desc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag determining whether or not this pricelist record is active</description>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer active.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is valid will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this pricelist record is active. This is the first date the pricing/entitlements will be applied</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BA_Number__c</fullName>
        <description>To store BA number</description>
        <label>BA Number</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <label>CC Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceListItem__c.object
<CustomObject>
    <description>Represents an entry in the Pricelist.  Each pricelist object is made up of 1 or more pricelist item objects.  This item objects contain a reference to the product and hold a price value (0, in the case where only entitlements are being used).  The products referenced within these items will be displayed in search and product listings on the external site.</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The end date for the price list item.  The end date is the date at which the item will no longer be available.  For example if the end date is July 1, 2015 then the price list item is valid on June 30, 2015 but no longer valid on July 1, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>Holds the price for the item. If pricing is not being utilized, fill in a default value, such as 0.</description>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Pricelist__c</fullName>
        <description>Required - The reference to the pricelist</description>
        <label>Pricelist</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>E_PriceListItems1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the product entry</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>E_PriceListItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this item record is active. This is the first date the item will be active</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__UnitOfMeasure__c</fullName>
        <description>Unit of Measure for this price.  This field in combination with the product can give UOM specific pricing.  This field is optional, and allows for general pricing for a product independent of UOM.</description>
        <inlineHelpText>Unit of Measure for this price.  This field in combination with the product can give UOM specific pricing.  This field is optional, and allows for general pricing for a product independent of UOM.</inlineHelpText>
        <label>Unit Of Measure</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom_PricingUOM__c</fullName>
        <label>Custom Pricing UOM</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom_UnitPrice__c</fullName>
        <label>Custom UnitPrice</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price_Per__c</fullName>
        <label>Price Per</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CC Price List Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>PriceListItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date that this product will be available.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductStatus__c</fullName>
        <description>The status of the product. In Creation - Newly created product, that still requires augmentation and is not visible on the site; Blocked - product has been blocked from being displayed on the site; Not Orderable - product can be viewed, but cannot be added to a cart or ordered; Released - fully availble product</description>
        <label>Product Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Not Orderable</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>In Creation</fullName>
                    <default>true</default>
                    <label>In Creation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within B2B Commerce</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The first date that this product will be available.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Taxonomy__c</fullName>
        <description>To identity the type of product (Equipment or Chemical)</description>
        <label>Taxonomy </label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Package_Code__c</fullName>
        <description>formula field to get the package code from SKU</description>
        <formula>IF(CONTAINS(ccrz__SKU__c,&quot;.&quot; ), MID(ccrz__SKU__c, FIND(&apos;.&apos;, ccrz__SKU__c )+1,LEN(ccrz__SKU__c)) , &apos;&apos;)</formula>
        <label>Package Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__UnitOfMeasure__c</fullName>
        <description>Product unit of measure - such as Each</description>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Each</fullName>
                    <default>true</default>
                    <label>Each</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_ProductMedia__c.object
<CustomObject>
    <description>Encapsulates media such as hero, thumbnail images, product brochures, owner&apos;s manuals, assembly guides, and videos associated with a product. Media&apos;s source could be in a form of attachment, static resource, or external resource(URI).</description>
    <fields>
        <fullName>ccrz__Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag determining whether or not this media record is active</description>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date for which this media record is active. This is the last date the image will be displayed</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__MediaType__c</fullName>
        <description>Determines where this image is displayed. Values are &quot;Product Image&quot;, &quot;Product Image Thumbnail&quot;, &quot;Product Search Image&quot;, &quot;Alternate Image&quot;</description>
        <label>Media Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alternate Images</fullName>
                </value>
                <value>
                    <fullName>Alternate Thumbnails</fullName>
                </value>
                <value>
                    <fullName>Datasheets</fullName>
                </value>
                <value>
                    <fullName>Safety Documents</fullName>
                </value>
                <value>
                    <fullName>Sales Brochures</fullName>
                </value>
                <value>
                    <fullName>Product Search Image</fullName>
                </value>
                <value>
                    <fullName>Owner&apos;s Manuals</fullName>
                </value>
                <value>
                    <fullName>Assembly Guides</fullName>
                </value>
                <value>
                    <fullName>JPG Image</fullName>
                </value>
                <value>
                    <fullName>Product Image</fullName>
                </value>
                <value>
                    <fullName>Product Image Thumbnail</fullName>
                </value>
                <value>
                    <fullName>Flash Files</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>SVG Interactive Diagram</fullName>
                </value>
                <value>
                    <fullName>Specification Sheets</fullName>
                </value>
                <value>
                    <fullName>Product Bulletins</fullName>
                </value>
                <value>
                    <fullName>Operating Manuals</fullName>
                </value>
                <value>
                    <fullName>SDS Documents</fullName>
                </value>
                <value>
                    <fullName>Label 1s</fullName>
                </value>
                <value>
                    <fullName>Label 2s</fullName>
                </value>
                <value>
                    <fullName>Catalog Sheets</fullName>
                </value>
                <value>
                    <fullName>Analytical Procedures</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <description>Reference to the category entry to which this media corresponds</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>E_ProductMedias</relationshipLabel>
        <relationshipName>E_ProductMedias</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this media record is active. This is the first date the image will be displayed</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__URI__c</fullName>
        <description>If the source is a URL, contains the full URL to the image. This should reference a location with secure storage (SSL defined)</description>
        <label>URI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Product Media</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Product Media Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Product Media</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EC_BillingArrangementDetailHelper.cls
/* Class Name      : EC_BillingArrangementDetailHelper
* Description      :Controller Class for Billing Arrangement and Billing Arrangement Detail PAge
* Created By       :Moin Sawar
* Created On       :2020-Aug-27


* Modification Log:
* -------------------------------------------------------------------------------------------------------
* Developer                Date            Modification ID         Description
* -------------------------------------------------------------------------------------------------------
* Moin Sawar            2020-Aug-27         PBI-                    Created the class
*
*/
public with sharing class EC_BillingArrangementDetailHelper {

    private EC_BillingArrangementDetailHelper(){
    
    }
    public static ccrz.cc_RemoteActionResult fetchBADPData(ccrz.cc_RemoteActionResult res,String baId){
           
            EC_BillingArrangementController.baWrapper baWrapperObj = new EC_BillingArrangementController.baWrapper();
            Date today = Date.today();
            set<string> BAProdLineSet = EC_ProductDetailController.getBAProductLines();
            if(ccrz__E_PriceListItem__c.sObjectType.getDescribe().isAccessible()){ 
                
                List<ccrz__E_PriceListItem__c> pli = getProductlistBADP(baId,BAProdLineSet);
                if(!pli.isEmpty()){                     
                    baWrapperObj.profile = EC_QueryUtility.getProfile();
                    baWrapperObj.baNumber = pli[0].ccrz__Pricelist__r.BA_Number__c;
                    baWrapperObj.baId = pli[0].ccrz__Pricelist__r.ID;
                    baWrapperObj.baType = pli[0].ccrz__Pricelist__r.Price_List_Type_Expansion__c;
                    baWrapperObj.baDesc = pli[0].ccrz__Pricelist__r.ccrz__Desc__c;
                    DateTime startDate = pli[0].ccrz__Pricelist__r.ccrz__StartDate__c;
                    DateTime EndDate = pli[0].ccrz__Pricelist__r.ccrz__EndDate__c;                       
                    String formattedBAStartDate = startDate.formatGMT(EC_Constants.MMM)+' '+startDate.formatGMT(EC_Constants.d)+', '+startDate.formatGMT(EC_Constants.yyyy);
                    String formattedBAEndDate = EndDate.formatGMT(EC_Constants.MMM)+' '+EndDate.formatGMT(EC_Constants.d)+', '+EndDate.formatGMT(EC_Constants.yyyy);
                    baWrapperObj.startDate = formattedBAStartDate; 
                    baWrapperObj.EndDate = formattedBAEndDate;
                    Map<Id,ccrz__E_PriceListItem__c> prodIDPLI = new Map<Id,ccrz__E_PriceListItem__c> ();
                    for(ccrz__E_PriceListItem__c plItem : pli){
                        prodIDPLI.put(plItem.ccrz__Product__r.Id,plItem); 
                    }
                    Map<Id,ccrz__E_ProductMedia__c> prodIDMedia = new Map<Id,ccrz__E_ProductMedia__c> ();
                    for(ccrz__E_ProductMedia__c prodMedia : [select id ,ccrz__EndDate__c,ccrz__StartDate__c,ccrz__MediaType__c,ccrz__Enabled__c,ccrz__URI__c,ccrz__Product__r.Id from ccrz__E_ProductMedia__c where ccrz__Product__r.Id IN:prodIDPLI.KeySet() AND ccrz__Enabled__c =true AND ccrz__MediaType__c ='Product Image']){
                        prodIDMedia.put(prodMedia.ccrz__Product__r.Id,prodMedia);   
                    }
                    Set<String> pkgCodeSet = EC_BillingArrangementController.getPackageCode();
                    List<EC_BillingArrangementController.ItemWrapper> itemWrapperList = new List<EC_BillingArrangementController.ItemWrapper>();
                    List<EC_BillingArrangementController.ItemWrapper> prodLineItemWrapperList = new List<EC_BillingArrangementController.ItemWrapper>();
                    for(ccrz__E_PriceListItem__c plItem : pli){
                        if(BAProdLineSet.contains(plItem.ccrz__Product__r.ccrz__SKU__c)){
                            EC_BillingArrangementController.ItemWrapper ItemWrapperObj2 = new EC_BillingArrangementController.ItemWrapper();
                            ItemWrapperObj2.product = plItem.ccrz__Product__r;
                            ItemWrapperObj2.uri = prodIDMedia.containsKey(plItem.ccrz__Product__r.Id) ? prodIDMedia.get(plItem.ccrz__Product__r.Id).ccrz__URI__c : '';
                            prodLineItemWrapperList.add(ItemWrapperObj2);
                        }
                        else{
                            EC_BillingArrangementController.ItemWrapper ItemWrapperObj = createItemWrapperObj(plItem,prodIDMedia,pkgCodeSet);
                            itemWrapperList.add(ItemWrapperObj);
                        }
                        
                    }
                    
                    baWrapperObj.prodLineItems =prodLineItemWrapperList;
                    baWrapperObj.ItemWrapper = itemWrapperList;
                }
            }
            res.success = true;
            res.data = baWrapperObj;
            return res;
    }
    
    public static EC_BillingArrangementController.ItemWrapper createItemWrapperObj(ccrz__E_PriceListItem__c plItem, Map<Id,ccrz__E_ProductMedia__c> prodIDMedia,Set<String> pkgCodeSet){
            
            EC_BillingArrangementController.ItemWrapper ItemWrapperObj = new EC_BillingArrangementController.ItemWrapper();
            ItemWrapperObj.price =plItem.ccrz__Price__c;
            ItemWrapperObj.customPricingUOM = plItem.Custom_PricingUOM__c;
            ItemWrapperObj.customUnitPrice = plItem.Custom_UnitPrice__c;
            ItemWrapperObj.PricePer = Integer.valueOf(plItem.Price_Per__c);
            ItemWrapperObj.taxonomy =plItem.ccrz__Product__r.Taxonomy__c;
            String packageCode = plItem.ccrz__Product__r.Package_Code__c;
            ItemWrapperObj.packageTypeUOM = !pkgCodeSet.isEmpty() && pkgCodeSet.contains(packageCode) ? 'Bulk':'NonBulk';
            DateTime sDate= plItem.ccrz__StartDate__c;
            DateTime eDate=plItem.ccrz__EndDate__c; 
            String formattedPLIStartDate=sDate.formatGMT(EC_Constants.MMM)+' '+sDate.formatGMT(EC_Constants.d)+', '+sDate.formatGMT(EC_Constants.yyyy);
            String formattedPLIEndDate=eDate.formatGMT(EC_Constants.MMM)+' '+eDate.formatGMT(EC_Constants.d)+', '+eDate.formatGMT(EC_Constants.yyyy);
            ItemWrapperObj.startDate= formattedPLIStartDate;
            ItemWrapperObj.EndDate=  formattedPLIEndDate;
            ItemWrapperObj.product = plItem.ccrz__Product__r;
            ItemWrapperObj.uri = prodIDMedia.containsKey(plItem.ccrz__Product__r.Id) ? prodIDMedia.get(plItem.ccrz__Product__r.Id).ccrz__URI__c : '';
            return ItemWrapperObj;
    }

        public static Set<String> getDifferentBAType(){
        Set<String> baTypeSet = new Set<String>();
        List<Billing_Arrangement_Types__mdt> baTypes = new List<Billing_Arrangement_Types__mdt>();
        if(Billing_Arrangement_Types__mdt.sObjectType.getDescribe().isAccessible()){
            BATypes = [Select Label,BA_Type_Code__c,Active__c,Applicable_On_BADP__c from Billing_Arrangement_Types__mdt where Active__c = true AND Applicable_On_BADP__c =true];
            for (Billing_Arrangement_Types__mdt baType : baTypes) {
                baTypeSet.add(baType.Label);
            }
        }
        return baTypeSet;
    }

        
     public static  List<ccrz__E_PriceListItem__c> getProductlistBADP(String baId,set<string> BAProdLineSet){
        String productIndexStatus = System.label.EC_ProductIndexCurrent; 
        Map<String,ccrz__E_PriceListItem__c> plItemSkus = new Map<String,ccrz__E_PriceListItem__c>();
        Date today = Date.today();
        List<ccrz__E_PriceListItem__c> pli = new  List<ccrz__E_PriceListItem__c>();
        Set<ccrz__E_PriceListItem__c> pliTemp = new Set<ccrz__E_PriceListItem__c>();
        for(ccrz__E_PriceListItem__c plItem : [select Id,name,ccrz__Price__c,ccrz__Pricelist__r.BA_Number__c,ccrz__Pricelist__r.ID,ccrz__Pricelist__r.ccrz__Desc__c,ccrz__Pricelist__r.Price_List_Type_Expansion__c,ccrz__Pricelist__r.ccrz__StartDate__c,
                                               ccrz__Pricelist__r.ccrz__EndDate__c,ccrz__Product__r.ccrz__sku__c,ccrz__Product__r.ccrz__ProductStatus__c,ccrz__EndDate__c,ccrz__Product__r.Name,ccrz__Product__r.ccrz__UnitOfMeasure__c,
                                               ccrz__Product__r.Taxonomy__c,ccrz__Product__r.Package_Code__c,ccrz__Product__r.ccrz__ProductIndexStatus__c,Custom_PricingUOM__c,Custom_UnitPrice__c,Price_Per__c,ccrz__Product__r.ccrz__StartDate__c,ccrz__Product__r.ccrz__EndDate__c,ccrz__StartDate__c 
                                               from ccrz__E_PriceListItem__c where ccrz__StartDate__c <= :today AND ccrz__EndDate__c>=:today AND ccrz__Product__r.ccrz__StartDate__c <= :today AND ccrz__Product__r.ccrz__EndDate__c>=:today 
                                               AND ccrz__Pricelist__c =:baId  AND ((ccrz__Product__r.ccrz__ProductIndexStatus__c =:productIndexStatus AND ccrz__Product__r.ccrz__ProductStatus__c IN('Released','Not Orderable')) OR ccrz__Product__r.ccrz__sku__c IN:BAProdLineSet) order by ccrz__Product__r.ccrz__sku__c asc]){
                                                   
                                                   plItemSkus.put(plItem.ccrz__Product__r.ccrz__sku__c,plItem);
                                               }                
        
        for(ccrz__E_PriceListItem__c plItem : [select Id,ccrz__Product__r.ccrz__sku__c from ccrz__E_PriceListItem__c where ccrz__StartDate__c <= :today 
                                               AND ccrz__EndDate__c>=:today AND ccrz__Product__r.ccrz__StartDate__c <= :today AND ccrz__Product__r.ccrz__EndDate__c>=:today 
                                               AND ccrz__Pricelist__r.EC_Price_List_Type__c NOT IN :getDifferentBAType() AND ccrz__Product__r.ccrz__sku__c IN :plItemSkus.keySet() order by ccrz__Product__r.ccrz__sku__c asc]){
                                                   if(plItemSkus.containsKey(plItem.ccrz__Product__r.ccrz__sku__c)){
                                                       pliTemp.add(plItemSkus.get(plItem.ccrz__Product__r.ccrz__sku__c));
                                                   }  
                                               }
        for(String genLines: BAProdLineSet){
            if(plItemSkus.containsKey(genLines)){
                pliTemp.add(plItemSkus.get(genLines));
            } 
        }
        pli.addAll(pliTemp);
        return pli;
    }
}