src/objects/Billing_Arrangement_Types__mdt.object
<CustomObject>
    <description>List of Billing Arrangement Types which are in Scope (Eg: Usage, Fixed, UseRisk)</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BA_Type_Code__c</fullName>
        <label>BA Type Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Billing Arrangement Type</label>
    <pluralLabel>Billing Arrangement Types</pluralLabel>
</CustomObject>

src/objects/ccrz__E_AccountGroupPriceList__c.object
<CustomObject>
    <description>Represents a mapping of Account Group to Pricelist.  This objects ties the two together, enabling the assignment and entitlement/pricing functionality.</description>
    <fields>
        <fullName>EC_Price_List_Type__c</fullName>
        <label>Price List Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Z1CP</fullName>
                </value>
                <value>
                    <fullName>Z1GP</fullName>
                </value>
                <value>
                    <fullName>Z1MP</fullName>
                </value>
                <value>
                    <fullName>ZFCP</fullName>
                </value>
                <value>
                    <fullName>ZF00</fullName>
                </value>
                <value>
                    <fullName>Z1LS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the pricelist</description>
        <label>Pricelist</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>Account Group Price Lists</relationshipLabel>
        <relationshipName>E_AccountGroupPriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Account Group Price List</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Acct Group Pricelist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Account Group Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_ContactAddr__c.object
<CustomObject>
    <description>Used to store address information.  Associated with Carts, Orders, Invoices, Subscriptions, Payments, etc.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__CompanyName__c</fullName>
        <description>Company name associated with this address.</description>
        <label>Company Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CC Contact Address</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Contact Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Contact Addresss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>ccrz__EffectiveAccountID__c</fullName>
        <description>Holds the effective account for this order.  This field will be utilized in implementations where a user can order for multiple accounts inclusive or exclusive of their own.  The effective account is used to control the entitlements, pricing, integrations etc that drive the site experience.</description>
        <inlineHelpText>This field will be utilized in implementations where a user can order for multiple accounts inclusive or exclusive of their own.  The effective account is used to control the entitlements, pricing, integrations etc that drive the site experience.</inlineHelpText>
        <label>Effective Account ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent order, which originally submitted the subscription for this order, if applicable</description>
        <inlineHelpText>Parent order, which originally submitted the subscription for this order, if applicable</inlineHelpText>
        <label>Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Children Orders</relationshipLabel>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_OrderItem__c.object
<CustomObject>
    <description>The E_OrderItem__c object contains the line level detail of placed orders.</description>
    <fields>
        <fullName>Tank_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tank Detail</label>
        <referenceTo>Tank_Detail__c</referenceTo>
        <relationshipLabel>CC Order Items</relationshipLabel>
        <relationshipName>CC_Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unloading_Point__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unloading Point</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipLabel>CC Order Items</relationshipLabel>
        <relationshipName>CC_Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__OrderItemGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Order Item Group that the item belongs to. Used for Line Level Independence.</description>
        <label>Order Item Group</label>
        <referenceTo>ccrz__E_OrderItemGroup__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <description>The order that this order line is a part of.</description>
        <label>Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Order Items (ProductID)</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Arrangement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To stamp billing arrangement on order item</description>
        <label>Billing Arrangement</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>CC Order Items</relationshipLabel>
        <relationshipName>CC_Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Order Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>OrderItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_OrderItemGroup__c.object
<CustomObject>
    <description>Order Item Group represents a group of items on the order who share shipping details.</description>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <description>The Order that the Order Item Group is associated with.</description>
        <label>CC Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Order Item Groups</relationshipLabel>
        <relationshipName>E_OrderItemGroups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Billing_Arrangement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Arrangement</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>CC Order Item Groups</relationshipLabel>
        <relationshipName>CC_Order_Item_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Item_Group_Status__c</fullName>
        <description>Displayed Order Item Group  status. Order Item Group status initially placed are all in Order Submitted status. All other statuses may be implementation specific.</description>
        <label>Order Item Group Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Return Submitted</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Partial Shipped</fullName>
                </value>
                <value>
                    <fullName>Bill Of Material</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Order Not Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <label>Order Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Order Item Group</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Order Item Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceList__c.object
<CustomObject>
    <description>Represents a grouping of products to control pricing and entitlements.  The B2B Commerce pricelist object controls both pricing and entitlements, but can be used just for the purposes of entitlements. A list needs to be created for each currency that needs to be represented, allowing for different entitlments and pricing based on the locale and currency.</description>
    <fields>
        <fullName>EC_Price_List_Type__c</fullName>
        <description>This field stores the type of pricelist i.e. Sales Org, Customer Group</description>
        <inlineHelpText>This field stores the type of pricelist i.e. Sales Org, Customer Group</inlineHelpText>
        <label>Price List Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BA_Number__c</fullName>
        <description>To store BA number</description>
        <label>BA Number</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <label>CC Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceListItem__c.object
<CustomObject>
    <description>Represents an entry in the Pricelist.  Each pricelist object is made up of 1 or more pricelist item objects.  This item objects contain a reference to the product and hold a price value (0, in the case where only entitlements are being used).  The products referenced within these items will be displayed in search and product listings on the external site.</description>
    <fields>
        <fullName>ccrz__Pricelist__c</fullName>
        <description>Required - The reference to the pricelist</description>
        <label>Pricelist</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>E_PriceListItems1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the product entry</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>E_PriceListItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Price List Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>PriceListItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within B2B Commerce</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EC_SplitOrder.cls
/* Class Name      : EC_BillingArrangementController
* Description      : Controller Class for Splitting order
* Created By       : Bharath Kn
* Created On       : 2020-Sept-03


* Modification Log:
* -----------------------------------------------------------------------------------------------------------------------------------------------------------------
* Developer                Date            Modification ID         Description
* -----------------------------------------------------------------------------------------------------------------------------------------------------------------
* Bharath Kn            2020-Sept-03         PBI-                  Created the class
*
*/
public class EC_SplitOrder {
    
    @InvocableMethod
    public static void orderSubmitFlow(List<Id> orderIds){
        String orderId = orderIds.get(0);
        Map<String,List<ccrz__E_OrderItem__c>> BA_ULOrderItemMap = orderItemSplitLogic(orderId);
        List<ccrz__E_OrderItemGroup__c> OIGroupRecords = createOrderItemGroups(BA_ULOrderItemMap.size(),orderId);
        assOIwithOIGroup(OIGroupRecords,BA_ULOrderItemMap);
        
    }
    
    public static Map<String,List<ccrz__E_OrderItem__c>> orderItemSplitLogic(String orderId){
        Map<String,List<ccrz__E_OrderItem__c>> skuOrderItemMap =  (Map<String,List<ccrz__E_OrderItem__c>>) fetchSKUOrderItemMap(orderId).get('skuOrderItemMap');
        Map<String,ccrz__E_PriceListItem__c> skuSBAPriceListMap = (Map<String,ccrz__E_PriceListItem__c>) fetchSKUOrderItemMap(orderId).get('skuSBAPriceListMap');
        
        Map<String,String> skuPriceListMap = (Map<String,String>) fetchSKUOrderItemMap(orderId).get('skuPriceListMap');
        Map<String,List<String>> pricelistSKUMap = (Map<String,List<String>>) fetchSKUOrderItemMap(orderId).get('pricelistSKUMap');
        
        system.debug(skuSBAPriceListMap);
        Map<String,List<ccrz__E_OrderItem__c>> BA_ULOrderItemMap = new Map<String,List<ccrz__E_OrderItem__c>>();

        //ccrz__Order__r.ccrz__EffectiveAccountID__c
        for(String sku : skuOrderItemMap.keySet()){
            Boolean isBulk = false;
            List<ccrz__E_OrderItem__c> orderItems = skuOrderItemMap.get(sku);
            if(orderItems.size() == 1){
                isBulk = EC_SplitOrderHelper.checkIsBulk(orderItems[0]);
                processOrderItem(orderItems[0], isBulk,skuSBAPriceListMap,BA_ULOrderItemMap);
            }
            if(orderItems.size() > 1){
                for(ccrz__E_OrderItem__c orderItem : orderItems){
                    isBulk = EC_SplitOrderHelper.checkIsBulk(orderItem);
                    processOrderItems(orderItem, isBulk,skuSBAPriceListMap,BA_ULOrderItemMap);
                }
            }
        }
        
        for(String key : BA_ULOrderItemMap.keySet()){
            system.debug('key '+ key);
            system.debug('value '+ BA_ULOrderItemMap.get(key));
            String keyWithoutSPA = key.removeStartIgnoreCase('SPA_');
            if(key.startsWithIgnoreCase('SPA_Ship_and_Bill_') && BA_ULOrderItemMap.containsKey(keyWithoutSPA)){
                BA_ULOrderItemMap.get(keyWithoutSPA).addAll(BA_ULOrderItemMap.get(key));
                BA_ULOrderItemMap.remove(key);
            }
        }

        if((Boolean) fetchSKUOrderItemMap(orderId).get('multipleSPAAssociated')){
            system.debug('split');
            splitMultipleSPA(BA_ULOrderItemMap,skuPriceListMap,pricelistSKUMap);
        }
        return BA_ULOrderItemMap;
    }
    
    
    public static void splitMultipleSPA(Map<String,List<ccrz__E_OrderItem__c>> BA_ULOrderItemMap,Map<String,String> skuPriceListMap, Map<String,List<String>> pricelistSKUMap){
        for(String key : BA_ULOrderItemMap.keySet()){
            system.debug('key split'+ key);
            system.debug('value split'+ BA_ULOrderItemMap.get(key));
            if((key.startsWithIgnoreCase('Ship_and_Bill_') || key.startsWithIgnoreCase('SPA_Ship_and_Bill_')) && BA_ULOrderItemMap.get(key).size()> 1){
                for(String pricelist : pricelistSKUMap.keySet()){
                    for(ccrz__E_OrderItem__c orderItem : BA_ULOrderItemMap.get(key)){
                        splitMultipleSPAHelper(orderItem,pricelist,key,BA_ULOrderItemMap,skuPriceListMap,pricelistSKUMap);
                    }
                }
            }
        }
    }
	public static void splitMultipleSPAHelper(ccrz__E_OrderItem__c orderItem, String pricelist, String key, Map<String,List<ccrz__E_OrderItem__c>> BA_ULOrderItemMap,Map<String,String> skuPriceListMap, Map<String,List<String>> pricelistSKUMap){
        
        if(skuPriceListMap.containsKey(orderItem.ccrz__Product__r.ccrz__SKU__c) && !pricelistSKUMap.get(priceList).contains(orderItem.ccrz__Product__r.ccrz__SKU__c)){
            if(BA_ULOrderItemMap.containsKey(pricelist)){
                BA_ULOrderItemMap.get(pricelist).add(orderItem);
            }else{
                BA_ULOrderItemMap.put(pricelist, new List<ccrz__E_OrderItem__c>{orderItem});
            }
            BA_ULOrderItemMap.get(key).remove(BA_ULOrderItemMap.get(key).indexOf(orderItem));
            if(BA_ULOrderItemMap.get(key).size() == 0){
                BA_ULOrderItemMap.remove(key);
            }
        }
    }
    
    public static List<ccrz__E_OrderItemGroup__c> createOrderItemGroups(Integer numOfOrderItemGroup, String OrderId){
        List<ccrz__E_OrderItemGroup__c> OIGroupRecords = new List<ccrz__E_OrderItemGroup__c>();
        for(Integer i=1; i<=numOfOrderItemGroup; i++){
            ccrz__E_OrderItemGroup__c obj = new ccrz__E_OrderItemGroup__c();
            obj.ccrz__Order__c = OrderId;
            OIGroupRecords.add(obj);
        }
        
        insert OIGroupRecords;
        System.debug('OIGroupRecords size'+OIGroupRecords.size());
        return OIGroupRecords;
    }
    
    public static void assOIwithOIGroup(List<ccrz__E_OrderItemGroup__c> OIGroupRecords, Map<String,List<ccrz__E_OrderItem__c>> OrderItemBA_ULMap){        
        Map<id,ccrz__E_OrderItem__c> updateorderItem = new Map<id,ccrz__E_OrderItem__c>();
        Map<id,ccrz__E_OrderItemGroup__c> UpdateOIGroupRecords = new Map<id,ccrz__E_OrderItemGroup__c>();
        integer n =0;
        for(String key : OrderItemBA_ULMap.keyset()){           
            List<ccrz__E_OrderItem__c> OrderItems = OrderItemBA_ULMap.get(key);
            for(ccrz__E_OrderItem__c orderItem : OrderItems) {
                orderItem.ccrz__OrderItemGroup__c = OIGroupRecords[n].Id;
                OIGroupRecords[n].Order_Item_Group_Status__c='Order not submitted';
                if(orderItem.Billing_Arrangement__c == null){
                    OIGroupRecords[n].Order_Type__c = 'ZOS1';
                }else {
                    OIGroupRecords[n].Billing_Arrangement__c = orderItem.Billing_Arrangement__c;
                    map<string,string> batypeOrderTypeMap = batypeOrderTypeMap();
                    system.debug('EC_SplitOrder batypeOrderTypeMap-->'+batypeOrderTypeMap);
                    OIGroupRecords[n].Order_Type__c = batypeOrderTypeMap.get(orderItem.Billing_Arrangement__r.EC_Price_List_Type__c);
                }
                UpdateOIGroupRecords.put(OIGroupRecords[n].id,OIGroupRecords[n]);
                updateorderItem.put(orderItem.Id,orderItem);
            }
            n++;
        }
        update updateorderItem.values();
        update UpdateOIGroupRecords.values();
    }
    
    
    public static map<string,string> batypeOrderTypeMap () {
        List<Billing_Arrangement_Types__mdt> BATypes = new List<Billing_Arrangement_Types__mdt>();
        if (Billing_Arrangement_Types__mdt.sObjectType.getDescribe().isAccessible()) { 
            BATypes = [Select Label,BA_Type_Code__c,Active__c from Billing_Arrangement_Types__mdt where Active__c = true];
        }
        Map<String,String> batypeOrderTypeMap = new Map<String,String>();
        if(!BATypes.isEmpty()) {
            for(Billing_Arrangement_Types__mdt BAType: BATypes ) {
                batypeOrderTypeMap.put(BAType.Label,BAType.BA_Type_Code__c);
            }
        }        
        return batypeOrderTypeMap;
    }    
    
    public static Map<String,Object> fetchSKUOrderItemMap(String orderId){
        Map<String,Object> responseMap = new Map<String,Object>();
         Map<String,List<ccrz__E_OrderItem__c>> skuOrderItemMap = new Map<String,List<ccrz__E_OrderItem__c>>();
        String effectiveAccount = ''; 
        for(ccrz__E_OrderItem__c orderItem : [select id,ccrz__Order__c,Billing_Arrangement__r.BA_Number__c,Unloading_Point__r.ccrz__CompanyName__c,ccrz__Product__r.ccrz__SKU__c,Tank_Number__c,
                                              Billing_Arrangement__r.EC_Price_List_Type__c,ccrz__Order__r.ccrz__EffectiveAccountID__c 
                                              from ccrz__E_OrderItem__c where ccrz__Order__r.Id =:orderId]) {
                                                  effectiveAccount = orderItem.ccrz__Order__r.ccrz__EffectiveAccountID__c;
                                                  if(!skuOrderItemMap.containsKey(orderItem.ccrz__Product__r.ccrz__SKU__c)){
                                                      skuOrderItemMap.put(orderItem.ccrz__Product__r.ccrz__SKU__c,new List<ccrz__E_OrderItem__c>{orderItem});                                   
                                                  }else{
                                                      skuOrderItemMap.get(orderItem.ccrz__Product__r.ccrz__SKU__c).add(orderItem);   
                                                  }
                                              }
        Map<String,ccrz__E_PriceListItem__c> skuSBAPriceListMap = new Map<String,ccrz__E_PriceListItem__c>();
        
        String acgrp = [Select ccrz__E_AccountGroup__c from Account Where Id=:effectiveAccount Limit 1].ccrz__E_AccountGroup__c;
        Map<String,String> skuPriceListMap = new Map<String,String>();
        Map<String,List<String>> pricelistSKUMap = new Map<String,List<String>>();
        
        for(ccrz__E_PriceListItem__c sbaPLI : [Select Id,ccrz__Product__r.ccrz__SKU__c,ccrz__Pricelist__r.Name from ccrz__E_PriceListItem__c where ccrz__Product__r.ccrz__SKU__c in:skuOrderItemMap.keySet() and ccrz__Pricelist__r.EC_Price_List_Type__c = 'SBA'
                                               and ccrz__Pricelist__c in (SELECT ccrz__Pricelist__c from ccrz__E_AccountGroupPriceList__c 
                                                                          where ccrz__AccountGroup__c=:acgrp )]){
                                                                              skuSBAPriceListMap.put(sbaPLI.ccrz__Product__r.ccrz__SKU__c,sbaPLI);
                                                                              skuPriceListMap.put(sbaPLI.ccrz__Product__r.ccrz__SKU__c,sbaPLI.ccrz__Pricelist__r.Name);
                                                                              
                                                                              if(pricelistSKUMap.containsKey(sbaPLI.ccrz__Pricelist__r.Name)){
                                                                                  pricelistSKUMap.get(sbaPLI.ccrz__Pricelist__r.Name).add(sbaPLI.ccrz__Product__r.ccrz__SKU__c);
                                                                              }else{
                                                                                  pricelistSKUMap.put(sbaPLI.ccrz__Pricelist__r.Name, new List<String>{sbaPLI.ccrz__Product__r.ccrz__SKU__c});
                                                                              }
                                                                          }
        
        responseMap.put('skuOrderItemMap',skuOrderItemMap);
        responseMap.put('skuSBAPriceListMap',skuSBAPriceListMap);
        responseMap.put('skuPriceListMap',skuPriceListMap);
        responseMap.put('pricelistSKUMap',pricelistSKUMap);
        responseMap.put('multipleSPAAssociated',false);
        if(skuPriceListMap.values().size() > 1 ){
            responseMap.put('multipleSPAAssociated',true);
        }
        return responseMap;
    }

    public static void processOrderItem(ccrz__E_OrderItem__c orderItem, Boolean isBulk,Map<String,ccrz__E_PriceListItem__c> skuSBAPriceListMap, Map<String,List<ccrz__E_OrderItem__c>> BA_ULOrderItemMap){
        
        if(orderItem.Billing_Arrangement__r != null){
            if(orderItem.Billing_Arrangement__r.EC_Price_List_Type__c == 'FBA' || orderItem.Billing_Arrangement__r.EC_Price_List_Type__c =='USR'){
                String BANumber = orderItem.Billing_Arrangement__r.EC_Price_List_Type__c +'_'+ orderItem.Billing_Arrangement__r.BA_Number__c;
                EC_SplitOrderHelper.addOrderItemToMap_V2(orderItem,BA_ULOrderItemMap,BANumber,null,isBulk);
            }else if(orderItem.Billing_Arrangement__r.EC_Price_List_Type__c == 'USG'){
                EC_SplitOrderHelper.addOrderItemToMap_V2(orderItem,BA_ULOrderItemMap,null,null,isBulk);
            }
        }else{
            if(skuSBAPriceListMap.containsKey(orderItem.ccrz__Product__r.ccrz__SKU__c)){
                EC_SplitOrderHelper.addOrderItemToMap_V2(orderItem,BA_ULOrderItemMap,null,null,isBulk);
            }else{
                //Ship and bill without SPA
                EC_SplitOrderHelper.addOrderItemToMap_V2(orderItem,BA_ULOrderItemMap,'Ship_and_Bill',null,isBulk);
            }
        }
    }
    public static void processOrderItems(ccrz__E_OrderItem__c orderItem, Boolean isBulk,Map<String,ccrz__E_PriceListItem__c> skuSBAPriceListMap, Map<String,List<ccrz__E_OrderItem__c>> BA_ULOrderItemMap){
        
        if(orderItem.Billing_Arrangement__r == null){
            if(skuSBAPriceListMap.containsKey(orderItem.ccrz__Product__r.ccrz__SKU__c)){
                EC_SplitOrderHelper.addOrderItemToMap_V2(orderItem,BA_ULOrderItemMap,'SPA_Ship_and_Bill',null,isBulk);
            }else{
                //Ship and bill without SPA
                EC_SplitOrderHelper.addOrderItemToMap_V2(orderItem,BA_ULOrderItemMap,'Ship_and_Bill',null,isBulk);
            }
        }else{
            if(orderItem.Billing_Arrangement__r.EC_Price_List_Type__c == 'FBA' || orderItem.Billing_Arrangement__r.EC_Price_List_Type__c =='USR'){
                String BANumber = orderItem.Billing_Arrangement__r.EC_Price_List_Type__c +'_'+orderItem.Billing_Arrangement__r.BA_Number__c;
                EC_SplitOrderHelper.addOrderItemToMap_V2(orderItem,BA_ULOrderItemMap,BANumber,null,isBulk);
            }else if(orderItem.Billing_Arrangement__r.EC_Price_List_Type__c == 'USG'){
                EC_SplitOrderHelper.addOrderItemToMap_V2(orderItem,BA_ULOrderItemMap,null,null,isBulk);
            }
        }
    }
}