src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Category_1_4__c</fullName>
        <description>E101CRMXIF_SUBJECT_CODE</description>
        <label>Category 1 4</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_1_8__c</fullName>
        <description>E101CRMXIF_SUBJECT_CODEGROUP</description>
        <label>Category 1 8</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_2_4__c</fullName>
        <description>E101CRMXIF_SUBJECT_CODE</description>
        <label>Category 2 4</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_2_8__c</fullName>
        <description>E101CRMXIF_SUBJECT_CODEGROUP</description>
        <label>Category 2 8</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <description>E101CRMXIF_BUSTRANS-Process_Type</description>
        <label>Order Type</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <description>E101CRMXIF_PARTNER- PARTNER_NO
Record with Application Name: CRMXIF_PARTNER
Read the partner segment for partner function (PARTNER_FCT) ‘00000001’</description>
        <label>Ship To</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To__c</fullName>
        <description>E101CRMXIF_PARTNER- PARTNER_NO
Record with Application Name: CRMXIF_PARTNER
Read the partner segment for partner function (PARTNER_FCT) ‘00000001’.</description>
        <label>Sold To</label>
        <length>20</length>
        <type>Text</type>
    </fields>
	<fields>
		<fullName>Integration_Status__c</fullName>
		<description>Integration Status</description>
		<inlineHelpText>Integration Status</inlineHelpText>
		<label>Integration Status</label>
		<length>255</length>
		<type>Text</type>
    </fields>
</CustomObject>

src/objects/Global_Static__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings object to store general global static values</description>
    <fields>
        <fullName>value__c</fullName>
        <label>value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Global Static</label>
</CustomObject>

src/objects/SAP_TIBCO_URL__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>TIBCO_End_Point_Url__c</fullName>
        <label>TIBCO End Point Url</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>SAP TIBCO URL</label>
</CustomObject>

force-app/main/default/classes/EC_CaseTriggerHandlerTest.cls
@isTest
public class EC_CaseTriggerHandlerTest {
    static String destUrlStr = 'Destination URL';
  	@isTest 
    public static void doFutureCalloutTestPositive() {
        Case testCase = [Select Id from Case];
        List<Id> testCaseList = new List<Id>{testCase.id};
        Test.startTest();
        Test.setMock(WebServiceMock.class, new EC_CaseTextMyRepToSAPMockUp());
        EC_CaseTriggerHandler.doFutureCallout(testCaseList);
		Test.stopTest();
        Case testCaseUpdated = [Select Id,Integration_Status__c from Case];
        System.assertEquals(testCaseUpdated.Integration_Status__c, EC_Constants.SERVICE_REQUEST_INTEGRATION_STATUS);
    }
    
    @isTest 
    public static void doFutureCalloutTestNegative() { 
       	Case testCase = [Select Id from Case];
        List<Id> testCaseList = new List<Id>{testCase.id};  
        Test.startTest();
        Test.setMock(WebServiceMock.class, new EC_CaseTextMyRepToSAPMockUpNegative());
        EC_CaseTriggerHandler.doFutureCallout(testCaseList);
        Test.stopTest();
        Case testCaseUpdated = [Select Id,Integration_Status__c from Case];
        System.assertEquals(testCaseUpdated.Integration_Status__c, EC_Constants.SERVICE_REQUEST_INTEGRATION_STATUS_FAIL);
       
    }

    @isTest 
    public static void doFutureCalloutTestException() { 
       	Case testCase = [Select Id from Case];
        List<Id> testCaseList = new List<Id>{testCase.id};  
        Test.startTest();
        Test.setMock(WebServiceMock.class, new EC_CaseTextMyRepToSAPMockUpExceptionResp());
        EC_CaseTriggerHandler.doFutureCallout(testCaseList);
        Test.stopTest();
        Case testCaseUpdated = [Select Id,Integration_Status__c from Case];
        System.assertEquals(testCaseUpdated.Integration_Status__c, EC_Constants.SERVICE_REQUEST_INTEGRATION_STATUS_FAIL);
       
    }
    
    
    @isTest
    public static void retryServiceRequestSubmitTest(){   
      	Case testCase = [Select Id from Case];
        List<Id> testCaseList = new List<Id>{testCase.id};
        Test.startTest();       
        Test.setMock(WebServiceMock.class, new EC_CaseTextMyRepToSAPMockUp());
        EC_CaseTriggerHandler.retryServiceRequestSubmit(testCaseList);
        Test.stopTest();
        Case testCaseUpdated = [Select Id,Integration_Status__c from Case];
        System.assertEquals(testCaseUpdated.Integration_Status__c, EC_Constants.SERVICE_REQUEST_INTEGRATION_STATUS);
       
     }
    
    @testSetup
    public static void testDataSetup(){
        Case newTestC = new Case();
        newTestC.Origin = 'Portal';
        newTestC.Order_Type__c = 'ZESR';
        newTestC.Sold_To__c = '2345/22333';
        newTestC.Ship_To__c = '2312/33433';
        newTestC.Type = 'Request Service';
        newTestC.SuppliedName = 'testname';
        newTestC.SuppliedPhone = '2343454556';
        newTestC.SuppliedEMail = 'test@test.com';        
        newTestC.Category_1_4__c = 'Test';
        newTestC.Category_1_8__c = 'Firs';
        newTestC.Category_2_4__c = 'test';
        newTestC.Category_2_8__c = 'last';
        newTestC.Subject = 'Pest Portal - Request Service Visit';
        newTestC.Description = 'SFDC to Tibco Test SFDC to Tibco Test SFDC to Tibco Test SFDC to Tibco'
            + 'TestSFDC to Tibco Test SFDC to Tibco Test';
        insert newTestC;
        
        Global_Static__c gsSettings = new Global_Static__c();
        gsSettings.Name = 'Source_System';
        gsSettings.value__c = 'Connect'; 
        insert gsSettings;  

        SAP_TIBCO_URL__c settings = new SAP_TIBCO_URL__c();
        settings.Name = destUrlStr;
        settings.TIBCO_End_Point_Url__c = '__https://local';
        insert settings;

    }
}