src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <description>E101CRMXIF_BUSTRANS-Process_Type</description>
        <label>Order Type</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <description>E101CRMXIF_PARTNER- PARTNER_NO
Record with Application Name: CRMXIF_PARTNER
Read the partner segment for partner function (PARTNER_FCT) ‘00000001’</description>
        <label>Ship To</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To__c</fullName>
        <description>E101CRMXIF_PARTNER- PARTNER_NO
Record with Application Name: CRMXIF_PARTNER
Read the partner segment for partner function (PARTNER_FCT) ‘00000001’.</description>
        <label>Sold To</label>
        <length>20</length>
        <type>Text</type>
    </fields>
	<fields>
		<fullName>Integration_Status__c</fullName>
		<description>Integration Status</description>
		<inlineHelpText>Integration Status</inlineHelpText>
		<label>Integration Status</label>
		<length>255</length>
		<type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Error_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Integration Error Log</description>
        <label>Integration Error Log (if any)</label>
        <referenceTo>Integration_Log__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
	<fields>
        <fullName>Category__c</fullName>
        <description>Used to in routing in Ecolab project.</description>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SupportCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <description>Used to in routing in Ecolab project.</description>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>SupportSubCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution_Category__c</fullName>
        <description>Required to be populated when resolving the case for service cloud project.</description>
        <label>Resolution Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Apply Break / Fix</fullName>
                </value>
                <value>
                    <fullName>Case Abandoned</fullName>
                </value>
                <value>
                    <fullName>Correct Data Error</fullName>
                </value>
                <value>
                    <fullName>No Workaround Applied</fullName>
                </value>
                <value>
                    <fullName>Provide Training or Documentation</fullName>
                </value>
                <value>
                    <fullName>Request for Enhancement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution_Description__c</fullName>
        <description>Required to be populated when resolving the case for service cloud project.</description>
        <inlineHelpText>Please note it will be visible to customer.</inlineHelpText>
        <label>Resolution Description</label>
        <type>TextArea</type>
    </fields>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <businessProcess>Support</businessProcess>
        <!--<compactLayoutAssignment>Support_Compact_Layout</compactLayoutAssignment>-->
        <description>Used for Ecolab service cloud, for Sales Rep, Community user and Agents.</description>
        <label>Support</label>
    </recordTypes>
</CustomObject>

src/globalValueSets/SupportCategory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Checkout</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Login</fullName>
    </customValue>
    <customValue>
        <fullName>Orders</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <customValue>
        <fullName>Quicklist</fullName>
    </customValue>
    <customValue>
        <fullName>Self-Service Register</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>User</fullName>
    </customValue>
    <description>Common picklist values on case and Chat bot routing object for Ecolab Project.</description>
    <masterLabel>Category</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/CaseUpdateRestResourceTest.cls
@istest
public class CaseUpdateRestResourceTest {
    public static void createCase(){
        Id supRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Support').getRecordTypeId();
        Case newTestC = new Case();
        newTestC.RecordTypeId = supRecordTypeId;
        newTestC.Origin = 'Portal';
        newTestC.Order_Type__c = 'ZESR';
        newTestC.Sold_To__c = '2345';
        newTestC.Ship_To__c = '2312';
        newTestC.SuppliedName = 'testname';
        newTestC.SuppliedPhone = '2343454556';
        newTestC.SuppliedEMail = 'test@test.com'; 
        newTestC.Subject = 'Pest Portal - Request Service Visit';
        newTestC.Description = 'SFDC to Tibco Test';
        newTestC.External_Id__c = 'CS000001';
        newTestC.Category__c= 'Login';
        newTestC.Sub_Category__c = 'Forgot Username';
        newTestC.Resolution_Category__c = 'No Workaround Applied';
        newTestC.Resolution_Description__c = 'test';
        insert newTestC;
    }
    @istest
    public static void doPost(){
        createCase();
        String caseNumber = [select casenumber from case limit 1].casenumber;
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/caseapi';  //Request URL
        req.httpMethod = 'POST';//HTTP Request Type
        
        RestContext.request = req;
        RestContext.response= res;
        
        try{
            CaseUpdateRestResource.doPatch('',null,null,null,null,null);
            CaseUpdateRestResource.doPatch('11633910071',null,null,null,null,null);
            CaseUpdateRestResource.doPatch(caseNumber,null,null,null,null,null);
            CaseUpdateRestResource.doPatch(caseNumber,null,null,null,null,'Group');
            string actual = [select id,Integration_Error_Log__c,Integration_Status__c from case where CaseNumber=:caseNumber limit 1].Integration_Error_Log__c;
        	system.assertEquals(true, actual!=null);
        }
        catch(exception e){
             system.debug('-------Error Message-------'+e.getMessage());
        }
    }
    
    @istest
    public static void doPostResolved(){
        createCase();
        String caseNumber = [select casenumber from case limit 1].casenumber;
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/caseapi';  //Request URL
        req.httpMethod = 'POST';//HTTP Request Type
        
        RestContext.request = req;
        RestContext.response= res;
        
        try{
            CaseUpdateRestResource.doPatch(caseNumber,'Resolved','test description',null,null,null);
            CaseUpdateRestResource.doPatch(caseNumber,'Resolved','test description',null,null,'Group');
            CaseUpdateRestResource.doPatch(caseNumber,'Resolved','test description',null,null,null);
            CaseUpdateRestResource.doPatch(caseNumber,null,null,'unResolved','test description','Agents');
            string actual = [select id,External_Id__c,Integration_Status__c from case where CaseNumber=:caseNumber limit 1].Integration_Status__c;
        	system.assertEquals('Received Resolved', actual);
        }
        catch(exception e){
             system.debug('-------Error Message-------'+e.getMessage());
        }
    }
    @istest
    public static void doPostResolvedWithoutResolutionNotes(){
        createCase();
        String caseNumber = [select casenumber from case limit 1].casenumber;
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/caseapi';  //Request URL
        req.httpMethod = 'POST';//HTTP Request Type
        
        RestContext.request = req;
        RestContext.response= res;
        
        try{
            CaseUpdateRestResource.doPatch(caseNumber,'Resolved',null,null,null,null);
            string actual = [select id,Integration_Error_Log__c,Integration_Status__c from case where CaseNumber=:caseNumber limit 1].Integration_Error_Log__c;
        	system.assertEquals(true, actual!=null);
        }
        catch(exception e){
             system.debug('-------Error Message-------'+e.getMessage());
        }
    }
    @istest
    public static void doPostUnResolved(){
        createCase();
        String caseNumber = [select casenumber from case limit 1].casenumber;
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/caseapi';  //Request URL
        req.httpMethod = 'POST';//HTTP Request Type
        
        RestContext.request = req;
        RestContext.response= res;
        
        try{
            CaseUpdateRestResource.doPatch(caseNumber,null,null,'unResolved','test description','L3_Agents');
            CaseUpdateRestResource.doPatch(caseNumber,'unResolved',null,'unResolved','test description',null);
            string actual = [select id,owner.name from case where CaseNumber=:caseNumber limit 1].Integration_Error_Log__c;
        	system.assertEquals('L3_Agents', actual);
        }
        catch(exception e){
             system.debug('-------Error Message-------'+e.getMessage());
        }
    }
    @istest
    public static void doPostException(){
        Id supRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Support').getRecordTypeId();
        Case newTestC = new Case();
        newTestC.RecordTypeId = supRecordTypeId;
        newTestC.Origin = 'Portal';
        newTestC.Order_Type__c = 'ZESR';
        newTestC.Sold_To__c = '2345';
        newTestC.Ship_To__c = '2312';
        newTestC.SuppliedName = 'testname';
        newTestC.SuppliedPhone = '2343454556';
        newTestC.SuppliedEMail = 'test@test.com'; 
        newTestC.Subject = 'Pest Portal - Request Service Visit';
        newTestC.Description = 'SFDC to Tibco Test';
        newTestC.External_Id__c = 'CS000001';
        newTestC.Category__c= 'Login';
        newTestC.Sub_Category__c = 'Forgot Username';
        newTestC.Resolution_Category__c = 'No Workaround Applied';
        newTestC.Resolution_Description__c = 'test';
        newTestC.status = 'Closed';
        insert newTestC;
        String caseNumber = [select casenumber from case where id=:newTestC.Id limit 1].casenumber;
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/caseapi';  //Request URL
        req.httpMethod = 'POST';//HTTP Request Type
        
        RestContext.request = req;
        RestContext.response= res;
        
        try{
            CaseUpdateRestResource.doPatch(caseNumber,'Resolved','test description',null,null,null);
            string actual = [select id,Integration_Error_Log__c,Integration_Status__c from case where CaseNumber=:caseNumber limit 1].Integration_Error_Log__c;
        	system.assertEquals(true, actual!=null);
        }
        catch(exception e){
            system.debug('-------Error Message-------'+e.getMessage());
        }
    }
}