src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>EC_PortalAccessRole__c</fullName>
        <label>Portal Access Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Basic</fullName>
                </value>
                <value>
                    <fullName>Buyer</fullName>
                </value>
                <value>
                    <fullName>Payer</fullName>
                </value>
                <value>
                    <fullName>Basic+</fullName>
                    <isActive>false</isActive>
                    <label>Basic+</label>
                </value>
                <value>
                    <fullName>Buyer+</fullName>
                    <isActive>false</isActive>
                    <label>Buyer+</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EC_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to user field</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/EC_Mulesoft_CDM_Staging__c.object
<CustomObject>
    <description>This object is used by Mulesoft to dump the CDM Data</description>
    <fields>
        <fullName>EC_Action__c</fullName>
        <label>Action</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_User__c</fullName>
        <label>User</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Mulesoft CDM Staging</label>
    <nameField>
        <label>Mulesoft CDM Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mulesoft CDM Stagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>EC_CDM_User__c</fullName>
        <description>US-74960:Raghav:26/06/2019:This field will be used for mapping between CDM and user object.</description>
        <externalId>true</externalId>
        <label>External UserKey</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/EC_StagingPermissionSetDeleteTest.cls
@istest
public class EC_StagingPermissionSetDeleteTest {

    /***************************************************************************************************************************************
Method Name : createPermissionSetAssignment
Description : Used to test scenarios for DeletePermissionSet in Staging
Return type : void
Author      : Shivam Vats
*************************************************************************************************************************************/
    @istest
    public static void createPermissionSetAssignment(){

        User testOwner = [SELECT TimeZoneSidKey, UserRoleId
                          FROM User
                          WHERE Id = :UserInfo.getUserId()];
        String user_cdmKey = '15102019';

        system.runAs(testOwner){
            UserRole role = new UserRole(DeveloperName = 'TestUser1', Name = 'TestRole');
            insert role;

            Profile profile = [SELECT Id
                               FROM Profile
                               WHERE Name = 'System Administrator' LIMIT 1];
            String language = 'en_US';
            String emailAddress = String.valueOf(System.now().getTime() + '@3cc-test.mail');
            User  testUser = new User(
                Alias                    = 'cctest',
                Email                    = emailAddress,
                EmailEncodingKey         = 'UTF-8',
                LastName                 = 'TestUser',
                LanguageLocaleKey        = language,
                LocaleSidKey             = language,
                ProfileId                = profile.Id,
                TimeZoneSidKey           = testOwner.TimeZoneSidKey,
                Username                 = emailAddress,
                isActive                 = true,
                UserRole                 = role,
                EC_CDM_User__c           = user_cdmKey
            );
            insert testUser;
            
            User  testUser1 = new User(
                Alias                    = 'cctest',
                Email                    = emailAddress+'2',
                EmailEncodingKey         = 'UTF-8',
                LastName                 = 'TestUsero',
                LanguageLocaleKey        = language,
                LocaleSidKey             = language,
                ProfileId                = profile.Id,
                TimeZoneSidKey           = testOwner.TimeZoneSidKey,
                Username                 = emailAddress+'2',
                isActive                 = true,
                UserRole                 = role,
                EC_CDM_User__c           = user_cdmKey+'2'
            );
            insert testUser1;
            
            Case testCase = new Case(
                Type = EC_Constants.CASE_TYPE_ACCESS,
                Status = EC_Constants.STATUS_Pending,
                EC_User__c = testUser.Id,
                EC_PortalAccessRole__c = EC_Constants.Portal_Access_Role
            );
            insert testCase;
            PermissionSet ps1 = [SELECT Id FROM PermissionSet WHERE Name = 'EC_Viewprice'];
            insert new PermissionSetAssignment(AssigneeId = testUser.id, PermissionSetId = ps1.Id);

            PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'EC_BuyerSet'];
            insert new PermissionSetAssignment(AssigneeId = testUser.id, PermissionSetId = ps.Id);
            insert new PermissionSetAssignment(AssigneeId = testUser1.id, PermissionSetId = ps.Id);
            
            PermissionSet ps2 = [SELECT Id FROM PermissionSet WHERE Name = 'EC_PESTPI'];
            insert new PermissionSetAssignment(AssigneeId = testUser.id, PermissionSetId = ps2.Id);
            
            PermissionSet ps3 = [SELECT Id FROM PermissionSet WHERE Name = 'EC_DSR'];
            insert new PermissionSetAssignment(AssigneeId = testUser.id, PermissionSetId = ps3.Id);

        }
        PermissionSet ps1 = [SELECT Id FROM PermissionSet WHERE Name = 'EC_Viewprice'];
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'EC_BuyerSet'];
        PermissionSet ps2 = [SELECT Id FROM PermissionSet WHERE Name = 'EC_DSR'];
        PermissionSet ps3 = [SELECT Id FROM PermissionSet WHERE Name = 'EC_PESTPI'];

        Map<String,Id> permissionMap = new Map<String,Id>();
        permissionMap.put('EC_Viewprice',ps1.Id);
        permissionMap.put('EC_BuyerSet',ps.Id);
        permissionMap.put('EC_DSR',ps2.Id);
        permissionMap.put('EC_PESTPI',ps3.Id);
		List<String> userIds= new List<String>();
        userIds.add(user_cdmKey);
        userIds.add(user_cdmKey+'2');
        List<User> delUser = [Select Id from User where EC_CDM_User__c in :userIds];
        String action = 'DeleteAction';
        EC_Mulesoft_CDM_Staging__c usrPermissionDelte2 =  EC_TestData.createuserPermissionRecStaging(user_cdmKey,'ECOVWPRCE');
        usrPermissionDelte2.EC_Action__c = action;
        insert  usrPermissionDelte2;

        EC_Mulesoft_CDM_Staging__c usrPermissionDelte1 =  EC_TestData.createuserPermissionRecStaging(user_cdmKey,'ECOBYRUSR');
        usrPermissionDelte1.EC_Action__c = action;
        insert  usrPermissionDelte1;
        
        EC_Mulesoft_CDM_Staging__c usrPermissionDelte4 =  EC_TestData.createuserPermissionRecStaging(user_cdmKey,'ECOPESTPI');
        usrPermissionDelte4.EC_Action__c = action;
        insert  usrPermissionDelte4;
        
        EC_Mulesoft_CDM_Staging__c usrPermissionDelte3 =  EC_TestData.createuserPermissionRecStaging(user_cdmKey,'ECODSR');
        usrPermissionDelte3.EC_Action__c = action;
        insert  usrPermissionDelte3;
        
        EC_Mulesoft_CDM_Staging__c usrPermissionDelte7 =  EC_TestData.createuserPermissionRecStaging(user_cdmKey+'2','ECOBYRUSR');
        usrPermissionDelte7.EC_Action__c = action;
        insert  usrPermissionDelte7;

        List<EC_Mulesoft_CDM_Staging__c> stgList = new List<EC_Mulesoft_CDM_Staging__c>();
        stgList.add(usrPermissionDelte1);
        stgList.add(usrPermissionDelte2);
        stgList.add(usrPermissionDelte3);
        stgList.add(usrPermissionDelte4);
        stgList.add(usrPermissionDelte7);

        test.startTest();

        EC_StagingPermissionSetDelete batchObj = new EC_StagingPermissionSetDelete(permissionMap,delUser,stgList,stgList);
        Id batchId = Database.executeBatch(batchObj,5);
        test.stopTest();

    }


}