src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Category_1_4__c</fullName>
        <description>E101CRMXIF_SUBJECT_CODE</description>
        <label>Category 1 4</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_1_8__c</fullName>
        <description>E101CRMXIF_SUBJECT_CODEGROUP</description>
        <label>Category 1 8</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_2_4__c</fullName>
        <description>E101CRMXIF_SUBJECT_CODE</description>
        <label>Category 2 4</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_2_8__c</fullName>
        <description>E101CRMXIF_SUBJECT_CODEGROUP</description>
        <label>Category 2 8</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <description>E101CRMXIF_BUSTRANS-Process_Type</description>
        <label>Order Type</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <description>E101CRMXIF_PARTNER- PARTNER_NO
Record with Application Name: CRMXIF_PARTNER
Read the partner segment for partner function (PARTNER_FCT) ‘00000001’</description>
        <label>Ship To</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To__c</fullName>
        <description>E101CRMXIF_PARTNER- PARTNER_NO
Record with Application Name: CRMXIF_PARTNER
Read the partner segment for partner function (PARTNER_FCT) ‘00000001’.</description>
        <label>Sold To</label>
        <length>20</length>
        <type>Text</type>
    </fields>
	<fields>
		<fullName>Integration_Status__c</fullName>
		<description>Integration Status</description>
		<inlineHelpText>Integration Status</inlineHelpText>
		<label>Integration Status</label>
		<length>255</length>
		<type>Text</type>
    </fields>
</CustomObject>

src/objects/Global_Static__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings object to store general global static values</description>
    <fields>
        <fullName>value__c</fullName>
        <label>value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Global Static</label>
</CustomObject>

src/objects/Integration_Log__c.object
<CustomObject>
    <description>Object to hold integration related error logs but can be modified</description>
    <fields>
        <fullName>Identifier__c</fullName>
        <label>Identifier</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Component__c</fullName>
        <description>integration component - for eg Service Request, Order Submit etc</description>
        <inlineHelpText>integration component - for eg Service Request, Order Submit etc</inlineHelpText>
        <label>Integration Component</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Service Request</fullName>
                </value>
                <value>
                    <fullName>ServiceNow Case Create</fullName>
                </value>
                <value>
                    <fullName>Salesforce Case Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Integration_Type__c</fullName>
        <description>Integration from and To</description>
        <inlineHelpText>Integration from and To</inlineHelpText>
        <label>Integration Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SFDC_To_TIBCO</fullName>
                </value>
                <value>
                    <fullName>SFDC_To_MULESOFT(ServiceNow Case Creation)</fullName>
                </value>
                <value>
                    <fullName>MULESOFT_To_SFDC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Retry_Counter__c</fullName>
        <description>Retry Counter</description>
        <inlineHelpText>Retry Counter</inlineHelpText>
        <label>Retry Counter</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the integration call</description>
        <inlineHelpText>Status of the integration call</inlineHelpText>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>INTLOGS-{00000}</displayFormat>
        <label>Integration Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SAP_TIBCO_URL__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>TIBCO_End_Point_Url__c</fullName>
        <label>TIBCO End Point Url</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>SAP TIBCO URL</label>
</CustomObject>

force-app/main/default/classes/IntegrationsRetryBatchJobTest.cls
/********************************************************************************************************
* @Class Name    IntegrationsRetryBatchJobTest 
* @description   IntegrationsRetryBatchJobTest is used to test functionality of IntegrationsRetryBatchJob
* @Created By -    
* @Created On -  
* *********************************************************************************************************

 * Modification Log:  
 * ------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID             Description 
 * ------------------------------------------------------------------------------------------------------
 *                                     Initial version
 *********************************************************************************************************/ 


@isTest
public class IntegrationsRetryBatchJobTest {
    /***************************************************************************************************************************************
      Method Name : testBatchWithException
      Description : This method is used to test exception scenario
      Return type : void
     **************************************************************************************************************************************/
    static testMethod void testBatchWithException() {
        
        Global_Static__c gsSettings = new Global_Static__c();
        gsSettings.Name = 'Source_System';
        gsSettings.value__c = 'Connect'; 
        insert gsSettings;  

        SAP_TIBCO_URL__c settings = new SAP_TIBCO_URL__c();
        settings.Name = 'Destination URL';
        settings.TIBCO_End_Point_Url__c = '__https://local'; 
        insert settings;

        Case testCase = new Case();
        testCase.Origin = 'Portal';
        testCase.Order_Type__c = 'ZESR';
        testCase.Sold_To__c = '2345';
        testCase.Ship_To__c = '2312';
        testCase.Type = 'Request Service';
        testCase.SuppliedName = 'testname';
        testCase.SuppliedPhone = '2343454556';
        testCase.SuppliedEMail = 'test@test.com';
        
        testCase.Category_1_4__c = 'Test';
        testCase.Category_1_8__c = 'Firs';
        testCase.Category_2_4__c = 'test';
        testCase.Category_2_8__c = 'last';
        testCase.Subject = 'Pest Portal - Request Service Visit';
        testCase.Description = 'Test Case for Integrations Retry Batch';
        insert testCase; 
        testCase = [select Id, CaseNumber from Case where id =: testCase.id];
        System.debug('testCase.CaseNumber' + testCase.CaseNumber + '/ id: ' + testCase.id);
        Integration_Log__c intLog = new Integration_Log__c();
        intLog.Identifier__c = testCase.CaseNumber;
        intLog.Integration_Component__c = 'Service Request';
        intLog.Integration_Type__c = 'SFDC_To_TIBCO';
        intLog.Retry_Counter__c = 0;
        intLog.Status__c = 'false';
		insert intLog;

        Test.startTest();
        IntegrationsRetryBatchJob bJob = new IntegrationsRetryBatchJob();
        Database.executeBatch(bJob,1); 
        Test.stopTest();

        Case caseForTest = [Select id, integration_Status__c, caseNumber from Case where id = :testCase.id];
        system.assert( caseForTest.integration_Status__c != '');

    }    
}