src/objects/Case.object
<CustomObject>
	<fields>
        <fullName>Category__c</fullName>
        <description>Used to in routing in Ecolab project.</description>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SupportCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <description>Used to in routing in Ecolab project.</description>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>SupportSubCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Run_Assignment_Rule__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field used for community case routing in Ecolab Project.</description>
        <label>Run Assignment Rule</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
	<fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SupportCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SupportSubCategory</valueSetName>
        </valueSet>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

src/globalValueSets/SupportCategory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Checkout</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Login</fullName>
    </customValue>
    <customValue>
        <fullName>Orders</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <customValue>
        <fullName>Quicklist</fullName>
    </customValue>
    <customValue>
        <fullName>Self-Service Register</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>User</fullName>
    </customValue>
    <description>Common picklist values on case and Chat bot routing object for Ecolab Project.</description>
    <masterLabel>Category</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/SupportCaseCreateGuestControllerTest.cls
/* Class Name      :SupportCaseCreateGuestControllerTest
* Description      :Test class of Guest user Case Creation Form Controller
* Created By       :Graytitude Team
* Created On       :26-09-2020
*
* Modification Log:
* ----------------------------------------------------------------------------------------------------------------
* Developer                Date                Modification ID             Description
* ----------------------------------------------------------------------------------------------------------------
* Graytitude Team        26-09-2020                                        Test Class of Guest User Case Creation Form Controller
*/
@isTest
private class SupportCaseCreateGuestControllerTest{
    @isTest
    static void createAsGuest(){
        
        User customer = [select id, contactid from User where profile.name = 'Ecolab Profile' and isactive = true limit 1];
        
        knowledge__kav newArticle = new knowledge__kav(Title='How to checkout',summary='How to checkout',urlname='How-to-Checkout9876', category__c = 'Checkout', Sub_Category__c = 'How to checkout');
        insert newArticle;
        
        knowledge__kav viewArticle = SupportCaseCreateGuestController.getDefaultValues(newArticle.urlname);
        String caseId;
        Case objCase = SupportCaseCreateGuestControllerTest.createCase(viewArticle );
        system.RunAs(customer){
          caseId = SupportCaseCreateGuestController.saveCase(objCase);
        }
        System.AssertNotEquals(caseId, null);
        system.assertEquals(customer.Id, [select id, createdById from case where id=: caseId].createdById);
    }
    private static Case createCase(knowledge__kav viewArticle){
        return new Case(Category__c = viewArticle.Category__c,
                        Sub_Category__c = viewArticle.Sub_Category__c, Run_Assignment_Rule__c = TRUE);
    }    
}