src/objects/Case.object
<CustomObject>
	<fields>
        <fullName>Category__c</fullName>
        <description>Used to in routing in Ecolab project.</description>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SupportCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <description>Used to in routing in Ecolab project.</description>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>SupportSubCategory</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <businessProcess>Support</businessProcess>
        <!--<compactLayoutAssignment>Support_Compact_Layout</compactLayoutAssignment>-->
        <description>Used for Ecolab service cloud, for Sales Rep, Community user and Agents.</description>
        <label>Support</label>
    </recordTypes>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EC_CDM_Contact__c</fullName>
        <description>US-74958:Raghav:26/06/2019:This field will be used for mapping between CDM and contact object.</description>
        <externalId>true</externalId>
        <label>External Contact Key</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
	<fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SupportCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SupportSubCategory</valueSetName>
        </valueSet>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>EC_CDM_User__c</fullName>
        <description>US-74960:Raghav:26/06/2019:This field will be used for mapping between CDM and user object.</description>
        <externalId>true</externalId>
        <label>External UserKey</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/globalValueSets/SupportCategory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Checkout</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Login</fullName>
    </customValue>
    <customValue>
        <fullName>Orders</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <customValue>
        <fullName>Quicklist</fullName>
    </customValue>
    <customValue>
        <fullName>Self-Service Register</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>User</fullName>
    </customValue>
    <description>Common picklist values on case and Chat bot routing object for Ecolab Project.</description>
    <masterLabel>Category</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/SupportCaseCreateController.cls
/* Class Name      :SupportCaseCreateController
* Description      :Community Case Creation Form Controller
* Created By       :Graytitude Team
* Created On       :14-09-2020
*
* Modification Log:
* ----------------------------------------------------------------------------------------------------------------
* Developer                Date                Modification ID             Description
* ----------------------------------------------------------------------------------------------------------------
* Graytitude Team       14-09-2020                                         Community Case Creation Form Controller
*/
public without sharing class SupportCaseCreateController{
    
    //Method to get Contact Id
    //Contact Id for Community user or CDM Contact in case of Sales Rep user.
    @AuraEnabled
    public static Contact getContactId(Id userId){        
        try{
            contact objContact = new contact();
            if(Schema.sObjectType.User.isAccessible()){
                list<user> users = [select contactid, contact.Email, contact.Phone, EC_CDM_User__c from user where id=:userId];
                if(users[0].contactid == null){    
                    //It's for Sales Rep user because it's internal user. Through CDM User field match with CDM Contact.
                    if(users[0].EC_CDM_User__c!=null && Schema.sObjectType.Contact.isAccessible()){
                        list<contact> contacts  = [select id, Email, Phone from contact where EC_CDM_Contact__c=:users[0].EC_CDM_User__c];
                        objContact = contacts.isEmpty() ? new Contact() : contacts[0];
                    }                           
                }
                else{
                    objContact = new Contact(Id = users[0].contactId, Email = users[0].contact.Email, Phone = users[0].contact.Phone);
                }
            }
            return objContact;
        }catch(Exception e){ throw new AuraHandledException(e.getMessage()); }
    }
    
    //On Case form, populate "Account" dropdown to show all accounts which are related to either Customer's contact or Sales Rep's Contact.
    @AuraEnabled(cacheable=true)
    public static list<AccountContactRelation> getContactRelatedAccounts(Id contactId){
        list<AccountContactRelation> lstACR = new list<AccountContactRelation>();
        try{
            if(Schema.sObjectType.AccountContactRelation.isAccessible()){
                lstACR = [SELECT Id, AccountId, Account.Name, ContactId FROM AccountContactRelation where ContactId=:contactId];
            }
        }catch(Exception e){ throw new AuraHandledException(e.getMessage()); }
        return lstACR;
    }
    
    //Get record type of Case to set once we create a case record from community.
    @AuraEnabled
    public static Id getIssueRecordTypeId(){
        try{
            return Schema.SObjectType.Case.getRecordTypeInfosByName().get('Support').getRecordTypeId();
        }catch(Exception e){ throw new AuraHandledException(e.getMessage()); }
    }
    //Get category and sub category value of Knowledge record on which user click on contact support button.
    @AuraEnabled
    public static Knowledge__kav getDefaultValues(String articleUrl){
        try{
            Knowledge__kav artical = new Knowledge__kav();
            if(Schema.sObjectType.Knowledge__kav.isAccessible()){
                artical = [SELECT Title, UrlName, Id, Category__c, Sub_Category__c
                    FROM Knowledge__kav 
                    Where UrlName =: articleUrl];
            }
            return artical;
        }catch(Exception e){   throw new AuraHandledException(e.getMessage());  }        
    }
    //Create a case and share record if case is created as sales rep. Because case is private, so need to share with sales rep user.
    @AuraEnabled
    public static String saveCase(Case objCase){      
        try{
            if(Schema.sObjectType.Case.isCreateable()){
                Insert objCase; 
            }
            if(Schema.sObjectType.User.isAccessible()){
                List<User> currentUser = [Select Id from User Where Id = : userInfo.getUserId() AND ContactId = null];
                if(!currentUser.isEmpty()) {
                
                    CaseShare caseShr  = new CaseShare();
                    caseShr.CaseId = objCase.id;
                    caseShr.UserOrGroupId = userInfo.getUserId();
                    caseShr.CaseAccessLevel = 'Edit';
                    caseShr.RowCause = Schema.CaseShare.RowCause.Manual;
                    if(Schema.sObjectType.CaseShare.isCreateable()){
                        Insert caseShr;
                    }
                }      
            }  
            return objCase.id;   
        }catch(Exception e){ throw new AuraHandledException(e.getMessage());  }
    }
}