src/objects/Case.object
<CustomObject>
	<fields>
        <fullName>Category__c</fullName>
        <description>Used to in routing in Ecolab project.</description>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SupportCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <description>Used to in routing in Ecolab project.</description>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>SupportSubCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Run_Assignment_Rule__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field used for community case routing in Ecolab Project.</description>
        <label>Run Assignment Rule</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <businessProcess>Support</businessProcess>
        <!--<compactLayoutAssignment>Support_Compact_Layout</compactLayoutAssignment>-->
        <description>Used for Ecolab service cloud, for Sales Rep, Community user and Agents.</description>
        <label>Support</label>
    </recordTypes>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EC_CDM_Contact__c</fullName>
        <description>US-74958:Raghav:26/06/2019:This field will be used for mapping between CDM and contact object.</description>
        <externalId>true</externalId>
        <label>External Contact Key</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
	<fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SupportCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SupportSubCategory</valueSetName>
        </valueSet>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>EC_CDM_User__c</fullName>
        <description>US-74960:Raghav:26/06/2019:This field will be used for mapping between CDM and user object.</description>
        <externalId>true</externalId>
        <label>External UserKey</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/globalValueSets/SupportCategory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Checkout</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Login</fullName>
    </customValue>
    <customValue>
        <fullName>Orders</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <customValue>
        <fullName>Quicklist</fullName>
    </customValue>
    <customValue>
        <fullName>Self-Service Register</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>User</fullName>
    </customValue>
    <description>Common picklist values on case and Chat bot routing object for Ecolab Project.</description>
    <masterLabel>Category</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/SupportCaseCreateControllerTest.cls
/* Class Name      :SupportCaseCreateControllerTest
* Description      :Test class of Community Case Creation Form Controller
* Created By       :Graytitude Team
* Created On       :20-09-2020
*
* Modification Log:
* ----------------------------------------------------------------------------------------------------------------
* Developer                Date                Modification ID             Description
* ----------------------------------------------------------------------------------------------------------------
* Graytitude Team        20-09-2020                                        Test Class of Community Case Creation Form Controller
*/
@isTest
private class SupportCaseCreateControllerTest{
    static String lang = 'en_US';
    @isTest
    static void createAsCustomer(){
        SupportCaseCreateController.getIssueRecordTypeId();
        Blob b = Crypto.GenerateAESKey(128);
        String h = EncodingUtil.ConvertTohex(b);
        String uid = h.SubString(0,8);
        Id p = [select id from profile where name = 'Ecolab Customer Community Plus Users' limit 1].id;
        
        Account ac = new Account(name ='Grazitti') ;
        insert ac; 
        
        Contact conRec = new Contact(LastName ='testCon',AccountId = ac.Id,EC_CDM_Contact__c='testcontact');
        insert conRec;  
        
        User customer = new User(alias = 'test1234', email='test1234@noemail.com'+ uid,
                                 emailencodingkey='UTF-8', lastname='Testing', languagelocalekey=lang,contactid=conRec.id,
                                 localesidkey=lang , profileid = p, country='United States',IsActive =true,EC_CDM_User__c='testuser',
                                 timezonesidkey='America/Los_Angeles', username='tester@noemail.com'+ uid);
        
        insert customer;       
        Contact con = SupportCaseCreateController.getContactId(customer.Id);
        System.assertEquals(customer.contactid, con.id);
        SupportCaseCreateController.getContactRelatedAccounts(con.Id);
        
        knowledge__kav newArticle = new knowledge__kav(Title='How to checkout',summary='How to checkout',urlname='How-to-Checkout123', category__c = 'Checkout', Sub_Category__c = 'How to checkout');
        insert newArticle;
        
        knowledge__kav viewArticle = SupportCaseCreateController.getDefaultValues(newArticle.urlname);
        String caseId;
        Case objCase = SupportCaseCreateControllerTest.createCase(con.Id, ac.Id, viewArticle );
        system.RunAs(customer){
          caseId = SupportCaseCreateController.saveCase(objCase);
        }
        System.AssertNotEquals(caseId, null);
    }
    private static Case createCase(String contactId, String accId, knowledge__kav viewArticle){
        return new Case(recordtypeid = SupportCaseCreateController.getIssueRecordTypeId(),
                        origin = 'Portal Support', 
                        ContactId = contactId, accountid = accId, 
                        Category__c = viewArticle.Category__c,
                        Sub_Category__c = viewArticle.Sub_Category__c, Run_Assignment_Rule__c = TRUE);
    }    
    @isTest
    static void createAsSalesRep(){
        SupportCaseCreateController.getIssueRecordTypeId();
        Account ac = new Account(name ='Grazitti') ;
        insert ac; 
        Contact con = SupportCaseCreateController.getContactId(UserInfo.getUserId());
        list<AccountContactRelation> acrList = SupportCaseCreateController.getContactRelatedAccounts(con.id);
        system.assertEquals(acrList.size(), 0);
        
        knowledge__kav newArticle = new knowledge__kav(Title='Cannot Checkout Rush Order',summary='Cannot Checkout Rush Order',urlname='Cannot-Checkout-Rush-Order1', category__c = 'Checkout', Sub_Category__c = 'Cannot Checkout Rush Order');
        insert newArticle;
        
        knowledge__kav viewArticle = SupportCaseCreateController.getDefaultValues(newArticle.urlname);
        String caseId = SupportCaseCreateController.saveCase(SupportCaseCreateControllerTest.createCase(con.Id, ac.Id, viewArticle ));
        
        system.AssertEquals(caseId, [select id, caseid from CaseShare where caseId =: caseId limit 1].caseId);
        system.AssertEquals(UserInfo.getUserId(), [select id, caseid, UserOrGroupId from CaseShare where caseId =: caseId limit 1].UserOrGroupId);
        System.AssertNotEquals(caseId, null);
    }
    @isTest
    static void getContactId(){
        SupportCaseCreateController.getIssueRecordTypeId();
        Blob b = Crypto.GenerateAESKey(128);
        String h = EncodingUtil.ConvertTohex(b);
        String uid = h.SubString(0,8);
        Id p = [select id from profile where name like '%salesforce%' limit 1].id;
        
        Account ac = new Account(name ='Grazitti') ;
        insert ac; 
        
        Contact conRec = new Contact(LastName ='testCon',AccountId = ac.Id,EC_CDM_Contact__c='testcontact2');
        insert conRec;  
        
        User user = new User(alias = 'test123', email='test123@noemail.com'+ uid,
                             emailencodingkey='UTF-8', lastname='Testing', languagelocalekey=lang ,
                             localesidkey=lang , profileid = p, country='United States',IsActive =true,EC_CDM_User__c='testuser2',
                             timezonesidkey='America/Los_Angeles', username='tester@noemail.com'+ uid);
        
        insert user;
        Contact con = SupportCaseCreateController.getContactId(user.Id);
        SupportCaseCreateController.getContactRelatedAccounts(con.Id);
        System.AssertNotEquals(con, null);
    }
}