src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>EC_Request_Service_Type__c</fullName>
        <label>EC Request Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HEALTHCARE</fullName>
                </value>
                <value>
                    <fullName>INSTITUTIONAL</fullName>
                </value>
                <value>
                    <fullName>PEST ELIMINATION</fullName>
                </value>
                <value>
                    <fullName>ENERGY SERVICE</fullName>
                </value>
                <value>
                    <fullName>FOOD &amp; BEVERAGE</fullName>
                </value>
                <value>
                    <fullName>LIFE SCIENCES</fullName>
                </value>
                <value>
                    <fullName>TEXTILE CARE</fullName>
                </value>
                <value>
                    <fullName>WPS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>ccrz__ActiveCart__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When a new Cart is created, the cart is active by default. Whenever, we want to make anyother cart active, the current active cart should be deactivated</description>
        <label>Active Cart</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__AnonymousId__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Checks if the user is anonymous or not.
If true the user is anonymous or not logged in
if false he is logged in. Will be used in merging of an anonymous cart with a logged in users cart.</description>
        <label>Anonymous Id</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Contact of the User that this cart was created for.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CC Carts</relationshipLabel>
        <relationshipName>CC_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__EffectiveAccountID__c</fullName>
        <description>Holds the effective account for this cart.  This field will be utilized in implementations where a user can order for multiple accounts inclusive or exclusive of their own.  The effective account is used to control the entitlements, pricing, integrations etc that drive the site experience.</description>
        <inlineHelpText>This field will be utilized in implementations where a user can order for multiple accounts inclusive or exclusive of their own.  The effective account is used to control the entitlements, pricing, integrations etc that drive the site experience.</inlineHelpText>
        <label>Effective Account ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Portal_ESR_Category_Lookup__c.object
<CustomObject>
    <description>Contains the values used to complete a ESR submission. These match up with SAP values and is updated manually.</description>
    <label>Portal ESR Category Lookup</label>
    <nameField>
        <label>Portal ESR Category Lookup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal ESR Category Lookup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EC_ServiceRequestAssignmentRuleTest.cls
@isTest
private class EC_ServiceRequestAssignmentRuleTest {
    @isTest    
    private static void caseRulesTest () {

        
        case testingVar = new case();
        
        // testingVar.EC_Request_Service_Type__c = 'Request Service';
        testingVar.status = 'New';
        testingVar.Origin = 'Portal';
        testingVar.Type = 'Request Service';
        insert testingVar;
        EC_ServiceRequestAssignmentRule ruleRunning = new EC_ServiceRequestAssignmentRule();
        testingVar = ruleRunning.caseRules(testingVar);
        
        /* system.assertEquals (testingVar.OwnerId=queueItem.Queue.Id;); */
        system.assertnotequals(testingVar, null);
      
    }
    
    @testSetup
    static void getTestDataServiceRequest(){  
        EC_TestData.setupTestUser();
		User testUser = [SELECT Id, contactId FROM User WHERE LastName = 'TestUser'];      
        Account testAccount = EC_TestData.testAccountServiceRequest;
              	
        User testOwner = [SELECT TimeZoneSidKey, UserRoleId FROM User WHERE Id = :UserInfo.getUserId()];
        system.runAs(testOwner) {  
            EC_TestData.insertSettings();
            EC_TestData.insertGlobalStaticSettings();
            Test.setMock(WebServiceMock.class, new EC_CaseTextMyRepToSAPMockUp());
            Case caseRec = EC_TestData.insertCase();
            String base64Data = '' +'ABCDEFGHIJKLMNOPQRSTUVWXYZ' +'abcdefghijklmnopqrstuvwxyz'+'0123456789+/';
            String contentType = 'image/jpeg';
            EC_ServiceRequestHandler.saveChunk(caseRec.Id, 'test.png',base64Data,contentType);
            List<Portal_ESR_Category_Lookup__c> lookupdata = new List<Portal_ESR_Category_Lookup__c>();
            Portal_ESR_Category_Lookup__c record = EC_TestData.getRecord1();
            Portal_ESR_Category_Lookup__c record2 = EC_TestData.getRecord2();
            lookupdata.add(record);
            lookupdata.add(record2);
            insert lookupdata;
            EC_ServiceRequestHandler.addSAPFields(caseRec,'INSTITUTIONAL','PRICING');  
        }
        system.runAs(testUser){
            ccrz__E_Cart__c cart=new ccrz__E_Cart__c(ccrz__ActiveCart__c=TRUE,ccrz__EffectiveAccountID__c=testAccount.ID,ccrz__AnonymousId__c=false, ccrz__Contact__c=testUser.contactId);
            insert cart;
        }	
        EC_TestData.insertContentVersion();
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        List<ContentDocumentLink> cdLinkList  = new List<ContentDocumentLink>();
        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=testUser.contactId;
        contentlink.ShareType= 'V'; 
        contentlink.ContentDocumentId=documents[0].Id;
        contentlink.Visibility = 'AllUsers'; 
        cdLinkList.add(contentlink);
        insert cdLinkList;
    }
}