src/objects/ccrz__E_AccountGroup__c.object
<CustomObject>
    <description>This object is used to group multiple accounts together to provide pricing and/or entitlements.  An account group can have 1 or more accounts associated with it.  It also can have 1 or more pricelists (used for pricing and entitlements) associated.  This object then ties the accounts and entitlements/pricing together, ultimately controlling the product list and pricing that a given account can see within B2B Commerce.</description>
    <label>CC Account Group</label>
    <nameField>
        <label>Account Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Account Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_AccountGroupPriceList__c.object
<CustomObject>
    <description>Represents a mapping of Account Group to Pricelist.  This objects ties the two together, enabling the assignment and entitlement/pricing functionality.</description>
    <fields>
        <fullName>ccrz__AccountGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the account group</description>
        <label>Account Group</label>
        <referenceTo>ccrz__E_AccountGroup__c</referenceTo>
        <relationshipLabel>Account Group Price Lists</relationshipLabel>
        <relationshipName>E_AccountGroupPriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer available for the account group.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is available to the account group will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the pricelist</description>
        <label>Pricelist</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>Account Group Price Lists</relationshipLabel>
        <relationshipName>E_AccountGroupPriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this mapping record is active. This is the first date the mapping will be applied</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Account Group Price List</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Acct Group Pricelist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Account Group Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceList__c.object
<CustomObject>
    <description>Represents a grouping of products to control pricing and entitlements.  The B2B Commerce pricelist object controls both pricing and entitlements, but can be used just for the purposes of entitlements. A list needs to be created for each currency that needs to be represented, allowing for different entitlments and pricing based on the locale and currency.</description>
    <fields>
        <fullName>ccrz__CurrencyISOCode__c</fullName>
        <description>Required - The 3-character ISO currency code corresponding to this list. For example, USD</description>
        <label>Currency ISO Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer active.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is valid will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this pricelist record is active. This is the first date the pricing/entitlements will be applied</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceListItem__c.object
<CustomObject>
    <description>Represents an entry in the Pricelist.  Each pricelist object is made up of 1 or more pricelist item objects.  This item objects contain a reference to the product and hold a price value (0, in the case where only entitlements are being used).  The products referenced within these items will be displayed in search and product listings on the external site.</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The end date for the price list item.  The end date is the date at which the item will no longer be available.  For example if the end date is July 1, 2015 then the price list item is valid on June 30, 2015 but no longer valid on July 1, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Pricelist__c</fullName>
        <description>Required - The reference to the pricelist</description>
        <label>Pricelist</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>E_PriceListItems1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the product entry</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>E_PriceListItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this item record is active. This is the first date the item will be active</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Price List Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>PriceListItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date that this product will be available.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductIndexStatus__c</fullName>
        <description>Indicates the status of the associated Product Index records. Possible values are Current, Not Current and Pending. This field is primarily used by the Product Index batch process.</description>
        <inlineHelpText>Indicates the status of the associated Product Index records. Possible values are Current, Not Current and Pending. This field is primarily used by the Product Index batch process.</inlineHelpText>
        <label>Product Index Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductStatus__c</fullName>
        <description>The status of the product. In Creation - Newly created product, that still requires augmentation and is not visible on the site; Blocked - product has been blocked from being displayed on the site; Not Orderable - product can be viewed, but cannot be added to a cart or ordered; Released - fully availble product</description>
        <label>Product Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Not Orderable</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>In Creation</fullName>
                    <default>true</default>
                    <label>In Creation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The first date that this product will be available.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_ProductCategory__c.object
<CustomObject>
    <description>The Product Category is a link table which link product with category. It is a many-to-many relationship.</description>
    <fields>
        <fullName>ccrz__Category__c</fullName>
        <description>Reference to the Category</description>
        <label>Category</label>
        <referenceTo>ccrz__E_Category__c</referenceTo>
        <relationshipLabel>Product Categories</relationshipLabel>
        <relationshipName>Product_Categories</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date that this association of product to category is available</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <description>Product contained within the associated category. The same product can exist within multiple categories</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Product Categories</relationshipLabel>
        <relationshipName>Product_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The first date that this association of product to category is available</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Product Category</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ProductCatAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Product Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/EC_ccLogicCategoryGetTree.cls
/* Class Name    : EC_ccLogicCategoryGetTree 
 * Description      :Class to extend the Cloudcraze Logic Class ccLogicCategoryGetTree
 * Created By       :Ashish
 * Created On       :2019-Jun-10
 

 * Modification Log:
 * -----------------------------------------------------------------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID         Description
 * -----------------------------------------------------------------------------------------------------------------------------------------------------------------
 * Ashish                     2019-Jun-10        BC-74102     Created the class   
 *
 */
global virtual with sharing class EC_ccLogicCategoryGetTree extends ccrz.ccLogicCategoryGetTree{
    
    /***************************************************************************************************************************************
    Method Name : getTree
    Description : Returns the category tree by removing the empty categories
    Return type : Returns Map<String,Object>
    **************************************************************************************************************************************/
    global virtual override Map<String, Object> getTree(Map<String, Object> inputData) {
        ccrz.ccLog.log(System.LoggingLevel.DEBUG, 'EC_ccLogicCategoryGetTree:getTree:inputData', inputData);
        
        Map<String,Object> superRet = new Map<String,Object>();
        if(!Test.isRunningTest()) {
            superRet = super.getTree(inputData);
        }else{
            superRet = inputData;
        }    
        ccrz.ccLog.log(System.LoggingLevel.DEBUG, 'EC_ccLogicCategoryGetTree:getTree:superRet', superRet);
        List<Object> theTree = (List<Object>)superRet.get(ccrz.ccApiCategory.CATEGORYTREE);
        ccrz.ccLog.log(System.LoggingLevel.DEBUG, 'eComm_ccLogicCat:theTree', theTree);
       
        List<Object> theTreeDup = new List<Object>();        
        
        Set<String> catIdString = new Set<String>();
        

        
        ccrz.cclog.log('catIdStringViraj'+catIdString);
        
        Set<String> priceIdsIdsSet = new Set<String>();
        Set<String> prodIdsSet = new Set<String>();
        String accGroupId;
        
        /* 
        if(!Test.IsRunningTest()){
            ccrz__E_AccountGroup__c accGroupOb = ccrz.cc_CallContext.currAccountGroup;
            accGroupId=accGroupOb.id;
        }else{
            accGroupId = ccrz.cc_CallContext.effAccountId;
        }

       
        List<ccrz__E_AccountGroupPriceList__c> accGroupPriceList = [SELECT ccrz__AccountGroup__c,ccrz__Pricelist__c,ccrz__Pricelist__r.ccrz__CurrencyISOCode__c from ccrz__E_AccountGroupPriceList__c where ccrz__AccountGroup__c = :accGroupId and ccrz__Pricelist__r.ccrz__CurrencyISOCode__c=:ccrz.cc_CallContext.userCurrency];
        
        for(ccrz__E_AccountGroupPriceList__c accGroup : accGroupPriceList){
            
            priceIdsIdsSet.add(accGroup.ccrz__Pricelist__c);
            
        }
        */
        
        String prodStatus = Label.EC_ProductStatusFilter;
        String[] prodSts = prodStatus.split(';');
        Set<String> setProdStatus = new Set<String>(prodSts);
		Date today = Date.today();        
        for(ccrz__E_AccountGroupPriceList__c accGroup : [SELECT ccrz__AccountGroup__c,ccrz__Pricelist__c,ccrz__Pricelist__r.ccrz__CurrencyISOCode__c 
                                                         from ccrz__E_AccountGroupPriceList__c 
                                                         where ccrz__AccountGroup__c IN (Select ccrz__E_AccountGroup__c from Account Where Id=:ccrz.cc_CallContext.effAccountId)
                                                         AND ccrz__Pricelist__r.ccrz__CurrencyISOCode__c=:ccrz.cc_CallContext.userCurrency
                                                         AND ccrz__Pricelist__r.ccrz__StartDate__c <= :today
                                                         AND ccrz__Pricelist__r.ccrz__EndDate__c >= : today
                                                         AND ccrz__StartDate__c <= :today
                                                         AND ccrz__EndDate__c >= : today]){            
                                                             priceIdsIdsSet.add(accGroup.ccrz__Pricelist__c);            
                                                         }
        
        List<ccrz__E_PriceListItem__c> entPriceListItems = [SELECT ccrz__Product__c,ccrz__Pricelist__c from ccrz__E_PriceListItem__c 
                                                            where ccrz__Pricelist__c in :priceIdsIdsSet 
                                                            AND ccrz__StartDate__c <= :today
                                      						AND ccrz__EndDate__c >= : today
                                                            AND ccrz__Product__r.ccrz__StartDate__c <= :today 
                                                            AND ccrz__Product__r.ccrz__EndDate__c >= :today 
                                                            AND ccrz__Product__r.ccrz__ProductStatus__c in :setProdStatus
                                                            AND ccrz__Product__r.ccrz__ProductIndexStatus__c != :Label.EC_ProductIndexPending Limit 50000];
        
        for(ccrz__E_PriceListItem__c PIOb : entPriceListItems){
            
            prodIdsSet.add(PIOb.ccrz__Product__c);
            
        }
        
        List<AggregateResult> prodCatList = [SELECT ccrz__Category__c cat from ccrz__E_ProductCategory__c where ccrz__Product__c in :prodIdsSet group by ccrz__Category__c];
        
        Set<String> catIdsSet = new Set<String>();
        
        for(AggregateResult prodCatOb : prodCatList){
            
            catIdsSet.add(String.valueOf(prodCatOb.get('cat')));
            
        }
        
        List<Object> childTree = new List<Object>();
        List<Object> subChildTree = new List<Object>();
        
        Map<String,Object> parentcatElem = new Map<String,Object>();
        Map<String,Object> childCatElem = new Map<String,Object>();
        Map<String,Object> finalChildCatElem = new Map<String,Object>();
        
        theTreeDup = getChildRecordId(theTree,catIdsSet);
       
        ccrz.ccLog.log(System.LoggingLevel.DEBUG, 'eComm_ccLogicCat:theTreeDup', theTreeDup);
        superRet.put(ccrz.ccApiCategory.CATEGORYTREE,(Object)theTreeDup);
        
        return superRet;
        
    }
    /***************************************************************************************************************************************
    Method Name : getChildRecordId
    Description : Recursive function to remove the empty categories
    Return type : List<Object>
    **************************************************************************************************************************************/
    global List<Object> getChildRecordId(List<Object> theTree,Set<String> catIdsSet){
        try{
            Map<String,Object> parentcatElem; 
            parentcatElem = new Map<String,Object>();            
            List<Integer> indexToRemove = new List<Integer>();
            if(theTree != null && theTree.size()>0){
                Integer index = 0;
                for(Object treeVal:theTree){                    
                    parentcatElem = (Map<String,Object>)treeVal;
                    if(parentcatElem.containsKey('children') && parentcatElem.get('children') != null && ((List<Object>)parentcatElem.get('children')).size()>0 ){              
                        List<Object> catElem = (List<Object>)parentcatElem.get('children');          
                        getChildRecordId(catElem,catIdsSet);
                        if(catElem.size()==0 && !catIdsSet.contains((String)parentcatElem.get('sfid'))){
                            indexToRemove.add(index);
                        }
                    }else{
                        Map<String,Object> finalChildCatElem = new Map<String,Object>();
                        finalChildCatElem = (Map<String,Object>)parentcatElem;     
                        if(!catIdsSet.contains((String)finalChildCatElem.get('sfid'))){
                            indexToRemove.add(index);
                        }                         
                    }
                    index++;                    
                }
                if(!indexToRemove.isEmpty()){
                    for(integer i=indexToRemove.size()-1;i>=0;i--){
                        theTree.remove(indexToRemove.get(i));
                    }           
                }
                indexToRemove.clear();
            }          
            
        }catch(Exception ex){
            ccrz.ccLog.log(System.LoggingLevel.DEBUG, 'exception eComm_ccLogicCat:theTreeDup', ex.getMessage());
        }
        
        
        return theTree;
    }
  
}