src/objects/ccrz__E_Category__c.object
<CustomObject>
    <description>Product Category detail record</description>
    <fields>
        <fullName>ccrz__CategoryID__c</fullName>
        <description>External Id used for mapping the category to an externally defined entity</description>
        <externalId>true</externalId>
        <label>Category ID</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The end date for which this category is active. After this date the category will no longer be displayed.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this category is active. This is the first date the category will be displayed.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EC_SalesRep_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EC SalesRep User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/EC_OutageFlag__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>EC_isCommunityActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isCommunityActive</label>
        <type>Checkbox</type>
    </fields>
    <label>EC_OutageFlag</label>
</CustomObject>

force-app/main/default/classes/EC_HeaderControllerTest.cls
/* Class Name    : EC_HeaderControllerTest
 * Description      Test Class to cover EC_HeaderController
 * Created By       :Viraj 
 * Created On       :2019-Aug-29
 

 * Modification Log:
 * -----------------------------------------------------------------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID         Description
 * -----------------------------------------------------------------------------------------------------------------------------------------------------------------
 * Viraj                 2019-Aug-29              BC-76699        Created the class   
 *
 */
@isTest
public class EC_HeaderControllerTest{
    /***************************************************************************************************************************************
    Method Name : headerTest
    Description : Test method to cover multiple controller classes
    Return type : void
    *************************************************************************************************************************************/
    @isTest 
    static void headerTest(){
        
        
        User thisUser = [SELECT Id,ContactId,Contact.AccountId  FROM User WHERE Id = :UserInfo.getUserId()];
        
        List<PermissionSet> permSetList = [Select Id,Name from PermissionSet where Name = 'EC_BuyerSet'];
        PermissionSetAssignment permSet = new PermissionSetAssignment ();
        permSet.AssigneeId = thisUser.id;
        if(permSetList.size()>0){
            permSet.PermissionSetId = permSetList[0].id;
            insert permSet;
        }
        EC_CacheWrapper usrInfo;
        usrInfo = new EC_CacheWrapper();
        //usrInfo.lstPermisssionSet = permissionSetList;
        EC_CacheHelper.updateCache();
        //Cache.Session.put('local.UserCache.UserInfo1',usrInfo);
        
        system.runas(thisUser){
            
            
            Test.startTest();
            
            ccrz.cc_CallContext.effAccountId = EC_TestData.testAccount.id;
            
            EC_HeaderController classOb = new EC_HeaderController();
            EC_ProductDetailController classOb2  = new EC_ProductDetailController();
            EC_ProductListController classOb3 = new EC_ProductListController();
            EC_MiniCartController classOb4 = new EC_MiniCartController();
            EC_QuickOrderController classOb5 = new EC_QuickOrderController();
            EC_SuggestedProducts classOb6 = new EC_SuggestedProducts();
            ccrz__E_Category__c testAllRoot = new ccrz__E_Category__c(
                    Name                = 'Products',
                    ccrz__CategoryID__c = '0',
                    ccrz__StartDate__c  = Date.today().addDays(-1),
                    ccrz__EndDate__c    = Date.today().addDays(1)
            );
            insert testAllRoot;
            EC_QuickListController  classOb7 = new EC_QuickListController();
            EC_CartDetailController classOb8 = new EC_CartDetailController();
            
            System.assertNotEquals(classOb ,null);
              
            Test.stopTest();
            
        }
    }
    /***************************************************************************************************************************************
    Method Name : headerTest2
    Description : Test method to cover multiple controller classes
    Return type : void
    *************************************************************************************************************************************/
    @isTest 
    static void headerTest2(){
        User thisUser = [SELECT Id  FROM User WHERE Id = :UserInfo.getUserId()];
        
        EC_OutageFlag__c outFlag  = new EC_OutageFlag__c();
        outFlag.EC_isCommunityActive__c = true;
        outFlag.Name ='CommunityActive';
        insert outFlag;
        
        EC_TestData.setupTestUser();
        EC_TestData.setupcatalog();
        User TestUser = [SELECT id,ContactId,Contact.AccountId,LastName  from User where LastName = 'TestUser' and Alias = 'cctest'];
        
        Contact currCon = TestUser.Contact;
        String accId = currCon.AccountId;
        currCon.AccountId = EC_TestData.testAccountShipTo.id;
        currCon.EC_SalesRep_User__c = UserInfo.getUserId();
        update currCon;
        
        system.runas(TestUser){
            
            EC_CacheWrapper usrInfo  ;
            usrInfo = new EC_CacheWrapper();
            //usrInfo.lstPermisssionSet = permissionSetList;
            EC_CacheHelper.updateCache();
            //Cache.Session.put('local.UserCache.UserInfo1',usrInfo);
        
            Test.startTest();
            
            ccrz.cc_CallContext.effAccountId = currCon.AccountId;
            
            EC_HeaderController classOb = new EC_HeaderController();
             EC_CartDetailController classOb8 = new EC_CartDetailController();
            System.assertNotEquals(classOb ,null);
              
            Test.stopTest();
            
        }
    }
}