src/objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>ccrz__CartType__c</fullName>
        <description>Cart type &quot;WishList&quot; can be used to keep track of items users want.</description>
        <label>Cart Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Read-Only WishList</fullName>
                </value>
                <value>
                    <fullName>WishList</fullName>
                </value>
                <value>
                    <fullName>Cart</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__EncryptedId__c</fullName>
        <description>Semi-random UUID used to refer to the order in URLs.</description>
        <label>Encrypted Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within B2B Commerce</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EC_QuickListControllerTest.cls
/* Class Name    : EC_QuickListControllerTest
 * Description      Test Class to cover EC_QuickListController
 * Created By       :Venkatesh
 * Created On       :2020-Sep-01
 

 * Modification Log:
 * -----------------------------------------------------------------------------
 * Developer                Date            Modification ID         Description
 * -----------------------------------------------------------------------------
 * Venkatesh            2020-Sep-01                           Created the class   
 *
 */
@isTest
public class EC_QuickListControllerTest{
    /***************************************************************************************************************************************
  Method Name : addToCartItemsTest
  Description : Test method to cover addToCartItems method
  Return type : void
 *************************************************************************************************************************************/
    public static testMethod void addToCartItemsTest(){
         
        /** creating test data for EC_QLProductWrapper **/
        User thisUserAdmin = [SELECT ID FROM User WHERE ID =: UserInfo.getUserId() LIMIT 1]; 
        System.runas(thisUserAdmin){
            EC_TestData.setupTestUser();
            EC_TestData.setupCatalog();
        }
        User thisUser = [SELECT Id FROM User WHERE LastName = 'TestUser' LIMIT 1];    
        System.runas(thisUser){
            /** Test Start Here **/
            Test.startTest();
            ccrz__E_Product__c product = [SELECT ccrz__SKU__c, Name FROM ccrz__E_Product__c LIMIT 1];
            List <EC_QLProductWrapper> listAddToCartProducts = new List<EC_QLProductWrapper>(); 
            EC_QLProductWrapper suggestedProductWarpper = new EC_QLProductWrapper();
            suggestedProductWarpper.sku = product.ccrz__SKU__c;
            suggestedProductWarpper.quantity = 2;
            listAddToCartProducts.add(suggestedProductWarpper);
            
            ccrz__E_Cart__c cart = EC_TestData.createCart();
			cart.ccrz__CartType__c = 'Wishlist';
			update cart;
            
            ccrz__E_Cart__c ocart = [Select ccrz__EncryptedId__c from ccrz__E_Cart__c where id=:cart.id limit 1];
            String encryptedID = ocart.ccrz__EncryptedId__c;
            ccrz.cc_RemoteActionContext rac = new ccrz.cc_RemoteActionContext();
            new EC_QuickListController();
            EC_QuickListController.addToCartItems(rac,listAddToCartProducts,encryptedID);
            EC_QuickListController.getWLCount(rac,'USD');
            System.assertNotEquals(listAddToCartProducts,null);
            Test.stopTest();  
            /** Test Stop Here **/
        }          
    }
}