src/objects/ccrz__E_ContactAddr__c.object
<CustomObject>
    <description>Used to store address information.  Associated with Carts, Orders, Invoices, Subscriptions, Payments, etc.</description>
    <fields>
        <fullName>ccrz__CompanyName__c</fullName>
        <description>Company name associated with this address.</description>
        <label>Company Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CC Contact Address</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Contact Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Contact Addresss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_OrderItem__c.object
<CustomObject>
    <description>The E_OrderItem__c object contains the line level detail of placed orders.</description>
    <fields>
        <fullName>Tank_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tank Detail</label>
        <referenceTo>Tank_Detail__c</referenceTo>
        <relationshipLabel>CC Order Items</relationshipLabel>
        <relationshipName>CC_Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unloading_Point__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unloading Point</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipLabel>CC Order Items</relationshipLabel>
        <relationshipName>CC_Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Order Items (ProductID)</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Arrangement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To stamp billing arrangement on order item</description>
        <label>Billing Arrangement</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>CC Order Items</relationshipLabel>
        <relationshipName>CC_Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Order Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>OrderItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceList__c.object
<CustomObject>
    <description>Represents a grouping of products to control pricing and entitlements.  The B2B Commerce pricelist object controls both pricing and entitlements, but can be used just for the purposes of entitlements. A list needs to be created for each currency that needs to be represented, allowing for different entitlments and pricing based on the locale and currency.</description>
    <fields>
        <fullName>BA_Number__c</fullName>
        <description>To store BA number</description>
        <label>BA Number</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <label>CC Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within B2B Commerce</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EC_SplitOrderHelper.cls
public class EC_SplitOrderHelper {
    private EC_SplitOrderHelper() { }
    public static void addOrderItemToMap_V2(ccrz__E_OrderItem__c orderItem, Map<String,List<ccrz__E_OrderItem__c>> BA_ULOrderItemMap,String BANumberValue, String unloadingPointValue,  Boolean isBulk ){
        String BANumber = createBANumber(orderItem,BANumberValue);
        String unloadingPoint = createUnloadingPoint(orderItem,unloadingPointValue,isBulk);
        String BAULMapKey = '';
        system.debug(BANumber);
        system.debug(unloadingPoint);
        BAULMapKey = BANumber + '_' + unloadingPoint;
        processBAULMap(BA_ULOrderItemMap,BAULMapKey,orderItem);
    }
    
    public static String createBANumber(ccrz__E_OrderItem__c orderItem,String BANumber){
        return BANumber == null ? orderItem.Billing_Arrangement__r.BA_Number__c == null ? 'Ship_and_Bill'  : orderItem.Billing_Arrangement__r.BA_Number__c : BANumber;
        //return BANumber != null ? BANumber : orderItem.Billing_Arrangement__r.BA_Number__c !=null
        // ? orderItem.Billing_Arrangement__r.BA_Number__c : 'Ship_and_Bill';
    }
    public static boolean checkIsBulk(ccrz__E_OrderItem__c orderItem){
       return orderItem.Tank_Number__c == null ? false: true;
    }
    public static String createUnloadingPoint(ccrz__E_OrderItem__c orderItem,String unloadingPoint,Boolean isBulk){
        String unloadingPointnew = unloadingPoint == null ? orderItem.Unloading_Point__r.ccrz__CompanyName__c == null ? '' : orderItem.Unloading_Point__r.ccrz__CompanyName__c : unloadingPoint ;
        //String unloadingPointnew = unloadingPoint != null ? unloadingPoint: orderItem.Unloading_Point__r.ccrz__CompanyName__c != null
        // ? orderItem.Unloading_Point__r.ccrz__CompanyName__c : '';
        unloadingPointnew = isBulk ? 'bulk' : unloadingPointnew;
        return unloadingPointnew;
    }
    
    public static void updateBAULOrderItemMap( Map<String,List<ccrz__E_OrderItem__c>> BA_ULOrderItemMap,String newBAULMapKey,ccrz__E_OrderItem__c orderItem){
        
        if(BA_ULOrderItemMap.containsKey(newBAULMapKey)){
            BA_ULOrderItemMap.get(newBAULMapKey).add(orderItem);
            
        }else{
            BA_ULOrderItemMap.put(newBAULMapKey, new List<ccrz__E_OrderItem__c>{orderItem});
        }
    }
    
    public static void processBAULMap(Map<String,List<ccrz__E_OrderItem__c>> BA_ULOrderItemMap,String BAULMapKey,ccrz__E_OrderItem__c orderItem){
        if(BA_ULOrderItemMap.containsKey(BAULMapKey)){
            processBAULMapforDuplicates(BA_ULOrderItemMap,BAULMapKey,orderItem);
             
        }else{
            BA_ULOrderItemMap.put(BAULMapKey, new List<ccrz__E_OrderItem__c>{orderItem});  
        }
    }
    
    public static void processBAULMapforDuplicates(Map<String,List<ccrz__E_OrderItem__c>> BA_ULOrderItemMap,String BAULMapKey,ccrz__E_OrderItem__c orderItem){
        String newBAULMapKey = BAULMapKey;

        Boolean skuAlreadyPresentInList = false;
        for(String BAULMapKeyIterate : BA_ULOrderItemMap.keySet()){
			system.debug('BAULMapKeyIterate :: '+ BAULMapKeyIterate);
            if(BAULMapKeyIterate.contains(BAULMapKey)){
                for(ccrz__E_OrderItem__c orderlineItem : BA_ULOrderItemMap.get(BAULMapKeyIterate)){
                    if(orderlineItem.ccrz__Product__r.ccrz__SKU__c == orderItem.ccrz__Product__r.ccrz__SKU__c && !BAULMapKey.startsWithIgnoreCase('FBA') && !BAULMapKey.startsWithIgnoreCase('USR') && !BAULMapKey.startsWithIgnoreCase('Ship_and_Bill')){
                        skuAlreadyPresentInList = true;
                        newBAULMapKey = BAULMapKeyIterate + orderlineItem.id;
                        system.debug('newBAULMapKey :: '+ newBAULMapKey);
                        break;
                    }else{
                        skuAlreadyPresentInList = false;
                        newBAULMapKey = BAULMapKeyIterate;
                        continue;
                    }
                }
                if(!skuAlreadyPresentInList){
                    system.debug('skuAlreadyPresentInList false');
                    break;
                }
            }
        }
        system.debug('newBAULMapKey '+ newBAULMapKey );
        updateBAULOrderItemMap(BA_ULOrderItemMap,newBAULMapKey,orderItem);
    }
}