src/objects/ccrz__E_PriceList__c.object
<CustomObject>
    <description>Represents a grouping of products to control pricing and entitlements.  The B2B Commerce pricelist object controls both pricing and entitlements, but can be used just for the purposes of entitlements. A list needs to be created for each currency that needs to be represented, allowing for different entitlments and pricing based on the locale and currency.</description>
    <fields>
        <fullName>ccrz__PricelistId__c</fullName>
        <description>External reference id for this entry</description>
        <externalId>true</externalId>
        <label>Pricelist Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this pricelist record is active. This is the first date the pricing/entitlements will be applied</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceListItem__c.object
<CustomObject>
    <description>Represents an entry in the Pricelist.  Each pricelist object is made up of 1 or more pricelist item objects.  This item objects contain a reference to the product and hold a price value (0, in the case where only entitlements are being used).  The products referenced within these items will be displayed in search and product listings on the external site.</description>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>Holds the price for the item. If pricing is not being utilized, fill in a default value, such as 0.</description>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Pricelist__c</fullName>
        <description>Required - The reference to the pricelist</description>
        <label>Pricelist</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>E_PriceListItems1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the product entry</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>E_PriceListItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this item record is active. This is the first date the item will be active</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Price List Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>PriceListItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__ProductStatus__c</fullName>
        <description>The status of the product. In Creation - Newly created product, that still requires augmentation and is not visible on the site; Blocked - product has been blocked from being displayed on the site; Not Orderable - product can be viewed, but cannot be added to a cart or ordered; Released - fully availble product</description>
        <label>Product Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Not Orderable</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>In Creation</fullName>
                    <default>true</default>
                    <label>In Creation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within B2B Commerce</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The first date that this product will be available.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_ProductIndexBatchStatus__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>EC_Add_Product_to_Master_Pricelist_Batch__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>checkbox to enable/disable Pricelist Inactivation Batch</inlineHelpText>
        <label>Add Product to Master Pricelist Batch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EC_Product_Index_Switch__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Product Index Switch</label>
        <type>Checkbox</type>
    </fields>
    <label>Product Index Batch Status</label>
</CustomObject>

force-app/main/default/classes/EC_AddProductToMasterPricelist.cls
/********************************************************************************************************
* @Class Name    EC_AddProductToMasterPricelist 
* @description   EC_AddProductToMasterPricelist is used to master pricelist for new products
* @Created By -  Ravindra Singh  
* @Created On -  2019-09-10
* *********************************************************************************************************

 * Modification Log:  
 * ------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID             Description 
 * ------------------------------------------------------------------------------------------------------
 * Ravindra               2019-09-10                                   Initial version
 *********************************************************************************************************/ 

global with sharing class EC_AddProductToMasterPricelist implements Database.Batchable<sObject>, Database.Stateful {
    
    EC_ProductIndexBatchStatus__c indexBatchCS  = EC_ProductIndexBatchStatus__c.getOrgDefaults();
    
     /***************************************************************************************************************************************
      Method Name : start
      Description : start method is used to query the records to be processed in the batch
      Return type : Database.QueryLocator
     **************************************************************************************************************************************/
     
    global Database.QueryLocator start(Database.BatchableContext BC) {
       String productList = 'Select ID,ccrz__SKU__c FROM ccrz__E_Product__c Where ccrz__ProductStatus__c!= \'In Creation\' AND ID NOT IN ( Select ccrz__Product__c from ccrz__E_PriceListItem__c WHERE ccrz__PriceList__r.Name =\'AllProducts_PL\')';
      return Database.getQueryLocator(productList);
    }
    
    /***************************************************************************************************************************************
      Method Name : execute
      Description : execute method is used to create pricelist for the given products
      Return type : void
     **************************************************************************************************************************************/
           
    global void execute(Database.BatchableContext BC, List<ccrz__E_Product__c> scope) {
              
        if(indexBatchCS.EC_Add_Product_to_Master_Pricelist_Batch__c == true){       
            List<ccrz__E_PriceListItem__c> pliList = new List<ccrz__E_PriceListItem__c>();
            List<ccrz__E_PriceList__c> pricelist = [Select id from ccrz__E_PriceList__c where ccrz__PricelistId__c = 'AllProducts_PL' limit 1]; 
            try{
                for(ccrz__E_Product__c prod : scope)
                {
                    ccrz__E_PriceListItem__c pli = new ccrz__E_PriceListItem__c();
                    pli.ccrz__Product__c =  prod.id;
                    pli.ccrz__Price__c = 0.0;
                    pli.ccrz__Pricelist__c = pricelist[0].id;
                    pli.ccrz__StartDate__c = System.today()-10;
                    pliList.add(pli);
                }
            if(pliList.size()>0){   
                insert pliList;
            }
           }
          catch(Exception ex){
                    system.debug('Exception ex ' + ex.getMessage()); 
            }       
        }
        
    }
    
     /***************************************************************************************************************************************
      Method Name : finish
      Description : finish method is used to trigger product index job
      Return type : void
     **************************************************************************************************************************************/
          
    global void finish(Database.BatchableContext BC){
        
         if(indexBatchCS.EC_Product_Index_Switch__c == true){
            
            DateTime now = System.now().addMinutes(1);
            String dayVal = String.valueOf(now.day());
            String monthVal = String.valueOf(now.month());
            String hourVal = String.valueOf(now.hour());
            String minuteVal = String.valueOf(now.minute());
            String secondVal = String.valueOf(now.second());
            String yearVal = String.valueOf(now.year());
            String jobName = 'Product Index Job '+secondVal+minuteVal+hourVal+dayVal+monthVal+yearVal;
            String strSchedule = '0 ' + minuteVal + ' ' + hourVal + ' ' + dayVal + ' ' + monthVal + ' ?' + ' ' + yearVal;
            System.Schedule(jobName, strSchedule, new EC_TriggerProductIndexSchedulable());
            
         
         }
    }

}