src/objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent order, which originally submitted the subscription for this order, if applicable</description>
        <inlineHelpText>Parent order, which originally submitted the subscription for this order, if applicable</inlineHelpText>
        <label>Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Children Orders</relationshipLabel>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__RequestDate__c</fullName>
        <description>Request date captured during the checkout process.</description>
        <label>Request Date</label>
        <type>Date</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_OrderItem__c.object
<CustomObject>
    <description>The E_OrderItem__c object contains the line level detail of placed orders.</description>
    <fields>
        <fullName>ccrz__Comments__c</fullName>
        <description>Cart line comments as applied to this item.</description>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__OrderLineType__c</fullName>
        <description>Either Major or Minor. Minor if this line item is part of a kit or bundle, otherwise Major.</description>
        <label>Order Line Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Major</fullName>
                </value>
                <value>
                    <fullName>Minor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <description>The order that this order line is a part of.</description>
        <label>Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>The price of the product at the time the item was ordered.</description>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Order Items (ProductID)</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Quantity__c</fullName>
        <description>The number of items ordered for this line.</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__RequestDate__c</fullName>
        <description>The request date for this line item. This will be the same value as at the order header.</description>
        <label>Request Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__SubAmount__c</fullName>
        <description>The sub-total amount for the order. This will be calculated as price * quantity - coupon adjustments during order placement.</description>
        <label>Sub Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>CC Order Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>OrderItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EC_OrderItemTriggerHandlerTest.cls
//EC_OrderItemTriggerHandlerTest
//This is the test class to test the EC_OrderItemTriggerHandler class
//----------------------------------------------------------------------------------------------------------------------
// Author           Date              Description
//-------------------------------------------------------------------------------------------------------------------
// Shruti Sinha     5th Aug, 2019   to concatenate the name of the product on OrderItem 
//

@isTest
public class EC_OrderItemTriggerHandlerTest {
 /***************************************************************************************************************************************
      Method Name :  orderUpdateTest
      Description : to test the orderUpdate Method Of EC_OrderItemTriggerHandler
      Return type : void
      Author      :Shruti Sinha
*************************************************************************************************************************************/
   
    public static testmethod void orderItemTriggerTest(){
        
        EC_TestData.setupTestUser();
        User thisUser = [SELECT Id FROM User WHERE LastName = 'TestUser'];
        System.runAs(thisUser){
             EC_TestData.setupCatalog();
             EC_TestData.createOrders(1);
             List<ccrz__E_Order__c> order = [Select Id from ccrz__E_Order__c LIMIT 1];
            List<ccrz__E_Product__c> products = [Select Id from ccrz__E_Product__c limit 1];
           
            
            //Creating Order Item 
             List<ccrz__E_OrderItem__c> testOrderItems = new List<ccrz__E_OrderItem__c>();
             ccrz__E_OrderItem__c fstOrdItem = new ccrz__E_OrderItem__c();
             fstOrdItem.ccrz__Order__c= order[0].Id;
             fstOrdItem.ccrz__Price__c = 50 ;
             fstOrdItem.ccrz__Quantity__c = 2 ;
             fstOrdItem.ccrz__Product__c = products[0].Id;
             fstOrdItem.ccrz__Comments__c = 'test';
             fstOrdItem.ccrz__OrderLineType__c = 'Minor' ;
             fstOrdItem.ccrz__SubAmount__c =30;
              fstOrdItem.ccrz__RequestDate__c = system.today();
            ccrz__E_OrderItem__c SecOrdItem = new ccrz__E_OrderItem__c();
             SecOrdItem.ccrz__Order__c= order[0].Id;
             SecOrdItem.ccrz__Price__c = 50 ;
             SecOrdItem.ccrz__Quantity__c = 2 ;
             SecOrdItem.ccrz__Product__c = products[0].Id;
             SecOrdItem.ccrz__Comments__c = 'test';
             SecOrdItem.ccrz__OrderLineType__c = 'Minor';
             SecOrdItem.ccrz__SubAmount__c = 20;
             SecOrdItem.ccrz__RequestDate__c = system.today();
             testOrderItems.add(fstOrdItem);
            testOrderItems.add(SecOrdItem);
            test.startTest();
                 insert testOrderItems;
                         
            test.stopTest();
            
        }
        
}
    
  
}