src/objects/ccrz__E_AccountGroupPriceList__c.object
<CustomObject>
    <description>Represents a mapping of Account Group to Pricelist.  This objects ties the two together, enabling the assignment and entitlement/pricing functionality.</description>
    <fields>
        <fullName>EC_Price_List_Type__c</fullName>
        <label>Price List Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Z1CP</fullName>
                </value>
                <value>
                    <fullName>Z1GP</fullName>
                </value>
                <value>
                    <fullName>Z1MP</fullName>
                </value>
                <value>
                    <fullName>ZFCP</fullName>
                </value>
                <value>
                    <fullName>ZF00</fullName>
                </value>
                <value>
                    <fullName>Z1LS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__AccountGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the account group</description>
        <label>Account Group</label>
        <referenceTo>ccrz__E_AccountGroup__c</referenceTo>
        <relationshipLabel>Account Group Price Lists</relationshipLabel>
        <relationshipName>E_AccountGroupPriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the pricelist</description>
        <label>Pricelist</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>Account Group Price Lists</relationshipLabel>
        <relationshipName>E_AccountGroupPriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Account Group Price List</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Acct Group Pricelist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Account Group Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>EC_AttentionTo__c</fullName>
        <description>Attention To Field - to capture comments on Order Info Page</description>
        <label>Attention To</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_Attention_To_Number__c</fullName>
        <label>Attention To Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_Ship_To_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC Carts (Ship To Account)</relationshipLabel>
        <relationshipName>CC_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Account of the User that this cart was created for.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Carts</relationshipLabel>
        <relationshipName>E_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
        <fields>
        <fullName>Default_Unloading_Point__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Selected Unloading Point</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipLabel>CC Carts (Default Unloading Point)</relationshipLabel>
        <relationshipName>CC_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__PONumber__c</fullName>
        <label>PO Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__PaymentMethod__c</fullName>
        <description>The payment method defined in E_PaymentDetail__c.Payment_Method__c.</description>
        <label>Payment Method</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the User that this order was placed for.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>E_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>ccrz__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Account of the User that this order was placed for.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__OriginatedCart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the CC Cart object used to create this order.</description>
        <label>Originated Cart</label>
        <referenceTo>ccrz__E_Cart__c</referenceTo>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__PONumber__c</fullName>
        <description>Deprecated</description>
        <label>PO Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__PaymentMethod__c</fullName>
        <description>The payment method defined in E_PaymentDetail__c.Payment_Method__c.</description>
        <label>PaymentMethod</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the User that this order was placed for.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_OrderItem__c.object
<CustomObject>
    <description>The E_OrderItem__c object contains the line level detail of placed orders.</description>
    <fields>
        <fullName>Tank_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tank Detail</label>
        <referenceTo>Tank_Detail__c</referenceTo>
        <relationshipLabel>CC Order Items</relationshipLabel>
        <relationshipName>CC_Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unloading_Point__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unloading Point</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipLabel>CC Order Items</relationshipLabel>
        <relationshipName>CC_Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Arrangement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To stamp billing arrangement on order item</description>
        <label>Billing Arrangement</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>CC Order Items</relationshipLabel>
        <relationshipName>CC_Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Order Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>OrderItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceList__c.object
<CustomObject>
    <description>Represents a grouping of products to control pricing and entitlements.  The B2B Commerce pricelist object controls both pricing and entitlements, but can be used just for the purposes of entitlements. A list needs to be created for each currency that needs to be represented, allowing for different entitlments and pricing based on the locale and currency.</description>
    <fields>
        <fullName>EC_Price_List_Type__c</fullName>
        <description>This field stores the type of pricelist i.e. Sales Org, Customer Group</description>
        <inlineHelpText>This field stores the type of pricelist i.e. Sales Org, Customer Group</inlineHelpText>
        <label>Price List Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BA_Number__c</fullName>
        <description>To store BA number</description>
        <label>BA Number</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <label>CC Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_TransactionPayment__c.object
<CustomObject>
    <description>Transaction payments represent payments made to the system.</description>
    <fields>
        <fullName>ccrz__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account of the user that created this transaction payment.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC Transaction Payments</relationshipLabel>
        <relationshipName>TransactionPayments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__CCOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>References the order this payment was applied to (optional).</description>
        <label>CC Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>CC Transaction Payments</relationshipLabel>
        <relationshipName>TransactionPayments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Token__c</fullName>
        <description>Tokenized form of the payment</description>
        <label>Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User that created this transaction payment.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TransactionPayments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Transaction Payment</label>
    <nameField>
        <displayFormat>TP-{0000000000}</displayFormat>
        <label>CC Transaction Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Transaction Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Chemical_Product_Type__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To identify the bulk product (User Story-122127)</description>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Chemical Product Type</label>
</CustomObject>

src/objects/Tank_Detail__c.object
<CustomObject>
    <description>Object to store all tank numbers for a particular Unloading point &amp; product.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tank Detail</relationshipLabel>
        <relationshipName>EC_Tank_Detail</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tank_ID__c</fullName>
        <externalId>true</externalId>
        <label>Tank ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Tank_Number__c</fullName>
        <label>Tank Number</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unloading_Point__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Unloading Point</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipLabel>Tank Detail</relationshipLabel>
        <relationshipName>EC_Tank_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tank Detail</label>
    <nameField>
        <label>Tank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tank Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>User_Type__c</fullName>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/EC_OrderSubmitEmailTest.cls
/* Class Name    : EC_OrderSubmitEmailTest
 * Description      Test Class to cover EC_OrderSubmitEmail Class
 * Created By       :Ravindra Singh
 * Created On       :2019-8-6


 * Modification Log:
 * -----------------------------------------------------------------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID         Description
 * -----------------------------------------------------------------------------------------------------------------------------------------------------------------
 * Ravindra Singh               2019-8-6     BC-76559        Created the class
 *
 */
@isTest
public class EC_OrderSubmitEmailTest {    
    /***************************************************************************************************************************************
  Method Name : fetchAccountsTest
  Description : Test method to cover getOrderInfoWrapper method
  Return type : void
 *************************************************************************************************************************************/
    static testMethod void test_positiveResponse(){

        EC_TestData.setupTestUser();
        User thisUser = [SELECT Id FROM User WHERE LastName = 'TestUser'];
        createChemicalProductType('90R_Bulk','90R');
        createChemicalProductType('91B_Bulk','91B');
        System.runas(thisUser){
            EC_TestData.setupCatalog();
            list<ccrz__E_Order__c> orders = EC_TestData.createOrders(1);
            List<ccrz__E_ContactAddr__c> uloadingList = unloadingPointUtility(orders);
            ccrz__E_Cart__c cart = [Select Id, Default_Unloading_Point__c FROM ccrz__E_Cart__c WHERE Id = :orders[0].ccrz__OriginatedCart__c];
            cart.Default_Unloading_Point__c = uloadingList[0].Id;
            cart.EC_AttentionTo__c = 'Kieron Pollard';
            cart.EC_Attention_To_Number__c= '868840';
            update cart;



            Tank_Detail__c tank = new Tank_Detail__c();
            tank.Unloading_Point__c =uloadingList[0].id;
            tank.Tank_ID__c = '123';
            tank.Account__c = orders[0].ccrz__Account__c;
            tank.Tank_Number__c = '1234';
            insert tank;

            //ccrz__E_OrderItem__c orderItem1 = [Select Id, ]
            List<ccrz__E_OrderItem__c> orderItem = orderItemUtility(tank.Id,orders[0].Id,uloadingList);

            ccrz__E_Order__c order = [Select ccrz__User__c,ccrz__OriginatedCart__r.EC_Ship_To_Account__r.ccrz__E_AccountGroup__c from ccrz__E_Order__c where id = :orders[0].Id];
            String accountGroup = order.ccrz__OriginatedCart__r.EC_Ship_To_Account__r.ccrz__E_AccountGroup__c;
            User u = [Select Id from User where Id = :order.ccrz__User__c];
            u.User_Type__c = 'Internal';
            order.ccrz__PaymentMethod__c = 'PO';
            order.ccrz__PONumber__c = '12345';
            update order;
            update u;



            List<ccrz__E_AccountGroupPriceList__c> accGrpPLList = [Select id,ccrz__AccountGroup__c,ccrz__Pricelist__r.EC_Price_List_Type__c,ccrz__Pricelist__r.Name,ccrz__Pricelist__c  from ccrz__E_AccountGroupPriceList__c where ccrz__AccountGroup__c = :accountGroup];

            ccrz__E_PriceList__c priceList = [Select id from ccrz__E_PriceList__c where id =:accGrpPLList[0].ccrz__Pricelist__c limit 1];
            priceList.EC_Price_List_Type__c  ='SBA';
            priceList.BA_Number__c = '123';
            update priceList;

            ccrz__E_TransactionPayment__c transactions = new ccrz__E_TransactionPayment__c();
            transactions.ccrz__Token__c = 'token';
            transactions.ccrz__CCOrder__c = order.Id;
            insert transactions;

            paymentDetailUtility('02',2020,order);
            
             orderItem[1].Billing_Arrangement__c = priceList.Id;
            update orderItem[1];

            Test.startTest();
            EC_OrderSubmitEmail ordersubmitmail = new EC_OrderSubmitEmail();
            ordersubmitmail.ordId = orders[0].Id;
            EC_OrderSubmitEmail.OrderInfoWrapper orderInfoWrapper = ordersubmitmail.getOrderInfoWrapper();
            orderInfoWrapper.staticResourceUrl= 'https://ecolabconnect--testec1.my.salesforce.com';
            order.ccrz__PaymentMethod__c = 'CC';            
            update order;
            orderInfoWrapper = ordersubmitmail.getOrderInfoWrapper();
            System.assertNotEquals(null, orderInfoWrapper);            
            Test.stopTest();
        }
    }
    
     /***************************************************************************************************************************************
	 Method Name : createChemicalProductType
	 Description : to create custom setting records
	 Return type : void
	 Author      : Parju
	 *************************************************************************************************************************************/
    
    private static void createChemicalProductType(String Name, String PackageCode) {       
        Chemical_Product_Type__c varCustomSettingRecord = new Chemical_Product_Type__c();
        varCustomSettingRecord.Active__c = true;
        varCustomSettingRecord.Package_Code__c = PackageCode;  
        varCustomSettingRecord.Name = Name;
        varCustomSettingRecord.Product_Type__c = 'Bulk';
        insert varCustomSettingRecord;
    }
    
     /***************************************************************************************************************************************
	 Method Name : paymentDetailUtility
	 Description : to create custom setting records
	 Return type : void
	 Author      : Parju
	 *************************************************************************************************************************************/
    
    private static void paymentDetailUtility(String monthName, Integer year,ccrz__E_Order__c order) {       
        ccrz__E_PaymentDetail__c payments = new ccrz__E_PaymentDetail__c();
        payments.ccrz__Payment_Token__c = 'token';
        payments.EC_Card_Holder_Name__c = 'name';
        payments.ccrz__CC_Order__c = order.Id;
        payments.ccrz__Cart__c = order.ccrz__OriginatedCart__c;
        payments.ccrz__Expiration_Month__c = monthName;
        payments.ccrz__Expiration_Year__c = year;
        insert payments;
    }
    
     /***************************************************************************************************************************************
	 Method Name : orderItemUtility
	 Description : to create Order Item records
	 Return type : List<ccrz__E_OrderItem__c>
	 Author      : Parju
	 *************************************************************************************************************************************/
    
    private static List<ccrz__E_OrderItem__c> orderItemUtility(Id tankId, Id OrderId,List<ccrz__E_ContactAddr__c> uloadingList) {       
        List<ccrz__E_OrderItem__c> orderItem = new List<ccrz__E_OrderItem__c>{
                                new ccrz__E_OrderItem__c(ccrz__Price__c= 50,ccrz__Quantity__c= 2,ccrz__SubAmount__c= 20,Tank_Number__c = tankId,ccrz__Order__c = orderId,Unloading_Point__c = uloadingList[0].Id),
                                new ccrz__E_OrderItem__c(ccrz__Price__c= 50,ccrz__Quantity__c= 2,ccrz__SubAmount__c= 20,Tank_Number__c = tankId,ccrz__Order__c = orderId,Unloading_Point__c = uloadingList[1].Id),
                                new ccrz__E_OrderItem__c(ccrz__Price__c= 50,ccrz__Quantity__c= 2,ccrz__SubAmount__c= 20,ccrz__Order__c = orderId,Unloading_Point__c = uloadingList[1].Id)
                        };
            insert orderItem;
        return orderItem;
    }
    
     /***************************************************************************************************************************************
	 Method Name : unloadingPointUtility
	 Description : to create Order Item records
	 Return type : List<ccrz__E_ContactAddr__c>
	 Author      : Parju
	 *************************************************************************************************************************************/
    
    private static List<ccrz__E_ContactAddr__c> unloadingPointUtility(List<ccrz__E_Order__c> orders) {       
        List<ccrz__E_ContactAddr__c> uloadingList = new List<ccrz__E_ContactAddr__c>();
        ccrz__E_ContactAddr__c UL1 = EC_TestData.getContactAddress();
        UL1.EC_Account_Number__c = orders[0].ccrz__Account__c;
        UL1.ccrz__CompanyName__c = 'Test Company1';
        ccrz__E_ContactAddr__c UL2 = EC_TestData.getContactAddress();
        UL2.EC_Account_Number__c = orders[0].ccrz__Account__c;
        UL2.ccrz__CompanyName__c = 'Test Company2';
        uloadingList.add(UL1);
        uloadingList.add(UL2);
        insert uloadingList;                
        return uloadingList;
    }  
}