src/objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>ccrz__EffectiveAccountID__c</fullName>
        <description>Holds the effective account for this cart.  This field will be utilized in implementations where a user can order for multiple accounts inclusive or exclusive of their own.  The effective account is used to control the entitlements, pricing, integrations etc that drive the site experience.</description>
        <inlineHelpText>This field will be utilized in implementations where a user can order for multiple accounts inclusive or exclusive of their own.  The effective account is used to control the entitlements, pricing, integrations etc that drive the site experience.</inlineHelpText>
        <label>Effective Account ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__RequestDate__c</fullName>
        <description>Request date captured during the checkout process.</description>
        <label>Request Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>The storefront under which the order was placed.</description>
        <label>Storefront</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_CartItem__c.object
<CustomObject>
    <description>Cart Items</description>
    <fields>
        <fullName>ccrz__Comments__c</fullName>
        <description>User entered comments on the line item.</description>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__OriginalQuantity__c</fullName>
        <description>Stores the original child quantity per unit for Kits, Bundles, and Dynamic Kits.</description>
        <label>Original Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>The unit price of the line.</description>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line item.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Cart Items (ProductID)</relationshipLabel>
        <relationshipName>E_CartItem2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Quantity of the line item.</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__RequestDate__c</fullName>
        <description>Requested date for the line item.</description>
        <label>Request Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__SubAmount__c</fullName>
        <description>Sub Amount total for the line.  Typically will be Price times Quantity.</description>
        <label>Sub Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__UnitOfMeasure__c</fullName>
        <description>Unit of measure as copied from the product data.</description>
        <label>Unit Of Measure</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>CC Cart Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CartItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent order, which originally submitted the subscription for this order, if applicable</description>
        <inlineHelpText>Parent order, which originally submitted the subscription for this order, if applicable</inlineHelpText>
        <label>Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Children Orders</relationshipLabel>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__RequestDate__c</fullName>
        <description>Request date captured during the checkout process.</description>
        <label>Request Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>The storefront under which the order was placed.</description>
        <label>Storefront</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_OrderItem__c.object
<CustomObject>
    <description>The E_OrderItem__c object contains the line level detail of placed orders.</description>
    <fields>
        <fullName>ccrz__Comments__c</fullName>
        <description>Cart line comments as applied to this item.</description>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__OrderLineType__c</fullName>
        <description>Either Major or Minor. Minor if this line item is part of a kit or bundle, otherwise Major.</description>
        <label>Order Line Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Major</fullName>
                </value>
                <value>
                    <fullName>Minor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <description>The order that this order line is a part of.</description>
        <label>Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__OriginalQuantity__c</fullName>
        <description>The purpose of this field is to store the appropriate quantity of line items that have products in the form of parent and child like bundles kits and dynamic kits</description>
        <label>Original Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>The price of the product at the time the item was ordered.</description>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Order Items (ProductID)</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Quantity__c</fullName>
        <description>The number of items ordered for this line.</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__RequestDate__c</fullName>
        <description>The request date for this line item. This will be the same value as at the order header.</description>
        <label>Request Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__SubAmount__c</fullName>
        <description>The sub-total amount for the order. This will be calculated as price * quantity - coupon adjustments during order placement.</description>
        <label>Sub Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__UnitOfMeasure__c</fullName>
        <description>Unit of measure copied from the product.</description>
        <label>Unit Of Measure</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>CC Order Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>OrderItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date that this product will be available.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__HazardousFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Product is Hazardous.</description>
        <label>Hazardous Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__LongDesc__c</fullName>
        <description>Product long description</description>
        <label>LongDesc</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductId__c</fullName>
        <description>External product Id, tying this product to the source system. Typically contains the SKU/product id from a backend system such as SAP.</description>
        <externalId>true</externalId>
        <label>Product Id</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__ProductIndexStatus__c</fullName>
        <description>Indicates the status of the associated Product Index records. Possible values are Current, Not Current and Pending. This field is primarily used by the Product Index batch process.</description>
        <inlineHelpText>Indicates the status of the associated Product Index records. Possible values are Current, Not Current and Pending. This field is primarily used by the Product Index batch process.</inlineHelpText>
        <label>Product Index Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductStatus__c</fullName>
        <description>The status of the product. In Creation - Newly created product, that still requires augmentation and is not visible on the site; Blocked - product has been blocked from being displayed on the site; Not Orderable - product can be viewed, but cannot be added to a cart or ordered; Released - fully availble product</description>
        <label>Product Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Not Orderable</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>In Creation</fullName>
                    <default>true</default>
                    <label>In Creation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__ProductWeight__c</fullName>
        <description>Weight of the product - used as a shipping parameter</description>
        <label>Product Weight</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within B2B Commerce</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__ShortDesc__c</fullName>
        <description>Product short description</description>
        <label>ShortDesc</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The first date that this product will be available.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>Mulit-select list that allows you to assign the product to one or more storefronts.</description>
        <label>Storefront</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DefaultStore</fullName>
                    <default>true</default>
                    <label>DefaultStore</label>
                </value>
                <value>
                    <fullName>Connect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__UnitOfMeasure__c</fullName>
        <description>Product unit of measure - such as Each</description>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Each</fullName>
                    <default>true</default>
                    <label>Each</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EC_cc_hk_OrderTest.cls
/*******************************************************************************************************************
Apex Class Name     : EC_cc_hk_OrderTest
Created Date        : 8 August 2019
Description         : Test class for EC_cc_hk_Order
* Developer                        Date                   Description
* -----------------------------------------------------------------------------------------------------------------
* Vishal                           8 August 2019          Test class for EC_cc_hk_Order
*************************************************************************************************************************/

@isTest
public class EC_cc_hk_OrderTest{

    /************************************************************************
    Method Name: place
    Description: Test method for place(Map<String,Object> inputData) in EC_cc_hk_Order class
    Parameters: NA
    Returns: void
    *************************************************************************/

    public static testMethod void place(){
        Map<String,Object> inputData = new Map<String,Object>();
        Test.startTest();
        EC_cc_hk_Order hkOrder = new EC_cc_hk_Order();
        List<ccrz__E_Order__c> orderList = EC_TestData.createOrders(1);
        List<ccrz__E_OrderItem__c> orderItems = [Select Id,ccrz__Order__c,ccrz__Product__c from ccrz__E_OrderItem__c];
        List<ccrz__E_Product__c> prod = [Select Id from ccrz__E_Product__c];
        List<ccrz__E_OrderItem__c> testOrderItems = new List<ccrz__E_OrderItem__c>();
        prod[0].Name = 'newTestProduct';
        update prod;

        testOrderItems.add(
            new ccrz__E_OrderItem__c(
                ccrz__Order__c           = orderList.get(0).Id,
                ccrz__Price__c           = 50,
                ccrz__Quantity__c        = 2,
                ccrz__SubAmount__c       = 20,
                ccrz__Product__c         = prod[0].Id,
                ccrz__Comments__c        = 'test',
                ccrz__OrderLineType__c = 'Minor',
                ccrz__RequestDate__c     = system.today(),
                ccrz__OriginalQuantity__c =2
            ));

         testOrderItems.add(
            new ccrz__E_OrderItem__c(
                ccrz__Order__c           = orderList.get(0).Id,
                ccrz__Price__c           = 50,
                ccrz__Quantity__c        = 2,
                ccrz__SubAmount__c       = 20,
                ccrz__Product__c         = prod[1].Id,
                ccrz__Comments__c        = 'test',
                ccrz__OrderLineType__c = 'Minor',
                ccrz__RequestDate__c     = system.today(),
                ccrz__OriginalQuantity__c =2
            ));
        ccrz__E_Product__c prodNew = new ccrz__E_Product__c(
                        Name                       = 'MyProd Bag',
                        ccrz__SKU__c               = 'test001MyProd',
                        ccrz__ProductId__c         = 'test001MyProd',
                        ccrz__ProductStatus__c     = 'Released',
                        ccrz__UnitOfMeasure__c     = 'BG',
                        ccrz__StartDate__c         = Date.today().addDays(-7),
                        ccrz__EndDate__c           = Date.today().addDays(7),
                        ccrz__Storefront__c        = 'DefaultStore',
                        ccrz__ProductWeight__c     = 500,
                        ccrz__HazardousFlag__c     = true,
                        ccrz__ShortDesc__c       ='product001 Bag',
                        ccrz__LongDesc__c       ='product001 Bag',
                    ccrz__ProductIndexStatus__c = Label.EC_ProductIndexCurrent
                );
        insert prodNew;


         testOrderItems.add(
            new ccrz__E_OrderItem__c(
                ccrz__Order__c           = orderList.get(0).Id,
                ccrz__Price__c           = 50,
                ccrz__Quantity__c        = 2,
                ccrz__SubAmount__c       = 20,
                ccrz__Product__c         = prodNew.Id,
                ccrz__Comments__c        = 'test',
                ccrz__OrderLineType__c = 'Minor',
                ccrz__RequestDate__c     = system.today(),
                ccrz__OriginalQuantity__c =2
            ));

        insert testOrderItems;

        ccrz__E_Order__c order = orderList[0];
        Account account = EC_TestData.testAccount;
        order.ccrz__EffectiveAccountID__c = account.id;
        update order;
        List<ccrz__E_Cart__c> wishListCart = EC_TestData.createQuickLists(1);
        wishListCart[0].ccrz__CartType__c = 'WishList';
		wishListCart[0].EC_PurchasedWishlist__c = true;
        update wishListCart;

         List<ccrz__E_CartItem__c> testCartItems = new List<ccrz__E_CartItem__c>();

        for(ccrz__E_Product__c pc: prod){
            pc.Name = 'New Product';
        }
        update prod;

        for(ccrz__E_Product__c pc: prod){
            testCartItems.add(
                   new ccrz__E_CartItem__c(
                            ccrz__Cart__c           = wishListCart.get(0).Id,
                            ccrz__Price__c           = 50,
                            ccrz__Quantity__c        = 2,
                            ccrz__SubAmount__c       = 20,
                            ccrz__Product__c         = pc.Id,
                            ccrz__Comments__c        = 'test',
                            ccrz__RequestDate__c     = system.today()
                    ));

        }

        insert testCartItems;

        inputData.put('order', order);
        inputData.put('orderItems', (Object)testOrderItems);
        inputData.put('placeStep', ccrz.cc_hk_Order.STEP_END);
        hkOrder.place(inputData);
        Test.stopTest();
        System.assert(inputData.containsKey('order'), null);
    }
    /************************************************************************
    Method Name: pplace2lace
    Description: Test method for place(Map<String,Object> inputData) in EC_cc_hk_Order class
    Parameters: NA
    Returns: void
    *************************************************************************/

    public static testMethod void place2(){
        Map<String,Object> inputData = new Map<String,Object>();
        Test.startTest();
        EC_cc_hk_Order hkOrder = new EC_cc_hk_Order();
        List<ccrz__E_Order__c> orderList = EC_TestData.createOrders(1);
        List<ccrz__E_Product__c> prod = [Select Id from ccrz__E_Product__c];
        List<ccrz__E_OrderItem__c> testOrderItems = new List<ccrz__E_OrderItem__c>();
        prod[0].Name = 'newTestProduct';
        update prod;

        testOrderItems.add(
            new ccrz__E_OrderItem__c(
                ccrz__Order__c           = orderList.get(0).Id,
                ccrz__Price__c           = 50,
                ccrz__Quantity__c        = 2,
                ccrz__SubAmount__c       = 20,
                ccrz__Product__c         = prod[0].Id,
                ccrz__Comments__c        = 'test',
                ccrz__OrderLineType__c = 'Minor',
                ccrz__RequestDate__c     = system.today(),
                ccrz__OriginalQuantity__c =2
            ));

         testOrderItems.add(
            new ccrz__E_OrderItem__c(
                ccrz__Order__c           = orderList.get(0).Id,
                ccrz__Price__c           = 50,
                ccrz__Quantity__c        = 2,
                ccrz__SubAmount__c       = 20,
                ccrz__Product__c         = prod[1].Id,
                ccrz__Comments__c        = 'test',
                ccrz__OrderLineType__c = 'Minor',
                ccrz__RequestDate__c     = system.today(),
                ccrz__OriginalQuantity__c =2
            ));
        ccrz__E_Product__c prodNew = new ccrz__E_Product__c(
                        Name                       = 'MyProd Bag',
                        ccrz__SKU__c               = 'test001MyProd',
                        ccrz__ProductId__c         = 'test001MyProd',
                        ccrz__ProductStatus__c     = 'Released',
                        ccrz__UnitOfMeasure__c     = 'BG',
                        ccrz__StartDate__c         = Date.today().addDays(-7),
                        ccrz__EndDate__c           = Date.today().addDays(7),
                        ccrz__Storefront__c        = 'DefaultStore',
                        ccrz__ProductWeight__c     = 500,
                        ccrz__HazardousFlag__c     = true,
                        ccrz__ShortDesc__c       ='product001 Bag',
                        ccrz__LongDesc__c       ='product001 Bag',
                    ccrz__ProductIndexStatus__c = Label.EC_ProductIndexCurrent
                );
        insert prodNew;


         testOrderItems.add(
            new ccrz__E_OrderItem__c(
                ccrz__Order__c           = orderList.get(0).Id,
                ccrz__Price__c           = 50,
                ccrz__Quantity__c        = 2,
                ccrz__SubAmount__c       = 20,
                ccrz__Product__c         = prodNew.Id,
                ccrz__Comments__c        = 'test',
                ccrz__OrderLineType__c = 'Minor',
                ccrz__RequestDate__c     = system.today(),
                ccrz__OriginalQuantity__c =2
            ));

        insert testOrderItems;
        ccrz__E_Order__c order = orderList[0];
        Account account = EC_TestData.testAccount;
        order.ccrz__EffectiveAccountID__c = account.id;
        update order;
        inputData.put('order', order);
        inputData.put('placeStep', ccrz.cc_hk_Order.STEP_END);
        inputData.put('orderItems', (Object)testOrderItems);
        hkOrder.place(inputData);
        Test.stopTest();
        System.assert(inputData.containsKey('order'), null);
    }
    //bharath test class

    public static testMethod void place3(){
        Map<String,Object> inputData = new Map<String,Object>();
        Test.startTest();
        EC_cc_hk_Order hkOrder = new EC_cc_hk_Order();
        List<ccrz__E_Order__c> orderList = EC_TestData.createOrders(1);
        List<ccrz__E_OrderItem__c> orderItems = [Select Id,ccrz__Order__c,ccrz__Product__c from ccrz__E_OrderItem__c];
        List<ccrz__E_Product__c> prod = [Select Id from ccrz__E_Product__c];
        List<ccrz__E_OrderItem__c> testOrderItems = new List<ccrz__E_OrderItem__c>();
        prod[0].Name = 'newTestProduct';
        update prod;
        
        ccrz__E_Product__c prodNew = new ccrz__E_Product__c(
                        Name                       = 'MyProd Bag',
                        ccrz__SKU__c               = 'test001MyProd',
                        ccrz__ProductId__c         = 'test001MyProd',
                        ccrz__ProductStatus__c     = 'Released',
                        ccrz__UnitOfMeasure__c     = 'BG',
                        ccrz__StartDate__c         = Date.today().addDays(-7),
                        ccrz__EndDate__c           = Date.today().addDays(7),
                        ccrz__Storefront__c        = 'DefaultStore',
                        ccrz__ProductWeight__c     = 500,
                        ccrz__HazardousFlag__c     = true,
                        ccrz__ShortDesc__c       ='product001 Bag',
                        ccrz__LongDesc__c       ='product001 Bag',
                    ccrz__ProductIndexStatus__c = Label.EC_ProductIndexCurrent
                );
        insert prodNew;
        
        testOrderItems.add(EC_TestData.createOrderItems(orderList.get(0).Id, prod[0].Id));
        testOrderItems.add(EC_TestData.createOrderItems(orderList.get(0).Id, prod[1].Id));
        testOrderItems.add(EC_TestData.createOrderItems(orderList.get(0).Id, prodNew.Id));

        insert testOrderItems;

        ccrz__E_Order__c order = orderList[0];
        Account account = EC_TestData.testAccount;
        order.ccrz__EffectiveAccountID__c = account.id;
        update order;
        List<ccrz__E_Cart__c> wishListCart = EC_TestData.createQuickLists(1);
        wishListCart[0].ccrz__CartType__c = 'WishList';
		wishListCart[0].EC_PurchasedWishlist__c = true;
        update wishListCart;
        List<ccrz__E_CartItem__c> testQuickListItems = new List<ccrz__E_CartItem__c>();
        for (Integer i = 0; i < 4; i++) {
            testQuickListItems.add(
                    new ccrz__E_CartItem__c(
                            ccrz__Cart__c           = orderList[0].ccrz__OriginatedCart__c,
                            ccrz__Price__c           = 50,
                            ccrz__Quantity__c        = 2,
                            ccrz__SubAmount__c       = 20,
                            ccrz__Product__c         =prod[1].Id,
                            ccrz__Comments__c        = 'test',
                            ccrz__RequestDate__c     = system.today(),
                            EC_Last_Purchased_Date__c = system.today()
                    ));
            testQuickListItems.add(
                    new ccrz__E_CartItem__c(
                            ccrz__Cart__c           = orderList[0].ccrz__OriginatedCart__c,
                            ccrz__Price__c           = 50,
                            ccrz__Quantity__c        = 2,
                            ccrz__SubAmount__c       = 20,
                            ccrz__Product__c         = prodNew.Id,
                            ccrz__Comments__c        = 'test',
                            ccrz__RequestDate__c     = system.today(),
                          EC_Last_Purchased_Date__c = system.today()
                    ));
        }
        insert testQuickListItems;

        inputData.put('order', order);
        inputData.put('orderItems', (Object)testOrderItems);
        inputData.put('placeStep', ccrz.cc_hk_Order.STEP_CREATE_ORDER_ITEMS_POST);
        hkOrder.place(inputData);
        Test.stopTest();
        System.assert(inputData.containsKey('order'), null);
    }

}