src/objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>ccrz__EncryptedId__c</fullName>
        <description>Semi-random UUID used to refer to the order in URLs.</description>
        <label>Encrypted Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_CartItem__c.object
<CustomObject>
    <description>Cart Items</description>
    <fields>
        <fullName>ccrz__Cart__c</fullName>
        <description>Reference to the parent cart.</description>
        <label>Cart</label>
        <referenceTo>ccrz__E_Cart__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>E_CartItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>The unit price of the line.</description>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line item.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Cart Items (ProductID)</relationshipLabel>
        <relationshipName>E_CartItem2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Quantity of the line item.</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__SubAmount__c</fullName>
        <description>Sub Amount total for the line.  Typically will be Price times Quantity.</description>
        <label>Sub Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__UnitOfMeasure__c</fullName>
        <description>Unit of measure as copied from the product data.</description>
        <label>Unit Of Measure</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>CC Cart Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CartItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_Category__c.object
<CustomObject>
    <description>Product Category detail record</description>
    <fields>
        <fullName>ccrz__CategoryID__c</fullName>
        <description>External Id used for mapping the category to an externally defined entity</description>
        <externalId>true</externalId>
        <label>Category ID</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The end date for which this category is active. After this date the category will no longer be displayed.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this category is active. This is the first date the category will be displayed.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date that this product will be available.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The first date that this product will be available.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__UnitOfMeasure__c</fullName>
        <description>Product unit of measure - such as Each</description>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Each</fullName>
                    <default>true</default>
                    <label>Each</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_PunchOutInfo__c.object
<CustomObject>
    <fields>
        <fullName>EC_BuyerCookie__c</fullName>
        <label>EC_BuyerCookie</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_EncryptedCartId__c</fullName>
        <label>EC_EncryptedCartId</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_From_Domain__c</fullName>
        <label>EC_From_Domain</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_From_Identity__c</fullName>
        <label>EC_ From_Identity</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_PayloadId__c</fullName>
        <label>EC_PayloadId</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_SenderUserAgent__c</fullName>
        <label>EC_SenderUserAgent</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_Sender_Domain__c</fullName>
        <label>EC_Sender_Domain</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_Sender_Identity__c</fullName>
        <label>EC_ Sender_Identity</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_To_Domain__c</fullName>
        <label>EC_To_Domain</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_To_Identity__c</fullName>
        <label>EC_ To_Identity</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_Version__c</fullName>
        <label>EC_Version</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_XMLLanguage__c</fullName>
        <label>EC_XMLLanguage</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>PunchOutInfo</label>
    <nameField>
        <label>EC_PunchOutInfo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PunchOutInfos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EC_PunchoutControllerTest.cls
/* Class Name       :EC_PunchoutControllerTest
 * Description      :This is the test class to test the EC_PunchoutController class
 * Created By       :Harsha N
 * Created On       :24-10-2019
 *
 * Modification Log:
 * ----------------------------------------------------------------------------------------------------------------
 * Developer                Date                Modification ID             Description
 * ----------------------------------------------------------------------------------------------------------------
 * Ayusha Patnaik          17-10-2019                                  This is the controller class that helps the iBuy user to punch out of the system
 *
 */
@isTest
public class EC_PunchoutControllerTest {

	/*************************************************************************************************************************************
	 Method Name : completeTest
	 Description : Test class to create the CXML with the Cart Id
	 Parameter   : NA
	 Return type : void
	 Author      : Harsha N
	 *************************************************************************************************************************************/

	@isTest
	public static void completeTest() {
		EC_TestData.setupTestUser();
		User thisUser = [SELECT Id FROM User WHERE LastName = 'TestUser'];

		system.runas(thisUser) {

			EC_TestData.setupCatalog();

			ccrz__E_Category__c allProdsCateg = new ccrz__E_Category__c(Name = 'All Products',
																	    ccrz__CategoryID__c = 'ALL-PRODUCTS',
																	    ccrz__StartDate__c  = Date.today().addDays(-1),
																	    ccrz__EndDate__c    = Date.today().addDays(1));
			insert allProdsCateg;

			ccrz__E_Cart__c cartRec = EC_TestData.createCart();
			ccrz__E_Product__c prodRec = [SELECT Id FROM ccrz__E_Product__c LIMIT 1];
			ccrz__E_CartItem__c cartItemRec = addCartItem(cartRec, prodRec.Id, 1.00, 100.00);

			EC_PunchOutInfo__c punchRec = new EC_PunchOutInfo__c();
			punchRec.EC_BuyerCookie__c = 'randomText';
			punchRec.EC_From_Domain__c = 'randomText';
			punchRec.EC_From_Identity__c = 'randomText';
			punchRec.EC_To_Domain__c = 'randomText';
			punchRec.EC_To_Identity__c = 'randomText';
			punchRec.EC_Sender_Domain__c = 'randomText';
			punchRec.EC_Sender_Identity__c = 'randomText';
			punchRec.EC_SenderUserAgent__c = 'randomText';
			punchRec.EC_Version__c = 'randomText';
			punchRec.EC_XMLLanguage__c = 'randomText';
			punchRec.EC_PayloadId__c = 'randomText';
			punchRec.EC_EncryptedCartId__c = cartRec.ccrz__EncryptedId__c;
			insert punchRec;

			Test.startTest();


			Map<String, String> cXMLDummy = EC_PunchoutController.generateCXMLWithCart(cartRec.ccrz__EncryptedId__c);
			string cXMLStr = cXMLDummy.get('cxmlString');
			string cXMLErrorStr = EC_PunchoutController.generateCXMLWIthError('Test Error');
			EC_PunchoutController ec = new EC_PunchoutController();
            ec.returnValue = 'test value';
            ec.cXMLStr = 'test value';
            ec.punchOutCallbackURL = 'test value';
			PageReference pageRef = Page.EC_PunchoutLogin;
			Test.setCurrentPage(pageRef);
            System.currentPageReference().getParameters().put('ukey', 'randomText');
			System.currentPageReference().getParameters().put('pkey', 'randomText');
			System.currentPageReference().getParameters().put('effectiveAccount', 'randomText');
			System.currentPageReference().getParameters().put('cartId', cartRec.ccrz__EncryptedId__c);
			PageReference pageRefOut = EC_PunchoutController.redirectToPunchoutLogin();
            
            System.currentPageReference().getParameters().put('ukey', '');
			System.currentPageReference().getParameters().put('pkey', '');
			System.currentPageReference().getParameters().put('effectiveAccount', 'randomText');
			System.currentPageReference().getParameters().put('cartId', cartRec.ccrz__EncryptedId__c);
            System.currentPageReference().getParameters().put('startURL', 'startURL');
            
			PageReference pageRefOut22 = EC_PunchoutController.redirectToPunchoutLogin();

			System.currentPageReference().getParameters().put('ukey', 'randomText');
			System.currentPageReference().getParameters().put('pkey', 'randomText');
			System.currentPageReference().getParameters().put('effectiveAccount', 'randomText');
			System.currentPageReference().getParameters().put('cartId', cartRec.ccrz__EncryptedId__c);
			System.currentPageReference().getParameters().put('startURL', 'startURL');
            
			PageReference pageRefOutAnother = EC_PunchoutController.redirectToPunchoutLogin();

			Test.stopTest();
		}
	}

	/*************************************************************************************************************************************
	 Method Name : addCartItem
	 Description : Add Cart Item
	 Parameter   : ccrz__E_Cart__c, Id, Decimal, Decimal
	 Return type : ccrz__E_CartItem__c
	 Author      : Harsha N
	 *************************************************************************************************************************************/

	public static ccrz__E_CartItem__c addCartItem(ccrz__E_Cart__c testCart, Id prodId, Decimal qty, Decimal price) {
		return addCartItems(testCart,
						    new Map<Id, Decimal>{ prodId => qty },
						    new Map<Id, Decimal>{ prodId => price }).get(0);
	}

	/*************************************************************************************************************************************
	 Method Name : addCartItems
	 Description : Test class to add cart item
	 Parameter   : ccrz__E_Cart__c, Map<Id, Decimal>,Map<Id, Decimal>
	 Return type : void
	 Author      : Harsha N
	 *************************************************************************************************************************************/

	public static List<ccrz__E_CartItem__c> addCartItems(ccrz__E_Cart__c testCart,
													     Map<Id, Decimal> productQuantityMap,
													     Map<Id, Decimal> productPriceMap) {
		final List<ccrz__E_CartItem__c> items = new List<ccrz__E_CartItem__c>();
		final Map<Id, Decimal> itemPrices = (null == productPriceMap) ? new Map<Id, Decimal>() :productPriceMap;

		for (Id productId :productQuantityMap.keySet()) {
			final Decimal itemPrice = itemPrices.containsKey(productId) ? itemPrices.get(productId) :1000.00;
			items.add(new ccrz__E_CartItem__c(ccrz__Cart__c = testCart.Id,
				      ccrz__Quantity__c     = productQuantityMap.get(productId),
				      ccrz__Product__c      = productId,
				      ccrz__Price__c        = itemPrice,
				      ccrz__SubAmount__c    = productQuantityMap.get(productId) * itemPrice,
				      ccrz__UnitOfMeasure__c= 'Each'));
		}
		insert items;
		return items;
	}
}