src/objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>EC_Division__c</fullName>
        <formula>TEXT(ccrz__OriginatedCart__r.EC_Ship_To_Account__r.EC_Division__c)</formula>
        <label>Division</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent order, which originally submitted the subscription for this order, if applicable</description>
        <inlineHelpText>Parent order, which originally submitted the subscription for this order, if applicable</inlineHelpText>
        <label>Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Children Orders</relationshipLabel>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__OriginatedCart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the CC Cart object used to create this order.</description>
        <label>Originated Cart</label>
        <referenceTo>ccrz__E_Cart__c</referenceTo>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_OrderItemGroup__c.object
<CustomObject>
    <description>Order Item Group represents a group of items on the order who share shipping details.</description>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <description>The Order that the Order Item Group is associated with.</description>
        <label>CC Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Order Item Groups</relationshipLabel>
        <relationshipName>E_OrderItemGroups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order_Item_Group_Status__c</fullName>
        <description>Displayed Order Item Group  status. Order Item Group status initially placed are all in Order Submitted status. All other statuses may be implementation specific.</description>
        <label>Order Item Group Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Return Submitted</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Partial Shipped</fullName>
                </value>
                <value>
                    <fullName>Bill Of Material</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Order Not Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submission_Failure_Count__c</fullName>
        <label>Submission Failure Count</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CC Order Item Group</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Order Item Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EC_OrderItemGroupSubmissionBatchJob.cls
/* Class Name      : EC_OrderItemGroupSubmissionBatchJob
* Description      : Batch Class for order submit retry logic
* Created By       : Bharath Kn
* Created On       : 2020-Sept-03


* Modification Log:
* -----------------------------------------------------------------------------------------------------------------------------------------------------------------
* Developer                Date            Modification ID         Description
* -----------------------------------------------------------------------------------------------------------------------------------------------------------------
* Bharath Kn            2020-Sept-03         PBI-                  Created the class
*
*/
global class EC_OrderItemGroupSubmissionBatchJob implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful{    
    global EC_OrderItemGroupService.ServiceResponse response;     
    global list<sObject> records;
    
    global EC_OrderItemGroupSubmissionBatchJob(){
        records = new list<sObject>();
    }    
    
    global Iterable<sObject> start(Database.BatchableContext BC){
    	String divisions = Label.EC_Nalco;
		List<String> divisionList = divisions.split(',');
		String divisionQuery = '\''+ String.join(divisionList,'\',\'')+'\'';  	
    	
        String query  = EC_OrderItemGroupService.getOrderItemGroupQuery();
        query += ' Where (Submission_Failure_Count__c < 5 or Submission_Failure_Count__c = null) and  Order_Item_Group_Status__c = \'Failed\' and ccrz__Order__r.ccrz__OriginatedCart__r.EC_Ship_To_Account__r.EC_Division__c in ('+divisionQuery + ')'; 
        system.debug('start query: ' + query);
        records = Database.query(query);
        system.debug('EC_OrderItemGroupSubmissionBatchJob start: records ' + records);
        return records;
    }
  
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        list<ccrz__E_OrderItemGroup__c> orderItemGroups = ( list<ccrz__E_OrderItemGroup__c> ) scope;
        system.debug('EC_OrderItemGroupSubmissionBatchJob execute: records ' + orderItemGroups);
        if( orderItemGroups != null && !orderItemGroups.isEmpty() ){
            response = EC_OrderItemGroupService.processOrderItemGroups(orderItemGroups); 
        }        
    }

    global void finish(Database.BatchableContext BC){ 
        system.debug('EC_OrderItemGroupSubmissionBatchJob Finish: response ' + response);
        if (response != null && response.errors.size() > 0){ 
            system.debug('EC_OrderItemGroupSubmissionBatchJob Finish: records ' + response.orderItemGroups.values());  
            system.debug('number of errors: ' + response.errors.size());
        }
    }
    
}