src/objects/ccrz__E_PriceList__c.object
<CustomObject>
    <description>Represents a grouping of products to control pricing and entitlements.  The B2B Commerce pricelist object controls both pricing and entitlements, but can be used just for the purposes of entitlements. A list needs to be created for each currency that needs to be represented, allowing for different entitlments and pricing based on the locale and currency.</description>
    <fields>
        <fullName>EC_Price_List_Type__c</fullName>
        <description>This field stores the type of pricelist i.e. Sales Org, Customer Group</description>
        <inlineHelpText>This field stores the type of pricelist i.e. Sales Org, Customer Group</inlineHelpText>
        <label>Price List Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_InformaticaAuditTable__c.object
<CustomObject>
    <fields>
        <fullName>EC_JobEndTime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Job End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EC_JobName__c</fullName>
        <label>Job Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_JobStartTime__c</fullName>
        <label>Job Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>InformaticaAuditTable</label>
    <nameField>
        <label>InformaticaAuditTable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>InformaticaAuditTable</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_ProductIndexBatchStatus__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>EC_Category_Batch_Schedule_Interval__c</fullName>
        <label>Category Batch Schedule Interval</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EC_Category_Index_Switch__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Category Index Switch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EC_InActive_AccountGroupPriceList_Batch__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>checkbox to enable/disable PricelistItem Inactivation Batch</inlineHelpText>
        <label>InActive AccountGroupPriceList Batch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EC_InActive_PriceListItem_Batch__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>checkbox to enable/disable PricelistItem Inactivation Batch</inlineHelpText>
        <label>InActive PriceListItem Batch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EC_InActive_PriceList_Batch__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>checkbox to enable/disable Pricelist Inactivation Batch</inlineHelpText>
        <label>InActive PriceList Batch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EC_InActive_ProductMedia_Batch__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>flag to enable/disable ProductMedia Inactivation Batch</inlineHelpText>
        <label>InActive ProductMedia Batch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EC_Product_Index_Interval__c</fullName>
        <label>Product Index Interval</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EC_Product_Index_Switch__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Product Index Switch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EC_Spec_Index_Switch__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Spec Index Switch</label>
        <type>Checkbox</type>
    </fields>
    <label>Product Index Batch Status</label>
</CustomObject>

force-app/main/default/objects/EC_ProductIndexBatchStatus__c/fields/EC_InActive_ProductCategroy_Batch__c.field-meta.xml
<CustomField>
    <fullName>EC_InActive_ProductCategroy_Batch__c</fullName>
    <defaultValue>false</defaultValue>
    <description>EC InActive ProductCategroy Batch</description>
    <inlineHelpText>EC InActive ProductCategroy Batch</inlineHelpText>
    <label>EC InActive ProductCategroy Batch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EC_ProductIndexBatchStatus__c/fields/EC_Product_Sequence_Index__c.field-meta.xml
<CustomField>
    <fullName>EC_Product_Sequence_Index__c</fullName>
    <defaultValue>false</defaultValue>
    <description>EC Product Sequence Index</description>
    <label>EC Product Sequence Index</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EC_ControllerTriggerCCIndexesTest.cls
/********************************************************************************************************
* @Class Name    EC_ControllerTriggerCCIndexesTest 
* @description   EC_ControllerTriggerCCIndexesTest is used to test functionality of EC_ControllerTriggerCCIndexes
* @Created By -  Ravindra Singh  
* @Created On -  2019-09-10
* *********************************************************************************************************

 * Modification Log:  
 * ------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID             Description 
 * ------------------------------------------------------------------------------------------------------
 * Ravindra               2019-09-10                                   Initial version
 *********************************************************************************************************/ 

@isTest
public class EC_ControllerTriggerCCIndexesTest {


/***************************************************************************************************************************************
      Method Name : runCCBatchesTest
      Description : runCCBatchesTest method is used to test functionality of runCCBatches method
      Return type : void
     **************************************************************************************************************************************/
     

    
    @isTest
    private static void runCCBatchesTest(){
           
        EC_TestData.setupTestUser();
         User thisUser = [SELECT Id FROM User WHERE LastName = 'TestUser' limit 1];
         System.runas(thisUser){
         
         EC_InformaticaAuditTable__c record = new EC_InformaticaAuditTable__c();
        record.EC_JobEndTime__c = System.now().addDays(2);
        record.Name = 'record';
        record.EC_JobName__c = Label.EC_Run_Product_Index_JobName;
        record.EC_JobStartTime__c = System.now();
        insert record;
        
        EC_ProductIndexBatchStatus__c indexBatch = new EC_ProductIndexBatchStatus__c();
        indexBatch.EC_Category_Index_Switch__c = true;
        indexBatch.EC_InActive_AccountGroupPriceList_Batch__c = true;
        indexBatch.EC_InActive_PriceListItem_Batch__c = true;
        indexBatch.EC_InActive_PriceList_Batch__c = true;
        indexBatch.EC_InActive_ProductMedia_Batch__c=true;
        indexBatch.EC_InActive_ProductCategroy_Batch__c = true;
        indexBatch.EC_Product_Index_Switch__c=true;
        indexBatch.EC_Spec_Index_Switch__c = true;
        indexBatch.EC_Category_Batch_Schedule_Interval__c = 15;
        indexBatch.EC_Product_Index_Interval__c = 5;
        indexBatch.EC_Product_Sequence_Index__c=true;
        insert indexBatch;
        
        EC_TestData.setupCatalog();     
       ccrz__E_PriceList__c priceList = [select id,EC_Price_List_Type__c from ccrz__E_PriceList__c limit 1];
       priceList.EC_Price_List_Type__c = 'SBA';
        update priceList;
             
         
         Test.startTest();
        EC_ControllerTriggerCCIndexes.runCCBatches(); 
        Test.stopTest();
             
         }
    }
}