src/objects/ccrz__E_PriceList__c.object
<CustomObject>
    <description>Represents a grouping of products to control pricing and entitlements.  The B2B Commerce pricelist object controls both pricing and entitlements, but can be used just for the purposes of entitlements. A list needs to be created for each currency that needs to be represented, allowing for different entitlments and pricing based on the locale and currency.</description>
    <fields>
        <fullName>ccrz__Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag determining whether or not this pricelist record is active</description>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer active.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is valid will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__PricelistId__c</fullName>
        <description>External reference id for this entry</description>
        <externalId>true</externalId>
        <label>Pricelist Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this pricelist record is active. This is the first date the pricing/entitlements will be applied</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date that this product will be available.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The first date that this product will be available.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_ProductIndexBatchStatus__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>EC_Category_Batch_Schedule_Interval__c</fullName>
        <label>Category Batch Schedule Interval</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EC_Category_Index_Switch__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Category Index Switch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EC_InActive_AccountGroupPriceList_Batch__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>checkbox to enable/disable PricelistItem Inactivation Batch</inlineHelpText>
        <label>InActive AccountGroupPriceList Batch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EC_InActive_PriceListItem_Batch__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>checkbox to enable/disable PricelistItem Inactivation Batch</inlineHelpText>
        <label>InActive PriceListItem Batch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EC_InActive_PriceList_Batch__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>checkbox to enable/disable Pricelist Inactivation Batch</inlineHelpText>
        <label>InActive PriceList Batch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EC_InActive_ProductMedia_Batch__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>flag to enable/disable ProductMedia Inactivation Batch</inlineHelpText>
        <label>InActive ProductMedia Batch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EC_Product_Index_Interval__c</fullName>
        <label>Product Index Interval</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EC_Product_Index_Switch__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Product Index Switch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EC_Spec_Index_Switch__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Spec Index Switch</label>
        <type>Checkbox</type>
    </fields>
    <label>Product Index Batch Status</label>
</CustomObject>

force-app/main/default/classes/EC_AddProductToMasterPricelistTest.cls
/********************************************************************************************************
* @Class Name    EC_AddProductToMasterPricelistTest 
* @description   EC_AddProductToMasterPricelistTest is used to test the functionality of EC_AddProductToMasterPricelist
* @Created By -  Ravindra Singh  
* @Created On -  2019-09-10
* *********************************************************************************************************

 * Modification Log:  
 * ------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID             Description 
 * ------------------------------------------------------------------------------------------------------
 * Ravindra               2019-09-10                                   Initial version
 *********************************************************************************************************/ 
@isTest
public class EC_AddProductToMasterPricelistTest {
    
     /***************************************************************************************************************************************
      Method Name : AddProductToMasterPricelist_postive
      Description : This method is used to test positive scenario
      Return type : void
     **************************************************************************************************************************************/
      
    
    @isTest
    public static void AddProductToMasterPricelist_postive(){
        EC_AddProductToMasterPricelist addproducttopl= new EC_AddProductToMasterPricelist();
   
        Database.BatchableContext dbc ;
        addproducttopl.start(dbc);
        //EC_TestData.setupCatalog();
        Test.startTest();
        List<ccrz__E_PriceList__c> pricelist = [Select id from ccrz__E_PriceList__c];
        delete pricelist;    
        Database.executeBatch(new EC_AddProductToMasterPricelist());
        List<ccrz__E_Product__c> scope= new List<ccrz__E_Product__c>();
        scope = [select id from ccrz__E_Product__c];
        addproducttopl.execute(dbc,scope);
        addproducttopl.finish(dbc);
        system.assertNotEquals(addproducttopl.start(dbc), null);
        Test.stopTest();
    }
    
    /***************************************************************************************************************************************
      Method Name : AddProductToMasterPricelist
      Description : This method is used to test positive scenario
      Return type : void
     **************************************************************************************************************************************/
      
    
    @isTest
    public static void AddProductToMasterPricelist(){
        
        EC_AddProductToMasterPricelist addproducttopl= new EC_AddProductToMasterPricelist();
        Database.BatchableContext dbc ;
        addproducttopl.start(dbc);
        EC_TestData.setupCatalog();
        Test.startTest();
        ccrz__E_PriceList__c priceList = new ccrz__E_PriceList__c();
        priceList.Name = 'AllProducts_PL';
        priceList.ccrz__PricelistId__c = 'AllProducts_PL';
        priceList.ccrz__EndDate__c = System.today() +10;
        priceList.ccrz__Enabled__c = true;
        priceList.ccrz__StartDate__c = System.today() - 1;
        insert priceList;
        
        EC_ProductIndexBatchStatus__c indexBatch = new EC_ProductIndexBatchStatus__c();
        indexBatch.EC_Category_Index_Switch__c = true;
        indexBatch.EC_InActive_AccountGroupPriceList_Batch__c = true;
        indexBatch.EC_InActive_PriceListItem_Batch__c = true;
        indexBatch.EC_InActive_PriceList_Batch__c = true;
        indexBatch.EC_InActive_ProductMedia_Batch__c=true;
        indexBatch.EC_Product_Index_Switch__c=true;
        indexBatch.EC_Spec_Index_Switch__c = true;
        indexBatch.EC_Category_Batch_Schedule_Interval__c = 15;
         indexBatch.EC_Product_Index_Interval__c = 5;
        insert indexBatch;
        
        Database.executeBatch(new EC_AddProductToMasterPricelist());
        List<ccrz__E_Product__c> scope= new List<ccrz__E_Product__c>();
        scope = [select id from ccrz__E_Product__c];
        addproducttopl.execute(dbc,scope);
        addproducttopl.finish(dbc);
        system.assertNotEquals(addproducttopl.start(dbc), null);
        Test.stopTest();
    }
  /***************************************************************************************************************************************
      Method Name : AddProductToMasterPricelist_exception
      Description : This method is used to test exception scenario
      Return type : void
     **************************************************************************************************************************************/
      
    @isTest
    public static void AddProductToMasterPricelist_exception(){
        EC_AddProductToMasterPricelist addproducttopl= new EC_AddProductToMasterPricelist();
        Database.BatchableContext dbc ;
        addproducttopl.start(dbc);
        Test.startTest();
        EC_TestData.setupCatalog();
        Database.executeBatch(new EC_AddProductToMasterPricelist());        
        List<ccrz__E_Product__c> scope= new List<ccrz__E_Product__c>();
        scope = [select id from ccrz__E_Product__c];
        addproducttopl.execute(dbc,scope);
        addproducttopl.finish(dbc);
        Test.stopTest();
    }
}