src/objects/ccrz__E_PriceList__c.object
<CustomObject>
    <description>Represents a grouping of products to control pricing and entitlements.  The B2B Commerce pricelist object controls both pricing and entitlements, but can be used just for the purposes of entitlements. A list needs to be created for each currency that needs to be represented, allowing for different entitlments and pricing based on the locale and currency.</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer active.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is valid will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__PricelistId__c</fullName>
        <description>External reference id for this entry</description>
        <externalId>true</externalId>
        <label>Pricelist Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this pricelist record is active. This is the first date the pricing/entitlements will be applied</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceListItem__c.object
<CustomObject>
    <description>Represents an entry in the Pricelist.  Each pricelist object is made up of 1 or more pricelist item objects.  This item objects contain a reference to the product and hold a price value (0, in the case where only entitlements are being used).  The products referenced within these items will be displayed in search and product listings on the external site.</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The end date for the price list item.  The end date is the date at which the item will no longer be available.  For example if the end date is July 1, 2015 then the price list item is valid on June 30, 2015 but no longer valid on July 1, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Pricelist__c</fullName>
        <description>Required - The reference to the pricelist</description>
        <label>Pricelist</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>E_PriceListItems1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the product entry</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>E_PriceListItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this item record is active. This is the first date the item will be active</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Price List Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>PriceListItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date that this product will be available.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductIndexStatus__c</fullName>
        <description>Indicates the status of the associated Product Index records. Possible values are Current, Not Current and Pending. This field is primarily used by the Product Index batch process.</description>
        <inlineHelpText>Indicates the status of the associated Product Index records. Possible values are Current, Not Current and Pending. This field is primarily used by the Product Index batch process.</inlineHelpText>
        <label>Product Index Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductStatus__c</fullName>
        <description>The status of the product. In Creation - Newly created product, that still requires augmentation and is not visible on the site; Blocked - product has been blocked from being displayed on the site; Not Orderable - product can be viewed, but cannot be added to a cart or ordered; Released - fully availble product</description>
        <label>Product Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Not Orderable</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>In Creation</fullName>
                    <default>true</default>
                    <label>In Creation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within B2B Commerce</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The first date that this product will be available.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_ProductIndexBatchStatus__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>EC_Product_Index_Batch_Last_Run__c</fullName>
        <label>Product Index Batch Last Run</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EC_Product_Index_Interval__c</fullName>
        <label>Product Index Interval</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Index Batch Status</label>
</CustomObject>

force-app/main/default/classes/EC_TriggerProductIndex.cls
/********************************************************************************************************
* @Class Name    EC_TriggerProductIndex
* @description   EC_TriggerProductIndex is used to update Pending products to Not Current and executes product index batch job
* @Created By -  Ravindra Singh  
* @Created On -  2019-11-27
* *********************************************************************************************************

 * Modification Log:  
 * ------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID             Description 
 * ------------------------------------------------------------------------------------------------------
 * Ravindra               2019-11-27                                    Initial version
 *********************************************************************************************************/ 
global class EC_TriggerProductIndex implements Database.batchable<sObject>, Database.Stateful{
    
    EC_ProductIndexBatchStatus__c indexBatchCS  = EC_ProductIndexBatchStatus__c.getOrgDefaults();
   
     /***************************************************************************************************************************************
      Method Name : start
      Description : start method is used to query the records to be processed in the batch
      Return type : Database.QueryLocator
     **************************************************************************************************************************************/
     
     
    global Database.QueryLocator start(Database.BatchableContext BC) {
       String productList = 'Select ccrz__SKU__c,ccrz__StartDate__c,ccrz__EndDate__c,ccrz__ProductStatus__c, ccrz__ProductIndexStatus__c FROM ccrz__E_Product__c WHERE ccrz__ProductIndexStatus__c = \'Pending\' AND ccrz__ProductStatus__c in (\'Released\',\'Not Orderable\') AND ccrz__EndDate__c > Today AND id in (Select ccrz__Product__c from ccrz__E_PriceListItem__c WHERE ccrz__PriceList__r.ccrz__pricelistId__c =\'AllProducts_PL\')';
      return Database.getQueryLocator(productList);
    }
    
     /***************************************************************************************************************************************
      Method Name : execute
      Description : execute method is used to update Pending products to Not Current
      Return type : void
     **************************************************************************************************************************************/
         
    
    global void execute(Database.BatchableContext BC, List<ccrz__E_Product__c> products) {
        
            
        for(ccrz__E_Product__c product : products){
   
               product.ccrz__ProductIndexStatus__c = 'Not Current';
 
            }

        update products;
               
    
    }
    
      /***************************************************************************************************************************************
      Method Name : finish
      Description : finish method is used to trigger product index job
      Return type : void
     **************************************************************************************************************************************/
          
    
    global void finish(Database.BatchableContext BC){
    
      List<ccrz__E_Product__c> pendingProductList = [Select ccrz__SKU__c,ccrz__StartDate__c,ccrz__EndDate__c,ccrz__ProductStatus__c, ccrz__ProductIndexStatus__c FROM ccrz__E_Product__c WHERE ccrz__ProductIndexStatus__c in ('Pending','Not Current') AND ccrz__ProductStatus__c in ('Released','Not Orderable') AND ccrz__EndDate__c > Today AND id in (Select ccrz__Product__c from ccrz__E_PriceListItem__c WHERE ccrz__PriceList__r.ccrz__pricelistId__c ='AllProducts_PL')];
        
      if(pendingProductList.size()>0){
      
          List<ccrz__E_PriceList__c> pricelist = [Select id from ccrz__E_PriceList__c where ccrz__PricelistId__c = 'AllProducts_PL' limit 1];    
                ccrz.ccProductIndexBuilder.build(new Map<String,Object>{
                    ccrz.ccAPIProductIndex.LOCALES => new Set<String>{'en_US','en','en_CA'},
                        ccrz.ccAPIProductIndex.CLEAN_ONLY => TRUE,
                        ccrz.ccAPIProductIndex.MASTER_PRICE_LIST => pricelist[0].Id
                        });
        
 
          EC_ProductIndexBatchStatus__c batchStartTime = EC_ProductIndexBatchStatus__c.getOrgDefaults();
          Integer batchScheduleInterval = Integer.valueOf(batchStartTime.EC_Product_Index_Interval__c);
          batchStartTime.EC_Product_Index_Batch_Last_Run__c = System.now();
          upsert batchStartTime; 
            
         DateTime now = System.now().addMinutes(batchScheduleInterval);
            
            String dayVal = String.valueOf(now.day());
            String monthVal = String.valueOf(now.month());
            String hourVal = String.valueOf(now.hour());
            String minuteVal = String.valueOf(now.minute());
            String secondVal = String.valueOf(now.second());
            String yearVal = String.valueOf(now.year());
            String jobName = 'Product Index Job '+secondVal+minuteVal+hourVal+dayVal+monthVal+yearVal;
            String strSchedule = '0 ' + minuteVal + ' ' + hourVal + ' ' + dayVal + ' ' + monthVal + ' ?' + ' ' + yearVal;
            System.Schedule(jobName, strSchedule, new EC_TriggerProductIndexSchedulable());
            
 
      }
    
       
    }
    
}