src/objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>ccrz__ActiveCart__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When a new Cart is created, the cart is active by default. Whenever, we want to make anyother cart active, the current active cart should be deactivated</description>
        <label>Active Cart</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__CartStatus__c</fullName>
        <description>Cart Status: Every cart is created with a &quot;Open&quot; state, and set to &quot;Closed&quot; state after a corresponding order is placed.</description>
        <label>Cart Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Contact of the User that this cart was created for.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CC Carts</relationshipLabel>
        <relationshipName>CC_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Unsubscribe__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to check if the user has opted out of Abandoned Cart emails</description>
        <label>Unsubscribe</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/classes/EC_UnsubscribeTest.cls
@isTest
public class EC_UnsubscribeTest {

    static testMethod void testupdateContact(){
        Contact cont = new Contact();
        cont.FirstName = 'TestFirst';
        cont.LastName = 'TestLast';
        cont.Email = 'test@test.com';
        cont.Unsubscribe__c = false;
        insert cont;
        
        ccrz__E_Cart__c cart = new ccrz__E_Cart__c();
        cart.ccrz__Contact__c = cont.Id;
        cart.ccrz__ActiveCart__c = true;
        cart.ccrz__CartStatus__c = 'Open';
		insert cart;		        
        
        Test.setCurrentPageReference(new PageReference('Page.EC_Unsubscribe'));
		System.currentPageReference().getParameters().put('Email', cont.Email);
		System.currentPageReference().getParameters().put('contactId', cont.Id);
        
        

    }
}