src/objects/ccrz__E_AccountGroup__c.object
<CustomObject>
    <description>This object is used to group multiple accounts together to provide pricing and/or entitlements.  An account group can have 1 or more accounts associated with it.  It also can have 1 or more pricelists (used for pricing and entitlements) associated.  This object then ties the accounts and entitlements/pricing together, ultimately controlling the product list and pricing that a given account can see within B2B Commerce.</description>
    <fields>
        <fullName>ccrz__AccountGroupID__c</fullName>
        <description>External ID used for mapping the account group to an externally defined entity.</description>
        <externalId>true</externalId>
        <label>Account Group ID</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CC Account Group</label>
    <nameField>
        <label>Account Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Account Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_AccountGroupPriceList__c.object
<CustomObject>
    <description>Represents a mapping of Account Group to Pricelist.  This objects ties the two together, enabling the assignment and entitlement/pricing functionality.</description>
    <fields>
        <fullName>ccrz__AccountGroupPriceListID__c</fullName>
        <description>External reference id for this entry</description>
        <externalId>true</externalId>
        <label>Account Group Pricelist ID</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__AccountGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the account group</description>
        <label>Account Group</label>
        <referenceTo>ccrz__E_AccountGroup__c</referenceTo>
        <relationshipLabel>Account Group Price Lists</relationshipLabel>
        <relationshipName>E_AccountGroupPriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Enable__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag determining whether or not this mapping record is active</description>
        <label>Enable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the pricelist</description>
        <label>Pricelist</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>Account Group Price Lists</relationshipLabel>
        <relationshipName>E_AccountGroupPriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Account Group Price List</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Acct Group Pricelist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Account Group Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceList__c.object
<CustomObject>
    <description>Represents a grouping of products to control pricing and entitlements.  The B2B Commerce pricelist object controls both pricing and entitlements, but can be used just for the purposes of entitlements. A list needs to be created for each currency that needs to be represented, allowing for different entitlments and pricing based on the locale and currency.</description>
    <fields>
        <fullName>ccrz__PricelistId__c</fullName>
        <description>External reference id for this entry</description>
        <externalId>true</externalId>
        <label>Pricelist Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CC Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_ProductIndexBatchStatus__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>EC_InActive_AccountGroupPriceList_Batch__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>checkbox to enable/disable PricelistItem Inactivation Batch</inlineHelpText>
        <label>InActive AccountGroupPriceList Batch</label>
        <type>Checkbox</type>
    </fields>
    <label>Product Index Batch Status</label>
</CustomObject>

src/objects/exceptionConfig__mdt.object
<CustomObject>
    <description>agpl Updation</description>
    <fields>
        <fullName>Account_Group__c</fullName>
        <description>Account Group value</description>
        <label>Account Group</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Check status</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Date</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriceList__c</fullName>
        <description>PriceList value</description>
        <label>PriceList</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>ExceptionConfiguration</label>
    <pluralLabel>ExceptionConfigurations</pluralLabel>
</CustomObject>

force-app/main/default/classes/EC_InactiveAccountGroupPriceList.cls
/********************************************************************************************************
* @Class Name    EC_InactiveAccountGroupPriceList 
* @description   EC_InactiveAccountGroupPriceList is used to inactivate account group pricelist records based on configured lastModified Date
* @Created By -  Ravindra Singh  
* @Created On -  2019-09-10
* *********************************************************************************************************

 * Modification Log:  
 * ------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID             Description 
 * ------------------------------------------------------------------------------------------------------
 * Ravindra               2019-09-10                                   Initial version
 *********************************************************************************************************/ 

global with sharing class EC_InactiveAccountGroupPriceList implements Database.Batchable<sObject>, Database.Stateful{
    
    private DateTime lastJobRunTime;
    private String accountGroupPriceListIds;
    private String accountGroupAllPL;
    private String priceListString;

/***************************************************************************************************************************************
      Constructor Name : EC_InactiveAccountGroupPriceList
      Description : Method is used to query and initialize the AG,PL,AGPL to be skipped for the current batch Job
      Return type : N/A
**************************************************************************************************************************************/
    global EC_InactiveAccountGroupPriceList(DateTime lastJobRunTime) {
        this.lastJobRunTime = lastJobRunTime;
        
        Date today = Date.today();
        Set<String> onlyAccountGroups = new Set<String>();
        Set<String> priceListSet = new Set<String>();
        Set<String> accGroupSet = new Set<String>();
        Set<String> accGroupPLset = new Set<String>();
        accountGroupAllPL = '';
        accountGroupPriceListIds = '';
        priceListString = '';
        // Get the AG/PL Ids to be skipped from custom metadata.
        List<String> accountGrpPriceListStr = new List<String>();
        for(exceptionConfig__mdt acg: [SELECT id,Account_Group__c,Active__c,PriceList__c,Start_Date__c,End_Date__c, DeveloperName FROM exceptionConfig__mdt 
                                       where Active__c = true AND Start_Date__c <= :today AND End_Date__c >= :today]){
            // Check if Both PriceList & account group are available.
            if(String.isNotBlank(acg.Account_Group__c) &&  String.isNotBlank(acg.PriceList__c)){
                accGroupSet.add(acg.Account_Group__c);
                accGroupPLset.add(acg.PriceList__c);
                accountGrpPriceListStr.add(acg.Account_Group__c+'|'+acg.PriceList__c);
                //Check if Account Group is available & PriceGroup is empty
            }else if(String.isNotBlank(acg.Account_Group__c) && String.isBlank(acg.PriceList__c) && !onlyAccountGroups.contains(acg.Account_Group__c)){
                onlyAccountGroups.add(acg.Account_Group__c); 
                accountGroupAllPL += '\'' +acg.Account_Group__c + '\',';
                // Check if Account group is empty & PriceGroup is available.
            }else if(String.isBlank(acg.Account_Group__c) && String.isNotBlank(acg.PriceList__c) && !priceListSet.contains(acg.PriceList__c)){
                priceListSet.add(acg.PriceList__c); 
                priceListString += '\'' +acg.PriceList__c + '\',';
            }
        }
        // Logic to Get all PL from AccountGroupPL set & AccountGroup Set created above. 
        if(!accGroupSet.isEmpty() && !accGroupPLset.isEmpty()){
            for(ccrz__E_AccountGroupPriceList__c agpL : [Select Id,ccrz__Pricelist__r.ccrz__PricelistId__c , ccrz__AccountGroup__r.ccrz__AccountGroupID__c , ccrz__AccountGroupPriceListID__c from ccrz__E_AccountGroupPriceList__c 
                                                         where ccrz__AccountGroup__r.ccrz__AccountGroupID__c  in :accGroupSet and ccrz__Pricelist__r.ccrz__PricelistId__c in :accGroupPLset])
            {
                String acountGrpPLStr = agpL.ccrz__AccountGroup__r.ccrz__AccountGroupID__c + '|'+ agpL.ccrz__Pricelist__r.ccrz__PricelistId__c;
                if(accountGrpPriceListStr.contains(acountGrpPLStr)){
                    accountGroupPriceListIds += '\'' + agpL.ccrz__AccountGroupPriceListID__c + '\',';
                }
            }
        }
        accountGroupAllPL = String.isNotBlank(accountGroupAllPL) ? accountGroupAllPL.removeEnd(','): '';
        accountGroupPriceListIds = String.isNotBlank(accountGroupPriceListIds) ? accountGroupPriceListIds.removeEnd(',') : '';
        priceListString = String.isNotBlank(priceListString) ? priceListString.removeEnd(',') : '';
    }
  
   /***************************************************************************************************************************************
      Method Name : start
      Description : start method is used to query the records to be processed in the batch
      Return type : Database.QueryLocator
     **************************************************************************************************************************************/
     
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        String formattedEndDate = lastJobRunTime.formatGmt('yyyy-MM-dd\'T\'HH:mm:ss.SSSZ');
        String query = 'Select id,ccrz__Enable__c from ccrz__E_AccountGroupPriceList__c where lastModifiedDate <='+formattedEndDate;
        // Add an extra condition to the query to skip if AGPL is available.
        if(!String.isBlank(accountGroupPriceListIds)){
            query = query + ' AND ccrz__AccountGroupPriceListID__c not in ('+ accountGroupPriceListIds + ')';    
        }
        // Add an extra condition in query to skip if AG is available.
        if(!String.isBlank(accountGroupAllPL)){
            query = query + ' AND ccrz__AccountGroup__r.ccrz__AccountGroupID__c not in ('+ accountGroupAllPL + ')';    
        }
        // Add an extra condition in query to skip if PL is available.
        if(!String.isBlank(priceListString)){
            query = query + ' AND ccrz__Pricelist__r.ccrz__PricelistId__c not in ('+ priceListString + ')';    
        }
        system.debug('AccountGroupPL query-- '+query);
        return Database.getQueryLocator(query);
    }
    
    /***************************************************************************************************************************************
      Method Name : execute
      Description : execute method is used to inactive the given account group pricelist records
      Return type : void
     **************************************************************************************************************************************/
       
    
    global void execute(Database.BatchableContext BC, List<ccrz__E_AccountGroupPriceList__c> scope) {
        
        
      EC_ProductIndexBatchStatus__c indexBatchCS  = EC_ProductIndexBatchStatus__c.getOrgDefaults();
      
        if(indexBatchCS.EC_InActive_AccountGroupPriceList_Batch__c == true){
            
            List<ccrz__E_AccountGroupPriceList__c> accGrpPlList = new List<ccrz__E_AccountGroupPriceList__c>();
            
            for(ccrz__E_AccountGroupPriceList__c acGrpPL : scope){
              
               acGrpPL.ccrz__Enable__c = false;
               accGrpPlList.add(acGrpPL);
            
            }
    
            update accGrpPlList;
    
        }

    }
    
    
     /***************************************************************************************************************************************
      Method Name : finish
      Description : finish method is used to trigger inactive product media job
      Return type : void
     **************************************************************************************************************************************/
          
    
    global void finish(Database.BatchableContext BC) {
        
        EC_InactiveProductMediaBatch inactiveMediaBatchJob = new EC_InactiveProductMediaBatch(lastJobRunTime);
        
        Database.executeBatch(inactiveMediaBatchJob);
        
    }
}