src/objects/ccrz__E_AccountAddressBook__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>ccrz__AccountId__c</fullName>
        <description>Account id in text form to work around account sharing issue</description>
        <label>AccountId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__AddressType__c</fullName>
        <description>Indicates which type of address correponds to the address book entry</description>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Account Address Book</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Account Address Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EC_InactiveAccountAddressbookBatch.cls
/********************************************************************************************************
* @Class Name    EC_InactiveAccountAddressbookBatch 
* @description   This Batch class is used to deactivate account address book records based on Configured lastModifiedDate
* @Created By -  Ravindra Singh  
* @Created On -  2019-09-10
* *********************************************************************************************************

 * Modification Log:  
 * ------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID             Description 
 * ------------------------------------------------------------------------------------------------------
 * Ravindra               2019-09-10                                   Initial version
 *********************************************************************************************************/ 
 
global with sharing class EC_InactiveAccountAddressbookBatch implements Database.Batchable<sObject>, Database.Stateful{
    
     private DateTime lastJobRunTime;
    
    global EC_InactiveAccountAddressbookBatch(DateTime lastJobRunTime) {
        this.lastJobRunTime = lastJobRunTime;
    } 
    
    /***************************************************************************************************************************************
      Method Name : start
      Description : start method is used to query the records to be processed in the batch
      Return type : Database.QueryLocator
     **************************************************************************************************************************************/
     

    global Database.QueryLocator start(Database.BatchableContext BC) {
        
      String formattedEndDate = lastJobRunTime.formatGmt('yyyy-MM-dd\'T\'HH:mm:ss.SSSZ');
      
      String query = 'SELECT Id,LastModifiedDate, ccrz__AddressType__c FROM ccrz__E_AccountAddressBook__c where lastModifiedDate <= '+formattedEndDate+' and ccrz__AddressType__c = \'billing\' and ccrz__AccountId__c != null';
      
      return Database.getQueryLocator(query);
    }
    
      /***************************************************************************************************************************************
      Method Name : execute
      Description : execute method is used to delete accountId for given account address book records
      Return type : void
     **************************************************************************************************************************************/
      
     global void execute(Database.BatchableContext BC, List<ccrz__E_AccountAddressBook__c> scope) {
        
        List<ccrz__E_AccountAddressBook__c> accountAddrBookList = new List<ccrz__E_AccountAddressBook__c>();
      
         System.debug('records-->'+scope);
        for(ccrz__E_AccountAddressBook__c addBook : scope){
   
            addBook.ccrz__AccountId__c = null;
            accountAddrBookList.add(addBook);

        }
        update accountAddrBookList; 
       
    
    }
    
     /***************************************************************************************************************************************
      Method Name : finish
      Description : Overriden method for batch class
      Return type : void
     **************************************************************************************************************************************/
      
    
      global void finish(Database.BatchableContext BC) {
      
    }
}