src/objects/ccrz__E_AccountGroup__c.object
<CustomObject>
    <description>This object is used to group multiple accounts together to provide pricing and/or entitlements.  An account group can have 1 or more accounts associated with it.  It also can have 1 or more pricelists (used for pricing and entitlements) associated.  This object then ties the accounts and entitlements/pricing together, ultimately controlling the product list and pricing that a given account can see within B2B Commerce.</description>
    <label>CC Account Group</label>
    <nameField>
        <label>Account Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Account Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_CategoryTreeCache__c.object
<CustomObject>
    <fields>
        <fullName>EC_AccountGroup__c</fullName>
        <label>Account Group</label>
        <referenceTo>ccrz__E_AccountGroup__c</referenceTo>
        <relationshipLabel>CategoryTreeCache</relationshipLabel>
        <relationshipName>EC_CategoryTreeCache</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EC_CacheData__c</fullName>
        <label>CacheData</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EC_Currency__c</fullName>
        <label>Currency</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_Locale__c</fullName>
        <label>Locale</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_Sequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EC_Storefront__c</fullName>
        <label>Storefront</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CategoryTreeCache</label>
    <nameField>
        <label>CategoryTreeCache Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CategoryTreeCache</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/EC_GetTreeByAcountGroupFromCache.cls
/* Class Name    : EC_GetTreeByAcountGroupFromCache
 * Description      :Class used to get the category cache data on run time by looking at user account group id
 * Created By       :Jitan Goyal
 * Created On       :07-30-2019

 

 * Modification Log:
 * -----------------------------------------------------------------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID         Description
 * -----------------------------------------------------------------------------------------------------------------------------------------------------------------
 * Jitan Goyal             07-30-2019       BC-74102       Created the class   
 *
 */
global with sharing class EC_GetTreeByAcountGroupFromCache extends ccrz.ccLogicCategoryGetTree{
	 /***************************************************************************************************************************************
  Method Name : process
  Description : return category tree data from EC_CategoryTreeCache__c object 
  Return type : Returns Map<String,Object>
 *************************************************************************************************************************************/
	global virtual override Map<String, Object> process(Map<String, Object> inputData){
        /*
         * Account acc = [Select ccrz__E_AccountGroup__c from Account Where Id=:ccrz.cc_CallContext.effAccountId Limit 1];
        String accGroup = '';
        if(acc!=null){
            accGroup = acc.ccrz__E_AccountGroup__c;
        }*/

		List<EC_CategoryTreeCache__c> caches = [
			SELECT
			EC_CacheData__c,
			EC_Locale__c,
			EC_Currency__c,
            EC_Sequence__c
			FROM
			EC_CategoryTreeCache__c
			WHERE
			EC_Storefront__c = :ccrz.cc_CallContext.storefront AND
			EC_AccountGroup__c IN (Select ccrz__E_AccountGroup__c from Account Where Id=:ccrz.cc_CallContext.effAccountId) AND
			(
			EC_Locale__c = :ccrz.cc_CallContext.userLocale
			)
			ORDER BY
			EC_Sequence__c ASC
		];
		ccrz.ccLog.log(LoggingLevel.DEBUG,'@@','@@caches='+ caches);
		// if no cache is found, fall back on the default full category tree
		if(caches.isEmpty()){
			return null;//super.process(inputData);
		}
        String cache = '';
        for(EC_CategoryTreeCache__c cacheRecord:caches){
            if(String.isNotBlank(cache)){
                cache = cache + cacheRecord.EC_CacheData__c;
            }else{
               cache = cacheRecord.EC_CacheData__c; 
            }
        }
		List<ccrz.cc_bean_Category> theCategories = (List<ccrz.cc_bean_Category>)JSON.deserialize(cache,List<ccrz.cc_bean_Category>.class);
		ccrz.ccLog.log(LoggingLevel.DEBUG,'@@','@@theCategories='+ theCategories);
		Map<String, Object> ret = new Map<String,Object>();
		ret.put(ccrz.ccAPICategory.CATEGORYTREE,(Object)theCategories);
		return ret;
	}
    
}