src/objects/ccrz__E_AccountGroupPriceList__c.object
<CustomObject>
    <description>Represents a mapping of Account Group to Pricelist.  This objects ties the two together, enabling the assignment and entitlement/pricing functionality.</description>
    <fields>
        <fullName>EC_Price_List_Type__c</fullName>
        <label>Price List Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Z1CP</fullName>
                </value>
                <value>
                    <fullName>Z1GP</fullName>
                </value>
                <value>
                    <fullName>Z1MP</fullName>
                </value>
                <value>
                    <fullName>ZFCP</fullName>
                </value>
                <value>
                    <fullName>ZF00</fullName>
                </value>
                <value>
                    <fullName>Z1LS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the pricelist</description>
        <label>Pricelist</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>Account Group Price Lists</relationshipLabel>
        <relationshipName>E_AccountGroupPriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Sequence__c</fullName>
        <defaultValue>500</defaultValue>
        <description>Sequence</description>
        <label>Sequence</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CC Account Group Price List</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Acct Group Pricelist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Account Group Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceList__c.object
<CustomObject>
    <description>Represents a grouping of products to control pricing and entitlements.  The B2B Commerce pricelist object controls both pricing and entitlements, but can be used just for the purposes of entitlements. A list needs to be created for each currency that needs to be represented, allowing for different entitlments and pricing based on the locale and currency.</description>
    <fields>
        <fullName>EC_Price_List_Type__c</fullName>
        <description>This field stores the type of pricelist i.e. Sales Org, Customer Group</description>
        <inlineHelpText>This field stores the type of pricelist i.e. Sales Org, Customer Group</inlineHelpText>
        <label>Price List Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag determining whether or not this pricelist record is active</description>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__PricelistId__c</fullName>
        <description>External reference id for this entry</description>
        <externalId>true</externalId>
        <label>Pricelist Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CC Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_ProductIndexBatchStatus__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>EC_InActive_PriceList_Batch__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>checkbox to enable/disable Pricelist Inactivation Batch</inlineHelpText>
        <label>InActive PriceList Batch</label>
        <type>Checkbox</type>
    </fields>
    <label>Product Index Batch Status</label>
</CustomObject>

src/objects/exceptionConfig__mdt.object
<CustomObject>
    <description>agpl Updation</description>
    <fields>
        <fullName>Account_Group__c</fullName>
        <description>Account Group value</description>
        <label>Account Group</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Check status</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Date</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriceList__c</fullName>
        <description>PriceList value</description>
        <label>PriceList</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>ExceptionConfiguration</label>
    <pluralLabel>ExceptionConfigurations</pluralLabel>
</CustomObject>

force-app/main/default/classes/EC_InactivePriceList.cls
/********************************************************************************************************
* @Class Name    EC_InactivePriceList 
* @description   EC_InactivePriceList is used to inactive the price list records based on configured end date
* @Created By -  Ravindra Singh  
* @Created On -  2019-09-10
* *********************************************************************************************************

 * Modification Log:  
 * ------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID             Description 
 * ------------------------------------------------------------------------------------------------------
 * Ravindra               2019-09-10                                   Initial version
 *********************************************************************************************************/ 


global with sharing class EC_InactivePriceList implements Database.Batchable<sObject>, Database.Stateful{
    
    private DateTime lastJobRunTime;
    private Set<String> ccrzPricelistSet = new Set<String>();
    private String exceptionPriceList;

/***************************************************************************************************************************************
      Constructor Name : EC_InactivePriceList
      Description : Method is used to query and initialize PL to be skipped for the current batch Job
      Return type : N/A
**************************************************************************************************************************************/
     
    global EC_InactivePriceList(DateTime lastJobRunTime) {
        this.lastJobRunTime = lastJobRunTime;
        Date today = Date.today();
        exceptionPriceList = '';
        // Get the AG/PL Ids to be skipped from custom metadata.
        for(exceptionConfig__mdt acg: [SELECT id,Account_Group__c,PriceList__c,Active__c,Start_Date__c,End_Date__c,  DeveloperName FROM exceptionConfig__mdt
                                       Where PriceList__c != null and Active__c = true AND Start_Date__c <= :today AND End_Date__c >= :today]){
                                           if(!this.ccrzPricelistSet.contains(acg.PriceList__c)){
                                               this.ccrzPricelistSet.add(acg.PriceList__c);
                                               exceptionPriceList += '\''+ acg.PriceList__c + '\',';
                                           }
                                       }
        exceptionPriceList = String.isNotBlank(exceptionPriceList) ? exceptionPriceList.removeEnd(',') : '';
    }
    
      /***************************************************************************************************************************************
      Method Name : start
      Description : start method is used to query the records to be processed in the batch
      Return type : Database.QueryLocator
     **************************************************************************************************************************************/
     
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
       String pricelistType = Label.EC_InactivePriceListType;
       String pricelistSequence = Label.EC_InactivePLSequence;
       List<String> pricelistTypeList = pricelistType.split(',');
       String pricelistTypeQuery = '\''+ String.join(pricelistTypeList,'\',\'')+'\'';
        
        String formattedEndDate = lastJobRunTime.formatGmt('yyyy-MM-dd\'T\'HH:mm:ss.SSSZ');        
        String query = 'SELECT id,ccrz__Enabled__c,lastModifiedDate FROM ccrz__E_PriceList__c where ccrz__Enabled__c=true and EC_Price_List_Type__c in ('+pricelistTypeQuery +')  and  ccrz__PricelistId__c != \'AllProducts_PL\' and lastModifiedDate <='+formattedEndDate+' AND id in (select ccrz__Pricelist__c from ccrz__E_AccountGroupPriceList__c where ccrz__Sequence__c in ('+pricelistSequence+'))';
         
         System.debug('exceptionPriceList:'+exceptionPriceList);
         // Add an extra condition in query to skip if PL is available.
         if(!String.isBlank(exceptionPriceList)){
            query = query + ' AND ccrz__PricelistId__c not in (' + exceptionPriceList + ')';
        }
        system.debug('PriceList query-->'+query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<ccrz__E_PriceList__c> scope) {
        
        EC_ProductIndexBatchStatus__c indexBatchCS  = EC_ProductIndexBatchStatus__c.getOrgDefaults();
      
        if(indexBatchCS.EC_InActive_PriceList_Batch__c == true){
            
             List<ccrz__E_PriceList__c> PlList = new List<ccrz__E_PriceList__c>();
            
            for(ccrz__E_PriceList__c pl : scope){
              
               pl.ccrz__Enabled__c = false;
               PlList.add(pl);
            
            }
    
            update PlList;

        }    
    }
    
    /***************************************************************************************************************************************
      Method Name : finish
      Description : finish method is used to trigger Inactive AccountGroupPriceList job
      Return type : void
     **************************************************************************************************************************************/
  
    
    global void finish(Database.BatchableContext BC) {
        
        EC_InactiveAccountGroupPriceList inactiveAccountGroupPriceListBatchJob = new EC_InactiveAccountGroupPriceList(lastJobRunTime);
        
        Database.executeBatch(inactiveAccountGroupPriceListBatchJob);
        
    }
}