src/objects/ccrz__E_Category__c.object
<CustomObject>
    <description>Product Category detail record</description>
    <fields>
        <fullName>ccrz__CategoryID__c</fullName>
        <description>External Id used for mapping the category to an externally defined entity</description>
        <externalId>true</externalId>
        <label>Category ID</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The end date for which this category is active. After this date the category will no longer be displayed.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__ShortDescRT__c</fullName>
        <description>Short category description as a rich text field.</description>
        <label>ShortDescRT</label>
        <length>2000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this category is active. This is the first date the category will be displayed.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceList__c.object
<CustomObject>
    <description>Represents a grouping of products to control pricing and entitlements.  The B2B Commerce pricelist object controls both pricing and entitlements, but can be used just for the purposes of entitlements. A list needs to be created for each currency that needs to be represented, allowing for different entitlments and pricing based on the locale and currency.</description>
    <fields>
        <fullName>ccrz__CurrencyISOCode__c</fullName>
        <description>Required - The 3-character ISO currency code corresponding to this list. For example, USD</description>
        <label>Currency ISO Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag determining whether or not this pricelist record is active</description>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer active.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is valid will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__PricelistId__c</fullName>
        <description>External reference id for this entry</description>
        <externalId>true</externalId>
        <label>Pricelist Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this pricelist record is active. This is the first date the pricing/entitlements will be applied</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>Mulit-select list that allows you to assign the pricelist to one or more storefronts.</description>
        <label>Storefront</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DefaultStore</fullName>
                </value>
                <value>
                    <fullName>Connect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date that this product will be available.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__HazardousFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Product is Hazardous.</description>
        <label>Hazardous Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ERP_Product_Description__c</fullName>
        <label>ERP Product Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductId__c</fullName>
        <description>External product Id, tying this product to the source system. Typically contains the SKU/product id from a backend system such as SAP.</description>
        <externalId>true</externalId>
        <label>Product Id</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__ProductIndexStatus__c</fullName>
        <description>Indicates the status of the associated Product Index records. Possible values are Current, Not Current and Pending. This field is primarily used by the Product Index batch process.</description>
        <inlineHelpText>Indicates the status of the associated Product Index records. Possible values are Current, Not Current and Pending. This field is primarily used by the Product Index batch process.</inlineHelpText>
        <label>Product Index Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductStatus__c</fullName>
        <description>The status of the product. In Creation - Newly created product, that still requires augmentation and is not visible on the site; Blocked - product has been blocked from being displayed on the site; Not Orderable - product can be viewed, but cannot be added to a cart or ordered; Released - fully availble product</description>
        <label>Product Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Not Orderable</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>In Creation</fullName>
                    <default>true</default>
                    <label>In Creation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__ProductWeight__c</fullName>
        <description>Weight of the product - used as a shipping parameter</description>
        <label>Product Weight</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within B2B Commerce</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__ShortDescRT__c</fullName>
        <description>Rich text field for the Short Description</description>
        <label>ShortDescRT</label>
        <length>2000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The first date that this product will be available.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>Mulit-select list that allows you to assign the product to one or more storefronts.</description>
        <label>Storefront</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DefaultStore</fullName>
                    <default>true</default>
                    <label>DefaultStore</label>
                </value>
                <value>
                    <fullName>Connect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__UnitOfMeasure__c</fullName>
        <description>Product unit of measure - such as Each</description>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Each</fullName>
                    <default>true</default>
                    <label>Each</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EC_cclogicPICreateTest.cls
/* Class Name      :EC_cclogicPICreateTest
* Description      :EC_cclogicPICreateTest is code coverage for EC_cclogicPICreate
* Created By       :Rajeshwar Bachu. 
* Created On       :25-05-2020

* Modification Log:
* ------------------------------------------------------------------------------------------------------------------
* Developer                Date            Modification ID         Description
* ------------------------------------------------------------------------------------------------------------------
* Rajeshwar bachu         25-05-2020                             Initial version (log modification)
*
*
*/
@isTest
public class EC_cclogicPICreateTest {
    public static final String STOREFRONT_NAME = 'DefaultStore'; 
    
    @testSetup static void setup(){
        //INSERT CATEGORIES
        ccrz__E_Category__c testAllRoot = new ccrz__E_Category__c(
            Name                = 'Products',
            ccrz__CategoryID__c = '0',
            ccrz__StartDate__c  = Date.today().addDays(-1),
            ccrz__EndDate__c    = Date.today().addDays(1)
        );
        insert testAllRoot;
        //INSERT PRODUCTS
        ccrz__E_Product__c productint = new ccrz__E_Product__c(
            Name                       = 'product003',
            ccrz__SKU__c               = 'test003',
            ccrz__ProductId__c         = 'test003',
            ccrz__ProductStatus__c     = 'Released',
            ccrz__UnitOfMeasure__c     = 'BG',
            ccrz__StartDate__c         = Date.today().addDays(-7),
            ccrz__EndDate__c           = Date.today().addDays(7),
            ccrz__Storefront__c        = STOREFRONT_NAME,
            ccrz__ProductWeight__c     = 500,
            ccrz__HazardousFlag__c     = true,
            ccrz__ProductIndexStatus__c = Label.EC_ProductIndexCurrent,
            //ERP_Product_Description__c = 'Text123',
            ccrz__ShortDescRT__c = 'Text12345'
        );
        insert productint;
        //ccrz__E_Product__c product = [SELECT Id FROM ccrz__E_Product__c limit 1];        
        ccrz__E_PriceList__c priceList= new ccrz__E_PriceList__c(
            Name                     = 'PL002',
            ccrz__CurrencyISOCode__c = 'USD',
            ccrz__Enabled__c         = true,
            ccrz__Storefront__c      = STOREFRONT_NAME,
            ccrz__StartDate__c       = Date.today().addDays(-7),
            ccrz__EndDate__c         = Date.today().addDays(7),
            ccrz__PricelistId__c     = '250287-SIEMENS'
            
        );
        insert priceList;
    }
    
    static testMethod void createProductIndicesMethod()
    {
        ccrz__E_Category__c testAllRoot = [SELECT Id,Name,ccrz__CategoryID__c,ccrz__StartDate__c,ccrz__EndDate__c FROM ccrz__E_Category__c LIMIT 1];
        ccrz__E_Product__c productint = [SELECT Id,Name,ccrz__SKU__c,ccrz__ProductId__c,ccrz__ProductStatus__c,ccrz__UnitOfMeasure__c,ccrz__StartDate__c,ccrz__EndDate__c,ccrz__Storefront__c,ccrz__ProductWeight__c,ccrz__HazardousFlag__c,ccrz__ProductIndexStatus__c,ccrz__ShortDescRT__c FROM ccrz__E_Product__c LIMIT 1];
        ccrz__E_PriceList__c priceList = [SELECT Id,Name,ccrz__CurrencyISOCode__c,ccrz__Enabled__c,ccrz__Storefront__c,ccrz__StartDate__c,ccrz__EndDate__c,ccrz__PricelistId__c FROM ccrz__E_PriceList__c LIMIT 1];
        
        Map<String,Map<String,Map<String, Object>>> pricingDataMap = new Map<String,Map<String,Map<String, Object>>>{
            productint.Id => New Map<String, Map<String,Object>>{
                'USD'=> New Map<String, Map<String,Object>>{
                    'USD' => New Map<String,Object>{
                        'price' => 1.0,
                            'priceLists' => priceList.Id
                            }
                    
                }
            }
        };
        //Map<String, Map<String, Object>> currencyPricingData = new Map<String, Map<String, Object>>();
        String productJSON = '{"shortDesc":"","ERPProductDescription":"","SKU":"3ET465.36","sfdcName":"Bella Chrome Coffee Machine","sfid":"' + productint.Id + '"}'; 
        //String productJSON = '{"shortDesc":"","ERPProductDescription":"","SKU":"3ET465.36","sfdcName":"Bella Chrome Coffee Machine","sfid":"' + productint.Id + '"}';
        string productCat = '{"startDate":"2019-03-22","sequence":100,"endDate":"2099-12-31","category":"' + testAllRoot.id + '","sfdcName":"012289","sfid":"' + productint.Id + '","product":"' + productint.Id + '"}';        
        List<Map<String,Object>> productListCatMap = new List<Map<String,Object>>();
        productListCatMap.add((Map<String,Object>)JSON.deserializeUntyped(productCat)); 
        List<Map<String,Object>> productListMap = new List<Map<String,Object>>();
        Map<String,Object> productMap = new Map<String,Object>();
        productMap = (Map<String,Object>)JSON.deserializeUntyped(productJSON);
        productMap.put('productCategoriesS', productListCatMap);
        productListMap.add(productMap); 
        Map<String, Object> inputData = new Map<String, Object>();
        inputData.put(ccrz.ccAPIProductIndex.PRODUCT_PRICING_DATA,pricingDataMap);
        inputData.put(ccrz.ccAPIProduct.PRODUCTLIST, productListMap);
        inputData.put(ccrz.ccAPIProductIndex.LOCALE,'en_US');
        inputData.put(ccrz.ccAPIProductIndex.CURRENCIES, 'USD');
        inputData.put(ccrz.ccAPI.API_VERSION, 8);
        EC_cclogicPICreate logicPICreate=new EC_cclogicPICreate();
        Test.startTest();
        logicPICreate.createProductIndices(inputData);
        system.assert(inputData!=Null);
        Test.stopTest();
    }
    
    static testMethod void productWithoutCategory()
    {
        ccrz__E_Product__c productint = [SELECT Id,Name,ccrz__SKU__c,ccrz__ProductId__c,ccrz__ProductStatus__c,ccrz__UnitOfMeasure__c,ccrz__StartDate__c,ccrz__EndDate__c,ccrz__Storefront__c,ccrz__ProductWeight__c,ccrz__HazardousFlag__c,ccrz__ProductIndexStatus__c,ccrz__ShortDescRT__c FROM ccrz__E_Product__c LIMIT 1];
        ccrz__E_PriceList__c priceList = [SELECT Id,Name,ccrz__CurrencyISOCode__c,ccrz__Enabled__c,ccrz__Storefront__c,ccrz__StartDate__c,ccrz__EndDate__c,ccrz__PricelistId__c FROM ccrz__E_PriceList__c LIMIT 1];
        
        Map<String,Map<String,Map<String, Object>>> pricingDataMap = new Map<String,Map<String,Map<String, Object>>>{
            +productint.Id => New Map<String, Map<String,Object>>{
                'USD'=> New Map<String, Map<String,Object>>{
                    'USD' => New Map<String,Object>{
                        'price' => 1.0,
                            'priceLists' => +priceList.Id
                            }
                    
                }
            }
        };
        system.debug('testestest: ' + ccrz.ccAPIProductIndex.PRODUCT_PRICING_DATA);
        //Map<String, Map<String, Object>> currencyPricingData = new Map<String, Map<String, Object>>();
        String productJSON = '{"shortDesc":"","ERPProductDescription":"","SKU":"3ET465.36","sfdcName":"Bella Chrome Coffee Machine","sfid":"' + productint.Id + '"}'; 
        //String productJSON = '{"shortDesc":"","ERPProductDescription":"","SKU":"3ET465.36","sfdcName":"Bella Chrome Coffee Machine","sfid":"' + productint.Id + '"}';
        List<Map<String,Object>> productListMap = new List<Map<String,Object>>();
        Map<String,Object> productMap = new Map<String,Object>();
        productMap = (Map<String,Object>)JSON.deserializeUntyped(productJSON);
        productListMap.add(productMap); 
        Map<String, Object> inputData = new Map<String, Object>();
        system.debug('ccrz.ccAPIProductIndex.PRODUCT_PRICING_DATA'+ccrz.ccAPIProductIndex.PRODUCT_PRICING_DATA);
        inputData.put(ccrz.ccAPIProductIndex.PRODUCT_PRICING_DATA,pricingDataMap);
        inputData.put(ccrz.ccAPIProduct.PRODUCTLIST, productListMap);
        inputData.put(ccrz.ccAPIProductIndex.LOCALE,'en_US');
        inputData.put(ccrz.ccAPIProductIndex.CURRENCIES, 'USD');
        inputData.put(ccrz.ccAPI.API_VERSION, 8);
        EC_cclogicPICreate logicPICreate=new EC_cclogicPICreate();
        Test.startTest();
        logicPICreate.createProductIndices(inputData);
        system.assert(inputData!=Null);
        Test.stopTest();
    }
}