src/objects/ccrz__E_AccountGroup__c.object
<CustomObject>
    <description>This object is used to group multiple accounts together to provide pricing and/or entitlements.  An account group can have 1 or more accounts associated with it.  It also can have 1 or more pricelists (used for pricing and entitlements) associated.  This object then ties the accounts and entitlements/pricing together, ultimately controlling the product list and pricing that a given account can see within B2B Commerce.</description>
    <label>CC Account Group</label>
    <nameField>
        <label>Account Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Account Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_AccountGroupPriceList__c.object
<CustomObject>
    <description>Represents a mapping of Account Group to Pricelist.  This objects ties the two together, enabling the assignment and entitlement/pricing functionality.</description>
    <fields>
        <fullName>ccrz__AccountGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the account group</description>
        <label>Account Group</label>
        <referenceTo>ccrz__E_AccountGroup__c</referenceTo>
        <relationshipLabel>Account Group Price Lists</relationshipLabel>
        <relationshipName>E_AccountGroupPriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer available for the account group.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is available to the account group will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the pricelist</description>
        <label>Pricelist</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>Account Group Price Lists</relationshipLabel>
        <relationshipName>E_AccountGroupPriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this mapping record is active. This is the first date the mapping will be applied</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Account Group Price List</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Acct Group Pricelist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Account Group Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceList__c.object
<CustomObject>
    <description>Represents a grouping of products to control pricing and entitlements.  The B2B Commerce pricelist object controls both pricing and entitlements, but can be used just for the purposes of entitlements. A list needs to be created for each currency that needs to be represented, allowing for different entitlments and pricing based on the locale and currency.</description>
    <fields>
        <fullName>ccrz__CurrencyISOCode__c</fullName>
        <description>Required - The 3-character ISO currency code corresponding to this list. For example, USD</description>
        <label>Currency ISO Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer active.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is valid will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this pricelist record is active. This is the first date the pricing/entitlements will be applied</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>Mulit-select list that allows you to assign the pricelist to one or more storefronts.</description>
        <label>Storefront</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DefaultStore</fullName>
                </value>
                <value>
                    <fullName>Connect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceListItem__c.object
<CustomObject>
    <description>Represents an entry in the Pricelist.  Each pricelist object is made up of 1 or more pricelist item objects.  This item objects contain a reference to the product and hold a price value (0, in the case where only entitlements are being used).  The products referenced within these items will be displayed in search and product listings on the external site.</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The end date for the price list item.  The end date is the date at which the item will no longer be available.  For example if the end date is July 1, 2015 then the price list item is valid on June 30, 2015 but no longer valid on July 1, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Pricelist__c</fullName>
        <description>Required - The reference to the pricelist</description>
        <label>Pricelist</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>E_PriceListItems1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the product entry</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>E_PriceListItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this item record is active. This is the first date the item will be active</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Price List Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>PriceListItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date that this product will be available.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductIndexStatus__c</fullName>
        <description>Indicates the status of the associated Product Index records. Possible values are Current, Not Current and Pending. This field is primarily used by the Product Index batch process.</description>
        <inlineHelpText>Indicates the status of the associated Product Index records. Possible values are Current, Not Current and Pending. This field is primarily used by the Product Index batch process.</inlineHelpText>
        <label>Product Index Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductStatus__c</fullName>
        <description>The status of the product. In Creation - Newly created product, that still requires augmentation and is not visible on the site; Blocked - product has been blocked from being displayed on the site; Not Orderable - product can be viewed, but cannot be added to a cart or ordered; Released - fully availble product</description>
        <label>Product Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Not Orderable</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>In Creation</fullName>
                    <default>true</default>
                    <label>In Creation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The first date that this product will be available.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>Mulit-select list that allows you to assign the product to one or more storefronts.</description>
        <label>Storefront</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DefaultStore</fullName>
                    <default>true</default>
                    <label>DefaultStore</label>
                </value>
                <value>
                    <fullName>Connect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EC_cc_hk_Catalog.cls
/* Class Name      :EC_cc_hk_Catalog
* Description      :Hook class for Catalog
* Created By       :Ashish Kr. 
* Created On       :07-08-2019

* Modification Log:
* ------------------------------------------------------------------------------------------------------------------
* Developer                Date            Modification ID         Description
* ------------------------------------------------------------------------------------------------------------------
* Ashish Kr.               07-08-2019                              Initial version (log modification)
*
*
*/
global without sharing class EC_cc_hk_Catalog extends ccrz.cc_hk_Catalog {
    /*
*   Method name -   autoComplete
*   Parameters  -   Map<String,Object> inputData
*   Description -   method overrides auto fill of search functionality of cloud craze with contains in product name
*/
    global override Map<String,Object> autoComplete(Map<String,Object> inputData){
        ccrz.ccLog.log(System.LoggingLevel.DEBUG, 'EC_ccLogicProductFind:autoComplete:inputData', inputData);
        Map<String,Object> superRet = new Map<String,Object>();
        String prodName = (String)inputData.get(ccrz.cc_hk_Catalog.PARAM_SEARCH_STRING);
        String storeFront = (String)inputData.get('STOREFRONT_STRING');
        Integer iLimit = (Integer)inputData.get('RESULTS_LIMIT');
        String prodStatus = Label.EC_ProductStatusFilter;
        String[] prodSts = prodStatus.split(';');
        Set<String> setProdStatus = new Set<String>(prodSts);
        prodName = prodName + '%'; 
        String  prodName2 = '% '+ prodName;
        Date today = Date.today();
        try{
            List<String> lstProdName = new List<String>();
            Set<String> priceIdsIdsSet = new Set<String>();
            Set<String> prodIdsSet = new Set<String>();
            String accGroupId;
            String effAccID = ccrz.cc_CallContext.effAccountId;
            ccrz.ccLog.log(System.LoggingLevel.DEBUG, 'EC_ccLogicProductFind:autoComplete:effAccID', effAccID);
            if(Cache.Session.contains('local.UserCache.priceIdsIdsSet'+effAccID)){
                priceIdsIdsSet = (Set<String>) Cache.Session.get('local.UserCache.priceIdsIdsSet'+effAccID);
            }else{
                for(ccrz__E_AccountGroupPriceList__c accGroup : [SELECT ccrz__AccountGroup__c,ccrz__Pricelist__c,ccrz__Pricelist__r.ccrz__CurrencyISOCode__c 
                                                                 from ccrz__E_AccountGroupPriceList__c 
                                                                 where ccrz__StartDate__c <= :today 
                                                                 AND ccrz__EndDate__c >= :today 
                                                                 AND ccrz__AccountGroup__c IN (Select ccrz__E_AccountGroup__c from Account Where Id=:ccrz.cc_CallContext.effAccountId)
                                                                 AND ccrz__Pricelist__r.ccrz__CurrencyISOCode__c=:ccrz.cc_CallContext.userCurrency
                                                                 AND ccrz__PriceList__r.ccrz__Storefront__c INCLUDES (:storeFront) 
                                                                 AND ccrz__Pricelist__r.ccrz__StartDate__c <= :today 
                                                                 AND ccrz__Pricelist__r.ccrz__EndDate__c >= :today]){            
                                                                     priceIdsIdsSet.add(accGroup.ccrz__Pricelist__c);            
                                                                 }
                Cache.Session.put('local.UserCache.priceIdsIdsSet'+effAccID, priceIdsIdsSet);
            }
            ccrz.ccLog.log(System.LoggingLevel.DEBUG, 'EC_ccLogicProductFind:autoComplete:priceIdsIdsSet', priceIdsIdsSet);
            
            for(AggregateResult ep : [SELECT ccrz__Product__r.Name prodName from ccrz__E_PriceListItem__c 
                                      where ccrz__Pricelist__c in :priceIdsIdsSet
                                      AND ccrz__StartDate__c <= :today
                                      AND ccrz__EndDate__c >= : today
                                      AND ccrz__Product__r.ccrz__StartDate__c <= :today 
                                      AND ccrz__Product__r.ccrz__EndDate__c >= :today 
                                      AND ccrz__Product__r.ccrz__Storefront__c=:storeFront 
                                      AND (ccrz__Product__r.name like :prodName or ccrz__Product__r.name like :prodName2) 
                                      AND ccrz__Product__r.ccrz__ProductStatus__c in :setProdStatus AND ccrz__Product__r.ccrz__ProductIndexStatus__c !=: Label.EC_ProductIndexPending Group By ccrz__Product__r.Name limit :iLimit]){
                                          lstProdName.add(String.valueOf(ep.get('prodName')));
                                      }
			ccrz.ccLog.log(System.LoggingLevel.DEBUG, 'EC_ccLogicProductFind:autoComplete:lstProdName', lstProdName);            
            inputData.put(ccrz.cc_hk_Catalog.PARAM_SEARCH_RESULTS, lstProdName);
        }        
        catch (exception ex)
        {
            System.debug('autoComplete: exception' + ex.getMessage() + ' ' + ex.getLineNumber() + ' '+ ex.getStackTraceString());
            ccrz.ccLog.log(System.LoggingLevel.DEBUG, 'EC_ccLogicProductFind:autoComplete:error', ex.getMessage() + ' ' + ex.getLineNumber());
        }
        return inputData;
    }
}