src/objects/ccrz__E_Category__c.object
<CustomObject>
    <description>Product Category detail record</description>
    <fields>
        <fullName>ccrz__CategoryID__c</fullName>
        <description>External Id used for mapping the category to an externally defined entity</description>
        <externalId>true</externalId>
        <label>Category ID</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__ParentCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used when building a category hierarchy. Contains a reference to this same object, pointing to the parent of this entry</description>
        <label>Parent Category</label>
        <referenceTo>ccrz__E_Category__c</referenceTo>
        <relationshipLabel>E_Categories</relationshipLabel>
        <relationshipName>Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__SEOId__c</fullName>
        <description>A shortened name for the category. This is used when constructing friendly URLs.</description>
        <externalId>true</externalId>
        <inlineHelpText>A shortened name for the category. This is used when constructing friendly URLs.</inlineHelpText>
        <label>SEO Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__SEOId__c</fullName>
        <description>A shortened name for the product. This is used when constructing friendly URLs.</description>
        <externalId>true</externalId>
        <inlineHelpText>A shortened name for the product. This is used when constructing friendly URLs.</inlineHelpText>
        <label>SEO Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_ProductCategory__c.object
<CustomObject>
    <description>The Product Category is a link table which link product with category. It is a many-to-many relationship.</description>
    <fields>
        <fullName>ccrz__Category__c</fullName>
        <description>Reference to the Category</description>
        <label>Category</label>
        <referenceTo>ccrz__E_Category__c</referenceTo>
        <relationshipLabel>Product Categories</relationshipLabel>
        <relationshipName>Product_Categories</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <description>Product contained within the associated category. The same product can exist within multiple categories</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Product Categories</relationshipLabel>
        <relationshipName>Product_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CC Product Category</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ProductCatAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Product Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/EC_ccLogicCategoryGetTreeTest.cls
/* Class Name    : EC_ccLogicCategoryGetTreeTest
 * Description      Test Class to cover EC_ccLogicCategoryGetTree
 * Created By       :Viraj  
 * Created On       :2019-Jul-01
 

 * Modification Log:
 * -----------------------------------------------------------------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID         Description
 * -----------------------------------------------------------------------------------------------------------------------------------------------------------------
 * Viraj                     2019-Jul-01       BC-74102            Created the class   
 *
 */
@isTest
public class EC_ccLogicCategoryGetTreeTest{
    /***************************************************************************************************************************************
	Method Name : getTreeTest
	Description : Test method to cover getTree method
	Return type : void
	*************************************************************************************************************************************/
    @isTest 
    static void getTreeTest(){
        
        User thisUser = [SELECT Id  FROM User WHERE Id = :UserInfo.getUserId()];

         system.runas(thisUser){
         	
            Map<String,Object> inData = new Map<String,Object>();
            Map<String,String> queryParamIn = new Map<String,String>();
            EC_TestData.setupTestUser();  
            EC_TestData.setupCatalog();
            ccrz.cc_RemoteActionContext rCon = new ccrz.cc_RemoteActionContext();
            List<Account> accountGroup = [Select id from Account];
            queryParamIn.put('currAccountGroup',accountGroup[0].id);
	        rCon.effAccountId =accountGroup[0].id;
	        rCon.queryParams = queryParamIn;
	        ccrz.cc_CallContext.initRemoteContext(rCon);
	        
	        ccrz__E_Category__c cat1 = new ccrz__E_Category__c();
	        cat1.ccrz__CategoryID__c='ECOLAB-ROOT';
	        cat1.ccrz__SEOId__c='ecolabroot';
	        cat1.name='EcoLabRoot';
	        insert cat1;
	        ccrz__E_Category__c cat2 = new ccrz__E_Category__c();
	        cat2.ccrz__CategoryID__c='ECOLAB-ROOT2';
	        cat2.ccrz__ParentCategory__c=cat1.id;
	        cat2.ccrz__SEOId__c='ecolabroot2';
	        cat2.name='EcoLabRoot2';
	        insert cat2;
	        ccrz__E_Category__c cat3 = new ccrz__E_Category__c();
	        cat3.ccrz__CategoryID__c='ECOLAB-ROOT3';
	        cat3.ccrz__ParentCategory__c=cat1.id;
	        cat3.ccrz__SEOId__c='ecolabroot3';
	        cat3.name='EcoLabRoot3';
	        insert cat3;
	        
	        List<ccrz__E_Product__c> prodList = [SELECT id,name from ccrz__E_Product__c where name ='product001 Bag'];
	        
	        ccrz__E_ProductCategory__c prodcat1 = new ccrz__E_ProductCategory__c();
	        prodcat1.ccrz__Category__c=cat1.id;
	        prodcat1.ccrz__Product__c=prodList[0].id;
	        insert prodcat1;
	        ccrz__E_ProductCategory__c prodcat2 = new ccrz__E_ProductCategory__c();
	        prodcat2.ccrz__Category__c=cat2.id;
	        prodcat2.ccrz__Product__c=prodList[0].id;
	        //insert prodcat2;
	        ccrz__E_ProductCategory__c prodcat3 = new ccrz__E_ProductCategory__c();
	        prodcat3.ccrz__Category__c=cat3.id;
	        prodcat3.ccrz__Product__c=prodList[0].id;
	        //insert prodcat3;
	        
            String jsonString='[ { "sfid":"'+cat1.id+'", "categoryID":"ECOLAB-ROOT", "SEOId":"ecolabroot", "name":"EcoLabRoot", "children":[ { "sfid":"'+cat2.id+'", "categoryID":"EcoCat1", "SEOId":"ecocat1", "parentCategory":"'+cat1.id+'", "name":"EcoCat1", "children":[ { "sfid":"'+cat3.id+'", "categoryID":"EcoCat1SubCat1", "SEOId":"ecocat1subcat1", "parentCategory":"'+cat2.id+'", "name":"EcoCat1SubCat1" } ] } ] } ]';
            inData.put(ccrz.ccApiCategory.CATEGORYTREE,JSON.deserializeUntyped(jsonString));
            EC_ccLogicCategoryGetTree classOb = new EC_ccLogicCategoryGetTree();
            
            Test.startTest();
          
            Map<String,Object> outData = new Map<String,Object>();
            outData = classOb.getTree(inData);
            System.assertNotEquals(outData,null);
            
            jsonString='[ { "categoryID":"ECOLAB-ROOT", "SEOId":"ecolabroot", "name":"EcoLabRoot", "children": { "categoryID":"EcoCat1", "SEOId":"ecocat1", "parentCategory":"'+cat1.id+'", "name":"EcoCat1", "children": { "categoryID":"EcoCat1SubCat1", "SEOId":"ecocat1subcat1", "parentCategory":"'+cat2.id+'", "name":"EcoCat1SubCat1" }  }  } ]';
            inData.put(ccrz.ccApiCategory.CATEGORYTREE,JSON.deserializeUntyped(jsonString));
            outData = classOb.getTree(inData);
            System.assertNotEquals(outData,null);
            
            jsonString='[ { "sfid":"'+cat1.id+'", "categoryID":"ECOLAB-ROOT", "SEOId":"ecolabroot", "name":"EcoLabRoot", "children":[ { "sfid":"'+cat2.id+'", "categoryID":"EcoCat1", "SEOId":"ecocat1", "parentCategory":"'+cat1.id+'", "name":"EcoCat1", "children":[ { "sfid":"'+cat3.id+'", "categoryID":"EcoCat1SubCat1", "SEOId":"ecocat1subcat1", "parentCategory":"'+cat2.id+'", "name":"EcoCat1SubCat1" } ] } ] } ]';
            inData.put(ccrz.ccApiCategory.CATEGORYTREE,JSON.deserializeUntyped(jsonString));
            outData = classOb.getTree(inData);
            System.assertNotEquals(outData,null);
            Test.stopTest();
             
         }
        
    }
    

}