src/objects/ccrz__E_AccountGroupPriceList__c.object
<CustomObject>
    <description>Represents a mapping of Account Group to Pricelist.  This objects ties the two together, enabling the assignment and entitlement/pricing functionality.</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer available for the account group.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is available to the account group will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this mapping record is active. This is the first date the mapping will be applied</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Account Group Price List</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Acct Group Pricelist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Account Group Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_Category__c.object
<CustomObject>
    <description>Product Category detail record</description>
    <fields>
        <fullName>ccrz__CategoryID__c</fullName>
        <description>External Id used for mapping the category to an externally defined entity</description>
        <externalId>true</externalId>
        <label>Category ID</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The end date for which this category is active. After this date the category will no longer be displayed.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__LongDesc__c</fullName>
        <description>Long description of the category, usually containing more formatted marketing content.</description>
        <label>Long Desc</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__ShortDesc__c</fullName>
        <description>Short description of the category</description>
        <label>Short Desc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this category is active. This is the first date the category will be displayed.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceList__c.object
<CustomObject>
    <description>Represents a grouping of products to control pricing and entitlements.  The B2B Commerce pricelist object controls both pricing and entitlements, but can be used just for the purposes of entitlements. A list needs to be created for each currency that needs to be represented, allowing for different entitlments and pricing based on the locale and currency.</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer active.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is valid will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this pricelist record is active. This is the first date the pricing/entitlements will be applied</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>Mulit-select list that allows you to assign the pricelist to one or more storefronts.</description>
        <label>Storefront</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DefaultStore</fullName>
                </value>
                <value>
                    <fullName>Connect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceListItem__c.object
<CustomObject>
    <description>Represents an entry in the Pricelist.  Each pricelist object is made up of 1 or more pricelist item objects.  This item objects contain a reference to the product and hold a price value (0, in the case where only entitlements are being used).  The products referenced within these items will be displayed in search and product listings on the external site.</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The end date for the price list item.  The end date is the date at which the item will no longer be available.  For example if the end date is July 1, 2015 then the price list item is valid on June 30, 2015 but no longer valid on July 1, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this item record is active. This is the first date the item will be active</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__UnitOfMeasure__c</fullName>
        <description>Unit of Measure for this price.  This field in combination with the product can give UOM specific pricing.  This field is optional, and allows for general pricing for a product independent of UOM.</description>
        <inlineHelpText>Unit of Measure for this price.  This field in combination with the product can give UOM specific pricing.  This field is optional, and allows for general pricing for a product independent of UOM.</inlineHelpText>
        <label>Unit Of Measure</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Price List Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>PriceListItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date that this product will be available.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__HazardousFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Product is Hazardous.</description>
        <label>Hazardous Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__LongDesc__c</fullName>
        <description>Product long description</description>
        <label>LongDesc</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductId__c</fullName>
        <description>External product Id, tying this product to the source system. Typically contains the SKU/product id from a backend system such as SAP.</description>
        <externalId>true</externalId>
        <label>Product Id</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__ProductIndexStatus__c</fullName>
        <description>Indicates the status of the associated Product Index records. Possible values are Current, Not Current and Pending. This field is primarily used by the Product Index batch process.</description>
        <inlineHelpText>Indicates the status of the associated Product Index records. Possible values are Current, Not Current and Pending. This field is primarily used by the Product Index batch process.</inlineHelpText>
        <label>Product Index Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductStatus__c</fullName>
        <description>The status of the product. In Creation - Newly created product, that still requires augmentation and is not visible on the site; Blocked - product has been blocked from being displayed on the site; Not Orderable - product can be viewed, but cannot be added to a cart or ordered; Released - fully availble product</description>
        <label>Product Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Not Orderable</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>In Creation</fullName>
                    <default>true</default>
                    <label>In Creation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__ProductWeight__c</fullName>
        <description>Weight of the product - used as a shipping parameter</description>
        <label>Product Weight</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within B2B Commerce</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__ShortDesc__c</fullName>
        <description>Product short description</description>
        <label>ShortDesc</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The first date that this product will be available.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>Mulit-select list that allows you to assign the product to one or more storefronts.</description>
        <label>Storefront</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DefaultStore</fullName>
                    <default>true</default>
                    <label>DefaultStore</label>
                </value>
                <value>
                    <fullName>Connect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__UnitOfMeasure__c</fullName>
        <description>Product unit of measure - such as Each</description>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Each</fullName>
                    <default>true</default>
                    <label>Each</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_ProductCategory__c.object
<CustomObject>
    <description>The Product Category is a link table which link product with category. It is a many-to-many relationship.</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date that this association of product to category is available</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The first date that this association of product to category is available</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Product Category</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ProductCatAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Product Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/EC_CreateCacheTreeBatchTest.cls
/* Class Name    : EC_CreateCacheTreeBatchTest
 * Description      Test class for Storing/Creating the cache tree of all categories
 * Created By       :Jitan Goyal 
 * Created On       :07-31-2019
 

 * Modification Log:
 * -----------------------------------------------------------------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID         Description
 * -----------------------------------------------------------------------------------------------------------------------------------------------------------------
 * Jitan Goyal          07-31-2019     BC-74102       Created the class   
 *
 */
@isTest
public class EC_CreateCacheTreeBatchTest {
   /***************************************************************************************************************************************
  Method Name : createdata
  Description : sets the test data
  Return type : void
 *************************************************************************************************************************************/
    public static void createdata(){
        ccrz__E_Product__c pro = new ccrz__E_Product__c(
            Name                       = 'product 601',
            ccrz__SKU__c               = '9782721',
            ccrz__ProductId__c         = '978273',
            ccrz__ProductStatus__c     = 'Released',
            ccrz__UnitOfMeasure__c     = 'BG',
            ccrz__StartDate__c         = Date.today().addDays(-7),
            ccrz__EndDate__c           = Date.today().addDays(7),
            ccrz__Storefront__c        = EC_TestData.STOREFRONT_NAME,
            ccrz__ProductWeight__c     = 500,
            ccrz__HazardousFlag__c     = false,
            ccrz__ShortDesc__c       ='SIEMENS 6012',
            ccrz__LongDesc__c       ='SIEMENS 6012345',
            ccrz__ProductIndexStatus__c = Label.EC_ProductIndexCurrent 
        );
        insert pro;
        
        // all root
        ccrz__E_Category__c testAllRoot = new ccrz__E_Category__c(
            Name                = 'Products',
            ccrz__CategoryID__c = '0',
            ccrz__StartDate__c  = Date.today().addDays(-3),
            ccrz__EndDate__c    = Date.today().addDays(3)
        );
        insert testAllRoot;
        
        ccrz__E_Category__c storefrontRoot = new ccrz__E_Category__c(
            Name                    = EC_TestData.STOREFRONT_CATEGORY_ROOT,
            ccrz__CategoryID__c     = EC_TestData.STOREFRONT_CATEGORY_ROOT_EXT_ID,
            ccrz__StartDate__c      = Date.today().addDays(-1),
            ccrz__EndDate__c        = Date.today().addDays(1),
            ccrz__ParentCategory__c = testAllRoot.Id
        );
        insert storefrontRoot;
        
        ccrz__E_ProductCategory__c product001subbrand1 = new ccrz__E_ProductCategory__c(
            ccrz__Product__c  = pro.Id,
            ccrz__Category__c = storefrontRoot.Id
        );
        insert product001subbrand1; 
        
        ccrz__E_AccountGroup__c acGrp = EC_TestData.testAccountGroup;
        
        ccrz__E_PriceList__c priceLists = new ccrz__E_PriceList__c(
            Name                     = 'PL002',
            ccrz__CurrencyISOCode__c = 'USD',
            ccrz__Enabled__c         = true,
            ccrz__Storefront__c      = EC_TestData.STOREFRONT_NAME,
            ccrz__StartDate__c       = Date.today().addDays(-7),
            ccrz__EndDate__c         = Date.today().addDays(7),
            //  ccrz__Seller__c          = sellers[0].Id,
            ccrz__PricelistId__c  = '250287-SIEMENS'
            
        );
        insert priceLists;
        
        ccrz__E_AccountGroupPriceList__c accGrppricelist = new ccrz__E_AccountGroupPriceList__c(
            ccrz__AccountGroup__c = acGrp.Id,
            ccrz__PriceList__c    = priceLists.Id,
            ccrz__Enable__c       = true
        );
        insert accGrppricelist;
        
        ccrz__E_PriceListItem__c pitem =  new ccrz__E_PriceListItem__c(
            ccrz__Pricelist__c = priceLists.Id,
            ccrz__Product__c   = pro.Id,
            ccrz__StartDate__c = Date.today().addDays(-7),
            ccrz__EndDate__c   = Date.today().addDays(7),
            ccrz__Price__c     = EC_TestData.DEFAULT_PRICE
        );
        insert pitem;
        
    }
    
   /***************************************************************************************************************************************
  Method Name : createCacheFromBatch
  Description : Test method to cover process method
  Return type : void
 *************************************************************************************************************************************/
    public static testMethod void createCacheFromBatch(){
        Map<String,Object> inData = new Map<String,Object>();
        Map<String,String> queryParamIn = new Map<String,String>();
        
        User thisUser = [SELECT Id  FROM User WHERE Id = :UserInfo.getUserId()];
        system.runas(thisUser){
            
            EC_TestData.setupCatalog();
            //createdata();
            String curr = 'USD';
			String loc = 'en_US';
            String front = EC_TestData.STOREFRONT_NAME;
            
            List<ccrz__E_AccountGroup__c> accountGroup = [Select ID FROM ccrz__E_AccountGroup__c];
            Account acc = EC_TestData.testAccount;
            acc.ccrz__E_AccountGroup__c = accountGroup[0].id;
            update acc; 
               
            System.debug('accountGroup'+accountGroup);
            ccrz.cc_CallContext.storefront = EC_TestData.STOREFRONT_NAME;
            ccrz.cc_CallContext.userLocale = 'en_US';
            ccrz.cc_CallContext.effAccountId = acc.id;
           // ccrz.cc_CallContext.currAccountGroup = accountGroup[0].id;
            
            /**Test Start Here**/
            Test.startTest();
            EC_CreatePriceListCategoryMappingBatch allowedCatJob=new EC_CreatePriceListCategoryMappingBatch(EC_TestData.STOREFRONT_NAME,curr,loc);
            Database.executebatch(allowedCatJob,5);
            Test.stopTest();
            /**Test Stop Here**/
            
            EC_GetTreeByAcountGroupFromCache cacheObj = new EC_GetTreeByAcountGroupFromCache();
            inData.put(ccrz.ccApiCategory.CATEGORYTREE,'');
            Map<String,Object> outData = cacheObj.process(inData);
            
            /*Assert Check Here*/
            System.assertNotEquals(null, outData);
        }
    }
    
   /***************************************************************************************************************************************
  Method Name : withExistingPricelist
  Description : Test method to cover process method
  Return type : void
 *************************************************************************************************************************************/
    public static testMethod void withExistingPricelist(){
        Map<String,Object> inData = new Map<String,Object>();
        Map<String,String> queryParamIn = new Map<String,String>();
        
        User thisUser = [SELECT Id  FROM User WHERE Id = :UserInfo.getUserId()];
        system.runas(thisUser){
            
            EC_TestData.setupCatalog();
            //createdata();
            String curr = 'USD';
			String loc = 'en_US';
            String front = EC_TestData.STOREFRONT_NAME;
            
            List<ccrz__E_AccountGroup__c> accountGroup = [Select ID FROM ccrz__E_AccountGroup__c];
              List<Account> accList = [SELECT ID FROM Account];
            Account acc = EC_TestData.testAccount;
            acc.ccrz__E_AccountGroup__c = accountGroup[0].id;
            update acc; 
            System.debug('accountGroup'+accountGroup);
            ccrz.cc_CallContext.storefront = EC_TestData.STOREFRONT_NAME;
            ccrz.cc_CallContext.userLocale = 'en_US';
           // ccrz.cc_CallContext.currAccountGroup = accountGroup[0];
 			  ccrz.cc_CallContext.effAccountId = acc.id;
            /**Test Start Here**/
            Test.startTest();
            EC_CreatePriceListCategoryMappingBatch allowedCatJob=new EC_CreatePriceListCategoryMappingBatch(EC_TestData.STOREFRONT_NAME,curr,loc);
            Database.executebatch(allowedCatJob,5);
           
            Test.stopTest();
            /**Test Stop Here**/
            EC_CreatePriceListCategoryMappingBatch allowedCatJob2=new EC_CreatePriceListCategoryMappingBatch(EC_TestData.STOREFRONT_NAME,curr,loc);
            Database.executebatch(allowedCatJob2,5);
            EC_GetTreeByAcountGroupFromCache cacheObj = new EC_GetTreeByAcountGroupFromCache();
            inData.put(ccrz.ccApiCategory.CATEGORYTREE,'');
            Map<String,Object> outData = cacheObj.process(inData);
            
            /*Assert Check Here*/
            System.assertNotEquals(null, outData);
        }
    }
    
    /***************************************************************************************************************************************
  Method Name : withoutAnyCacheFromBatch
  Description : Test method to cover process
  Return type : void
 *************************************************************************************************************************************/
    public static testMethod void withoutAnyCacheFromBatch(){
        Map<String,Object> inData = new Map<String,Object>();
        Map<String,String> queryParamIn = new Map<String,String>();
        
        User thisUser = [SELECT Id  FROM User WHERE Id = :UserInfo.getUserId()];
        system.runas(thisUser){
            
            EC_TestData.setupCatalog();
            
            List<String> curr= new List<String>();
            curr.add('USD');
            List<String> loc= new List<String>();
            String front = EC_TestData.STOREFRONT_NAME;
            loc.add('en_US');
            
            List<ccrz__E_AccountGroup__c> accountGroup = [Select ID FROM ccrz__E_AccountGroup__c];
            Account acc = EC_TestData.testAccount;
            acc.ccrz__E_AccountGroup__c = accountGroup[0].id;
            update acc; 
            ccrz.cc_CallContext.storefront = EC_TestData.STOREFRONT_NAME;
            ccrz.cc_CallContext.userLocale = 'en_US';
           // ccrz.cc_CallContext.currAccountGroup = accountGroup[1];
               ccrz.cc_CallContext.effAccountId = acc.id;
            /**Test Start Here**/
            Test.startTest();
            
            EC_GetTreeByAcountGroupFromCache cacheObj = new EC_GetTreeByAcountGroupFromCache();
            inData.put(ccrz.ccApiCategory.CATEGORYTREE,'');
            Map<String,Object> outData = cacheObj.process(inData);
            
            Test.stopTest();
            /**Test Stop Here**/
 
            /*Assert Check Here*/
            System.assertEquals(null, outData);
        }
    }
}