src/objects/ccrz__E_AccountAddressBook__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>ccrz__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account that owns the address book entry</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC Address Books</relationshipLabel>
        <relationshipName>E_AccountAddressBooks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__AddressBookId__c</fullName>
        <description>External Id for Address Book</description>
        <externalId>true</externalId>
        <label>Address Book Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__AddressType__c</fullName>
        <description>Indicates which type of address correponds to the address book entry</description>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__E_ContactAddress__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CC Contact Address</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipLabel>CC Address Books</relationshipLabel>
        <relationshipName>E_Account_Address_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Account Address Book</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Account Address Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EC_InactiveAccountAddressbookBatchTest.cls
/********************************************************************************************************
* @Class Name    EC_InactiveAccountAddressbookBatchTest  
* @description   EC_InactiveAccountAddressbookBatchTest is used to test the functionality of EC_InactiveAccountAddressbookBatch
* @Created By -  Ravindra Singh  
* @Created On -  2019-09-10
* *********************************************************************************************************

 * Modification Log:  
 * ------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID             Description 
 * ------------------------------------------------------------------------------------------------------
 * Ravindra               2019-09-10                                   Initial version
 *********************************************************************************************************/ 
@isTest
public class EC_InactiveAccountAddressbookBatchTest {

 /***************************************************************************************************************************************
      Method Name : InactiveAccountAddressbook
      Description : This method is used to test positive scenario
      Return type : void
     **************************************************************************************************************************************/
      
    @isTest
    public static void InactiveAccountAddressbook(){
        EC_TestData.setupCatalog();
        EC_TestData.setupTestUser();
        ccrz__E_AccountAddressBook__c book = new ccrz__E_AccountAddressBook__c();
        Account a = [Select id from Account limit 1];
        book.ccrz__Account__c = a.Id;
        book.ccrz__AddressBookId__c = 'bookId';
        book.ccrz__AddressType__c = 'Billing';
        insert book;
        
        Datetime dt= system.now();
        EC_InactiveAccountAddressbookBatch ecpi= new EC_InactiveAccountAddressbookBatch(dt);
        Database.BatchableContext dbc ;
        ecpi.start(dbc);      
        List<ccrz__E_AccountAddressBook__c> scope= new List<ccrz__E_AccountAddressBook__c>();
        scope=[SELECT ccrz__Account__c,ccrz__AddressBookId__c,ccrz__AddressType__c,ccrz__E_ContactAddress__c from ccrz__E_AccountAddressBook__c];
        
        ecpi.execute(dbc,scope);
        ecpi.finish(dbc);
        system.assertNotEquals(ecpi.start(dbc), null);
        
    }
}