src/objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>ccrz__EncryptedId__c</fullName>
        <description>Semi-random UUID used to refer to the order in URLs.</description>
        <label>Encrypted Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_CartItem__c.object
<CustomObject>
    <description>Cart Items</description>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line item.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Cart Items (ProductID)</relationshipLabel>
        <relationshipName>E_CartItem2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Cart Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CartItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within B2B Commerce</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_ProductMedia__c.object
<CustomObject>
    <description>Encapsulates media such as hero, thumbnail images, product brochures, owner&apos;s manuals, assembly guides, and videos associated with a product. Media&apos;s source could be in a form of attachment, static resource, or external resource(URI).</description>
    <fields>
        <fullName>ccrz__MediaType__c</fullName>
        <description>Determines where this image is displayed. Values are &quot;Product Image&quot;, &quot;Product Image Thumbnail&quot;, &quot;Product Search Image&quot;, &quot;Alternate Image&quot;</description>
        <label>Media Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alternate Images</fullName>
                </value>
                <value>
                    <fullName>Alternate Thumbnails</fullName>
                </value>
                <value>
                    <fullName>Datasheets</fullName>
                </value>
                <value>
                    <fullName>Safety Documents</fullName>
                </value>
                <value>
                    <fullName>Sales Brochures</fullName>
                </value>
                <value>
                    <fullName>Product Search Image</fullName>
                </value>
                <value>
                    <fullName>Owner&apos;s Manuals</fullName>
                </value>
                <value>
                    <fullName>Assembly Guides</fullName>
                </value>
                <value>
                    <fullName>JPG Image</fullName>
                </value>
                <value>
                    <fullName>Product Image</fullName>
                </value>
                <value>
                    <fullName>Product Image Thumbnail</fullName>
                </value>
                <value>
                    <fullName>Flash Files</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>SVG Interactive Diagram</fullName>
                </value>
                <value>
                    <fullName>Specification Sheets</fullName>
                </value>
                <value>
                    <fullName>Product Bulletins</fullName>
                </value>
                <value>
                    <fullName>Operating Manuals</fullName>
                </value>
                <value>
                    <fullName>SDS Documents</fullName>
                </value>
                <value>
                    <fullName>Label 1s</fullName>
                </value>
                <value>
                    <fullName>Label 2s</fullName>
                </value>
                <value>
                    <fullName>Catalog Sheets</fullName>
                </value>
                <value>
                    <fullName>Analytical Procedures</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__ProductMediaSource__c</fullName>
        <description>Source of the image. Values are &quot;URL&quot;, &quot;Static Resource&quot; and &quot;Attachment&quot;</description>
        <label>Product Media Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attachment</fullName>
                </value>
                <value>
                    <fullName>Static Resource</fullName>
                </value>
                <value>
                    <fullName>URI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <description>Reference to the category entry to which this media corresponds</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>E_ProductMedias</relationshipLabel>
        <relationshipName>E_ProductMedias</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__StaticResourceName__c</fullName>
        <description>Pointing to static resource containing the images</description>
        <inlineHelpText>1. Use prefix &quot;c__&quot; for static resource defined in subscriber org
2. StaticResource name without prefix refers to static resource inside managed package</inlineHelpText>
        <label>Static Resource Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Product Media</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Product Media Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Product Media</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EC_SalesRep_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EC SalesRep User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/classes/EC_EmailCartControllerTest.cls
/* Class Name      :EC_EmailCartControllerTest
* Description      :Test class for EC_EmailCartController
* Created By       :Ravindra Singh
* Created On       :29-08-2019
*
* Modification Log:
* ----------------------------------------------------------------------------------------------------------------------------------
* Developer                     Date                                        Description
* ----------------------------------------------------------------------------------------------------------------------------------
* Ravindra                    29-08-2019                                Base code added.
*/

@isTest
public class EC_EmailCartControllerTest {

/***************************************************************************************************************************************
      Method Name : sendMailCartTest
      Description : This method is used to test positive scenario
      Return type : void
     **************************************************************************************************************************************/
      
    
    @isTest
    private static void sendMailCartTest(){
        
        EC_TestData.setupTestUser();
         User thisUser = [SELECT Id,ContactId FROM User WHERE LastName = 'TestUser'];
        EC_TestData.setupCatalog();
        List<ccrz__E_Cart__c> carts = EC_TestData.createCarts(1);
        
        ccrz__E_Product__c proditem = [SELECT id, ccrz__sku__c FROM ccrz__E_Product__c  LIMIT 1  ];
        
       ccrz__E_ProductMedia__c media =  new ccrz__E_ProductMedia__c(
                            ccrz__Product__c            = proditem.Id,                        
                            ccrz__ProductMediaSource__c = 'static',
                            //ccrz__StaticResourceName__c = generateRandomString(10),
                            ccrz__MediaType__c='Product Image Thumbnail');
        insert media;
        ccrz__E_CartItem__c  cartitems = EC_TestData.addCartItem(carts[0], proditem.id ,1 ,1);
        
        Contact c = [Select id,AccountId,Email from Contact where id = :thisUser.ContactId];
        
        
        ccrz.cc_RemoteActionContext ctx = new ccrz.cc_RemoteActionContext();
        ctx.effAccountId = c.AccountId;
        ctx.currentCartId = carts[0].ccrz__EncryptedId__c;
       // ccrz.cc_CallContext.initRemoteContext(ctx);
        //ccrz.cc_CallContext.effAccountId = accnt.id;
        Test.startTest();
        //System.runas (thisUser){            
            Map<String,String> result = EC_EmailCartController.cloneCart(carts[0].ccrz__EncryptedId__c,String.valueOf(thisUser.Id), String.valueOf(thisUser.ContactId), '', 'subject');
            EC_EmailCartController.sendEmail('cpadia@deloitte.com', 'rajkyadav@deloitte.com', 'Test...', 'Test...','Test');
            ccrz.cc_RemoteActionResult resultTrue = EC_EmailCartController.sendMailCart(ctx,c.Email, 'rajkyadav@deloitte.com', 'Test...', 'Test...');
           ccrz.cc_RemoteActionResult resultFalse =  EC_EmailCartController.sendMailCart(ctx,'cpadia@deloitte.com', 'rajkyadav@deloitte.com', 'Test...', 'Test...');
           System.assertEquals(true, resultTrue.success); 
           System.assertEquals(false,resultFalse.success); 
            
            Test.stopTest();
       // }
        
    }
    
    /***************************************************************************************************************************************
      Method Name : sendMailCartTest_SalesRep
      Description : This method is used to test positive scenario
      Return type : void
     **************************************************************************************************************************************/
     
    
        @isTest
    private static void sendMailCartTest_SalesRep(){
        
        EC_TestData.setupTestUser();
         User thisUser = [SELECT Id,ContactId FROM User WHERE LastName = 'TestUser'];
        EC_TestData.setupCatalog();
        List<ccrz__E_Cart__c> carts = EC_TestData.createCarts(1);
        Account a = [Select Id from Account limit 1];
        Contact c = new Contact();
        c.LastName = 'test';
        c.AccountId = a.Id;
        c.Email = 'test@test.com';
        c.EC_SalesRep_User__c = thisUser.Id;
        insert c;
        
        ccrz.cc_RemoteActionContext ctx = new ccrz.cc_RemoteActionContext();
        ctx.effAccountId = c.AccountId;
        ctx.currentCartId = carts[0].ccrz__EncryptedId__c;
       // ccrz.cc_CallContext.initRemoteContext(ctx);
        //ccrz.cc_CallContext.effAccountId = accnt.id;
        Test.startTest();
       // System.runas (thisUser){            
            Map<String,String> result = EC_EmailCartController.cloneCart(carts[0].ccrz__EncryptedId__c,String.valueOf(thisUser.Id), String.valueOf(thisUser.ContactId), '', 'subject');
            EC_EmailCartController.sendEmail('cpadia@deloitte.com', 'rajkyadav@deloitte.com', 'Test...', 'Test...','Test');
           ccrz.cc_RemoteActionResult resultTrue =  EC_EmailCartController.sendMailCart(ctx,c.Email, 'rajkyadav@deloitte.com', 'Test...', 'Test...');
           ccrz.cc_RemoteActionResult resultFalse =  EC_EmailCartController.sendMailCart(ctx,'cpadia@deloitte.com', 'rajkyadav@deloitte.com', 'Test...', 'Test...');
           System.assertEquals(true, resultTrue.success); 
           System.assertEquals(false,resultFalse.success); 
            
            Test.stopTest();
       // }
        
    }

}