src/objects/ccrz__E_ProductMedia__c.object
<CustomObject>
    <description>Encapsulates media such as hero, thumbnail images, product brochures, owner&apos;s manuals, assembly guides, and videos associated with a product. Media&apos;s source could be in a form of attachment, static resource, or external resource(URI).</description>
    <fields>
        <fullName>ccrz__Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag determining whether or not this media record is active</description>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date for which this media record is active. This is the last date the image will be displayed</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Product Media</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Product Media Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Product Media</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EC_InactiveProductMediaBatchTest.cls
/********************************************************************************************************
* @Class Name    EC_InactiveProductMediaBatchTest 
* @description   EC_InactiveProductMediaBatchTest is used to test the functionality of EC_InactiveProductMediaBatch
* @Created By -  Ravindra Singh  
* @Created On -  2019-09-10
* *********************************************************************************************************

 * Modification Log:  
 * ------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID             Description 
 * ------------------------------------------------------------------------------------------------------
 * Ravindra               2019-09-10                                   Initial version
 *********************************************************************************************************/ 
@isTest
public class EC_InactiveProductMediaBatchTest {

 /***************************************************************************************************************************************
      Method Name : InactiveProductMedia
      Description : This method is used to test positive scenario
      Return type : void
     **************************************************************************************************************************************/
      

    @isTest
    public static void InactiveProductMedia(){
        Datetime dt= system.now();
        EC_InactiveProductMediaBatch ecpi= new EC_InactiveProductMediaBatch(dt);
        Database.BatchableContext dbc ;
        ecpi.start(dbc);
        EC_TestData.setupCatalog();
        List<ccrz__E_ProductMedia__c> scope= new List<ccrz__E_ProductMedia__c>();
        scope=[SELECT ccrz__EndDate__c,ccrz__Enabled__c from ccrz__E_ProductMedia__c];
        system.debug('scope==='+scope);
        update scope;
        ecpi.execute(dbc,scope);
        ecpi.finish(dbc);
        system.assertNotEquals(ecpi.start(dbc), null);
    }
        
}