src/objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>ccrz__EffectiveAccountID__c</fullName>
        <description>Holds the effective account for this cart.  This field will be utilized in implementations where a user can order for multiple accounts inclusive or exclusive of their own.  The effective account is used to control the entitlements, pricing, integrations etc that drive the site experience.</description>
        <inlineHelpText>This field will be utilized in implementations where a user can order for multiple accounts inclusive or exclusive of their own.  The effective account is used to control the entitlements, pricing, integrations etc that drive the site experience.</inlineHelpText>
        <label>Effective Account ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_CartItem__c.object
<CustomObject>
    <description>Cart Items</description>
    <fields>
        <fullName>ccrz__Cart__c</fullName>
        <description>Reference to the parent cart.</description>
        <label>Cart</label>
        <referenceTo>ccrz__E_Cart__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>E_CartItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__OriginalQuantity__c</fullName>
        <description>Stores the original child quantity per unit for Kits, Bundles, and Dynamic Kits.</description>
        <label>Original Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>The unit price of the line.</description>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line item.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Cart Items (ProductID)</relationshipLabel>
        <relationshipName>E_CartItem2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Quantity of the line item.</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__SubAmount__c</fullName>
        <description>Sub Amount total for the line.  Typically will be Price times Quantity.</description>
        <label>Sub Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__UnitOfMeasure__c</fullName>
        <description>Unit of measure as copied from the product data.</description>
        <label>Unit Of Measure</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>CC Cart Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CartItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>ccrz__EffectiveAccountID__c</fullName>
        <description>Holds the effective account for this order.  This field will be utilized in implementations where a user can order for multiple accounts inclusive or exclusive of their own.  The effective account is used to control the entitlements, pricing, integrations etc that drive the site experience.</description>
        <inlineHelpText>This field will be utilized in implementations where a user can order for multiple accounts inclusive or exclusive of their own.  The effective account is used to control the entitlements, pricing, integrations etc that drive the site experience.</inlineHelpText>
        <label>Effective Account ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_OrderItem__c.object
<CustomObject>
    <description>The E_OrderItem__c object contains the line level detail of placed orders.</description>
    <fields>
        <fullName>ccrz__OriginalQuantity__c</fullName>
        <description>The purpose of this field is to store the appropriate quantity of line items that have products in the form of parent and child like bundles kits and dynamic kits</description>
        <label>Original Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>The price of the product at the time the item was ordered.</description>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Order Items (ProductID)</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Quantity__c</fullName>
        <description>The number of items ordered for this line.</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__SubAmount__c</fullName>
        <description>The sub-total amount for the order. This will be calculated as price * quantity - coupon adjustments during order placement.</description>
        <label>Sub Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__UnitOfMeasure__c</fullName>
        <description>Unit of measure copied from the product.</description>
        <label>Unit Of Measure</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>CC Order Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>OrderItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/EC_UtilityTest.cls
/***************************************************************************************************************************************
 Method Name : EC_UtilityTest
 Description : Test Class For EC_Utility
 Return type : void
 Author      :
 *************************************************************************************************************************************/

@isTest(SeeAllData = false) public class EC_UtilityTest {
	/***************************************************************************************************************************************
	 Method Name : isBlankOrEmptyTest
	 Description : Add items to the cart
	 Return type : Void
	 Author      : Priyanka Priya
	 *************************************************************************************************************************************/
	@isTest
	public static void isBlankOrEmptyTest() {
		System.assertEquals(EC_Utility.isBlankOrEmpty('10'), false);
		System.assertEquals(EC_Utility.isBlankOrEmpty(null), true);
	}
	/***************************************************************************************************************************************
	 Method Name : getGovLimitKpiTest
	 Description : Add items to the cart
	 Return type : Void
	 Author      : Priyanka Priya
	 *************************************************************************************************************************************/
	@isTest
	public static void getGovLimitKpiTest() {
		system.assertNotEquals(EC_Utility.getGovLimitKpi(), '');
	}
	/***************************************************************************************************************************************
	 Method Name : getCallingContextTest
	 Description : Add items to the cart
	 Return type : Void
	 Author      : Priyanka Priya
	 *************************************************************************************************************************************/

	@isTest
	public static void getCallingContextTest() {

		Test.startTest();
		EC_Utility.getCallingContext();
		List<EC_Utility.PermWrapper> permWrap = new List<EC_Utility.PermWrapper>();
		permWrap= EC_Utility.getPermCache();
		Test.stopTest();


	}
	/***************************************************************************************************************************************
	 Method Name : getPageUrlTest
	 Description : To test the methods
	 Return type : Void
	 Author      : Priyanka Priya
	 *************************************************************************************************************************************/

	@isTest
	public static void getPageUrlTest() {
		EC_TestData.createOutageRecord();
		EC_TestData.createEC_PermissionSetMapping();
		Test.startTest();
		EC_Utility.getPageUrl();
		EC_Utility.getProfileIBuy();
		EC_Utility.checkCustomPermissionOnUser();
		EC_Utility.getCommunityUrl();
		EC_Utility.permissionSetMap();
		EC_Utility.permissionSetId('Basic');
		EC_Utility.getOutageFlag();
		Test.stopTest();


	}
	/***************************************************************************************************************************************
	 Method Name : addItemsCartTest
	 Description : Add items to the cart
	 Return type : void
	 Author      : Shruti Sinha
	 *************************************************************************************************************************************/

	@isTest
	public static void addItemsCartTest() {
		EC_TestData.setupTestUser();
		List<User> usr = [Select Id, FirstName, LastName, ProfileId, ContactId from User where LastName = 'TestUser'];
		System.runAs(usr [0]) {
			EC_TestData.setupCatalog();
			EC_TestData.createOrders(3);
			ccrz__E_Order__c ord = [Select Id, ccrz__EffectiveAccountID__c from ccrz__E_Order__c limit 1];
			ccrz__E_Cart__c crt = [Select Id from ccrz__E_Cart__c limit 1];
			List<ccrz__E_OrderItem__c> lst = [Select Id, ccrz__Product__c, ccrz__OriginalQuantity__c, ccrz__UnitOfMeasure__c from ccrz__E_OrderItem__c limit 5];
			ccrz__E_CartItem__c cartItem = new ccrz__E_CartItem__c(ccrz__Cart__c = crt.Id,
																   ccrz__Quantity__c     = 5,
																   ccrz__Product__c      = lst [0].ccrz__Product__c,
																   ccrz__Price__c        = 20,
																   ccrz__SubAmount__c    = 22,
																   ccrz__UnitOfMeasure__c= 'Each');
			insert cartItem;

			boolean isReorder = TRUE;
			Id EffAccId = ord.ccrz__EffectiveAccountID__c;

			test.StartTest();
			EC_Utility.addItemsToCart(crt.Id, EffAccId, lst, isReorder);

			EC_Utility.getActiveCartForUser(EffAccId);


			test.StopTest();
		}
	}
	/***************************************************************************************************************************************
	 Method Name : addItemsCartTest
	 Description : Add items to the cart
	 Return type : void
	 Author      : Shruti Sinha
	 *************************************************************************************************************************************/

	@isTest
	public static void noActiveCartTest() {
		EC_TestData.setupTestUser();
		List<User> usr = [Select Id, FirstName, LastName, ProfileId, ContactId from User where LastName = 'TestUser'];
		System.runas(usr [0]) {
			EC_TestData.setupCatalog();
			EC_TestData.createOrders(3);
			ccrz__E_Order__c ord = [Select Id, ccrz__EffectiveAccountID__c from ccrz__E_Order__c limit 1];
			Id EffAccId = ord.ccrz__EffectiveAccountID__c;
			test.StartTest();

			EC_Utility.getActiveCartForUser(EffAccId);


			test.StopTest();
		}
	}




}