src/objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>EC_Ship_To_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC Carts (Ship To Account)</relationshipLabel>
        <relationshipName>CC_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>EC_Submission_Failure_Count__c</fullName>
        <label>Submission Failure Count</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EC_Division__c</fullName>
        <formula>TEXT(ccrz__OriginatedCart__r.EC_Ship_To_Account__r.EC_Division__c)</formula>
        <label>Division</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__OrderStatus__c</fullName>
        <description>Displayed order status. Orders initially placed are all in Order Submitted status. All other statuses may be implementation specific.</description>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancel Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Return Submitted</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Partial Shipped</fullName>
                </value>
                <value>
                    <fullName>Bill Of Material</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__OriginatedCart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the CC Cart object used to create this order.</description>
        <label>Originated Cart</label>
        <referenceTo>ccrz__E_Cart__c</referenceTo>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/EC_OrderSubmissionBatchJob.cls
/********************************************************************************************************
* @Class Name    EC_OrderSubmissionBatchJob 
* @description   EC_OrderSubmissionBatchJob is used to submit failed orders to resubmit to Tibco
* @Created By -  Ravindra Singh  
* @Created On -  2019-8-25
* *********************************************************************************************************

 * Modification Log:  
 * ------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID             Description 
 * ------------------------------------------------------------------------------------------------------
 * Ravindra               2019-8-25                                    Initial version
 *********************************************************************************************************/ 

global class EC_OrderSubmissionBatchJob implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful{    
    global EC_OrderService.ServiceResponse response;     
    global list<sObject> records;
    
    global EC_OrderSubmissionBatchJob(){
        records = new list<sObject>();
    }    
    
   /***************************************************************************************************************************************
      Method Name : start
      Description : start method is used to query the records to be processed in the batch
      Return type : Database.QueryLocator
     **************************************************************************************************************************************/
  
    global Iterable<sObject> start(Database.BatchableContext BC){
        String divisions = Label.EC_OrderSubmissionDivision;
        List<String> divisionList = divisions.split(',');
        String divisionQuery = '\''+ String.join(divisionList,'\',\'')+'\'';    
        
        String query  = EC_OrderService.getOrderQuery();
        query += ' Where (EC_Submission_Failure_Count__c < 5 or EC_Submission_Failure_Count__c = null) and  ccrz__OrderStatus__c = \'Failed\' and ccrz__OriginatedCart__r.EC_Ship_To_Account__r.EC_Division__c in ('+divisionQuery + ')'; 
        system.debug('start query: ' + query);
        records = Database.query(query);
        system.debug('EC_OrderSubmissionBatchJob start: records ' + records);
        return records;
    }
    
     /***************************************************************************************************************************************
      Method Name : execute
      Description : execute method is used to submit given orders to Tibco
      Return type : void
     **************************************************************************************************************************************/
   
  
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        list<ccrz__E_Order__c> orders = ( list<ccrz__E_Order__c> ) scope;
        system.debug('EC_OrderSubmissionBatchJob execute: records ' + orders);
        if( orders != null && !orders.isEmpty() ){
            response = EC_OrderService.processOrders(orders); 
        }        
    }
    
     /***************************************************************************************************************************************
      Method Name : finish
      Description : finish method is used to log failed order information
      Return type : void
     **************************************************************************************************************************************/
   

    global void finish(Database.BatchableContext BC){ 
        system.debug('EC_OrderSubmissionBatchJob Finish: response ' + response);
      
        if (response != null && response.errors.size() > 0){ 
            system.debug('EC_OrderSubmissionBatchJob Finish: records ' + response.orders.values());  
            system.debug('number of errors: ' + response.errors.size());
        }
      
       
    }
}