src/objects/ccrz__E_AccountGroup__c.object
<CustomObject>
    <description>This object is used to group multiple accounts together to provide pricing and/or entitlements.  An account group can have 1 or more accounts associated with it.  It also can have 1 or more pricelists (used for pricing and entitlements) associated.  This object then ties the accounts and entitlements/pricing together, ultimately controlling the product list and pricing that a given account can see within B2B Commerce.</description>
    <label>CC Account Group</label>
    <nameField>
        <label>Account Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Account Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_AccountGroupPriceList__c.object
<CustomObject>
    <description>Represents a mapping of Account Group to Pricelist.  This objects ties the two together, enabling the assignment and entitlement/pricing functionality.</description>
    <fields>
        <fullName>ccrz__AccountGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the account group</description>
        <label>Account Group</label>
        <referenceTo>ccrz__E_AccountGroup__c</referenceTo>
        <relationshipLabel>Account Group Price Lists</relationshipLabel>
        <relationshipName>E_AccountGroupPriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Enable__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag determining whether or not this mapping record is active</description>
        <label>Enable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer available for the account group.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is available to the account group will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the pricelist</description>
        <label>Pricelist</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>Account Group Price Lists</relationshipLabel>
        <relationshipName>E_AccountGroupPriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this mapping record is active. This is the first date the mapping will be applied</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Account Group Price List</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Acct Group Pricelist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Account Group Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceList__c.object
<CustomObject>
    <description>Represents a grouping of products to control pricing and entitlements.  The B2B Commerce pricelist object controls both pricing and entitlements, but can be used just for the purposes of entitlements. A list needs to be created for each currency that needs to be represented, allowing for different entitlments and pricing based on the locale and currency.</description>
    <fields>
        <fullName>ccrz__CurrencyISOCode__c</fullName>
        <description>Required - The 3-character ISO currency code corresponding to this list. For example, USD</description>
        <label>Currency ISO Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer active.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is valid will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this pricelist record is active. This is the first date the pricing/entitlements will be applied</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>Mulit-select list that allows you to assign the pricelist to one or more storefronts.</description>
        <label>Storefront</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DefaultStore</fullName>
                </value>
                <value>
                    <fullName>Connect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_AccountGroup_Category__c.object
<CustomObject>
    <description>Junction Object between CC Category((CloudCraze Managed package object) and CC Account Group (CloudCraze Managed package object)</description>
    <label>Account Group Category</label>
    <nameField>
        <label>EC Account Group Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Group Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EC_CreateCacheTreeBatch.cls
/* Class Name    : EC_CreateCacheTreeBatch
 * Description      :Storing/Creating the cache tree of all categories
 * Created By       :Jitan Goyal  
 * Created On       :07-30-2019

 

 * Modification Log:
 * -----------------------------------------------------------------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID         Description
 * -----------------------------------------------------------------------------------------------------------------------------------------------------------------
 * Jitan Goyal             07-30-2019        BC-74102    Created the class   
 *
 */
global with sharing class EC_CreateCacheTreeBatch implements Database.Batchable<sObject>{
	
	private String storefront;
	private String[] plCurrencies;
	private String[] locales;
    private Date today = Date.today();
    
	/***************************************************************************************************************************************
  Constructor Name : EC_CreateCacheTreeBatch
  Description : Constructor to initialize variables of EC_CreateCacheTreeBatch class
  Return type : N/A
 *************************************************************************************************************************************/
    global EC_CreateCacheTreeBatch(String storefront, String[] plCurrencies, String[] locales) {
		this.storefront = storefront;
		this.plCurrencies = plCurrencies;
		this.locales = locales;
	} 
	
	/***************************************************************************************************************************************
  Method Name : start
  Description : sets the ccrz__E_AccountGroup__c query string
  Return type : Database.QueryLocator
 *************************************************************************************************************************************/       
    global Database.QueryLocator start(Database.BatchableContext BC) {
		 String query = 'Select Id from ccrz__E_AccountGroup__c Where Id in ( ' +
		'Select ccrz__AccountGroup__c From ccrz__E_AccountGroupPriceList__c Where ccrz__Pricelist__r.ccrz__CurrencyISOCode__c IN: plCurrencies and ccrz__Pricelist__r.ccrz__Storefront__c =\'' + String.escapeSingleQuotes(storefront) +'\' AND ccrz__StartDate__c <= :today AND ccrz__EndDate__c >= :today AND ccrz__Enable__c = true)';

		return Database.getQueryLocator(query);
	}
	
	/***************************************************************************************************************************************
  Method Name : execute
  Description : get category json from the cache helper class and refreshes the cache
  Return type : void
 *************************************************************************************************************************************/    
    global void execute(Database.BatchableContext BC, List<sObject> scope) {
		Map<Id,List<EC_AccountGroup_Category__c>> accountGrpCategoryMap = EC_CreateCacheTreeHelper.createAccountGroupAllowedCategories(scope, plCurrencies, storefront); 
		EC_CreateCacheTreeHelper.refreshCategoryCaches(accountGrpCategoryMap, plCurrencies, storefront, locales);
	}
	
	/***************************************************************************************************************************************
  Method Name : finish
  Description : N/A
  Return type : void
 *************************************************************************************************************************************/   
    global void finish(Database.BatchableContext BC) {
	}

}