src/objects/ccrz__E_AccountGroupPriceList__c.object
<CustomObject>
    <description>Represents a mapping of Account Group to Pricelist.  This objects ties the two together, enabling the assignment and entitlement/pricing functionality.</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer available for the account group.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is available to the account group will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the pricelist</description>
        <label>Pricelist</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>Account Group Price Lists</relationshipLabel>
        <relationshipName>E_AccountGroupPriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this mapping record is active. This is the first date the mapping will be applied</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Account Group Price List</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Acct Group Pricelist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Account Group Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceList__c.object
<CustomObject>
    <description>Represents a grouping of products to control pricing and entitlements.  The B2B Commerce pricelist object controls both pricing and entitlements, but can be used just for the purposes of entitlements. A list needs to be created for each currency that needs to be represented, allowing for different entitlments and pricing based on the locale and currency.</description>
    <fields>
        <fullName>ccrz__CurrencyISOCode__c</fullName>
        <description>Required - The 3-character ISO currency code corresponding to this list. For example, USD</description>
        <label>Currency ISO Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag determining whether or not this pricelist record is active</description>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer active.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is valid will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this pricelist record is active. This is the first date the pricing/entitlements will be applied</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>Mulit-select list that allows you to assign the pricelist to one or more storefronts.</description>
        <label>Storefront</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DefaultStore</fullName>
                </value>
                <value>
                    <fullName>Connect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_CategoryTreeBatchStartEndTimeLine__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>EC_Batch_End_Time__c</fullName>
        <label>Batch End Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EC_Batch_Start_Time__c</fullName>
        <label>Batch Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>CategoryTreeBatchStartEndTimeLine</label>
</CustomObject>

src/objects/EC_PriceList_Category_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>EC_Category__c</fullName>
        <label>Category</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EC_Currency__c</fullName>
        <label>Currency</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_Locale__c</fullName>
        <label>Locale</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_PriceList__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price List</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>PriceList Category Mappings</relationshipLabel>
        <relationshipName>PriceList_Category_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PriceList Category Mapping</label>
    <nameField>
        <displayFormat>PL-CAT-{0000000}</displayFormat>
        <label>PriceList Category Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PriceList Category Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EC_CreatePriceListCategoryMappingBatch.cls
global with sharing class EC_CreatePriceListCategoryMappingBatch implements Database.Batchable<sObject>, Database.Stateful{
    private String storefront;
    private String plCurrencies;
    private String locales;
    private Date today = Date.today();
    global List<EC_PriceList_Category_Mapping__c> priceListCategoryMapping;
    global EC_CategoryTreeBatchStartEndTimeLine__c batchTime;
    
    global EC_CreatePriceListCategoryMappingBatch(String storefront, String plCurrencies, String locales) {
        this.storefront = storefront;
        this.plCurrencies = plCurrencies;
        this.locales = locales;
        batchTime = EC_CategoryTreeBatchStartEndTimeLine__c.getOrgDefaults();
    } 
    
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        batchTime.EC_Batch_Start_Time__c = System.now();
        String query = 'Select Id from ccrz__E_PriceList__c Where Id in (SELECT ccrz__Pricelist__c from ccrz__E_AccountGroupPriceList__c) AND ccrz__CurrencyISOCode__c=\''+String.escapeSingleQuotes(plCurrencies)+'\' AND ccrz__Storefront__c =\'' + String.escapeSingleQuotes(storefront) +'\' AND ccrz__StartDate__c <= :today AND ccrz__EndDate__c >= :today AND ccrz__Enabled__c = true';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        priceListCategoryMapping = new List<EC_PriceList_Category_Mapping__c>();
        Set<Id> pricelistIDs = new Set<Id>();
        
        Map<Id,EC_PriceList_Category_Mapping__c> newPriceListCatMap = new Map<Id,EC_PriceList_Category_Mapping__c>();
        for(sObject s: scope ){
            ccrz__E_PriceList__c priceList = (ccrz__E_PriceList__c) s;
            pricelistIDs.add(priceList.id);
        }
        
        List<EC_PriceList_Category_Mapping__c> allExistingPLCat = [Select Id,EC_PriceList__c,EC_Currency__c,EC_Category__c from EC_PriceList_Category_Mapping__c Where EC_PriceList__c in :(pricelistIDs) AND EC_Currency__c=:plCurrencies AND EC_Locale__c=:locales Limit 50000];
        Map<Id,EC_PriceList_Category_Mapping__c> existingPriceListCatMap = new Map<Id,EC_PriceList_Category_Mapping__c>();
        
        if(!allExistingPLCat.isEmpty()){
            for(EC_PriceList_Category_Mapping__c priceListCat : allExistingPLCat){
                existingPriceListCatMap.put(priceListCat.EC_PriceList__c, priceListCat);
            }
        }
        
        List<EC_PriceList_Category_Mapping__c> toRemoveFromExisting = new List<EC_PriceList_Category_Mapping__c>();
        
        for(sObject s: scope ){
            EC_PriceList_Category_Mapping__c plCat = new EC_PriceList_Category_Mapping__c();
            ccrz__E_PriceList__c priceList = (ccrz__E_PriceList__c) s;
            plCat.EC_PriceList__c = priceList.id;
            plCat.EC_Currency__c = plCurrencies;
            plCat.EC_Locale__c = locales;
            plCat.EC_Category__c = EC_CreateCacheTreeHelper.createPricelistCategoryMapping(priceList.id, plCurrencies, storefront);
            //Bulkified DML statements 
            
            
            if(!existingPriceListCatMap.isEmpty() && existingPriceListCatMap.containsKey(priceList.id)){
                if((existingPriceListCatMap.get(priceList.id).EC_Category__c == plCat.EC_Category__c)
                   && (existingPriceListCatMap.get(priceList.id).EC_Currency__c == plCat.EC_Currency__c)){
                       //need not to be deleted or modified
                       toRemoveFromExisting.add(existingPriceListCatMap.get(priceList.id));
                   }else{
                       //pricelist exist but neither category nor currency matching
                       priceListCategoryMapping.add(plCat);
                   }                
            }else{
                // no existing record nor pricelist not found - create new
                priceListCategoryMapping.add(plCat);
            }
        }
        
        if(!allExistingPLCat.isEmpty()){
            if(!toRemoveFromExisting.isEmpty()){
                for(Integer i= 0; i<allExistingPLCat.size(); i++){
                    if(toRemoveFromExisting.contains(allExistingPLCat[i])){
                        allExistingPLCat.remove(i);
                    }
                }
            }
            delete allExistingPLCat;
        }
        
        if(!priceListCategoryMapping.isEmpty()){
            insert priceListCategoryMapping;
        }
        
    }
    
    global void finish(Database.BatchableContext BC) {
        batchTime.EC_Batch_End_Time__c = System.now();
        upsert batchTime;
        //create custom labels 
        String front = storefront;
        /**Currency**/
        List<String> curr= new List<String>();
        curr.add(plCurrencies);
        //curr.add('USD');
        
        /**Locale**/
        List<String> loc= new List<String>();
        loc.add(locales);
        //loc.add('en_US');
        
        /**Execute Batch**/
        EC_CreateCacheTreeBatch allowedCatJob=new EC_CreateCacheTreeBatch(front,curr,loc);
        Database.executebatch(allowedCatJob,80);
        
        
    }
}