src/objects/ccrz__E_AccountGroup__c.object
<CustomObject>
    <description>This object is used to group multiple accounts together to provide pricing and/or entitlements.  An account group can have 1 or more accounts associated with it.  It also can have 1 or more pricelists (used for pricing and entitlements) associated.  This object then ties the accounts and entitlements/pricing together, ultimately controlling the product list and pricing that a given account can see within B2B Commerce.</description>
    <label>CC Account Group</label>
    <nameField>
        <label>Account Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Account Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_AccountGroupPriceList__c.object
<CustomObject>
    <description>Represents a mapping of Account Group to Pricelist.  This objects ties the two together, enabling the assignment and entitlement/pricing functionality.</description>
    <fields>
        <fullName>EC_Price_List_Type__c</fullName>
        <label>Price List Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Z1CP</fullName>
                </value>
                <value>
                    <fullName>Z1GP</fullName>
                </value>
                <value>
                    <fullName>Z1MP</fullName>
                </value>
                <value>
                    <fullName>ZFCP</fullName>
                </value>
                <value>
                    <fullName>ZF00</fullName>
                </value>
                <value>
                    <fullName>Z1LS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__AccountGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the account group</description>
        <label>Account Group</label>
        <referenceTo>ccrz__E_AccountGroup__c</referenceTo>
        <relationshipLabel>Account Group Price Lists</relationshipLabel>
        <relationshipName>E_AccountGroupPriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Enable__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag determining whether or not this mapping record is active</description>
        <label>Enable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer available for the account group.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is available to the account group will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the pricelist</description>
        <label>Pricelist</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>Account Group Price Lists</relationshipLabel>
        <relationshipName>E_AccountGroupPriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Account Group Price List</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Acct Group Pricelist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Account Group Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ccrz__E_PriceList__c.object
<CustomObject>
    <description>Represents a grouping of products to control pricing and entitlements.  The B2B Commerce pricelist object controls both pricing and entitlements, but can be used just for the purposes of entitlements. A list needs to be created for each currency that needs to be represented, allowing for different entitlments and pricing based on the locale and currency.</description>
    <fields>
        <fullName>EC_Price_List_Type__c</fullName>
        <description>This field stores the type of pricelist i.e. Sales Org, Customer Group</description>
        <inlineHelpText>This field stores the type of pricelist i.e. Sales Org, Customer Group</inlineHelpText>
        <label>Price List Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag determining whether or not this pricelist record is active</description>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer active.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is valid will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__PricelistId__c</fullName>
        <description>External reference id for this entry</description>
        <externalId>true</externalId>
        <label>Pricelist Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__Seller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Seller this Price List belongs to.</description>
        <label>Seller</label>
        <referenceTo>ccrz__E_Seller__c</referenceTo>
        <relationshipLabel>CC Price Lists</relationshipLabel>
        <relationshipName>E_PriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_ProductIndexBatchStatus__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>EC_Category_Batch_Schedule_Interval__c</fullName>
        <label>Category Batch Schedule Interval</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EC_InActive_PriceListItem_Batch__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>checkbox to enable/disable PricelistItem Inactivation Batch</inlineHelpText>
        <label>InActive PriceListItem Batch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EC_Product_Index_Interval__c</fullName>
        <label>Product Index Interval</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Index Batch Status</label>
</CustomObject>

force-app/main/default/classes/EC_InactivePriceListTest.cls
/********************************************************************************************************
* @Class Name    EC_InactivePriceListTest 
* @description   EC_InactivePriceListTest is used to test the functionality of EC_InactivePriceList
* @Created By -  Ravindra Singh  
* @Created On -  2019-09-10
* *********************************************************************************************************

 * Modification Log:  
 * ------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID             Description 
 * ------------------------------------------------------------------------------------------------------
 * Ravindra               2019-09-10                                   Initial version
 *********************************************************************************************************/ 
@isTest
public class EC_InactivePriceListTest {
    @isTest
    public static void InactivePriceList(){
        Datetime dt= system.now();
        EC_InactivePriceList ecp= new EC_InactivePriceList(dt);
        Database.BatchableContext dbc ;
        ecp.start(dbc);
        EC_TestData.setupCatalog();
        ccrz__E_AccountGroup__c accGroup = EC_TestData.testAccountGroup;
        List<ccrz__E_PriceList__c> scope= new List<ccrz__E_PriceList__c>();
        scope=[SELECT ccrz__PricelistId__c,ccrz__Enabled__c,ccrz__EndDate__c,EC_Price_List_Type__c,ccrz__Seller__c   from ccrz__E_PriceList__c];
        //scope[0].ccrz__Enabled__c=false;
        system.debug('scope==='+scope);
        update scope;
        ccrz__E_AccountGroupPriceList__c testAccountGroupPriceList = new ccrz__E_AccountGroupPriceList__c();
        testAccountGroupPriceList.ccrz__AccountGroup__c = accGroup.Id;
        testAccountGroupPriceList.EC_Price_List_Type__c = 'Z1MP';
        testAccountGroupPriceList.ccrz__PriceList__c    = scope[0].Id;
        testAccountGroupPriceList.ccrz__Enable__c       = true;
        insert testAccountGroupPriceList;      
        EC_ProductIndexBatchStatus__c indexBatch = new EC_ProductIndexBatchStatus__c();
        indexBatch.EC_InActive_PriceListItem_Batch__c = true;
        indexBatch.EC_Category_Batch_Schedule_Interval__c = 15;
        indexBatch.EC_Product_Index_Interval__c = 5;
        insert indexBatch;
        ecp.execute(dbc,scope);
        ecp.finish(dbc);
        system.assertNotEquals(ecp.start(dbc), null);
        
    }

 

}