src/objects/ccrz__E_ProductIndex__c.object
<CustomObject>
    <fields>
        <fullName>ccrz__Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Only Active Product Index records will be used. This allows for new records to be created, while leaving the old ones in place until the index batch job is complete.</description>
        <inlineHelpText>Only Active Product Index records will be used. This allows for new records to be created, while leaving the old ones in place until the index batch job is complete.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__FilterData__c</fullName>
        <description>The product spec key and spec values.</description>
        <inlineHelpText>The product spec key and spec values.</inlineHelpText>
        <label>Filter Data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__IndexCurrency__c</fullName>
        <description>The corresponding currency code, ONLY used to assist in batch creation of the index records. NOTE: When using a &quot;Master Price List&quot; this value will be set to GLOBAL, and be currency agnostic.</description>
        <inlineHelpText>The corresponding currency code, ONLY used to assist in batch creation of the index records. NOTE: When using a &quot;Master Price List&quot; this value will be set to GLOBAL, and be currency agnostic.</inlineHelpText>
        <label>Index Currency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__IndexPrice__c</fullName>
        <description>A single indexed Price for the associated product. Primarily used for sorting on the Product List Page.</description>
        <externalId>true</externalId>
        <inlineHelpText>A single indexed Price for the associated product. Primarily used for sorting on the Product List Page.</inlineHelpText>
        <label>Index Price</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__IndexType__c</fullName>
        <description>The type of index, possible values SEARCH, CATEGORY (Base 64 Encoded). Necessary for unique filtering on SOSL searches.</description>
        <inlineHelpText>The type of index, possible values SEARCH, CATEGORY (Base 64 Encoded)</inlineHelpText>
        <label>Index Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__LastIndex__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is only used for tracking purposes during batch job creation.</description>
        <inlineHelpText>This field is only used for tracking purposes during batch job creation.</inlineHelpText>
        <label>Last Index</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__Locale__c</fullName>
        <label>Locale</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__LongDescription__c</fullName>
        <description>The product long description. By default, the index uses the LongDescRT__c field on the CC Product object. If the LongDescRT__c field is empty, then the index will use the LongDesc__c field instead.</description>
        <inlineHelpText>The product long description. By default, the index uses the LongDescRT__c field on the CC Product object. If the LongDescRT__c field is empty, then the index will use the LongDesc__c field instead.</inlineHelpText>
        <label>Long Description</label>
        <length>5000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ccrz__PriceLists__c</fullName>
        <description>A complete list of CC Price List SFIDs separated by a single space, to which the product belongs.</description>
        <inlineHelpText>A complete list of CC Price List SFIDs separated by a single space, to which the product belongs.</inlineHelpText>
        <label>Price Lists</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Category</label>
        <referenceTo>ccrz__E_ProductCategory__c</referenceTo>
        <relationshipLabel>CC Product Indices</relationshipLabel>
        <relationshipName>ProductIndices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductName__c</fullName>
        <description>The localized Product Name. Used for sort order and performing SOSL search against a product.</description>
        <externalId>true</externalId>
        <inlineHelpText>The localized Product Name. Used for sort order and performing SOSL search against a product.</inlineHelpText>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product to which this Index applies.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>CC Product Indices</relationshipLabel>
        <relationshipName>CCProductIndices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ERP_Product_Description__c</fullName>
        <label>ERP Product Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__SEOKeywords__c</fullName>
        <description>The text used within meta tags on the product detail page to help drive search engine optimization.</description>
        <inlineHelpText>The text used within meta tags on the product detail page to help drive search engine optimization.</inlineHelpText>
        <label>SEO Keywords</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__ShortDescription__c</fullName>
        <description>The localized Product Short Description. Used for performing SOSL search against a product.</description>
        <inlineHelpText>The localized Product Short Description. Used for performing SOSL search against a product.</inlineHelpText>
        <label>Short Description</label>
        <length>2000</length>
        <type>Html</type>
    </fields>
    <label>CC Product Index</label>
    <nameField>
        <displayFormat>PI-{000000000}</displayFormat>
        <label>CC Product Index Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Product Indices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EC_cclogicPICreate.cls
/* Class Name      :EC_cclogicPICreate
* Description      :cclogicPICreate Related inherited cloud craze interface
* Created By       :Rajeshwar Bachu. 
* Created On       :25-05-2020

* Modification Log:
* ------------------------------------------------------------------------------------------------------------------
* Developer                Date            Modification ID         Description
* ------------------------------------------------------------------------------------------------------------------
* Rajeshwar bachu         25-05-2020                             Initial version (log modification)
*
*
*/

global class EC_cclogicPICreate extends ccrz.ccLogicPICreate{
    /***************************************************************************************************************************************
Method Name : createProductIndices
Description : It takes data from CC Product object and populates the CC Product Index
Return type : Returns Map<String,Object>
**************************************************************************************************************************************/
    
    global virtual override Map<String,Object> createProductIndices(Map<String,Object> inputData) {
        if(ccrz.ccUtil.isNotKeyValued(inputData, ccrz.ccAPIProduct.PRODUCTLIST) || ccrz.ccUtil.isNotKeyValued(inputData, ccrz.ccAPIProductIndex.PRODUCT_PRICING_DATA)){
            return inputData;
        }
        System.debug('inside createProductIndices');
        // The Localized Product Data
        List<Object> productList = (List<Object>)inputData.get(ccrz.ccAPIProduct.PRODUCTLIST);
        
        // Pricing Data Keyed By Product SFID, Currency ISO Code
        Map<String, Map<String, Map<String, Object>>> productPricingMap = (Map<String, Map<String, Map<String, Object>>>)inputData.get(ccrz.ccAPIProductIndex.PRODUCT_PRICING_DATA);
        
        List<ccrz__E_ProductIndex__c> newProductIndices = (List<ccrz__E_ProductIndex__c>)ccrz.ccUtil.defv(inputData, ccrz.ccAPIProductIndex.PRODUCT_INDICES, new List<ccrz__E_ProductIndex__c>());
        
        for(Object product : productList){
            System.debug(' product' + product);
            Map<String, Object> castProduct = (Map<String, Object>)product;
            
            if(ccrz.ccUtil.isKeyValued(productPricingMap, (String)castProduct.get('sfid'))){
                Map<String, Map<String, Object>> currencyPricingData = (Map<String, Map<String, Object>>)productPricingMap.get((String)castProduct.get('sfid'));
                for(String currencyCode : currencyPricingData.keySet()){
                    Map<String, Object> productPricingData = currencyPricingData.get(currencyCode);
                    //If Product Categories Exist --> Create Category Indices
                    if(ccrz.ccUtil.isKeyValued(castProduct, 'productCategoriesS')){
                        List<Object> productCategories = (List<Object>)castProduct.get('productCategoriesS');
                        Boolean isFirstProductCategory = TRUE;
                        
                        // Create Index Record For Each Category The Product Belongs...
                        for(Object productCategory : productCategories){
                            Map<String, Object> castProductCategory = (Map<String, Object>)productCategory;
                            String prodCategory = (String)castProductCategory.get('sfid');
                            ccrz__E_ProductIndex__c newProductIndex = createProductIndex(productPricingData, inputData, castProduct, prodCategory, currencyCode);
                           
                            // Only One Record Should Be Flagged To Show Up In Search...
                            if(isFirstProductCategory){
                                newProductIndex.ccrz__LastIndex__c = TRUE;
                                newProductIndex.ccrz__PriceLists__c = (String)productPricingData.get('priceLists');
                                newProductIndex.ccrz__IndexType__c = ccrz.ccAPIProductIndex.INDEX_TYPE_SEARCH;
                                isFirstProductCategory = FALSE;
                            }
                            
                            newProductIndices.add(newProductIndex);
                        }
                    }
                    else{
                        // Always Create A Record For Search --> Even If Product Does Not Belong To A Category...
                        string noCategory = '';
                        ccrz__E_ProductIndex__c newPISearch = createProductIndex(productPricingData, inputData, castProduct, noCategory, currencyCode);
                        
                      
                        newProductIndices.add(newPISearch);
                    }
                }
            }
        }
        
        if(ccrz.ccUtil.isNotEmpty(newProductIndices)){
            inputData.put(ccrz.ccAPIProductIndex.PRODUCT_INDICES, newProductIndices);
        }
        
        ccrz.ccLog.log(LoggingLevel.DEBUG, 'M:X', 'EC_cclogicPICreate.createProductIndices');
        return inputData;
        
    }
    
    private ccrz__E_ProductIndex__c  createProductIndex(Map<String, Object> productPricingData, Map<String,Object> inputData, 
                                                        Map<String, Object> castProduct, String productCategory, String currencyCode)
    {
        ccrz__E_ProductIndex__c pI = new ccrz__E_ProductIndex__c();
        pI.ccrz__IndexPrice__c = ccrz.ccUtil.isKeyValued(productPricingData, 'price') ? String.valueOf((Decimal)productPricingData.get('price')).leftPad(19, '0') : '0';
        pI.ccrz__Locale__c = (String)inputData.get(ccrz.ccAPIProductIndex.LOCALE);
        pI.ccrz__IndexType__c = ccrz.ccAPIProductIndex.INDEX_TYPE_SEARCH;
        pI.ccrz__PriceLists__c = (String)productPricingData.get('priceLists');
        pI.ccrz__Product__c = (String)castProduct.get('sfid');
        if(!String.isBlank(productCategory)) { pI.ccrz__ProductCategory__c = productCategory; }
        //ccrz__ProductCategory__c = (String)castProductCategory.get('sfid');
        pI.ccrz__ProductName__c = ccrz.ccUtil.isKeyValued(castProduct, 'alternateName') ? (String)castProduct.get('alternateName') : (String)castProduct.get('sfdcName');
        pI.ccrz__ShortDescription__c = (String)castProduct.get('shortDesc');
        pI.ccrz__LongDescription__c  = (String)castProduct.get('LongDesc');
        pI.ccrz__SKU__c = (String)castProduct.get('SKU');
        pI.ccrz__IndexCurrency__c = currencyCode;
        pI.ccrz__SEOKeywords__c =(String)castProduct.get('SEOKeywords');
        pI.ccrz__FilterData__c =(String)castProduct.get('filterData');
        pI.ccrz__LastIndex__c = TRUE;
        pI.ccrz__Active__c = FALSE;
        // New Custom Fields:
        pI.ERP_Product_Description__c = (String)castProduct.get('ERPProductDescription');
        return pI; 
    }
    
}