src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EC_CDM_Contact__c</fullName>
        <description>US-74958:Raghav:26/06/2019:This field will be used for mapping between CDM and contact object.</description>
        <externalId>true</externalId>
        <label>External Contact Key</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EC_isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>New Checkbox to soft delete the contacts</description>
        <label>EC_isActive</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>EC_CDM_User_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Captures the CDM User status</description>
        <label>CDM User Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EC_CDM_User__c</fullName>
        <description>US-74960:Raghav:26/06/2019:This field will be used for mapping between CDM and user object.</description>
        <externalId>true</externalId>
        <label>External UserKey</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

force-app/main/default/classes/EC_StagingPermissionUserUpdate.cls
/* Class Name      :EC_StagingPermissionUserUpdate
* Description      :Batch Class to update permission on user
* Created By       :Shivam Vats
* Created On       :09-23-2019
*
* Modification Log:
* ----------------------------------------------------------------------------------------------------------------
* Developer                Date                Modification ID             Description
* ----------------------------------------------------------------------------------------------------------------
* Shivam Vats         09-23-2019                                   Batch Class to update permission on user
*
*/

global class EC_StagingPermissionUserUpdate implements Database.Batchable<Sobject> {

   private List<String> userKeys;
   public EC_StagingPermissionUserUpdate(List<String> usrKeys){
        userKeys = usrKeys;
          }
    global Database.QueryLocator start(Database.BatchableContext bc) {
         return Database.getQueryLocator([select IsActive,EC_CDM_User_Status__c,EC_CDM_User__c from User where EC_CDM_User__c in: userKeys]);
    }
    global void execute(Database.BatchableContext bc, List<User> Userlst){
       Map<String,Boolean> usrStatusMap = new  Map<String,Boolean>();
       List<User> updtUserLst = new List<User>();
        for(Contact cntct:[Select EC_CDM_Contact__c,EC_isActive__c from Contact where EC_CDM_Contact__c in:userKeys ])
        {
         usrStatusMap.put(cntct.EC_CDM_Contact__c,cntct.EC_isActive__c);
        }

        for(User usr:Userlst){
            usr.IsActive = usrStatusMap.get(usr.EC_CDM_User__c);
            usr.EC_CDM_User_Status__c = usrStatusMap.get(usr.EC_CDM_User__c);
            updtUserLst.add(usr);
        }
        if(updtUserLst != null && updtUserLst.size()>0){

             Database.SaveResult[] saveRes = Database.update(updtUserLst,false);
        }


                }
    global void finish(Database.BatchableContext bc){

    }
}