src/objects/EC_InformaticaAuditTable__c.object
<CustomObject>
    <fields>
        <fullName>EC_JobEndTime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Job End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EC_JobName__c</fullName>
        <label>Job Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_JobStartTime__c</fullName>
        <label>Job Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>InformaticaAuditTable</label>
    <nameField>
        <label>InformaticaAuditTable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>InformaticaAuditTable</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_ProductIndexBatchStatus__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>EC_Category_Batch_Schedule_Interval__c</fullName>
        <label>Category Batch Schedule Interval</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EC_Category_Index_Switch__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Category Index Switch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EC_InActive_AccountGroupPriceList_Batch__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>checkbox to enable/disable PricelistItem Inactivation Batch</inlineHelpText>
        <label>InActive AccountGroupPriceList Batch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EC_InActive_PriceListItem_Batch__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>checkbox to enable/disable PricelistItem Inactivation Batch</inlineHelpText>
        <label>InActive PriceListItem Batch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EC_InActive_PriceList_Batch__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>checkbox to enable/disable Pricelist Inactivation Batch</inlineHelpText>
        <label>InActive PriceList Batch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EC_InActive_ProductMedia_Batch__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>flag to enable/disable ProductMedia Inactivation Batch</inlineHelpText>
        <label>InActive ProductMedia Batch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EC_Product_Index_Switch__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Product Index Switch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EC_Spec_Index_Switch__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Spec Index Switch</label>
        <type>Checkbox</type>
    </fields>
    <label>Product Index Batch Status</label>
</CustomObject>

force-app/main/default/classes/EC_CreateCacheTreeBatchSchedulableTest.cls
/* Class Name    : EC_CreateCacheTreeBatchSchedulableTest
 * Description      Test Class to cover EC_CreateCacheTreeBatchSchedulable
 * Created By       :Jitan Goyal 
 * Created On       :2019-8-5
 

 * Modification Log:
 * -----------------------------------------------------------------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID         Description
 * -----------------------------------------------------------------------------------------------------------------------------------------------------------------
 * Jitan Goyal            2019-8-5          BC-74102            Created the class   
 *
 */
@isTest
public class EC_CreateCacheTreeBatchSchedulableTest{
/***************************************************************************************************************************************
  Method Name : testScheduleJob
  Description : Test method to cover EC_CreateCacheTreeBatchSchedulable class
  Return type : void
 *************************************************************************************************************************************/
    public static testMethod void testScheduleJob(){
       
      EC_TestData.setupTestUser();
         User thisUser = [SELECT Id FROM User WHERE LastName = 'TestUser' limit 1];
         System.runas(thisUser){
         
         EC_InformaticaAuditTable__c record = new EC_InformaticaAuditTable__c();
        record.EC_JobEndTime__c = System.now().addDays(2);
        record.Name = 'record';
        record.EC_JobName__c = Label.EC_Run_Product_Index_JobName;
        record.EC_JobStartTime__c = System.now();
        insert record;
        
        EC_ProductIndexBatchStatus__c indexBatch = new EC_ProductIndexBatchStatus__c();
        indexBatch.EC_Category_Index_Switch__c = true;
        indexBatch.EC_InActive_AccountGroupPriceList_Batch__c = true;
        indexBatch.EC_InActive_PriceListItem_Batch__c = true;
        indexBatch.EC_InActive_PriceList_Batch__c = true;
        indexBatch.EC_InActive_ProductMedia_Batch__c=true;
        indexBatch.EC_Product_Index_Switch__c=true;
        indexBatch.EC_Spec_Index_Switch__c = true;
        indexBatch.EC_Category_Batch_Schedule_Interval__c = 15;
        insert indexBatch;
        EC_TestData.setupCatalog();  
        
      String sch = '0 59 * * * ?'; 
        // Schedule the test job
      Test.startTest();
      String jobId = System.schedule('EC_CreateCacheTreeBatch',sch,new EC_CreateCacheTreeBatchSchedulable());
      Test.stopTest();
		 // Get the information from the CronTrigger API object
      CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered,NextFireTime
         						FROM CronTrigger WHERE id = :jobId];
        
         System.assertEquals(sch, ct.CronExpression);

   }
  }
}