src/objects/EC_LogsEnabler__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>EC_LogsEnabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EC_LogsEnabled</label>
        <type>Checkbox</type>
    </fields>
    <label>EC_LogsEnabler</label>
</CustomObject>

src/objects/EC_Mulesoft_Integration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>EC_ClientId__c</fullName>
        <description>US:76262:Raghav:This field holds the client id for API Callout.</description>
        <label>EC_ClientId</label>
        <length>90</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_Client_Secret__c</fullName>
        <description>US-76262:Raghav:This fields holds the client secret for API Callout.</description>
        <label>EC_Client_Secret</label>
        <length>90</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC_Endpoint__c</fullName>
        <label>Endpoint</label>
        <type>Url</type>
    </fields>
    <label>Mulesoft Integration</label>
</CustomObject>

src/objects/EC_WebServiceCalloutsLog__c.object
<CustomObject>
    <description>This object to log all the Web Service Callouts</description>
    <fields>
        <fullName>EC_CodeTraverseLog__c</fullName>
        <description>Logs class entry exit, and method entry exits</description>
        <label>Code Traverse Log</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EC_ErrorMessage__c</fullName>
        <description>Error received in the Web Service callout</description>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EC_ResponseCall__c</fullName>
        <description>The response JSON received.</description>
        <label>Response Call</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EC_Status__c</fullName>
        <description>Status of the Web Service call performed</description>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>WebService Callouts Log</label>
    <nameField>
        <displayFormat>WBC-{0000000000}</displayFormat>
        <label>WebService Callouts Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WebService Callouts Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EC_DSRHeaderController.cls
/* Class Name      :EC_DSRHeaderController
* Description      :Controller for EC_DSRHeader component
* Created By       :Aqeeb Ahamed
* Created On       :29-07-2020
*
* Modification Log:
* ----------------------------------------------------------------------------------------------------------------
* Developer                Date                Modification ID             Description
* ----------------------------------------------------------------------------------------------------------------
* Aqeeb Ahamed        29-07-2020                                 Controller for EC_DSRHeader component
*
*/
public with sharing class EC_DSRHeaderController {
    public static final string currentClassName = 'EC_DSRHeaderController';
    /************************************************************************
Method Name: getDSRServiceDetails
Description: Method to get Service Dates and Detail response of the service visit.
Parameters: String recordId, String service startdate
Returns: String
*************************************************************************/

    @AuraEnabled
    public static String getDSRServiceDetails(String recordId, String serviceStart){
        String methodName = 'getDSRServiceDetails';
        EC_WebServiceCalloutsLog__c logRec = new EC_WebServiceCalloutsLog__c();
        EC_LogsEnabler__c enableLog =  EC_LogsEnabler__c.getValues('DigitalServiceReport');
        try{
            EC_Mulesoft_Integration__c serviceReportResponse = EC_Mulesoft_Integration__c.getValues('DigitalServiceReport');
            String clientId = serviceReportResponse.EC_ClientId__c;
            String clientSecret = serviceReportResponse.EC_Client_Secret__c;
            String endPointUrl = serviceReportResponse.EC_Endpoint__c;
            if(String.isBlank(serviceStart)){
                endPointUrl = endPointUrl + '/serviceDates?serviceAddressID='+ recordId;
            } else {
                endPointUrl = endPointUrl + '/serviceDetails?serviceAddressID='+ recordId +
                                +'&serviceStart='+serviceStart;
            }
            HttpResponse response = EC_HTTPCalloutUtils.doGet(endPointUrl,clientId, clientSecret);
            String result;
            if (response.getStatusCode() == 200) {
                result = response.getBody();
                logRec.EC_Status__c = EC_Constants.failure;
                logRec.EC_ResponseCall__c = result;
                logRec.EC_CodeTraverseLog__c = logRec.EC_CodeTraverseLog__c + EC_Constants.stringSeperater + methodName + EC_Constants.methodExit;
                logRec.EC_CodeTraverseLog__c = logRec.EC_CodeTraverseLog__c + EC_Constants.stringSeperater + currentClassName + EC_Constants.classExit;
                if(enableLog.EC_LogsEnabled__c == true){
                    insert logRec;
                }
            }
            else{
                throw new AuraHandledException('No response found');
            }
            return result;
        }
        //catch block to throw exceptions to Aura component
        catch(exception ex){
            EC_UtilityLogger.logException(ex,currentClassName,methodName,false,null,'');
            logRec.EC_Status__c = EC_Constants.failure;
            logRec.EC_ErrorMessage__c = ex.getMessage();
            logRec.EC_CodeTraverseLog__c = logRec.EC_CodeTraverseLog__c + EC_Constants.stringSeperater + methodName + EC_Constants.methodExit;
            logRec.EC_CodeTraverseLog__c = logRec.EC_CodeTraverseLog__c + EC_Constants.stringSeperater + currentClassName + EC_Constants.classExit;
            if(enableLog.EC_LogsEnabled__c == true){
                insert logRec;
            }
            throw new AuraHandledException(ex.getMessage());
        }
    }

        /************************************************************************
Method Name: getContactAccounts
Description: Method to get details of contact and Accounts to which the user is associated.
Parameters: String searchkey
Returns: Map of id and AccountListWrapper
*************************************************************************/
    @AuraEnabled
    public Static  Map<Id, List<EC_ServiceRequestHandler.AccountListWrapper>> getContactAccounts(String searchKey){
        try{
            if(Test.isRunningTest() && searchKey==null) {
                throw new AuraHandledException('Test coverage');
            }
            return EC_ServiceRequestHandler.getContactAccounts(searchKey);
        }
        //catch block to throw exceptions to Aura component
        catch(exception ex){
            system.debug('exception :' + ex);
            throw new AuraHandledException(ex.getMessage());
        }
    }
}