src/objects/Integration_Log__c.object
<CustomObject>
    <description>Object to hold integration related error logs but can be modified</description>
    <fields>
        <fullName>Identifier__c</fullName>
        <label>Identifier</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Component__c</fullName>
        <description>integration component - for eg Service Request, Order Submit etc</description>
        <inlineHelpText>integration component - for eg Service Request, Order Submit etc</inlineHelpText>
        <label>Integration Component</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Service Request</fullName>
                </value>
                <value>
                    <fullName>ServiceNow Case Create</fullName>
                </value>
                <value>
                    <fullName>Salesforce Case Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Integration_Type__c</fullName>
        <description>Integration from and To</description>
        <inlineHelpText>Integration from and To</inlineHelpText>
        <label>Integration Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SFDC_To_TIBCO</fullName>
                </value>
                <value>
                    <fullName>SFDC_To_MULESOFT(ServiceNow Case Creation)</fullName>
                </value>
                <value>
                    <fullName>MULESOFT_To_SFDC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Retry_Batch_Class__c</fullName>
        <description>Retry Batch Class</description>
        <inlineHelpText>Retry Batch Class</inlineHelpText>
        <label>Retry Batch Class</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retry_Counter__c</fullName>
        <description>Retry Counter</description>
        <inlineHelpText>Retry Counter</inlineHelpText>
        <label>Retry Counter</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the integration call</description>
        <inlineHelpText>Status of the integration call</inlineHelpText>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>INTLOGS-{00000}</displayFormat>
        <label>Integration Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Integration_Settings__mdt.object
<CustomObject>
    <description>Integration Settings</description>
    <fields>
        <fullName>Integration_Type__c</fullName>
        <label>Integration Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retry_Limit__c</fullName>
        <description>Generic retry limit for a trying a callout for a failed one.</description>
        <inlineHelpText>Generic retry limit for a trying a callout for a failed one.</inlineHelpText>
        <label>Retry Limit</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Integration Setting</label>
    <pluralLabel>Integration Settings</pluralLabel>
</CustomObject>

src/classes/IntegrationsRetryBatchJob.cls
/********************************************************************************************************
* @Class Name    IntegrationsRetryBatchJob 
* @description   IntegrationsRetryBatchJob is used 
* @Created By -  
* @Created On -  
* *********************************************************************************************************

 * Modification Log:  
 * ------------------------------------------------------------------------------------------------------
 * Developer                Date            Modification ID             Description 
 * ------------------------------------------------------------------------------------------------------
 *                                                    Initial version
 *********************************************************************************************************/ 

global class IntegrationsRetryBatchJob implements Database.Batchable<sObject>, Database.AllowsCallouts {       
    Integer globalRetryLimit = 5;
    Integer serviceRequestRetryLimit = 3;

    global Database.QueryLocator start(Database.BatchableContext BC){
         Integration_Settings__mdt[] intSettingMdtList = [Select Integration_Type__c, Retry_Limit__c from Integration_Settings__mdt ];
    	for(Integration_Settings__mdt intSettingMdt: intSettingMdtList){
        	if(intSettingMdt.Integration_Type__c == 'Service Request' && intSettingMdt.Retry_Limit__c != null)
            	serviceRequestRetryLimit = intSettingMdt.Retry_Limit__c.intValue() ;
        	if(intSettingMdt.Integration_Type__c == 'global' && intSettingMdt.Retry_Limit__c != null)
            	globalRetryLimit = intSettingMdt.Retry_Limit__c.intValue() ;
    	}
        System.debug(serviceRequestRetryLimit + '/' + globalRetryLimit);
        String query = 'Select Id, Identifier__c, Integration_Component__c, Integration_Type__c, Retry_Counter__c, Retry_Batch_Class__c from Integration_Log__c where Status__c != \'true\' and Retry_Counter__c < ' + globalRetryLimit;  
        system.debug('start query: ' + query);      
        return Database.getQueryLocator(query);
    }
    

    global void execute(Database.BatchableContext BC, List<Integration_Log__c> integrationsList){
        List<Id> ids = new List<Id>();
        List<String> caseNoList = new List<String>();
        for(Integration_Log__c integrationEntry : integrationsList){
            if(integrationEntry.Integration_Component__c == 'Service Request' && integrationEntry.Integration_Type__c == 'SFDC_To_TIBCO' && 
                integrationEntry.Retry_Counter__c < serviceRequestRetryLimit){
                caseNoList.add(integrationEntry.identifier__c);
            }
        }  
        if(caseNoList.size() > 0){
            List<Case> caseIns = new List<Case> ([Select id from case where caseNumber in :caseNoList]);
            if(caseIns.size()>0){
                for(Case caseRec: caseIns){
                    ids.add(caseRec.id);
                }
            }
            EC_CaseTriggerHandler.retryServiceRequestSubmit(ids); 
        } 
    }
    
     /***************************************************************************************************************************************
      Method Name : finish
      Description : finish method is used to log failed order information
      Return type : void
     **************************************************************************************************************************************/
   

    global void finish(Database.BatchableContext BC){ 
        system.debug('IntegrationsRetryBatchJob Finish: response ');     
    }
}