src/objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
	<fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SupportCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SupportSubCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Walkme_Url__c</fullName>
        <label>Walkme Url</label>
        <type>Url</type>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

src/globalValueSets/SupportCategory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Checkout</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Login</fullName>
    </customValue>
    <customValue>
        <fullName>Orders</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <customValue>
        <fullName>Quicklist</fullName>
    </customValue>
    <customValue>
        <fullName>Self-Service Register</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>User</fullName>
    </customValue>
    <description>Common picklist values on case and Chat bot routing object for Ecolab Project.</description>
    <masterLabel>Category</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/ChatBotArticleSearch.cls
/* Class Name      :ChatBotArticleSearch
* Description      :class called from einstien bot
* Created By       :Graytitude Team
* Created On       :14.09.2020
*
* Modification Log:
* ----------------------------------------------------------------------------------------------------------------
* Developer                Date                Modification ID             Description
* ----------------------------------------------------------------------------------------------------------------
* Graytitude Team          14.09.2020                                      searches articles based on category input and send to bot
*/
public without sharing class ChatBotArticleSearch {
       
    public class SearchInput {
        @InvocableVariable
        public String category;
        @InvocableVariable
        public String subCategory;
        @InvocableVariable(required=true)
        public String routableId;
    }
    
    public class SearchOutput {
        @InvocableVariable(required=true)
        public String sFAQSearchResult;
    } 
    
    @InvocableMethod(label='Search Articles')
    public static List<SearchOutput> searchFAQ(List<SearchInput> SearchInput) {
    
        String sArticleBaseUrl = getCommunityArticleBaseUrl();
        String sFAQSearchResult = '';
        
        String category = SearchInput[0].category;
                
        for(Knowledge__kav objKA : [SELECT Id,Title,UrlName,Walkme_Url__c FROM Knowledge__kav WHERE 
                                    /*Sub_Category__c IN :setSubCategory AND*/ PublishStatus='Online' AND IsVisibleInCsp = true 
                                    AND Category__c=:category AND Sub_Category__c =: SearchInput[0].subCategory]) {
            sFAQSearchResult += summarizeArticleForBot(sArticleBaseUrl, objKA);
        }
        sFAQSearchResult = sFAQSearchResult.removeEnd('\n\n');
        if(String.isBlank(sFAQSearchResult)) sFAQSearchResult = 'No article found';
        List<SearchOutput> faqSearchOutputs = new List<SearchOutput>();
        SearchOutput faqSearchOutput = new SearchOutput();
        faqSearchOutput.sFAQSearchResult = sFAQSearchResult;
        faqSearchOutputs.add(faqSearchOutput);
        return faqSearchOutputs;
    }

    public static String summarizeArticleForBot(String sArticleBaseUrl, Knowledge__kav article){
        String sSummary, sURL;
        sURL = article.Title + ' : ';
        if(String.isBlank(article.Walkme_Url__c)) sURL += sArticleBaseUrl + '/' + article.UrlName;
        else sURL += article.Walkme_Url__c;        
        //sURL = '<a href="' + sURL + '">' + article.Title + '</a>';
        sSummary = sURL + '\n\n'; 
        return sSummary;
    }
    
    public static string getCommunityArticleBaseUrl() {
        String sArticleBaseUrl = '';
        if(Schema.sObjectType.Network.isAccessible()) {            
            List<Network> communityNetworks = [SELECT Id FROM Network WHERE Name='Ecolab'];            
            if (!communityNetworks.isEmpty()) {
                Network communityNetwork = communityNetworks[0];
                String sLoginUrl = Network.getLoginUrl(communityNetwork.id);
                sArticleBaseUrl = sLoginUrl.replace('/login', '/article/');
            }
        }
        return sArticleBaseUrl;
    }
    
    @TestVisible private ChatBotArticleSearch(){} //added as per suggestion of codescan
}