src/objects/Permision_Set_Mapping__mdt.object
<CustomObject>
    <fields>
        <fullName>Is_DashBoard__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to differentiate Dashboard Permission set</description>
        <label>Is DashBoard?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Permission_Set_Name__c</fullName>
        <description>Salesforce PermissionSet name</description>
        <label>Permission Set Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Permision Set Mapping</label>
    <pluralLabel>Permision Set Mappings</pluralLabel>
</CustomObject>

src/classes/EC_Home_DSR_PowerBIController.cls
/*
* Class Name	: EC_Home_DSR_PowerBIController
* Description	: This Class contains methods for DSR/PowerBI component checks
*/
public with sharing class EC_Home_DSR_PowerBIController {

    /*
    * Method Name : getUserPermissions
    * Description : This method returns Current Users Permission Set Assignments
    * Parameters  : NA
    * Return type : String (JSON response)
    */
    @AuraEnabled
    public static rtnWrapper getUserPermissions() {
        try {
            rtnWrapper rtnWrapper = new rtnWrapper();
            rtnWrapper.enableDSR = false;
            rtnWrapper.enableIntelligence = false;

            List<String> dashboardPermissions = new List<String>();
            list<PermissionSet> lstPermissionSet = EC_QueryUtility.getPermissionSet();
            
            for(Permision_Set_Mapping__mdt eachDashboard : [SELECT Permission_Set_Name__c FROM Permision_Set_Mapping__mdt WHERE Is_DashBoard__c = true]) {
                dashboardPermissions.add(eachDashboard.Permission_Set_Name__c);
            }

            for(PermissionSet eachPermission: lstPermissionSet) {
                if(eachPermission.Name == EC_Constants.DSRPermissionSet) {
                    rtnWrapper.enableDSR = true;
                }
                if(dashboardPermissions.contains(eachPermission.Name)) {
                    rtnWrapper.enableIntelligence = true;
                }
            }

            if(Test.isRunningTest()) {
                throw new DMLException('Test coverage');
            }
            
            return rtnWrapper;
        }
        catch(Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    public class rtnWrapper {
        @AuraEnabled
        public Boolean enableDSR;
        @AuraEnabled
        public Boolean enableIntelligence;
    }
}